import{database,id}from"@/lib/db";
import{loadRuntimeSecrets}from"@/lib/runtime-secrets";
export const runtime="nodejs";export const dynamic="force-dynamic";
const escape=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
const template=(row:Record<string,any>)=>{const evidence=typeof row.evidence_json==="string"?JSON.parse(row.evidence_json):row.evidence_json||{},url=`${process.env.APP_URL||""}${evidence.deepLink||"/workspace/accounts"}`;return`<!doctype html><html><body style="margin:0;background:#f3f6f4;font-family:Arial,sans-serif;color:#10251d"><table role="presentation" width="100%"><tr><td align="center" style="padding:28px 14px"><table role="presentation" width="100%" style="max-width:600px;background:#fff;border:1px solid #d9e3de;border-radius:18px;overflow:hidden"><tr><td style="padding:22px 26px;background:#12372c;color:#fff"><b style="letter-spacing:.14em">NORTHSTAR</b><div style="margin-top:7px;color:#bfe3d4">Transaction notification</div></td></tr><tr><td style="padding:26px"><h1 style="font-size:21px;margin:0 0 10px">${escape(row.title)}</h1><p style="color:#52665e;line-height:1.55">${escape(row.explanation)}</p><p><b>${escape(evidence.institution)}</b> · ${escape(evidence.accountName)} ${evidence.mask?`•••• ${escape(evidence.mask)}`:""}<br>${escape(evidence.merchant)} · ${escape(evidence.category)} · ${evidence.pending?"Pending":"Posted"}</p><a href="${escape(url)}" style="display:inline-block;padding:12px 18px;border-radius:10px;background:#147a5b;color:#fff;text-decoration:none;font-weight:bold">Open transaction</a><p style="margin-top:24px;color:#718078;font-size:12px">Northstar never moves money or initiates a payment. Review suspicious activity directly with your financial institution.</p></td></tr></table></td></tr></table></body></html>`};

export async function POST(request:Request){
 await loadRuntimeSecrets();const authorization=request.headers.get("authorization");if(!process.env.CRON_SECRET||authorization!==`Bearer ${process.env.CRON_SECRET}`)return Response.json({error:"Unauthorized"},{status:401});
 const db=await database(),deliveries=await db.prepare(`SELECT d.*,a.title,a.explanation,a.evidence_json,u.email FROM alert_deliveries d JOIN alerts a ON a.id=d.alert_id JOIN users u ON u.id=d.user_id WHERE d.status IN ('QUEUED','FAILED') AND (d.status='QUEUED' OR NOT EXISTS(SELECT 1 FROM notification_delivery_attempts x WHERE x.delivery_id=d.id AND x.next_retry_at>CURRENT_TIMESTAMP)) ORDER BY d.created_at LIMIT 50`).all<Record<string,any>>();let delivered=0,failed=0;
 for(const row of deliveries.results){const prior=await db.prepare("SELECT COUNT(*) count FROM notification_delivery_attempts WHERE delivery_id=?").bind(row.id).first<{count:string}>(),attempt=Number(prior?.count||0)+1;if(attempt>5)continue;try{if(row.channel==="EMAIL"){if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)throw new Error("EMAIL_NOT_CONFIGURED");const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[row.email],subject:row.title,html:template(row)})});if(!response.ok)throw new Error(`EMAIL_${response.status}`)}else if(row.channel==="BROWSER_PUSH"){if(!process.env.PUSH_DELIVERY_URL||!process.env.PUSH_DELIVERY_TOKEN)throw new Error("PUSH_NOT_CONFIGURED");const evidence=typeof row.evidence_json==="string"?JSON.parse(row.evidence_json):row.evidence_json||{},response=await fetch(process.env.PUSH_DELIVERY_URL,{method:"POST",headers:{Authorization:`Bearer ${process.env.PUSH_DELIVERY_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({userId:row.user_id,title:row.title,body:row.explanation,url:evidence.deepLink||"/workspace/accounts",tag:row.alert_id,urgency:String(row.title).includes("suspicious")?"critical":"normal"})});if(!response.ok)throw new Error(`PUSH_${response.status}`)}await db.batch([db.prepare("UPDATE alert_deliveries SET status='DELIVERED',attempted_at=CURRENT_TIMESTAMP,delivered_at=CURRENT_TIMESTAMP,error_code=NULL WHERE id=?").bind(row.id),db.prepare("INSERT INTO notification_delivery_attempts(id,delivery_id,attempt_number,status) VALUES(?,?,?,'DELIVERED')").bind(id("delivery_attempt"),row.id,attempt)]);delivered++}catch(error){const code=(error instanceof Error?error.message:"DELIVERY_FAILED").slice(0,80),delay=Math.min(3600,30*2**(attempt-1));await db.batch([db.prepare("UPDATE alert_deliveries SET status='FAILED',attempted_at=CURRENT_TIMESTAMP,error_code=? WHERE id=?").bind(code,row.id),db.prepare("INSERT INTO notification_delivery_attempts(id,delivery_id,attempt_number,status,provider_code,next_retry_at) VALUES(?,?,?,'FAILED',?,CURRENT_TIMESTAMP + (? * INTERVAL '1 second'))").bind(id("delivery_attempt"),row.id,attempt,code,delay)]);failed++}
 }
 return Response.json({processed:deliveries.results.length,delivered,failed});
}
