import {workspace} from "@/lib/db";
import {loadRuntimeSecrets} from "@/lib/runtime-secrets";
import {marketDataProvider} from "@/lib/providers/alpaca-market-data";
import {decideInvestment,type DecisionModelAdapter,type DecisionOutput} from "@/lib/ai-investment-decision-engine";
import {optionsFlowForSymbol} from "@/lib/options-flow-engine";
import {evaluateCatalystEntryGate,loadCatalystContext} from "@/lib/catalyst-entry-gate";

export const dynamic="force-dynamic";
type J=Record<string,any>;
type Snap={latestQuote?:{bp?:number;ap?:number;t?:string};latestTrade?:{p?:number;t?:string};dailyBar?:{v?:number};greeks?:{delta?:number;gamma?:number;theta?:number;vega?:number;rho?:number};impliedVolatility?:number;openInterest?:number};
const pattern=/^([A-Z.]+)(\d{6})([CP])(\d{8})$/;
const decode=(symbol:string)=>{const m=symbol.match(pattern);if(!m)return null;return{expiration:`20${m[2].slice(0,2)}-${m[2].slice(2,4)}-${m[2].slice(4,6)}`,type:m[3]==="C"?"CALL" as const:"PUT" as const,strike:Number(m[4])/1000}};
const parse=(value:unknown)=>{try{return typeof value==="string"?JSON.parse(value):value||null}catch{return null}};
type MarketSnapshot={underlying:number;asOf:string;quoteSource?:string;payload:{snapshots?:Record<string,Snap>}};
const snapshotCache=new Map<string,{expires:number;promise:Promise<MarketSnapshot>}>();
async function loadMarketSnapshot(symbol:string){
 const feed=process.env.ALPACA_OPTIONS_FEED||"indicative",key=symbol+":"+feed,cached=snapshotCache.get(key),now=Date.now();
 if(cached&&cached.expires>now)return cached.promise;
 const promise=(async()=>{
  const[quotes,response]=await Promise.all([
   marketDataProvider().getQuotes([symbol]),
   fetch("https://data.alpaca.markets/v1beta1/options/snapshots/"+symbol+"?feed="+encodeURIComponent(feed)+"&limit=1000",{headers:{"APCA-API-KEY-ID":process.env.ALPACA_API_KEY!,"APCA-API-SECRET-KEY":process.env.ALPACA_API_SECRET!},cache:"no-store",signal:AbortSignal.timeout(15000)})
  ]),underlying=Number(quotes.quotes[symbol]?.last||0);
  if(!underlying)throw new Error("A current underlying price is required before evaluating options.");
  if(!response.ok)throw new Error("The option-chain provider rejected the request ("+response.status+").");
  return{underlying,asOf:quotes.asOf,quoteSource:quotes.quotes[symbol]?.source,payload:await response.json() as{snapshots?:Record<string,Snap>}};
 })();
 snapshotCache.set(key,{expires:now+30000,promise});
 try{return await promise}catch(error){snapshotCache.delete(key);throw error}
}
const bullish=new Set(["BUY_NOW","BUY_IF","ADD"]),bearish=new Set(["SELL_NOW","SELL_IF","TRIM"]);

const optionAdapter:DecisionModelAdapter=async(input,quality)=>{
 const contract=input.features.selectedContract as J,thesis=input.features.underlyingThesis as J|null,cash=Number((input.features.account as J).available_cash_cents||0)/100,premium=Number(contract.maximumPremiumRisk||0),maxRisk=Number(input.features.maxRisk||0),contracts=premium>0?Math.floor(Math.min(cash,maxRisk)/premium):0,type=String(contract.type),aligned=type==="CALL"?bullish.has(String(thesis?.action||"")):bearish.has(String(thesis?.action||"")),liquid=contract.liquidityQuality!=="POOR"&&Number(contract.spreadPct)<=18,score=Math.max(0,Math.min(100,Number(contract.score||0))),confidence=Math.round(Math.min(score,Number(thesis?.confidence||0),quality.score)),catalystGate=input.features.catalystGate as J,catalystPass=catalystGate?.pass===true,action=aligned&&liquid&&contracts>0&&confidence>=60&&catalystPass?"BUY_IF":"WAIT",entry=Number(contract.ask||0),stop=entry?Number((entry*.55).toFixed(2)):null,targets=entry?[Number((entry*1.5).toFixed(2)),Number((entry*2).toFixed(2))]:[];
 const direction=type==="CALL"?"bullish":"bearish",reasoning=[`Catalyst gate: ${catalystGate?.status||"UNAVAILABLE"} — ${catalystGate?.summary||"Current catalyst coverage is required"}`,`Latest Swing thesis: ${thesis?.action||"not available"} at ${thesis?.confidence||0}% confidence`,`Contract score ${score}/100; ${contract.liquidityQuality} liquidity; spread ${Number(contract.spreadPct||0).toFixed(1)}%`,`Account premium capacity supports ${contracts} contract${contracts===1?"":"s"} within the $${maxRisk.toFixed(2)} cap`];
 return{action,ticker:input.ticker,accountId:input.accountId,strategy:"OPTIONS",shares:action==="BUY_IF"?Math.min(contracts,1):0,entry,trigger:entry,stop,targets,confidence,confidenceBand:confidence>=85?"VERY_HIGH":confidence>=70?"HIGH":confidence>=50?"MEDIUM":"LOW",bull:{probability:type==="CALL"?45:25,priceZone:type==="CALL"?`Option premium toward $${targets[0]||0}`:"Underlying bearish thesis weakens",confirmation:`Underlying ${direction} Swing thesis remains confirmed`,invalidation:`Option premium <= $${stop||0}`},base:{probability:35,priceZone:"No trade until trigger and liquidity confirm",confirmation:"Spread and underlying trigger remain valid",invalidation:"Thesis becomes HOLD or WAIT"},bear:{probability:type==="PUT"?40:20,priceZone:type==="PUT"?`Option premium toward $${targets[0]||0}`:"Option premium can lose 100%",confirmation:`Underlying ${direction} thesis strengthens`,invalidation:`Option premium <= $${stop||0}`},reasoningFactors:reasoning,contradictingEvidence:[...(aligned?[]:[`The ${type} direction does not align with the latest account-specific Swing action.`]),...(catalystPass?[]:(catalystGate?.blockers||["Catalyst coverage did not pass"]))],historicalSimilarity:"Not used as a substitute for the current account thesis, live chain, Greeks, and liquidity.",interpretation:action==="BUY_IF"?`BUY 1 ${type} only if the underlying Swing trigger remains confirmed, the catalyst gate remains clear, and the contract ask is at or below $${entry.toFixed(2)} with spread <= 18%.`:catalystPass?`NO OPTION TRADE — first obtain a current account-specific Swing ${type==="CALL"?"BUY":"SELL"} thesis with at least 60% confidence, then recheck the chain.`:`WAIT FOR CATALYST — ${catalystGate?.blockers?.join("; ")||"current news and earnings evidence is required"}.`,invalidation:`Do not enter if the Swing thesis changes, ask exceeds $${entry.toFixed(2)}, spread exceeds 18%, or premium falls to $${stop||0}.`,risk:"A long option can lose 100% of premium through direction, volatility contraction, or time decay.",expectedCostProceeds:action==="BUY_IF"?premium:null,whatWouldChange:[`A current ${type==="CALL"?"BUY/ADD":"SELL/TRIM"} Swing decision for this account`,`Confidence >= 60% with fresh market evidence`,`Ask <= $${entry.toFixed(2)} and spread <= 18%`,`Available cash and premium-risk capacity for at least one contract`,...(!catalystPass?[`Catalyst gate must be CLEAR: ${catalystGate?.blockers?.join("; ")||"refresh news and earnings"}`]:[])],dataTimestamp:input.dataTimestamp,dataQuality:quality.score,providerFacts:[],modelInferences:reasoning,modelVersion:"northstar-options-account-alignment-1",strategyVersion:"swing-options-1"} satisfies DecisionOutput;
};

export async function POST(request:Request){try{
 await loadRuntimeSecrets();
 const{db,householdId}=await workspace(request),body=await request.json().catch(()=>({})),accountId=String(body.accountId||""),symbol=String(body.symbol||"SPY").toUpperCase().trim(),outlook=body.outlook==="bearish"?"bearish":"bullish",maxRisk=Math.max(50,Math.min(100000,Number(body.maxRisk)||500)),targetDte=Math.max(14,Math.min(365,Number(body.targetDte)||60));
 if(!accountId)return Response.json({error:"Select a Swing investment account before analyzing Calls & Puts."},{status:400});
 const account=await db.prepare("SELECT a.id,COALESCE(a.nickname,a.name) name,COALESCE(s.strategy_type,'CUSTOM') strategy_type,COALESCE(s.available_cash_cents,a.available_balance_cents,0) available_cash_cents,s.policy_json FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=? AND a.type='investment'").bind(accountId,householdId).first<J>();
 if(!account)return Response.json({error:"Investment account not found"},{status:404});
 if(!/SWING|OPTION|MIXED/i.test(String(account.strategy_type)))return Response.json({error:"Options suggestions are available only inside a Swing, Options, or Mixed investment account."},{status:422});
 if(!/^[A-Z.]{1,10}$/.test(symbol))return Response.json({error:"Invalid underlying symbol"},{status:400});
 if(!process.env.ALPACA_API_KEY||!process.env.ALPACA_API_SECRET)return Response.json({error:"Connect Alpaca market data to analyze live option contracts.",status:"not_configured"},{status:503});
 const snapshot=await loadMarketSnapshot(symbol),{underlying,payload}=snapshot,feed=process.env.ALPACA_OPTIONS_FEED||"indicative",now=new Date(),wanted=outlook==="bullish"?"CALL":"PUT",chain=Object.entries(payload.snapshots||{}).flatMap(([contractSymbol,s])=>{const c=decode(contractSymbol);if(!c||c.type!==wanted)return[];const dte=Math.ceil((new Date(`${c.expiration}T20:00:00Z`).getTime()-now.getTime())/86400000),bid=Number(s.latestQuote?.bp||0),ask=Number(s.latestQuote?.ap||0),mid=(bid+ask)/2;if(dte<Math.max(14,targetDte-30)||dte>targetDte+45||bid<=0||ask<=0||ask*100>maxRisk)return[];const spreadPct=mid?((ask-bid)/mid)*100:100,delta=Number(s.greeks?.delta||0),targetDelta=outlook==="bullish"?.45:-.45,volume=Number(s.dailyBar?.v||0),iv=Number(s.impliedVolatility||0),intrinsic=c.type==="CALL"?Math.max(0,underlying-c.strike):Math.max(0,c.strike-underlying),expectedMove=iv?underlying*iv*Math.sqrt(dte/365):null,score=Math.max(0,Math.round(100-Math.abs(delta-targetDelta)*70-Math.min(40,spreadPct)-Math.abs(dte-targetDte)*.3+Math.min(10,Math.log10(volume+1)*4)));return[{contractSymbol,...c,dte,bid,ask,mid,last:Number(s.latestTrade?.p||0)||null,volume,openInterest:Number(s.openInterest||0)||null,impliedVolatility:iv||null,delta:s.greeks?.delta??null,gamma:s.greeks?.gamma??null,theta:s.greeks?.theta??null,vega:s.greeks?.vega??null,rho:s.greeks?.rho??null,intrinsicValue:intrinsic,extrinsicValue:Math.max(0,mid-intrinsic),breakEven:c.type==="CALL"?c.strike+ask:c.strike-ask,expectedMove,midpointContractCost:mid*100,maximumPremiumRisk:ask*100,spreadPct,liquidityQuality:spreadPct<=8&&volume>=10?"GOOD":spreadPct<=18?"FAIR":"POOR",score}]}).sort((a,b)=>b.score-a.score),best=chain[0];
 if(!best)return Response.json({error:"No contract passed expiration, quote, liquidity, and maximum-premium filters."},{status:422});
 const latest=await db.prepare("SELECT output_json,data_timestamp FROM ai_decision_runs WHERE account_id=? AND ticker=? AND strategy='SWING_SHARES' AND status='COMPLETED' ORDER BY data_timestamp DESC LIMIT 1").bind(accountId,symbol).first<J>(),thesisAge=latest?.data_timestamp?Date.now()-new Date(String(latest.data_timestamp)).getTime():Infinity,underlyingThesis=thesisAge<=20*60*1000?parse(latest?.output_json):null,flow=await optionsFlowForSymbol(db,symbol),catalystContext=await loadCatalystContext(symbol),catalystGate=evaluateCatalystEntryGate(catalystContext,{mode:"OPTIONS",contractDte:best.dte,allowEventTrade:false}),asOf=snapshot.asOf;
 const decision=await decideInvestment({householdId,accountId,accountName:account.name,strategy:"OPTIONS",ticker:symbol,requestType:"OPTIONS_SELECTOR",features:{account,maxRisk,institutionalOptionsFlow:flow.summary,catalystGate,underlying:{price:underlying,outlook},underlyingThesis,selectedContract:best,chainSummary:chain.slice(0,20)},evidence:[{label:"catalystGate",value:{...catalystGate,events:catalystContext.events},sourceType:"PROVIDER",sourceId:catalystContext.provider,asOf:catalystContext.asOf},{label:"institutionalOptionsFlow",value:flow.summary,sourceType:"PROVIDER",sourceId:String(flow.summary?.source_mode||"NOT_CONFIGURED"),asOf:flow.summary?.data_as_of||asOf},{label:"underlyingPrice",value:underlying,sourceType:"PROVIDER",sourceId:snapshot.quoteSource,asOf},{label:"underlyingThesis",value:underlyingThesis,sourceType:"MODEL_INFERENCE",sourceId:String(underlyingThesis?.decisionId||"SWING_DECISION"),asOf:latest?.data_timestamp},{label:"optionQuote",value:{bid:best.bid,ask:best.ask,mid:best.mid},sourceType:"PROVIDER",sourceId:"ALPACA_OPTIONS",asOf},{label:"greeks",value:{delta:best.delta,gamma:best.gamma,theta:best.theta,vega:best.vega,rho:best.rho},sourceType:"PROVIDER",sourceId:"ALPACA_OPTIONS",asOf},{label:"liquidity",value:{volume:best.volume,openInterest:best.openInterest,spreadPct:best.spreadPct},sourceType:"CALCULATION",asOf},{label:"accountCash",value:account.available_cash_cents,sourceType:"USER",asOf}],dataTimestamp:asOf,requiredFacts:["underlyingPrice","underlyingThesis","catalystGate","optionQuote","greeks","liquidity","accountCash"]},{db,persist:true,adapter:optionAdapter});
 const contract={...best,contractMultiplier:100,premium:best.ask*100,maxLoss:best.maximumPremiumRisk,breakeven:best.breakEven,iv:best.impliedVolatility},status=decision.action==="BUY_IF"?"CANDIDATE":"NO_TRADE",rationale=[`${best.liquidityQuality} quoted liquidity with a ${best.spreadPct.toFixed(1)}% spread`,`${best.dte} DTE and Delta ${Number(best.delta||0).toFixed(2)} fit the selected window`,`Maximum premium risk $${best.maximumPremiumRisk.toFixed(2)} is within the entered risk cap`,underlyingThesis?`Aligned against latest Swing action ${underlyingThesis.action}`:"No current account-specific Swing thesis is available",catalystGate.summary,flow.summary?.provider_status==="CONNECTED"?"Options-flow evidence was included":"Options-flow evidence is unavailable and did not increase confidence"];
 return Response.json({status,underlying:symbol,underlyingPrice:underlying,account:{id:account.id,name:account.name,strategy:account.strategy_type},outlook,feed,asOf,contract,chain:chain.slice(0,30),rationale,decision,catalystGate,warnings:["Analysis only; no option order is placed.","Calls and Puts use separate short-duration theses from long-term holdings.","Verify live quote, earnings timing, implied-volatility crush, liquidity, taxes, and account permissions."]},{headers:{"Cache-Control":"private, no-store"}});
 }catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Options analysis unavailable"},{status:500})}}