import{loadRuntimeSecrets}from"@/lib/runtime-secrets";
import{freshness,MarketProviderError,type MarketClock,type MarketDataProvider,type MarketSession,type NormalizedBar,type NormalizedQuote}from"@/lib/providers/market-data";
import{marketSessionAt}from"@/lib/market-session";
type Snapshot={latestQuote?:{bp?:number;ap?:number;bs?:number;as?:number;t?:string};latestTrade?:{p?:number;t?:string};dailyBar?:{o?:number;h?:number;l?:number;c?:number;v?:number;t?:string};prevDailyBar?:{c?:number;t?:string}};
export class AlpacaMarketDataProvider implements MarketDataProvider{readonly name="Alpaca";private async config(){await loadRuntimeSecrets();const key=process.env.ALPACA_API_KEY,secret=process.env.ALPACA_API_SECRET;if(!key||!secret)throw new MarketProviderError("Alpaca market data is not configured.",503,"MARKET_DATA_NOT_CONFIGURED");return{headers:{"APCA-API-KEY-ID":key,"APCA-API-SECRET-KEY":secret},feed:process.env.ALPACA_DATA_FEED||"iex"}}
 async getClock():Promise<MarketClock>{const{headers}=await this.config(),base=(process.env.ALPACA_CLOCK_BASE_URL||"https://paper-api.alpaca.markets").replace(/\/(?:v2(?:\/clock)?)?\/?$/,"");const response=await fetch(`${base}/v2/clock`,{headers,cache:"no-store",signal:AbortSignal.timeout(8000)});if(!response.ok){const message=response.status===401||response.status===403?"Alpaca rejected the configured credentials.":response.status===429?"Alpaca rate-limited the market clock. Retry shortly.":response.status>=500?"Alpaca's market clock is temporarily unavailable.":"The official U.S. market clock could not be loaded.";throw new MarketProviderError(message,response.status,"MARKET_CLOCK_UNAVAILABLE")}const value=await response.json()as{timestamp:string;is_open:boolean;next_open:string;next_close:string};return{timestamp:value.timestamp,isOpen:value.is_open,nextOpen:value.next_open,nextClose:value.next_close,session:value.is_open?"REGULAR":marketSessionAt(value.timestamp),source:this.name}}
 async getQuotes(symbols:string[]){const{headers,feed}=await this.config(),clock=await this.getClock().catch(()=>({session:marketSessionAt(Date.now())as MarketSession})),response=await fetch(`https://data.alpaca.markets/v2/stocks/snapshots?symbols=${encodeURIComponent(symbols.join(","))}&feed=${encodeURIComponent(feed)}`,{headers,cache:"no-store",signal:AbortSignal.timeout(8000)});if(!response.ok)throw new MarketProviderError("Current stock quotes could not be loaded.",response.status,"QUOTE_PROVIDER_ERROR");const raw=await response.json()as Record<string,Snapshot>,asOf=new Date().toISOString(),quotes:Record<string,NormalizedQuote>={};for(const symbol of symbols){const value=raw[symbol]||{},timestamp=value.latestQuote?.t||value.latestTrade?.t||value.dailyBar?.t||null,state=freshness(timestamp,clock.session),last=Number(value.latestTrade?.p||value.dailyBar?.c)||null,previousClose=Number(value.prevDailyBar?.c)||null,change=last!==null&&previousClose!==null?last-previousClose:null,changePct=change!==null&&previousClose?change/previousClose*100:null;quotes[symbol]={symbol,bid:Number(value.latestQuote?.bp)||null,ask:Number(value.latestQuote?.ap)||null,last,previousClose,change,changePct,bidSize:Number(value.latestQuote?.bs)||null,askSize:Number(value.latestQuote?.as)||null,open:Number(value.dailyBar?.o)||null,high:Number(value.dailyBar?.h)||null,low:Number(value.dailyBar?.l)||null,volume:Number(value.dailyBar?.v)||null,timestamp,source:this.name,feed,freshness:state.freshness,ageSeconds:state.ageSeconds}}return{feed,asOf,quotes}}
 async getBars(symbol:string,input:{timeframe:string;start:string;limit:number}){const{headers,feed}=await this.config(),response=await fetch(`https://data.alpaca.markets/v2/stocks/${symbol}/bars?timeframe=${encodeURIComponent(input.timeframe)}&start=${encodeURIComponent(input.start)}&limit=${input.limit}&adjustment=all&feed=${encodeURIComponent(feed)}`,{headers,cache:"no-store",signal:AbortSignal.timeout(10000)});if(!response.ok)throw new MarketProviderError("Historical chart data could not be loaded.",response.status,"BAR_PROVIDER_ERROR");const data=await response.json()as{bars?:Array<{t:string;o:number;h:number;l:number;c:number;v:number;vw?:number;n?:number}>},bars:NormalizedBar[]=(data.bars||[]).map(bar=>({time:bar.t,open:bar.o,high:bar.h,low:bar.l,close:bar.c,volume:bar.v,vwap:bar.vw??null,tradeCount:bar.n??null}));return{feed,asOf:new Date().toISOString(),bars}}
}
export const marketDataProvider=()=>new AlpacaMarketDataProvider();
