import{workspace}from"@/lib/db";
import{buildActionGuidance}from"@/lib/domain/action-guidance";
import{calculatePortfolio,strategyTarget,type AllocationCategory}from"@/lib/domain/portfolio";
import type{StrategyType}from"@/lib/domain/investment-accounts";
export const dynamic="force-dynamic";
export async function GET(request:Request){
 try{
  const{db,householdId}=await workspace(request),accountId=new URL(request.url).searchParams.get("accountId");if(!accountId)return Response.json({error:"accountId is required"},{status:400});
  const account=await db.prepare("SELECT a.id,COALESCE(a.nickname,a.name) name,COALESCE(s.strategy_type,'GROWTH_5_7') strategy_type,COALESCE(s.share_mode,'WHOLE') share_mode,COALESCE(s.goal_name,'Build wealth') goal_name,COALESCE(s.horizon_months,60) horizon_months,COALESCE(s.maximum_position_bps,1000) maximum_position_bps,COALESCE(s.available_cash_cents,0) available_cash_cents,s.policy_json FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=? AND a.type='investment'").bind(accountId,householdId).first<any>();if(!account)return Response.json({error:"Investment account not found"},{status:404});
  const[holdings,targets,liabilities,spending,liquid]=await Promise.all([db.prepare("SELECT h.id,s.ticker symbol,s.name,s.type security_type,h.quantity::text,h.price_cents,COALESCE(h.quantity*h.price_cents,0)::bigint market_value_cents,h.cost_basis_cents FROM holdings h JOIN securities s ON s.id=h.security_id WHERE h.account_id=?").bind(accountId).all<any>(),db.prepare("SELECT category,target_bps FROM account_allocation_targets WHERE account_id=?").bind(accountId).all<any>(),db.prepare("SELECT COALESCE(SUM(current_balance_cents),0)::bigint amount FROM liabilities l JOIN entities e ON e.id=l.entity_id WHERE e.household_id=? AND COALESCE(l.apr_bps,0)>=800").bind(householdId).first<any>(),db.prepare("SELECT COALESCE(SUM(amount_cents),0)::bigint amount FROM transactions t JOIN entities e ON e.id=t.entity_id WHERE e.household_id=? AND t.direction='outflow' AND t.excluded=0 AND t.posted_at>=CURRENT_TIMESTAMP-INTERVAL '90 days'").bind(householdId).first<any>(),db.prepare("SELECT COALESCE(SUM(GREATEST(a.current_balance_cents,0)),0)::bigint amount FROM accounts a JOIN entities e ON e.id=a.entity_id WHERE e.household_id=? AND (a.type IN ('depository','cash') OR a.subtype IN ('checking','savings','money market'))").bind(householdId).first<any>()]);
  const custom=Object.fromEntries(targets.results.map((row:any)=>[String(row.category),Number(row.target_bps)]))as Partial<Record<AllocationCategory,number>>,target=strategyTarget(String(account.strategy_type)as StrategyType,Object.keys(custom).length?custom:undefined),debt=BigInt(String(liabilities?.amount||0)),monthlySpending=BigInt(String(spending?.amount||0))/3n,reserveTarget=monthlySpending*6n,liquidCash=BigInt(String(liquid?.amount||0)),reserveGap=reserveTarget>liquidCash?reserveTarget-liquidCash:0n,accountCash=BigInt(String(account.available_cash_cents||0)),safe=debt>0n||reserveGap>0n?0n:accountCash,policy=typeof account.policy_json==="string"?JSON.parse(account.policy_json):account.policy_json||{},goalTarget=policy.goalTargetCents?BigInt(String(policy.goalTargetCents)):null,annualContribution=policy.annualContributionCents?BigInt(String(policy.annualContributionCents)):0n;
  const portfolio=calculatePortfolio({holdings:holdings.results.map((row:any)=>({id:String(row.id),symbol:String(row.symbol||""),name:String(row.name||row.symbol||"Security"),securityType:row.security_type?String(row.security_type):null,quantity:String(row.quantity||"0"),marketValueCents:BigInt(String(row.market_value_cents||0)),priceCents:BigInt(String(row.price_cents||0)),costBasisCents:row.cost_basis_cents==null?null:BigInt(String(row.cost_basis_cents))})),cashCents:accountCash,target,shareMode:account.share_mode,maximumPositionBps:Number(account.maximum_position_bps),safeInvestmentCapacityCents:safe,goalTargetCents:goalTarget,horizonMonths:Number(account.horizon_months),annualContributionCents:annualContribution});
  const guidance=buildActionGuidance({account:{id:account.id,name:account.name,strategyType:account.strategy_type,shareMode:account.share_mode,goalName:account.goal_name,horizonMonths:Number(account.horizon_months),goalTargetCents:goalTarget?.toString()||null,monthlyContributionCents:(annualContribution/12n).toString(),maximumPositionBps:Number(account.maximum_position_bps)},portfolio,safety:{status:debt>0n?"BLOCKED_HIGH_INTEREST_DEBT":reserveGap>0n?"BLOCKED_EMERGENCY_RESERVE":"READY",highInterestDebtCents:debt.toString(),reserveGapCents:reserveGap.toString(),safeInvestmentCapacityCents:safe.toString()}});
  return Response.json({guidance,portfolio,target,householdSafety:{highInterestDebtCents:debt.toString(),reserveGapCents:reserveGap.toString(),safeInvestmentCapacityCents:safe.toString()}},{headers:{"Cache-Control":"private, no-store"}})
 }catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Action guidance unavailable"},{status:500})}
}
