import{workspace}from"@/lib/db";
import{buildActionGuidance,type ActionGuidance,type ActionPriority,type ActionType}from"@/lib/domain/action-guidance";
import{calculatePortfolio,strategyTarget,type AllocationCategory}from"@/lib/domain/portfolio";
import type{StrategyType}from"@/lib/domain/investment-accounts";
export const dynamic="force-dynamic";
const moneyText=(value:unknown)=>`$${(Number(value)/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const capitalSourceText=(cash:bigint,monthly:bigint,safe:bigint)=>{
 const funded=safe<cash+monthly?safe:cash+monthly,fromCash=cash<funded?cash:funded,fromMonthly=funded-fromCash;
 return[fromCash>0n?`Use ${moneyText(fromCash)} from opportunity cash.`:"",fromMonthly>0n?`Use ${moneyText(fromMonthly)} from the next contribution.`:"","Do not use emergency reserves."].filter(Boolean).join(" ");
};
export async function GET(request:Request){
 try{
  const{db,householdId}=await workspace(request),accountId=new URL(request.url).searchParams.get("accountId");if(!accountId)return Response.json({error:"accountId is required"},{status:400});
  const account=await db.prepare("SELECT a.id,COALESCE(a.nickname,a.name) name,COALESCE(s.strategy_type,'GROWTH_5_7') strategy_type,COALESCE(s.share_mode,'WHOLE') share_mode,COALESCE(s.goal_name,'Build wealth') goal_name,COALESCE(s.horizon_months,60) horizon_months,COALESCE(s.maximum_position_bps,1000) maximum_position_bps,COALESCE(s.available_cash_cents,0) available_cash_cents,s.policy_json FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=? AND a.type='investment'").bind(accountId,householdId).first<any>();if(!account)return Response.json({error:"Investment account not found"},{status:404});
  const[holdings,targets,liabilities,spending,liquid]=await Promise.all([db.prepare("SELECT h.id,s.ticker symbol,s.name,s.type security_type,h.quantity::text,h.price_cents,COALESCE(h.quantity*h.price_cents,0)::bigint market_value_cents,h.cost_basis_cents FROM holdings h JOIN securities s ON s.id=h.security_id WHERE h.account_id=?").bind(accountId).all<any>(),db.prepare("SELECT category,target_bps FROM account_allocation_targets WHERE account_id=?").bind(accountId).all<any>(),db.prepare("SELECT COALESCE(SUM(current_balance_cents),0)::bigint amount FROM liabilities l JOIN entities e ON e.id=l.entity_id WHERE e.household_id=? AND COALESCE(l.apr_bps,0)>=800").bind(householdId).first<any>(),db.prepare("SELECT COALESCE(SUM(amount_cents),0)::bigint amount FROM transactions t JOIN entities e ON e.id=t.entity_id WHERE e.household_id=? AND t.direction='outflow' AND t.excluded=0 AND t.posted_at>=CURRENT_TIMESTAMP-INTERVAL '90 days'").bind(householdId).first<any>(),db.prepare("SELECT COALESCE(SUM(GREATEST(a.current_balance_cents,0)),0)::bigint amount FROM accounts a JOIN entities e ON e.id=a.entity_id WHERE e.household_id=? AND (a.type IN ('depository','cash') OR a.subtype IN ('checking','savings','money market'))").bind(householdId).first<any>()]);
  const custom=Object.fromEntries(targets.results.map((row:any)=>[String(row.category),Number(row.target_bps)]))as Partial<Record<AllocationCategory,number>>,target=strategyTarget(String(account.strategy_type)as StrategyType,Object.keys(custom).length?custom:undefined),debt=BigInt(String(liabilities?.amount||0)),monthlySpending=BigInt(String(spending?.amount||0))/3n,reserveTarget=monthlySpending*6n,liquidCash=BigInt(String(liquid?.amount||0)),reserveGap=reserveTarget>liquidCash?reserveTarget-liquidCash:0n,accountCash=BigInt(String(account.available_cash_cents||0)),safe=debt>0n||reserveGap>0n?0n:accountCash,policy=typeof account.policy_json==="string"?JSON.parse(account.policy_json):account.policy_json||{},goalTarget=policy.goalTargetCents?BigInt(String(policy.goalTargetCents)):null,annualContribution=policy.annualContributionCents?BigInt(String(policy.annualContributionCents)):0n;
  const portfolio=calculatePortfolio({holdings:holdings.results.map((row:any)=>({id:String(row.id),symbol:String(row.symbol||""),name:String(row.name||row.symbol||"Security"),securityType:row.security_type?String(row.security_type):null,quantity:String(row.quantity||"0"),marketValueCents:BigInt(String(row.market_value_cents||0)),priceCents:BigInt(String(row.price_cents||0)),costBasisCents:row.cost_basis_cents==null?null:BigInt(String(row.cost_basis_cents))})),cashCents:accountCash,target,shareMode:account.share_mode,maximumPositionBps:Number(account.maximum_position_bps),safeInvestmentCapacityCents:safe,goalTargetCents:goalTarget,horizonMonths:Number(account.horizon_months),annualContributionCents:annualContribution});
  const guidance=buildActionGuidance({account:{id:account.id,name:account.name,strategyType:account.strategy_type,shareMode:account.share_mode,goalName:account.goal_name,horizonMonths:Number(account.horizon_months),goalTargetCents:goalTarget?.toString()||null,monthlyContributionCents:(annualContribution/12n).toString(),maximumPositionBps:Number(account.maximum_position_bps)},portfolio,safety:{status:debt>0n?"BLOCKED_HIGH_INTEREST_DEBT":reserveGap>0n?"BLOCKED_EMERGENCY_RESERVE":"READY",highInterestDebtCents:debt.toString(),reserveGapCents:reserveGap.toString(),safeInvestmentCapacityCents:safe.toString()}});
  const validatedRecommendations=await db.prepare("SELECT DISTINCT ON (r.security_id) r.id,s.ticker symbol,r.action,r.actionable,r.suggested_quantity::text quantity,r.entry_low_cents::text,r.entry_high_cents::text,r.ideal_price_cents::text,r.invalidation_cents::text,r.targets_json,r.confidence,r.reason,r.lifecycle,r.evidence_as_of,r.expires_at FROM recommendations r JOIN securities s ON s.id=r.security_id WHERE r.account_id=? AND r.household_id=? AND r.lifecycle IN ('MONITORING','TRIGGERED') AND r.expires_at>CURRENT_TIMESTAMP ORDER BY r.security_id,r.created_at DESC").bind(accountId,householdId).all<any>();
  const recommendationActions:ActionGuidance[]=validatedRecommendations.results.map((row:any)=>{const buy=["STRONG_BUY","BUY","BUY_PARTIAL","ACCUMULATE"].includes(row.action),sell=["SELL","EXIT"].includes(row.action),reduce=["REDUCE","TAKE_PARTIAL_PROFIT"].includes(row.action),entry=row.entry_low_cents&&row.entry_high_cents?`${moneyText(row.entry_low_cents)}–${moneyText(row.entry_high_cents)}`:row.ideal_price_cents?moneyText(row.ideal_price_cents):"No validated price range",ready=row.actionable===true&&row.lifecycle==="TRIGGERED",funded=buy&&ready&&safe>0n,action:ActionType=buy?(funded?"BUY_NOW":ready?"DO_NOTHING":"WAIT_FOR_PRICE"):sell?"SELL":reduce?"REDUCE":row.action==="HOLD"?"HOLD":"PLACE_ON_WATCH",priority:ActionPriority=action==="BUY_NOW"||sell||reduce?"ACTION_NOW":buy?"READY_IF_PRICE_TRIGGERS":"WATCH";return{rank:0,priority,action,symbol:row.symbol,quantity:funded||sell||reduce?row.quantity:"0",amountCents:"0",priceCondition:buy?`Entry ${entry}${row.ideal_price_cents?` · preferred ${moneyText(row.ideal_price_cents)}`:""}`:row.invalidation_cents?`Review if price crosses ${moneyText(row.invalidation_cents)}`:"Review current verified price",when:funded?"All stored checks passed and the condition triggered — verify the live quote before acting":ready?"Conditions passed, but account funding is unavailable":"Wait until the entry trigger and every required evidence check pass",why:`${row.reason} Confidence ${row.confidence}%.${row.actionable===true?" Required evidence passed.":" This is research only; required evidence is incomplete."}`,capitalSource:funded?capitalSourceText(accountCash,annualContribution/12n,safe):buy?"No purchase yet: the evidence gate, price trigger, or household funding check has not passed.":"If proceeds are confirmed, hold them until an underweight destination independently qualifies.",lifecycle:ready?"TRIGGERED":"MONITORING"}});
  const thesisRisks=await db.prepare("SELECT s.ticker symbol,t.state,t.thesis,t.invalidation,h.quantity::text quantity,COALESCE(h.quantity*h.price_cents,0)::bigint market_value_cents FROM investment_theses t JOIN securities s ON s.id=t.security_id JOIN holdings h ON h.account_id=t.account_id AND h.security_id=t.security_id WHERE t.account_id=? AND t.state IN ('WEAKENING','BROKEN') ORDER BY CASE t.state WHEN 'BROKEN' THEN 0 ELSE 1 END").bind(accountId).all<any>();
  const thesisActions=thesisRisks.results.map((row:any,index:number)=>({rank:index+1,priority:row.state==="BROKEN"?"CRITICAL":"ACTION_NOW",action:row.state==="BROKEN"?"SELL":"HOLD",symbol:row.symbol,quantity:row.state==="BROKEN"?row.quantity:"0",amountCents:String(row.market_value_cents),priceCondition:row.state==="BROKEN"?"Review at a verified current price; do not sell solely from this label":"Pause additions until the thesis review passes",when:"Review now",why:row.state==="BROKEN"?`THESIS BROKEN — ${row.thesis}. Invalidation evidence: ${row.invalidation}`:`THESIS WEAKENING — ${row.thesis}.`,capitalSource:row.state==="BROKEN"?"If you confirm a sale, retain proceeds until the Action Guidance Engine identifies an underweight, fully evaluated destination.":"No purchase funding while the thesis is weakening.",lifecycle:"PROPOSED"}));
  if(recommendationActions.length){guidance.today=[...recommendationActions,...guidance.today].slice(0,7);guidance.queue=[...recommendationActions,...guidance.queue]}
  if(thesisActions.length){const typedThesisActions=thesisActions as typeof guidance.today;guidance.today=[...typedThesisActions,...guidance.today].slice(0,7);guidance.queue=[...typedThesisActions,...guidance.queue]}
  guidance.queue=guidance.queue.map((action,index)=>({...action,rank:index+1}));guidance.today=guidance.today.map((action,index)=>({...action,rank:index+1}));
  return Response.json({guidance,portfolio,target,householdSafety:{highInterestDebtCents:debt.toString(),reserveGapCents:reserveGap.toString(),safeInvestmentCapacityCents:safe.toString()}},{headers:{"Cache-Control":"private, no-store"}})
 }catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Action guidance unavailable"},{status:500})}
}
