import {workspace} from "@/lib/db";
export const dynamic="force-dynamic";
type Row=Record<string,any>;
const n=(value:unknown)=>Number(value||0);
export async function GET(request:Request){
 try{
  const{db,householdId}=await workspace(request),[propertyResult,loanResult,paymentResult,householdResult]=await Promise.all([
   db.prepare(`SELECT p.id,p.property_type,p.purchase_price_cents,p.estimated_value_cents,p.monthly_rent_cents,p.monthly_expenses_cents,p.acquisition_date,p.updated_at,(SELECT ps.estimated_value_cents FROM property_snapshots ps WHERE ps.property_id=p.id ORDER BY ps.captured_at DESC LIMIT 1) snapshot_value_cents,(SELECT ps.captured_at FROM property_snapshots ps WHERE ps.property_id=p.id ORDER BY ps.captured_at DESC LIMIT 1) snapshot_at FROM properties p JOIN entities e ON e.id=p.entity_id WHERE e.household_id=?`).bind(householdId).all<Row>(),
   db.prepare(`SELECT p.id property_id,COALESCE(NULLIF(linked.debt_cents,0),manual.debt_cents,0) debt_cents,COALESCE(manual.monthly_payment_cents,0) monthly_payment_cents,(COALESCE(linked.link_count,0)>0 OR COALESCE(manual.loan_count,0)>0) debt_available FROM properties p JOIN entities e ON e.id=p.entity_id LEFT JOIN (SELECT l.property_id,SUM(ABS(a.current_balance_cents)) debt_cents,COUNT(*) link_count FROM property_account_links l JOIN accounts a ON a.id=l.account_id WHERE l.active=TRUE AND l.role IN ('MORTGAGE_PAYMENT','LOAN') GROUP BY l.property_id) linked ON linked.property_id=p.id LEFT JOIN (SELECT property_id,SUM(current_balance_cents) debt_cents,SUM(monthly_payment_cents) monthly_payment_cents,COUNT(*) loan_count FROM property_loans GROUP BY property_id) manual ON manual.property_id=p.id WHERE e.household_id=?`).bind(householdId).all<Row>(),
   db.prepare(`SELECT l.property_id,COALESCE(AVG(m.monthly_total),0) observed_payment_cents FROM property_account_links l JOIN properties p ON p.id=l.property_id JOIN entities e ON e.id=p.entity_id JOIN (SELECT account_id,DATE_TRUNC('month',posted_at::timestamptz) month,SUM(amount_cents) monthly_total FROM transactions WHERE direction='outflow' AND posted_at::timestamptz>=CURRENT_TIMESTAMP-INTERVAL '6 months' AND (COALESCE(merchant,'')||' '||description)~*'(mortgage|home loan|loan payment)' GROUP BY account_id,DATE_TRUNC('month',posted_at::timestamptz)) m ON m.account_id=l.account_id WHERE e.household_id=? AND l.active=TRUE AND l.role IN ('MORTGAGE_PAYMENT','LOAN') GROUP BY l.property_id`).bind(householdId).all<Row>(),
   db.prepare(`SELECT COALESCE(SUM(CASE WHEN a.type IN ('depository','checking','savings') AND a.current_balance_cents>0 THEN a.current_balance_cents ELSE 0 END),0) liquid_cents,(SELECT COALESCE(SUM(CASE WHEN t.direction='inflow' THEN t.amount_cents ELSE 0 END),0)/3 FROM transactions t JOIN entities te ON te.id=t.entity_id WHERE te.household_id=? AND t.posted_at::timestamptz>=CURRENT_TIMESTAMP-INTERVAL '3 months') monthly_income_cents,(SELECT COALESCE(SUM(CASE WHEN t.direction='outflow' AND t.excluded=0 THEN t.amount_cents ELSE 0 END),0)/3 FROM transactions t JOIN entities te ON te.id=t.entity_id WHERE te.household_id=? AND t.posted_at::timestamptz>=CURRENT_TIMESTAMP-INTERVAL '3 months') monthly_outflow_cents FROM accounts a JOIN entities e ON e.id=a.entity_id WHERE e.household_id=?`).bind(householdId,householdId,householdId).first<Row>(),
  ]),loans=new Map(loanResult.results.map(row=>[String(row.property_id),row])),payments=new Map(paymentResult.results.map(row=>[String(row.property_id),row])),household=householdResult||{},monthlyIncome=n(household.monthly_income_cents)/100,monthlyOutflow=n(household.monthly_outflow_cents)/100,liquid=n(household.liquid_cents)/100,protectedReserve=Math.max(monthlyOutflow*3,1000);
  const insights=propertyResult.results.map(property=>{const loan=loans.get(String(property.id))||{},observed=payments.get(String(property.id))||{},snapshot=n(property.snapshot_value_cents),recorded=n(property.estimated_value_cents),purchase=n(property.purchase_price_cents),acquired=property.acquisition_date?new Date(property.acquisition_date):null,years=acquired&&Number.isFinite(acquired.getTime())?Math.max(0,(Date.now()-acquired.getTime())/(365.25*86400000)):0,annualModel=/LAND|COMMERCIAL/.test(String(property.property_type||""))?.025:.03,modeled=snapshot||recorded||(purchase>0?Math.round(purchase*Math.pow(1+annualModel,Math.min(years,30))):0),confidence=snapshot?"MEDIUM":recorded?"USER PROVIDED":purchase&&acquired?"LOW":purchase?"BASELINE ONLY":"UNAVAILABLE",rangePct=snapshot?.08:recorded?.1:.15,modelRate=snapshot||recorded||!acquired?0:annualModel,monthlyPayment=(n(loan.monthly_payment_cents)||n(observed.observed_payment_cents))/100,operating=n(property.monthly_expenses_cents)/100,rent=n(property.monthly_rent_cents)/100,netHousingCost=Math.max(0,monthlyPayment+operating-rent),paymentToIncome=monthlyIncome?netHousingCost/monthlyIncome*100:null,projectedFreeCash=monthlyIncome-monthlyOutflow,status=monthlyPayment+operating>0&&liquid<monthlyPayment+operating?"CRITICAL":paymentToIncome!==null&&paymentToIncome>35?"WARNING":paymentToIncome!==null&&paymentToIncome>28||projectedFreeCash<netHousingCost?"WATCH":"HEALTHY";return{propertyId:property.id,estimatedValueCents:modeled,estimatedValueLowCents:Math.round(modeled*(1-rangePct)),estimatedValueHighCents:Math.round(modeled*(1+rangePct)),valuationSource:snapshot?"Latest saved valuation snapshot":recorded?"User-provided current value":purchase&&acquired?"Purchase price projected from acquisition date":purchase?"Purchase price baseline; add purchase date or current valuation":"No valuation basis is saved",valuationConfidence:confidence,annualModelPct:modelRate*100,monthlyPaymentCents:Math.round(monthlyPayment*100),monthlyOperatingCents:Math.round(operating*100),monthlyRentCents:Math.round(rent*100),netHousingCostCents:Math.round(netHousingCost*100),paymentToIncomePct:paymentToIncome,projectedFreeCashCents:Math.round(projectedFreeCash*100),protectedReserveCents:Math.round(protectedReserve*100),liquidCashCents:Math.round(liquid*100),debtCents:n(loan.debt_cents),debtAvailable:Boolean(loan.debt_available),status,reason:status==="CRITICAL"?"Liquid household cash does not cover one recorded month of property payments and operating costs.":status==="WARNING"?`Net property cost is ${paymentToIncome?.toFixed(1)}% of observed household income.`:status==="WATCH"?"Property cost or projected free cash is approaching the household safety threshold.":"Observed income, spending and liquid reserves currently support the recorded property cost."}});
  return Response.json({asOf:new Date().toISOString(),household:{monthlyIncomeCents:Math.round(monthlyIncome*100),monthlyOutflowCents:Math.round(monthlyOutflow*100),liquidCashCents:Math.round(liquid*100),protectedReserveCents:Math.round(protectedReserve*100)},insights},{headers:{"Cache-Control":"private, max-age=300"}});
 }catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Property insights unavailable"},{status:500})}
}
