import { workspace, id } from "@/lib/db";
import { createRecommendation, recommendationActions, requiredEvidenceKeys, type RecommendationAction, type RecommendationEvidence, type RecommendationLifecycle } from "@/lib/domain/recommendations";
export const dynamic = "force-dynamic";
type Json = Record<string, unknown>;
const lifecycles = new Set<RecommendationLifecycle>(["MONITORING","TRIGGERED","EXPIRED","CANCELLED","INVALIDATED","COMPLETED","MISSED"]);
const triggerTypes = new Set(["PRICE_AT_OR_ABOVE","PRICE_AT_OR_BELOW","PRICE_CROSSES_ABOVE","PRICE_CROSSES_BELOW","EVIDENCE_REFRESH"]);
const objectOf=(value:unknown):Json=>value&&typeof value==="object"&&!Array.isArray(value)?value as Json:{};
const arrayOf=(value:unknown):unknown[]=>Array.isArray(value)?value:[];
const cents=(value:unknown):string|null|number=>value==null||value===""?null:/^\d+$/.test(String(value))?BigInt(String(value)).toString():NaN;
async function accountFor(db:any,accountId:string,householdId:string){return db.prepare("SELECT a.id,COALESCE(s.strategy_type,a.investment_purpose,'GENERAL') strategy_type,COALESCE(s.share_mode,'WHOLE') share_mode FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=? AND a.type='investment'").bind(accountId,householdId).first()}
async function securityFor(db:any,symbol:string){return db.prepare("SELECT id,ticker,name FROM securities WHERE ticker=? ORDER BY id LIMIT 1").bind(symbol).first()as Promise<{id:string;ticker:string;name:string}|null>}

export async function GET(request:Request){
 try{
  const{db,householdId}=await workspace(request),url=new URL(request.url),accountId=url.searchParams.get("accountId"),symbol=String(url.searchParams.get("symbol")||"").trim().toUpperCase(),clauses=["r.household_id=?"],values:unknown[]=[householdId];
  if(accountId){clauses.push("r.account_id=?");values.push(accountId)}if(symbol){clauses.push("s.ticker=?");values.push(symbol)}if(url.searchParams.get("active")!=="false")clauses.push("r.lifecycle IN ('MONITORING','TRIGGERED') AND r.expires_at>CURRENT_TIMESTAMP");
  const result=await db.prepare(`SELECT r.id,r.account_id,s.ticker symbol,s.name,r.strategy_type,r.action,r.lifecycle,r.suggested_quantity::text,r.entry_low_cents::text,r.entry_high_cents::text,r.ideal_price_cents::text,r.invalidation_cents::text,r.targets_json,r.confidence,r.reason,r.checks_json,r.actionable,r.model_version,r.evidence_as_of,r.expires_at,r.created_at,COALESCE(json_agg(json_build_object('id',t.id,'type',t.trigger_type,'condition',t.condition_json,'status',t.status,'triggeredAt',t.triggered_at,'lastEvaluatedAt',t.last_evaluated_at) ORDER BY t.id) FILTER (WHERE t.id IS NOT NULL),'[]') triggers FROM recommendations r JOIN securities s ON s.id=r.security_id LEFT JOIN recommendation_triggers t ON t.recommendation_id=r.id WHERE ${clauses.join(" AND ")} GROUP BY r.id,s.ticker,s.name ORDER BY r.created_at DESC LIMIT 100`).bind(...values).all();
  return Response.json({recommendations:result.results},{headers:{"Cache-Control":"private, no-store"}})
 }catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Recommendations unavailable"},{status:500})}
}

export async function POST(request:Request){
 try{
  const{db,householdId}=await workspace(request),body=await request.json()as Json,accountId=String(body.accountId||""),symbol=String(body.symbol||"").trim().toUpperCase(),account=await accountFor(db,accountId,householdId);
  if(!account)return Response.json({error:"Investment account not found"},{status:404});if(!recommendationActions.includes(body.action as RecommendationAction))return Response.json({error:"Invalid recommendation action"},{status:400});
  const checks={}as RecommendationEvidence,supplied=objectOf(body.requiredChecks);for(const key of requiredEvidenceKeys){const value=String(supplied[key]);if(!["PASS","FAIL","MISSING","STALE"].includes(value))return Response.json({error:`Required evidence check ${key} is missing or invalid`},{status:400});checks[key]=value as RecommendationEvidence[typeof key]}
  const entryLow=cents(body.entryLowCents),entryHigh=cents(body.entryHighCents),ideal=cents(body.idealPriceCents),invalidation=cents(body.invalidationCents),targets=arrayOf(body.targetCents).map(cents);if([entryLow,entryHigh,ideal,invalidation,...targets].some(Number.isNaN))return Response.json({error:"Prices must be integer-cent strings"},{status:400});
  const decision=createRecommendation({accountId,symbol,action:body.action as RecommendationAction,suggestedQuantity:String(body.suggestedQuantity||"0"),shareMode:account.share_mode,entryRange:entryLow!==null&&entryHigh!==null?{low:Number(entryLow)/100,high:Number(entryHigh)/100}:null,idealPrice:ideal===null?null:Number(ideal)/100,invalidation:invalidation===null?null:Number(invalidation)/100,targets:targets.map(value=>Number(value)/100),confidence:Number(body.confidence),reason:String(body.reason||""),requiredChecks:checks,evidenceAsOf:String(body.evidenceAsOf||""),expiresAt:String(body.expiresAt||""),lifecycle:"MONITORING"});
  let security=await securityFor(db,symbol);if(!security){await db.prepare("INSERT INTO securities(id,ticker,name,type,currency) VALUES(?,?,?,'stock','USD') ON CONFLICT(ticker,type) DO NOTHING").bind(id("security"),symbol,symbol).run();security=await securityFor(db,symbol)}if(!security)return Response.json({error:"Security could not be resolved"},{status:500});
  const recommendationId=id("recommendation"),triggers=arrayOf(body.triggers).map(objectOf);for(const trigger of triggers)if(!triggerTypes.has(String(trigger.type)))return Response.json({error:"Invalid trigger"},{status:400});
  await db.transaction(async tx=>{await tx.prepare("UPDATE recommendations SET lifecycle='INVALIDATED' WHERE household_id=? AND account_id=? AND security_id=? AND lifecycle IN ('MONITORING','TRIGGERED')").bind(householdId,accountId,security!.id).run();await tx.prepare("INSERT INTO recommendations(id,household_id,account_id,security_id,strategy_type,action,lifecycle,suggested_quantity,entry_low_cents,entry_high_cents,ideal_price_cents,invalidation_cents,targets_json,confidence,reason,checks_json,actionable,model_version,evidence_as_of,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(recommendationId,householdId,accountId,security!.id,String(account.strategy_type),decision.action,decision.lifecycle,decision.suggestedQuantity,entryLow,entryHigh,ideal,invalidation,JSON.stringify(targets),decision.confidence,decision.reason,JSON.stringify(checks),decision.actionable,String(body.modelVersion||"northstar-rules-v1"),decision.evidenceAsOf,decision.expiresAt).run();for(const trigger of triggers)await tx.prepare("INSERT INTO recommendation_triggers(id,recommendation_id,trigger_type,condition_json,cooldown_until,status) VALUES(?,?,?,?,?,'MONITORING')").bind(id("recommendation_trigger"),recommendationId,String(trigger.type),JSON.stringify(objectOf(trigger.condition)),trigger.cooldownUntil||null).run()});
  return Response.json({id:recommendationId,action:decision.action,actionable:decision.actionable,blockers:requiredEvidenceKeys.filter(key=>checks[key]!=="PASS")},{status:201})
 }catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Recommendation could not be saved"},{status:400})}
}

export async function PATCH(request:Request){try{const{db,householdId}=await workspace(request),body=await request.json()as{recommendationId?:string;lifecycle?:RecommendationLifecycle};if(!body.recommendationId||!body.lifecycle||!lifecycles.has(body.lifecycle))return Response.json({error:"recommendationId and valid lifecycle are required"},{status:400});const updated=await db.prepare("UPDATE recommendations SET lifecycle=? WHERE id=? AND household_id=? RETURNING id,lifecycle").bind(body.lifecycle,body.recommendationId,householdId).first();return updated?Response.json(updated):Response.json({error:"Recommendation not found"},{status:404})}catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Recommendation could not be updated"},{status:400})}}
