import {intelligenceProof} from '@/lib/market-intelligence-queue';
import {workspace} from '@/lib/db';
import {scheduleNextSession,nextSessionStatus} from '@/lib/next-session-intelligence';
import {startAccountSearch} from '@/lib/account-market-search';
import {queueDiscoveryRefresh} from '@/lib/discovery-queue';
import {queueOptionResearch} from '@/lib/options-research-queue';
export const dynamic='force-dynamic';
async function context(request:Request,accountId:string){const ctx=await workspace(request);if(!await ctx.db.prepare("SELECT a.id FROM accounts a JOIN entities e ON e.id=a.entity_id WHERE a.id=? AND e.household_id=? AND a.type='investment' AND a.hidden=0").bind(accountId,ctx.householdId).first())throw Response.json({error:'Account not found'},{status:404});return ctx;}
export async function GET(request:Request){try{const accountId=new URL(request.url).searchParams.get('accountId')||'',{db}=await context(request,accountId);return Response.json({cycle:await nextSessionStatus(db,accountId),proof:await intelligenceProof(db,accountId).catch(()=>null)},{headers:{'Cache-Control':'private, no-store'}});}catch(e){if(e instanceof Response)return e;return Response.json({error:'Next-session research unavailable; saved plans are preserved'},{status:503});}}
export async function POST(request:Request){try{const body=await request.json(),accountId=String(body.accountId||''),{db,householdId}=await context(request,accountId),action=String(body.action||'REFRESH_MARKET');if(!['REFRESH_MARKET','REFRESH_ACCOUNT','RETRY','PRIORITIZE','REFRESH_TICKER'].includes(action))return Response.json({error:'Unsupported research action'},{status:400});
 const cycleId=await scheduleNextSession(db,Date.now(),true);if(!cycleId)return Response.json({error:'No supported completed exchange session'},{status:503});
 if(action==='REFRESH_MARKET')await db.transaction(async tx=>{const row=await tx.prepare('SELECT status FROM next_session_cycles WHERE id=? FOR UPDATE').bind(cycleId).first<any>();if(row?.status==='SCREENED'){await tx.prepare("UPDATE next_session_symbols SET status='QUEUED' WHERE cycle_id=?").bind(cycleId).run();await tx.prepare("UPDATE next_session_cycles SET status='QUEUED',context_at=NULL,revision=revision+1 WHERE id=?").bind(cycleId).run();}});
 if(action==='REFRESH_ACCOUNT'){const state=await nextSessionStatus(db,accountId);const run=await startAccountSearch(db,householdId,accountId,true,state?.counts_json.pending===0?cycleId:undefined);return Response.json({...run,cycleId},{status:202});}
 if(action==='RETRY'){await db.prepare("UPDATE next_session_cycles SET status='QUEUED',last_error=NULL WHERE id=? AND status='FAILED'").bind(cycleId).run();await db.prepare("UPDATE next_session_symbols SET status='QUEUED' WHERE cycle_id=? AND status IN ('UNAVAILABLE','STALE')").bind(cycleId).run();await db.prepare("UPDATE background_jobs SET status='QUEUED',attempts=0,available_at=CURRENT_TIMESTAMP WHERE job_type='ACCOUNT_OPPORTUNITY_REVIEW' AND household_id=? AND payload_json->>'accountId'=? AND status IN ('DEAD','FAILED') AND payload_json->>'runId'=(SELECT id FROM account_search_runs WHERE household_id=? AND account_id=? ORDER BY created_at DESC LIMIT 1)").bind(householdId,accountId,householdId,accountId).run();}
 if(action==='PRIORITIZE'||action==='REFRESH_TICKER'){const symbol=String(body.symbol||'').trim().toUpperCase();if(!/^[A-Z][A-Z0-9.-]{0,11}$/.test(symbol))return Response.json({error:'Valid supported ticker required'},{status:400});if(!await queueDiscoveryRefresh(db,symbol))return Response.json({error:'Ticker is not in the supported active universe'},{status:404});await db.prepare("UPDATE next_session_symbols SET priority=200,status='QUEUED' WHERE cycle_id=? AND symbol=?").bind(cycleId,symbol).run();await queueOptionResearch(db,householdId,accountId,symbol,true,200);}
 return Response.json({status:'QUEUED',cycleId,message:'Server research queued; saved plans remain visible.'},{status:202});
 }catch(e){if(e instanceof Response)return e;return Response.json({error:'Research request failed; retry preserves saved results'},{status:503});}}
