import type {Metadata} from "next";
import Link from "next/link";
import "./privacy.css";

export const metadata:Metadata={title:"Privacy Policy — Northstar",description:"How Northstar collects, uses, protects, and deletes personal and financial information."};

const effective="September 4, 2026";

export default function PrivacyPolicy(){return <main className="privacy-page">
  <header className="privacy-header"><Link href="/" className="privacy-brand"><span>N</span><b>NORTHSTAR</b></Link><Link href="/" className="privacy-return">← Return to Northstar</Link></header>
  <article className="privacy-document">
    <div className="privacy-title"><p>LEGAL &amp; DATA PRACTICES</p><h1>Privacy Policy</h1><span>Effective {effective} · Last updated {effective}</span></div>
    <aside><b>Plain-language summary</b><p>Northstar is a Bogaso LLC website and a private, read-only family financial-intelligence application. We use information you authorize to organize household finances, analyze investments, and provide educational decision support. Northstar does not move money or execute trades.</p></aside>

    <section><h2>1. Scope and operator</h2><p>Northstar is a website owned and operated by Bogaso LLC. This policy explains how Bogaso LLC, through Northstar (collectively, "Northstar," "we," "us," or "our"), handles information when an authorized family user accesses the Northstar web application or connects a financial institution through Plaid. Northstar is currently an owner-managed application intended for limited family use, not a bank, broker-dealer, investment adviser, or money transmitter.</p></section>

    <section><h2>2. Information we collect</h2><h3>Account and household information</h3><p>We process identity information supplied through AWS Cognito or a configured identity provider, such as name, email address, authentication identifiers, household membership, invitations, roles, and access status.</p><h3>Financial information you authorize</h3><p>When you connect an institution through Plaid, we may receive account names and types, partial account identifiers, balances, available credit, transactions, merchants and categories, liabilities, investment holdings, quantities, cost basis, and institution-provided prices. The exact information depends on the accounts you select, the institution, your consent, and the Plaid products enabled for Northstar.</p><h3>Information you provide</h3><p>We process settings, budgets, goals, account nicknames and purposes, watchlists, journal entries, simulated trades, invitations, uploaded educational documents, questions submitted to the investment coach, and other information you intentionally enter.</p><h3>Technical information</h3><p>Our hosting, authentication, and security providers may process ordinary service data such as IP address, browser type, timestamps, authentication events, request identifiers, diagnostic logs, and security signals.</p></section>

    <section><h2>3. How we use information</h2><p>We use information to authenticate users; enforce household permissions; connect and synchronize authorized accounts; calculate balances, cash flow, liabilities, allocations, and portfolio metrics; provide alerts, educational analysis, market context, simulations, and user-requested coaching; prevent duplicate or unauthorized access; diagnose failures; protect the service; and comply with applicable obligations.</p><p>Northstar uses financial information for the functionality the user requests. It does not sell personal information, execute transactions, or use Plaid data for advertising.</p></section>

    <section><h2>4. Plaid</h2><p>Northstar uses Plaid Link to let you authorize access to selected financial accounts. Your institution credentials are entered into Plaid or your institution's OAuth experience and are not provided to Northstar. Northstar receives a provider access token and the data types you authorize. Plaid handles information under its own <a href="https://plaid.com/legal/#consumers" target="_blank" rel="noreferrer">End User Privacy Policy</a>. You can also review and manage eligible connections through <a href="https://my.plaid.com" target="_blank" rel="noreferrer">Plaid Portal</a>.</p></section>

    <section><h2>5. Service providers and disclosures</h2><p>We disclose information only as needed to operate requested functionality, protect users, or comply with law. Current service providers may include AWS for hosting, authentication, secret management, and PostgreSQL storage; Plaid for financial connections; configured market-data and news providers for market information; Resend for transactional email when enabled; and OpenAI for a user-requested coaching response. Coach requests are sent only when a user invokes that feature, are limited by the application context provided with the request, and are submitted with API storage disabled.</p><p>We may disclose information when reasonably necessary to respond to lawful process, protect rights or safety, investigate misuse, or maintain service security. We do not share Plaid-derived consumer data with other household users unless their authenticated Northstar role grants access to the same household workspace.</p></section>

    <section><h2>6. Storage and security</h2><p>Northstar uses HTTPS/TLS for data in transit, an AWS RDS trust certificate for database-server verification, AWS-managed encryption at rest when enabled on the deployed database, AWS Secrets Manager for server credentials, application-level encryption for Plaid access tokens, Cognito authentication, and household-scoped role checks. Access to production infrastructure is intended to follow least-privilege permissions.</p><p>No system can guarantee absolute security. Users must protect their identity-provider account, enable multi-factor authentication when available, use trusted devices, and promptly report suspected unauthorized access.</p></section>

    <section><h2>7. Retention, disconnection, and deletion</h2><p>We retain information while it is needed to provide the family workspace, maintain security and audit continuity, resolve disputes, or meet applicable requirements. An authorized user can remove a connected institution in Northstar. The application then requests revocation of that Plaid Item and deletes the connection's synchronized accounts, holdings, and transactions from Northstar. Plaid may retain information under its own policy and legal obligations.</p><p>To request correction, access, household removal, or deletion of other Northstar information, contact us using the address below. We may need to verify identity and authority over the relevant household before acting. Some limited security, audit, backup, or legal records may be retained where reasonably necessary.</p></section>

    <section><h2>8. Household access and children</h2><p>Household owners control invitations and roles. Users should grant only the minimum access necessary and should not share invitation links publicly. Northstar's financial-account connection and personalized investment features are not directed to children. Any youth use of educational materials must be supervised by a parent or legal guardian, and children should not connect financial accounts or submit personal financial information.</p></section>

    <section><h2>9. Your choices</h2><p>You may choose not to connect an institution, select which eligible accounts to share during Plaid Link, disconnect an institution, decline browser notifications, or stop using Northstar. Revoking a Northstar connection does not close or alter the underlying bank or brokerage account.</p></section>

    <section><h2>10. Changes</h2><p>We may update this policy as Northstar's features, providers, or legal obligations change. The updated version will appear at this URL with a revised effective date. Material changes should be communicated to authorized users before materially different processing begins.</p></section>

    <section><h2>11. Contact</h2><p>For privacy, security, access, or deletion requests concerning the Northstar website, contact Bogaso LLC's Northstar owner and information-security lead at <a href="mailto:jose.linarest@gmail.com">jose.linarest@gmail.com</a>. Do not include bank credentials, passwords, full account numbers, security answers, or authentication codes in an email.</p></section>

    <footer><p>This policy describes Northstar's current application practices and is not a substitute for independent legal advice.</p><Link href="/">Return to secure sign-in →</Link></footer>
  </article>
</main>}
