import type {Metadata} from "next";
import Link from "next/link";
import "./privacy.css";

export const metadata:Metadata={title:"Privacy Policy — Northstar by Bogaso LLC",description:"How Bogaso LLC's Northstar website collects, uses, protects, shares, retains, and deletes personal and financial information."};

const effective="September 4, 2026";

export default function PrivacyPolicy(){return <main className="privacy-page">
  <header className="privacy-header"><Link href="/" className="privacy-brand"><span>N</span><b>NORTHSTAR</b></Link><Link href="/" className="privacy-return">← Return to Northstar</Link></header>
  <article className="privacy-document">
    <div className="privacy-title"><p>LEGAL &amp; DATA PRACTICES</p><h1>Privacy Policy</h1><span>Effective {effective} · Last updated {effective}</span></div>
    <aside><b>Plain-language summary</b><p>Northstar is a Bogaso LLC website and a private, invitation-only family financial-intelligence application. It helps authorized household members organize finances, review connected investment accounts, study market information, and use educational planning tools. Northstar does not hold customer funds, move money, or execute trades. This summary is provided for convenience; the complete policy below controls.</p></aside>

    <section><h2>1. Scope and operator</h2><p>Northstar is a website owned and operated by Bogaso LLC. This policy explains how Bogaso LLC, through Northstar (collectively, "Northstar," "we," "us," or "our"), collects, uses, discloses, protects, and retains information when an authorized user visits the website, signs in, joins a household, uses financial tools, or connects an eligible financial institution through Plaid.</p><p>Northstar is currently intended for limited family use. It is not a bank, broker-dealer, registered investment adviser, money transmitter, tax adviser, or custodian. Market analysis, forecasts, simulations, alerts, and AI-generated explanations are educational decision-support tools and are not guarantees or instructions to transact.</p></section>

    <section><h2>2. Invitation-only accounts and household access</h2><p>A Google identity verified through AWS Cognito is not, by itself, enough to obtain a valid Northstar workspace. Except for a controlled local-development bootstrap account, a user must receive a valid invitation sent to the same email address used for authentication. Invitations may add a person to an existing household with a defined role or authorize the recipient to create a separate household as its owner.</p><p>Each household is logically separated. A user can access another household only if that user has been expressly added to it. Household owners and co-owners may invite or remove members and assign available roles. Roles may restrict a user to read-only access, account connection, household management, investment planning, or educational features. Invitation creation, acceptance, revocation, and certain administrative actions may be recorded for security and accountability.</p></section>

    <section><h2>3. Information we collect</h2><h3>Identity and account information</h3><p>We process information received through AWS Cognito and the configured Google identity provider, which may include your name, email address, provider subject identifier, authentication timestamps, session information, invitation status, household membership, role, and access status. Northstar does not receive your Google password.</p><h3>Financial information you authorize</h3><p>When you connect an institution through Plaid, Northstar may receive institution and account names, account type and subtype, partial account identifiers, ownership information made available by the institution, balances, available credit, credit limits, transactions, merchants, categories, liabilities, payment information, investment holdings, security identifiers, quantities, cost basis, and institution-provided prices. The precise information depends on the accounts you select, the institution, your consent, and the Plaid products enabled for Northstar.</p><h3>Information you provide directly</h3><p>We process information you intentionally enter or upload, such as account nicknames and purposes, household settings, budgets, goals, watchlists, price-review levels, journal entries, simulated trades, notes, invitations, educational progress, uploaded documents, and questions submitted to the investment coach.</p><h3>Market and derived information</h3><p>Northstar may combine authorized account information with market prices, company fundamentals, economic data, and news obtained from configured providers. It may derive calculations such as net worth, cash flow, debt totals, investment allocation, gains or losses, risk indicators, technical indicators, simulated performance, and educational suggestions. Derived results may be incomplete or inaccurate when source data is delayed, missing, or incorrect.</p><h3>Technical and security information</h3><p>Northstar and its providers may process IP address, browser and device type, operating system, approximate location inferred from an IP address, timestamps, requested pages, authentication events, error details, request identifiers, security signals, and server logs needed to operate, troubleshoot, and protect the service.</p></section>

    <section><h2>4. Sources of information</h2><p>Information may come directly from you; from a household owner who invites you or manages shared records; from Google and AWS Cognito during authentication; from Plaid and the financial institutions you choose to connect; from market-data, economic-data, and news providers; and from hosting, email, security, and diagnostic services used to operate Northstar. Information visible in a shared household may have been entered or connected by another authorized household member.</p></section>

    <section><h2>5. How we use information</h2><p>We use information to:</p><ul><li>authenticate users and enforce invitation, membership, and role restrictions;</li><li>create and operate isolated household workspaces;</li><li>connect and synchronize accounts that a user expressly authorizes;</li><li>organize balances, transactions, bills, liabilities, holdings, and household records;</li><li>calculate cash flow, net worth, portfolio allocation, performance, technical indicators, and simulated outcomes;</li><li>provide watchlists, alerts, market context, educational analysis, and user-requested coaching;</li><li>remember settings such as timezone, household selection, and notification preferences;</li><li>send invitations, security messages, and operational notices when configured;</li><li>prevent duplicate records, investigate errors or misuse, secure the application, and preserve appropriate audit continuity; and</li><li>comply with applicable legal obligations and protect the rights, safety, and integrity of Bogaso LLC, users, and providers.</li></ul><p>Northstar does not sell personal information, use Plaid-derived financial data for advertising, or use connected accounts to initiate payments or trades.</p></section>

    <section><h2>6. Plaid and connected financial institutions</h2><p>Northstar uses Plaid Link to let you authorize access to selected financial accounts. Institution credentials, security answers, and one-time authentication codes are entered into Plaid or the institution's own OAuth experience and are not provided to Northstar. Northstar receives a Plaid access token and the account data you authorize. That token is intended to be encrypted before storage and is used only by the server to request permitted data.</p><p>Your use of Plaid is also governed by Plaid's <a href="https://plaid.com/legal/#consumers" target="_blank" rel="noreferrer">End User Privacy Policy</a> and applicable terms. Plaid explains that available data can vary by product and institution and may include data from multiple accounts accessible with the same institution credentials. You can review eligible connections through <a href="https://my.plaid.com" target="_blank" rel="noreferrer">Plaid Portal</a>.</p><p>Disconnecting an institution from Northstar does not close or modify the underlying account. Institution availability, refresh frequency, OAuth requirements, and data accuracy are controlled in part by Plaid and the financial institution.</p></section>

    <section><h2>7. Artificial intelligence and automated analysis</h2><p>When an authorized user asks the Northstar investment coach for analysis, Northstar may send the user's question and a limited application context to OpenAI through its API. The request is configured with API response storage disabled. OpenAI still processes the submitted content to generate the requested response and protect its service under its applicable business terms and privacy practices.</p><p>Do not place bank credentials, complete account numbers, Social Security numbers, authentication codes, security answers, or other unnecessary sensitive information in an AI prompt. AI responses may contain mistakes and must be verified against current primary data. Northstar does not allow an AI response to execute a transaction, transfer funds, or change an external financial account.</p></section>

    <section><h2>8. Household sharing</h2><p>Financial and planning information in a household workspace is shared with authenticated users whose active role grants access to that household. This may include records connected by a spouse or another household member. Owners should select the least-privileged role appropriate for each person and promptly remove access that is no longer needed.</p><p>A person who belongs to more than one household may switch between those households, but the data is not automatically combined. Bogaso LLC does not intentionally expose one household's information to another household. Users must not forward invitation links, share sessions, or attempt to access a workspace for which they lack authorization.</p></section>

    <section><h2>9. Service providers and disclosures</h2><p>We disclose information only as reasonably needed to provide requested functionality, protect the service, or comply with law. Providers may include AWS for hosting, authentication, secret management, logging, and PostgreSQL infrastructure; Plaid for financial-data connectivity; configured market, fundamentals, economic, and news providers; Resend or another configured provider for transactional email; and OpenAI for user-requested coaching responses.</p><p>These providers process information under their own agreements and privacy terms. AWS publishes an <a href="https://aws.amazon.com/privacy/" target="_blank" rel="noreferrer">AWS Privacy Notice</a>. We may also disclose information when reasonably necessary to comply with valid legal process, investigate fraud or misuse, protect rights or safety, enforce applicable terms, or support a corporate transaction involving Bogaso LLC, subject to appropriate safeguards and applicable law.</p></section>

    <section><h2>10. Cookies, sessions, and local device storage</h2><p>Northstar uses browser storage and authentication session mechanisms to maintain sign-in state, protect the OAuth flow, remember the selected household, preserve a pending invitation during sign-in, store certain interface preferences, and support features such as local notifications or educational progress. These technologies are used for service operation and security rather than behavioral advertising.</p><p>Clearing browser data may sign you out, remove unsynchronized local preferences, or interrupt a pending invitation flow. Blocking required storage may prevent authentication or application features from working correctly.</p></section>

    <section><h2>11. Data retention, disconnection, and deletion</h2><p>We retain information for as long as reasonably needed to provide the household workspace, maintain security and audit continuity, resolve disputes, enforce agreements, or meet applicable legal obligations. Retention varies by data type and operational need. We do not promise a fixed deletion period unless one is separately communicated or required by law.</p><p>When an authorized user removes a connected institution, Northstar is designed to request revocation of the corresponding Plaid Item and delete that connection's synchronized accounts, holdings, and transactions from the active Northstar database. Plaid, the financial institution, infrastructure providers, logs, and backups may retain information under their own policies or for limited security, recovery, contractual, or legal purposes.</p><p>To request access, correction, household removal, or deletion of other Northstar information, use the contact information below. We may need to verify your identity, invited email, household role, and authority before completing a request. Deletion may be limited when retention is reasonably necessary for security, fraud prevention, audit integrity, legal compliance, or the rights of another household member.</p></section>

    <section><h2>12. Security practices</h2><p>Northstar uses safeguards intended to protect information, including HTTPS/TLS in transit, AWS RDS certificate verification for database connections, AWS-managed encryption at rest when enabled for deployed infrastructure, AWS Secrets Manager for server credentials, application-level encryption for Plaid access tokens, Cognito authentication, invitation-only onboarding, household-scoped queries, role-based authorization, restricted server-side credentials, and audit records for selected security-sensitive actions.</p><p>No method of transmission or storage is completely secure, and Bogaso LLC cannot guarantee absolute security. Users should protect their Google account, enable multi-factor authentication where available, use trusted devices, avoid sharing invitation links or sessions, review household membership regularly, and promptly report suspected unauthorized access.</p></section>

    <section><h2>13. Your choices and privacy requests</h2><p>Depending on your location and applicable law, you may have rights to request access to, correction of, deletion of, or information about certain personal data. You may also choose not to connect an institution, select eligible accounts during Plaid Link, disconnect an institution, decline browser notifications, remove locally stored preferences, or stop using Northstar.</p><p>We will evaluate verified requests under applicable law. Northstar is currently a limited family application, and not every statutory privacy right applies in every situation. We will not discriminate against a person for making a legally protected privacy request.</p></section>

    <section><h2>14. Children and educational use</h2><p>Northstar's financial-account connection and personalized investment features are not directed to children. Educational sections and paper-trading simulations may be used by a child only under the supervision of a parent or legal guardian and through an appropriately restricted role. Children should not connect financial accounts or submit personal financial information, credentials, or sensitive identity information. A parent or guardian who believes a child supplied information improperly should contact us.</p></section>

    <section><h2>15. United States operation and international access</h2><p>Northstar and its providers operate primarily through infrastructure and services in the United States. If you access Northstar from another jurisdiction, information may be transferred to and processed in the United States or other locations where providers operate. Those locations may have data-protection rules different from those in your jurisdiction.</p></section>

    <section><h2>16. External links and third-party services</h2><p>Northstar may link to provider policies, market sources, financial institutions, or other third-party websites. Bogaso LLC does not control those services and this policy does not govern their independent practices. Review their privacy notices before providing information directly to them.</p></section>

    <section><h2>17. Changes to this policy</h2><p>We may update this policy as Northstar's features, providers, ownership information, security practices, or legal obligations change. The revised policy will be posted at this URL with an updated date. Material changes should be communicated to authorized users before materially different processing begins when reasonably practicable or required by law.</p></section>

    <section><h2>18. Contact Bogaso LLC</h2><p>For privacy, security, access, correction, or deletion requests concerning the Northstar website, contact Bogaso LLC's Northstar owner and information-security lead at <a href="mailto:jose.linarest@gmail.com">jose.linarest@gmail.com</a>. Include enough information to identify your invited account and the household involved, but do not email bank credentials, passwords, full account numbers, Social Security numbers, security answers, or authentication codes.</p></section>

    <footer><p>This policy describes Northstar's current application practices and is not a substitute for independent legal advice. Bogaso LLC should have qualified counsel review this policy before offering Northstar broadly to paying customers or the public.</p><Link href="/">Return to secure sign-in →</Link></footer>
  </article>
</main>}
