"use client";
import {useEffect,useState} from 'react';
import type {AcademyBar} from '@/lib/academy-curriculum';
type R=Record<string,any>;
export default function AcademyLab({accessToken}:{accessToken?:string}){
 const [dashboard,setDashboard]=useState<R|null>(null),[session,setSession]=useState<R|null>(null),[feedback,setFeedback]=useState<R|null>(null),[value,setValue]=useState(''),[module,setModule]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[count,setCount]=useState(0),[total,setTotal]=useState(5),[trade,setTrade]=useState(''),[mode,setMode]=useState('daily');
 const headers=()=>({'Content-Type':'application/json',...(accessToken?{Authorization:'Bearer '+accessToken}:{}),...(localStorage.getItem('northstar-household-id')?{'X-Household-ID':localStorage.getItem('northstar-household-id')!}:{})});
 const api=async(body?:R)=>{const r=await fetch('/api/academy',{method:body?'POST':'GET',headers:headers(),...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Academy no disponible. Reintenta.');return d;};
 const load=async()=>{try{setDashboard(await api())}catch(e){setNotice((e as Error).message)}};
 useEffect(()=>{void load();const p=new URLSearchParams(location.search);if(p.get('module'))setModule(p.get('module')!);if(p.get('tradeId')){setTrade(p.get('tradeId')!);setMode('trade')}},[accessToken]);
 const start=async(next=false)=>{setBusy(true);setNotice('');try{const p=new URLSearchParams(location.search);setSession(await api({action:'start',module:module||undefined,concept:!next?p.get('concept'):undefined,step:next?count:0,source:mode==='case'?'case':mode==='market'?'market':mode==='trade'?'trade':undefined,tradeId:trade}));setFeedback(null);setValue('');if(!next)setCount(0);}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}};
 const submit=async()=>{setBusy(true);setNotice('');try{setFeedback(await api({action:'answer',sessionId:session?.sessionId,value}));setCount(c=>c+1);await load()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}};
 const q=session?.question,skills=dashboard?.skills||[],mastered=skills.filter((s:R)=>s.mastered).length;
 return <div className="academy-studio"><header className="academy-hero"><div><span>NORTHSTAR ACADEMY</span><h2>Observa. Decide. Aprende.</h2><p>Práctica original en español · technical terms en English · ningún ejercicio envía una orden.</p></div><a href="/workspace/simulation">Practice Simulator ↗</a></header>
 <div className="academy-stats"><article><small>Exercises completed</small><b>{dashboard?.completed??'—'}</b></article><article><small>Accuracy</small><b>{dashboard?dashboard.accuracy+'%':'—'}</b></article><article><small>Mastery by skill</small><b>{mastered} / {skills.length||'—'}</b></article><article><small>Current level</small><b>{mastered<10?'Beginner':mastered<30?'Intermediate':mastered<50?'Advanced':'Professional Practice'}</b></article></div>
 <section className="academy-practice-controls"><label>Práctica<select value={mode} onChange={e=>{setMode(e.target.value);setTotal(['weekly','case'].includes(e.target.value)?10:5)}}><option value="daily">Daily · 5 ejercicios adaptativos</option><option value="weekly">Weekly review · 10 ejercicios</option><option value="exam">Module exam · 5 ejercicios</option><option value="case">Full-market case · 10 decisiones Options</option><option value="market">Practice With Today’s Market</option><option value="trade">Learn From My Trade</option></select></label><label>Módulo<select value={module} onChange={e=>setModule(e.target.value)}><option value="">Recommended next lesson · habilidades débiles</option>{dashboard?.modules.map((m:R)=><option key={m.id} value={m.id}>{m.level} · {m.title}</option>)}</select></label>{mode==='trade'&&<label>Trade privado<select value={trade} onChange={e=>setTrade(e.target.value)}><option value="">Selecciona un trade completado</option>{dashboard?.trades.map((t:R)=><option key={t.id} value={t.id}>{t.ticker} · {t.id.slice(-6)}</option>)}</select></label>}<button disabled={busy||!dashboard||(mode==='exam'&&!module)||(mode==='trade'&&!trade)} onClick={()=>start()}>Comenzar práctica →</button></section>
 {notice&&<p className="academy-notice" role="alert">{notice} <button disabled={busy} onClick={()=>dashboard?start():load()}>Reintentar</button></p>}
 {q&&<section className="academy-exercise"><div className="academy-exercise-heading"><span>{q.level} · {q.concept}</span><b>{Math.min(count+(!feedback?1:0),total)} / {mode==='market'||mode==='trade'?1:total}</b></div><h3>{q.task}</h3><p>{q.explanation}</p><small>{q.source} · {q.timeframe}</small>{q.facts&&<dl className="academy-facts">{Object.entries(q.facts).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl>}
 <ExerciseChart bars={q.bars} future={feedback?.future} mode={q.mode} value={value} setValue={setValue} feedback={feedback}/>
 <details><summary>Datos OHLC / Volume · accesibles en móvil</summary><div style={{overflowX:"auto"}}><table><thead><tr><th>Vela</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th></tr></thead><tbody>{q.bars.map((b:AcademyBar,i:number)=><tr key={i}><td>{i+1}</td><td>{b.open}</td><td>{b.high}</td><td>{b.low}</td><td>{b.close}</td><td>{b.volume}</td></tr>)}</tbody></table></div></details><div className="academy-answer">{q.mode==='choice'?q.choices.map((c:string,i:number)=><button disabled={!!feedback||busy} className={value===String(i)?'selected':''} onClick={()=>setValue(String(i))} key={i}>{c}</button>):<label>{q.mode==='candle'?'Número de vela (1–30)':q.mode==='price'?'Nivel marcado en el chart':'Respuesta '+(q.unit||'')}<input type="number" step="any" value={q.mode==='candle'&&value!==''?Number(value)+1:value} disabled={!!feedback||busy} onChange={e=>setValue(q.mode==='candle'&&e.target.value!==''?String(Number(e.target.value)-1):e.target.value)}/></label>}{!feedback&&<button disabled={busy||value===''} onClick={submit}>{busy?'Guardando…':'Confirmar y revelar solución'}</button>}</div>
 {feedback&&<div className={'academy-feedback '+(feedback.correct?'correct':'review')} role="status"><h3>{feedback.correct?'✓ Correcto':'Repasemos el razonamiento'}</h3><b>Respuesta: {feedback.answer}</b><p>{feedback.reason}</p>{feedback.alternatives?.length>0&&<details><summary>Por qué cada alternativa</summary>{feedback.alternatives.map((a:R)=><p key={a.choice}><b>{a.choice}</b> — {a.reason}</p>)}</details>}<p>{q.connection}</p><p>{feedback.outcome?.label} {feedback.outcome?.first!=null&&feedback.outcome?.last!=null&&`Close ${Number(feedback.outcome.first).toFixed(2)} → ${Number(feedback.outcome.last).toFixed(2)}`}</p>{feedback.outcome?.actualOutcome&&<details><summary>Recomendación original y resultado real</summary><p>Resultado realizado: {feedback.outcome.actualOutcome.actual?.realizedResult??"No disponible"} · Exit price: {feedback.outcome.actualOutcome.actual?.exitPrice??"No disponible"}</p><p>{feedback.outcome.actualOutcome.entryAssessment}</p><p>{feedback.outcome.actualOutcome.stopAssessment}</p>{feedback.outcome.actualOutcome.lessons?.map((lesson:string,i:number)=><p key={i}>{lesson}</p>)}<p>Recomendación original: {predictionText(feedback.outcome.originalRecommendation)}</p></details>}{count<total&&mode!=='market'&&mode!=='trade'?<button disabled={busy} onClick={()=>start(true)}>Siguiente escenario →</button>:<b>Práctica completada. Tu progreso está guardado.</b>}</div>}
 </section>}
 <section className="academy-progress"><h3>Tu mapa de habilidades</h3><p>Mastery requiere al menos 5 respuestas y el umbral de aciertos en las últimas 10. Los errores vuelven en 24 horas con otro gráfico; las habilidades fuertes se espacian entre 2 y 14 días. Todos los módulos siguen accesibles.</p><label>Mastery threshold <select value={dashboard?.threshold||80} disabled={busy} onChange={async e=>{setBusy(true);try{await api({action:'settings',threshold:Number(e.target.value)});await load()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}}>{[60,70,80,90,100].map(n=><option key={n} value={n}>{n}%</option>)}</select></label><div className="academy-modules">{dashboard?.modules.map((m:R)=>{const ss=skills.filter((s:R)=>m.concepts.includes(s.concept));return <details key={m.id}><summary>{m.title}<small>{m.level} · {ss.filter((s:R)=>s.mastered).length}/{ss.length} mastered</small></summary>{ss.map((s:R)=><div className="academy-skill" key={s.concept}><span>{s.concept} {s.due?'· Repasar hoy':''}</span><progress max="100" value={s.accuracy}/><small>{s.attempts?`${s.accuracy}% · ${s.attempts} respuestas`:'Sin practicar'}</small></div>)}<button onClick={()=>{setModule(m.id);setMode('exam');setNotice('Módulo seleccionado. Pulsa Comenzar práctica.')}}>Practicar módulo</button></details>})}</div></section><details><summary>Fuentes y método</summary><p>90 escenarios originales de Northstar. Los charts NORTHSTAR-SIM son sintéticos y no representan cotizaciones reales. Los históricos identifican ticker y corte. SMC es una hipótesis de Price Action, no prueba de intención institucional.</p>{dashboard?.references.map((r:R)=><p key={r.url}><a href={r.url} target="_blank" rel="noreferrer">{r.title} ↗</a></p>)}</details></div>;
}
function ExerciseChart({bars,future,mode,value,setValue,feedback}:{bars:AcademyBar[];future?:AcademyBar[];mode:string;value:string;setValue:(v:string)=>void;feedback:R|null}){
 const all=[...bars,...(future||[])],lo=Math.min(...all.map(b=>b.low))-5,hi=Math.max(...all.map(b=>b.high))+5,width=800,height=300,step=700/(bars.length+8),x=(i:number)=>50+i*step+step/2,y=(p:number)=>20+(hi-p)/(hi-lo)*240,selected=Number(value),interactive=!feedback&&(mode==='price'||mode==='candle');
 return <div className="academy-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Gráfico de velas. Para marcar, pulsa el gráfico o usa el campo numérico debajo." onClick={e=>{if(!interactive)return;const r=e.currentTarget.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*width,py=(e.clientY-r.top)/r.height*height;setValue(mode==='candle'?String(Math.max(0,Math.min(bars.length-1,Math.floor((px-50)/step)))):String(Math.max(lo,Math.min(hi,hi-(py-20)/240*(hi-lo))).toFixed(2)))}}>
 {[0,1,2,3,4].map(i=>{const p=lo+(hi-lo)*i/4;return <g key={i}><line x1="45" x2="765" y1={y(p)} y2={y(p)} stroke="#dce8e2"/><text x="5" y={y(p)+4} fontSize="10">{p.toFixed(1)}</text></g>})}
 {all.map((b,i)=><g key={i} opacity={i>=bars.length?.65:1}><line x1={x(i)} x2={x(i)} y1={y(b.high)} y2={y(b.low)} stroke={b.close>=b.open?'#117d62':'#c75d4b'}/><rect x={x(i)-step*.3} y={y(Math.max(b.open,b.close))} width={step*.6} height={Math.max(1,Math.abs(y(b.open)-y(b.close)))} fill={b.close>=b.open?'#117d62':'#c75d4b'}/>{i%5===0&&<text x={x(i)} y="282" textAnchor="middle" fontSize="9">{i+1}</text>}<title>{b.time} · O {b.open} H {b.high} L {b.low} C {b.close} · Volume {b.volume}</title></g>)}
 <line x1={x(bars.length)-step/2} x2={x(bars.length)-step/2} y1="15" y2="264" stroke="#83958c" strokeDasharray="4 4"/>
 <text x={x(bars.length)+4} y="15" fontSize="10">{feedback?'Resultado':'Futuro oculto'}</text>
 {value!==''&&mode==='price'&&<line x1="45" x2="765" y1={y(selected)} y2={y(selected)} stroke="#906bde" strokeWidth="2"/>}
 {value!==''&&mode==='candle'&&<rect x={x(selected)-step/2} y="20" width={step} height="240" fill="#906bde" opacity=".18"/>}
 {feedback?.solution.mode==='price'&&<g><line x1="45" x2="765" y1={y(feedback.solution.value)} y2={y(feedback.solution.value)} stroke="#04774f" strokeDasharray="6 3" strokeWidth="3"/><text x="50" y={y(feedback.solution.value)-6} fontSize="11">Solución {feedback.solution.value.toFixed(2)}</text></g>}
 {feedback?.solution.mode==='candle'&&<rect x={x(feedback.solution.value)-step/2} y="20" width={step} height="240" fill="none" stroke="#04774f" strokeWidth="3"/>}
 </svg><small>{interactive?'Pulsa para marcar; puedes ajustar el valor debajo. ':''}Vela 1 → {bars.length} · OHLC y volumen disponibles al señalar cada vela.</small></div>;
}

function predictionText(value:unknown):string{if(typeof value==="string")return value;if(!value||typeof value!=="object")return "No hay recomendación contemporánea guardada";const r=value as R;const text=[r.action,r.recommendation,r.reason,r.interpretation,r.attribution].filter(v=>typeof v==="string");return text.length?text.join(" · "):"Evidencia guardada sin una acción textual verificable; consulta Post-Trade Review."}
