"use client";
import {useEffect,useMemo,useState} from 'react';
const usd=(n:number)=>n.toLocaleString(undefined,{style:'currency',currency:'USD'});
export default function AccountGrowthChart({accountId,accessToken}:{accountId:string;accessToken:string}){
 const[data,setData]=useState<any>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[range,setRange]=useState(365),[mode,setMode]=useState('value'),[index,setIndex]=useState<number|null>(null);
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');setIndex(null);fetch(`/api/investments/performance?accountId=${encodeURIComponent(accountId)}`,{signal:controller.signal,cache:'no-store',headers:accessToken?{Authorization:`Bearer ${accessToken}`}:{}}).then(async r=>{if(!r.ok)throw Error('Unable to load account history');return r.json()}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[accountId,accessToken,refresh]);
 const points=useMemo(()=>(data?.snapshots||[]).filter((p:any)=>Date.parse(p.captured_at)>=Date.now()-range*86400000).map((p:any)=>({...p,time:Date.parse(p.captured_at),value:Number(p.market_value_cents)/100+Number(p.cash_cents)/100,basis:Number(p.cost_basis_cents)/100,pnl:Number(p.cost_basis_cents)>0?(Number(p.market_value_cents)-Number(p.cost_basis_cents))/100:null})),[data,range]);
 const chosen=points[Math.min(index??points.length-1,points.length-1)],valid=points.filter((p:any)=>mode==='value'||p.pnl!==null),values=valid.map((p:any)=>mode==='value'?p.value:p.pnl),low=Math.min(0,...values),high=Math.max(1,...values),start=points[0]?.time||0,end=points.at(-1)?.time||start+1,x=(t:number)=>60+(t-start)/Math.max(1,end-start)*800,y=(v:number)=>220-(v-low)/(high-low)*180;
 const events=(data?.transactions||[]).filter((t:any)=>Date.parse(t.trade_at)>=Math.max(start,Date.now()-range*86400000)&&Date.parse(t.trade_at)<=end);
 return <details open style={{margin:'16px 0',padding:16,border:'1px solid #bfd4ca',borderRadius:12,minWidth:0,background:'#f5faf7'}}><summary style={{cursor:'pointer',fontWeight:700}}>Account growth · value, gain/loss and purchases</summary>
 <div style={{display:'flex',flexWrap:'wrap',gap:10,margin:'12px 0'}}><label>Period <select aria-label="Period" value={range} onChange={e=>{setRange(Number(e.target.value));setIndex(null)}}><option value={30}>1 month</option><option value={90}>3 months</option><option value={365}>1 year</option><option value={100000}>Available history</option></select></label><label>View <select aria-label="View" value={mode} onChange={e=>setMode(e.target.value)}><option value="value">Account value</option><option value="pnl">Unrealized gain / loss</option></select></label><button onClick={()=>setRefresh(n=>n+1)}>Refresh history</button></div>
 {error?<p role="alert">{error}</p>:!data?<p>Loading account history…</p>:!points.length?<p>No recorded valuations in this period. History appears as account snapshots are collected; past balances are not reconstructed from today’s holdings.</p>:<>
 <p aria-live="polite"><b>{new Date(chosen.time).toLocaleString()}</b> · Value {usd(chosen.value)} · Unrealized P/L {chosen.pnl===null?'Cost basis unavailable':usd(chosen.pnl)}{chosen.basis>0&&chosen.pnl!==null?` (${(chosen.pnl/chosen.basis*100).toFixed(2)}% of recorded cost)`:''}</p>
 <svg viewBox="0 0 900 270" role="img" aria-label={`${mode==='value'?'Account value':'Unrealized gain and loss'} history; use the timeline slider for exact values`} style={{display:'block',width:'100%',height:'auto',background:'white',borderRadius:8}} onPointerMove={e=>{const rect=e.currentTarget.getBoundingClientRect(),time=start+Math.max(0,Math.min(1,((e.clientX-rect.left)/rect.width*900-60)/800))*(end-start);setIndex(points.reduce((best:number,p:any,i:number)=>Math.abs(p.time-time)<Math.abs(points[best].time-time)?i:best,0))}}>
 {[0,.5,1].map(f=>{const value=low+(high-low)*f;return <g key={f}><line x1="60" x2="860" y1={y(value)} y2={y(value)} stroke="#d5e3dc"/><text x="4" y={y(value)-4} fontSize="12">{usd(value)}</text></g>})}
 <path d={points.map((p:any,i:number)=>{const v=mode==='value'?p.value:p.pnl;if(v===null)return '';const prev=points[i-1];return `${i===0||(mode==='pnl'&&prev?.pnl===null)?'M':'L'}${x(p.time)},${y(v)}`}).join(' ')} fill="none" stroke="#087856" strokeWidth="3"/>
 {valid.map((p:any)=><circle key={p.time} cx={x(p.time)} cy={y(mode==='value'?p.value:p.pnl)} r="3" fill="#087856"/>)}
 {events.filter((t:any)=>['BUY','SELL'].includes(t.transaction_type)).map((t:any)=><circle key={t.id} cx={x(Date.parse(t.trade_at))} cy="235" r="5" fill={t.transaction_type==='BUY'?'#087856':'#b35429'}><title>{t.transaction_type} {t.quantity} {t.ticker} · {new Date(t.trade_at).toLocaleString()} · {usd(Math.abs(Number(t.amount_cents))/100)}</title></circle>)}
 <line x1={x(chosen.time)} x2={x(chosen.time)} y1="30" y2="225" stroke="#667c72" strokeDasharray="4 4"/><text x="60" y="263" fontSize="12">{new Date(start).toLocaleDateString()}</text><text x="860" y="263" textAnchor="end" fontSize="12">{new Date(end).toLocaleDateString()}</text></svg>
 <label style={{display:'block'}}>Explore valuation date<input aria-label="Explore valuation date" type="range" min="0" max={Math.max(0,points.length-1)} value={Math.min(index??points.length-1,points.length-1)} onChange={e=>setIndex(Number(e.target.value))} style={{display:'block',width:'100%'}}/></label><small>Green markers: purchases · Orange: sales. One recorded valuation per UTC day. {points.length===1?'Only one valuation is available; a trend needs more history.':''} Recorded values can be delayed. Account value includes cash and deposits; it is not investment return. P/L uses recorded cost basis for held positions and excludes realized gains, dividends and taxes; incomplete basis may distort it.</small>
 <details><summary>Transaction timeline · {events.length} events in chart period</summary>{events.length?<div style={{maxHeight:300,overflow:'auto'}}>{events.map((t:any)=><p key={t.id}>{new Date(t.trade_at).toLocaleDateString()} · <b>{t.transaction_type} {t.ticker||''}</b> {t.quantity?`${t.quantity} shares`:''} · {usd(Math.abs(Number(t.amount_cents))/100)}</p>)}</div>:<p>No recorded transactions within the displayed valuations.</p>}</details></>}
 <small>Shows up to 1,500 daily valuations and the latest 1,000 transactions.</small></details>
}
