"use client";
import {useEffect,useState} from 'react';
const money=(n:unknown)=>n==null||!Number.isFinite(Number(n))?'Unavailable':(Number(n)/100).toLocaleString(undefined,{style:'currency',currency:'USD'});
export default function AccountNextOpenSummary({accountId,accountName,accessToken}:{accountId:string;accountName:string;accessToken:string}){
 const [data,setData]=useState<any>(null),[plans,setPlans]=useState<any[]>([]),[error,setError]=useState(''),[planError,setPlanError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const c=new AbortController();setData(null);setPlans([]);setError('');setPlanError('');const headers:Record<string,string>={};if(accessToken)headers.Authorization=`Bearer ${accessToken}`;const household=localStorage.getItem('northstar-household-id');if(household)headers['X-Household-ID']=household;const get=async(path:string)=>{const r=await fetch(path,{headers,signal:c.signal,cache:'no-store'});if(!r.ok)throw Error('Unable to load saved account analysis');return r.json()};
 void get(`/api/action-guidance?accountId=${encodeURIComponent(accountId)}`).then(d=>{if(!c.signal.aborted){if(d.guidance?.accountId!==accountId)throw Error('Account summary mismatch');setData(d)}}).catch(e=>{if(!c.signal.aborted)setError(e.message)});
 void get(`/api/planned-actions?accountId=${encodeURIComponent(accountId)}`).then(d=>{if(!c.signal.aborted)setPlans(d.plannedActions||[])}).catch(()=>{if(!c.signal.aborted)setPlanError('Saved plans could not be loaded. Retry before preparing trades.')});return()=>c.abort();},[accountId,accessToken,refresh]);
 const actions=data?.guidance?.queue||[],groups=[{name:'Sell / trim reviews',items:actions.filter((a:any)=>/SELL|REDUCE|TRIM|TAKE_PROFIT/.test(a.action))},{name:'Buy / add candidates',items:actions.filter((a:any)=>/BUY|ADD|WAIT_FOR_PRICE/.test(a.action))},{name:'Hold / watch / unresolved',items:actions.filter((a:any)=>!/SELL|REDUCE|TRIM|TAKE_PROFIT|BUY|ADD|WAIT_FOR_PRICE/.test(a.action))}];
 return <details  style={{padding:16,border:'1px solid #b9cec4',borderRadius:12,margin:'12px 0',background:'#f5faf7',minWidth:0,overflowWrap:'anywhere'}}><summary style={{cursor:'pointer',fontWeight:700}}>{accountName} · Next market open preparation</summary><p>Review after the close, then recheck prices, overnight news and account cash before the next regular session.</p><button onClick={()=>setRefresh(n=>n+1)}>Refresh account summary</button>{error?<p role="alert">{error}</p>:!data?<p>Loading account preparation…</p>:<><p><b>Available cash:</b> {money(data.guidance.availableCashPlan?.cashCents)} · <b>Investment capacity:</b> {money(data.guidance.availableCashPlan?.safeInvestmentCapacityCents)} · <b>Protected cash:</b> {money(data.guidance.availableCashPlan?.untouchedCashCents)}</p><p>Latest saved analysis: {data.analysisStatus?.latestAt?new Date(data.analysisStatus.latestAt).toLocaleString():'No analysis timestamp available'} · Status: {data.analysisStatus?.state||data.analysisStatus?.status||'Revalidation required'}</p>{groups.map(g=><details  key={g.name}><summary style={{cursor:'pointer',padding:'12px 0',fontWeight:700}}>{g.name} · {g.items.length}</summary>{g.items.length?g.items.map((a:any,i:number)=><article key={i} style={{padding:12,marginBottom:8,background:'#fff',border:'1px solid #d5e1da',borderRadius:8}}><b>{a.symbol||'Account'} · {a.action.replaceAll('_',' ')}</b><p>{a.why}</p><p>Shares: {Number(a.quantity)>0?a.quantity:'No trade quantity approved'} · Amount: {money(a.amountCents)} · Average buy: {money(a.details?.averageCostCents)}</p><p><b>Price / confirmation:</b> {a.priceCondition||'Not yet evaluated'} · {a.when||'Recheck before the open'}</p><p>Stop / invalidation: {money(a.details?.invalidationCents)} · Targets: {a.details?.targetsCents?.length?a.details.targetsCents.map(money).join(' / '):'Not yet evaluated'}</p>{a.details?.analysisPending&&<p>Analysis incomplete: {a.details.missingReason||'Fresh analysis required'}</p>}{a.symbol&&<a target="_blank" rel="noopener noreferrer" href={`/workspace/charts?symbol=${encodeURIComponent(a.symbol)}&accountId=${encodeURIComponent(accountId)}&timeframe=5m`}>Open chart to validate ↗</a>}</article>):<p>No saved items in this group.</p>}</details>)}</>}
 <details ><summary style={{cursor:'pointer',padding:'12px 0',fontWeight:700}}>Saved plans to recheck · {plans.length}</summary>{planError?<p role="alert">{planError}</p>:plans.length?plans.map(p=><p key={p.id}><b>{p.symbol} · {p.action_type}</b> · {p.suggested_quantity} shares · Entry {money(p.entry_low_cents)}–{money(p.entry_high_cents)} · Stop {money(p.invalidation_cents)} · {p.lifecycle} · Expires {new Date(p.expires_at).toLocaleString()}</p>):<p>No active saved plans loaded.</p>}</details><p><b>Before the next open:</b> Refresh analysis, check overnight gaps and news, confirm entry/exit conditions, share quantities, stops, and available cash. Expired plans must be reviewed again. A saved plan does not authorize an order.</p></details>
}
