"use client";
import MovableStockPanel from './movable-stock-panel';
import {useEffect,useMemo,useState} from 'react';
const positions=(snapshot:any):any[]=>{try{const allocation=typeof snapshot.allocation_json==='string'?JSON.parse(snapshot.allocation_json):snapshot.allocation_json;return Array.isArray(allocation?.positions)?allocation.positions:[]}catch{return []}};
const usd=(n:number)=>n.toLocaleString(undefined,{style:'currency',currency:'USD'});
export default function AccountGrowthChart({accountId,accessToken}:{accountId:string;accessToken:string}){
 const [tooltip,setTooltip]=useState<{left:number;top:number}|null>(null);
 const [stock,setStock]=useState(''),[salePrice,setSalePrice]=useState(''),[saleShares,setSaleShares]=useState('');
 const[data,setData]=useState<any>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[range,setRange]=useState(365),[mode,setMode]=useState('value'),[index,setIndex]=useState<number|null>(null);
 useEffect(()=>{const controller=new AbortController();setTooltip(null);setData(null);setError('');setIndex(null);fetch(`/api/investments/performance?accountId=${encodeURIComponent(accountId)}`,{signal:controller.signal,cache:'no-store',headers:accessToken?{Authorization:`Bearer ${accessToken}`}:{}}).then(async r=>{if(!r.ok)throw Error('Unable to load account history');return r.json()}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[accountId,accessToken,refresh]);
 useEffect(()=>{setStock('');setSalePrice('');setSaleShares('')},[accountId]);
 const stocks=useMemo(()=>Array.from(new Set<string>([...(data?.holdings||[]).map((h:any)=>h.ticker),...(data?.snapshots||[]).flatMap((p:any)=>positions(p).map(h=>h.ticker))].filter(Boolean))).sort(),[data]);
 const holding=(data?.holdings||[]).filter((h:any)=>h.ticker===stock),owned=holding.reduce((n:number,h:any)=>n+Number(h.quantity),0),basisKnown=holding.length>0&&holding.every((h:any)=>h.cost_basis_cents!==null&&h.cost_basis_cents!==undefined&&Number.isFinite(Number(h.cost_basis_cents))),cost=holding.reduce((n:number,h:any)=>n+Number(h.cost_basis_cents)/100,0),average=owned>0&&basisKnown?cost/owned:null;
 const price=Number(salePrice),quantity=Number(saleShares),scenarioValid=salePrice.trim()!==''&&saleShares.trim()!==''&&Number.isFinite(price)&&Number.isFinite(quantity)&&price>0&&quantity>0&&quantity<=owned;
 const points=useMemo(()=>(data?.snapshots||[]).filter((p:any)=>Date.parse(p.captured_at)>=Date.now()-range*86400000).flatMap((p:any)=>{
 const matches=stock?positions(p).filter(h=>h.ticker===stock):[];
 if(stock&&!matches.length)return [];
 const market=stock?matches.reduce((n:number,h:any)=>n+Number(h.valueCents),0):Number(p.market_value_cents);
 const hasBasis=stock?matches.every(h=>h.costBasisCents!==null&&h.costBasisCents!==undefined&&Number.isFinite(Number(h.costBasisCents))):Number(p.cost_basis_cents)>0;
 const basis=stock?matches.reduce((n:number,h:any)=>n+Number(h.costBasisCents||0),0):Number(p.cost_basis_cents);
 return [{...p,time:Date.parse(p.captured_at),value:(market+(stock?0:Number(p.cash_cents)))/100,basis:basis/100,pnl:hasBasis?(market-basis)/100:null}]
 }),[data,range,stock]);
 const chosen=points[Math.min(index??points.length-1,points.length-1)],valid=points.filter((p:any)=>mode==='value'||p.pnl!==null),values=valid.map((p:any)=>mode==='value'?p.value:p.pnl),low=Math.min(0,...values),high=Math.max(1,...values),start=points[0]?.time||0,end=points.at(-1)?.time||start+1,x=(t:number)=>60+(t-start)/Math.max(1,end-start)*800,y=(v:number)=>220-(v-low)/(high-low)*180;
 const groupedPositions=Object.entries(positions(chosen||{}).filter(h=>!stock||h.ticker===stock).reduce((groups:Record<string,any[]>,h:any)=>{
 const known=h.costBasisCents!==null&&h.costBasisCents!==undefined&&Number.isFinite(Number(h.costBasisCents)),basis=Number(h.costBasisCents)/100,value=Number(h.valueCents)/100,pnl=known?(Number(h.valueCents)-Number(h.costBasisCents))/100:null;
 const group=pnl===null?'Missing cost data':pnl>0?'Gains':pnl<0?'Losses':'Unchanged';groups[group].push({...h,basis,value,pnl});return groups;
 },{Gains:[],Losses:[],Unchanged:[],'Missing cost data':[]})).filter(([,rows])=>rows.length).map(([name,rows])=>({name,rows:rows.sort((a:any,b:any)=>Math.abs(b.pnl||0)-Math.abs(a.pnl||0)||String(a.ticker).localeCompare(String(b.ticker)))}));
 const events=(data?.transactions||[]).filter((t:any)=>(!stock||t.ticker===stock)&&Date.parse(t.trade_at)>=Math.max(start,Date.now()-range*86400000)&&Date.parse(t.trade_at)<=end);
 return <details  style={{margin:'16px 0',padding:16,border:'1px solid #bfd4ca',borderRadius:12,minWidth:0,background:'#f5faf7'}}><summary style={{cursor:'pointer',fontWeight:700}}>Account growth · value, gain/loss and purchases</summary>
 <div style={{display:'flex',flexWrap:'wrap',gap:10,margin:'12px 0'}}><label>Stock <select aria-label="Stock" value={stock} onChange={e=>{setStock(e.target.value);setIndex(null);setSalePrice('');setSaleShares('')}}><option value="">Entire account</option>{stocks.map(ticker=><option key={ticker} value={ticker}>{ticker}</option>)}</select></label><label>Period <select aria-label="Period" value={range} onChange={e=>{setRange(Number(e.target.value));setIndex(null)}}><option value={30}>1 month</option><option value={90}>3 months</option><option value={365}>1 year</option><option value={100000}>Available history</option></select></label><label>View <select aria-label="View" value={mode} onChange={e=>setMode(e.target.value)}><option value="value">{stock?"Stock holding value":"Account value"}</option><option value="pnl">Unrealized gain / loss</option></select></label><button onClick={()=>setRefresh(n=>n+1)}>Refresh history</button></div>
 {stock&&<section aria-label="Stock sale scenario" style={{padding:12,background:'white',border:'1px solid #bfd4ca',borderRadius:8,marginBottom:12}}><b>{stock} · Explore a sale</b><p>Recorded shares: {owned.toLocaleString()} · Average purchase price: {average===null?'Unavailable':usd(average)}. Uses the latest saved holdings, not the selected historical date.</p><div style={{display:'flex',flexWrap:'wrap',gap:12}}><label>Hypothetical sale price ($)<input aria-label="Hypothetical sale price" type="number" min="0.01" step="0.01" value={salePrice} onChange={e=>setSalePrice(e.target.value)}/></label><label>Shares to sell<input aria-label="Shares to sell" type="number" min="0" max={owned} step="any" value={saleShares} onChange={e=>setSaleShares(e.target.value)}/></label><button onClick={()=>setSaleShares(String(owned))}>Use all shares</button></div><p aria-live="polite">{quantity>owned?'Quantity exceeds recorded shares.':!scenarioValid?'Enter a price and quantity to compare the outcome.':average===null?'Purchase cost unavailable; gain/loss cannot be calculated.':<>Estimated gain/loss: <strong style={{color:(price-average)*quantity<0?'#a32929':'#087856'}}>{usd((price-average)*quantity)}</strong> · Gross proceeds: {usd(price*quantity)} · Purchase cost of these shares: {usd(average*quantity)}</>}</p><small>What-if estimate before fees and taxes, based on average cost. Actual lots may differ. This does not place an order or predict a selling price.</small></section>}
 {error?<p role="alert">{error}</p>:!data?<p>Loading account history…</p>:!points.length?<p>No recorded valuations in this period. History appears as account snapshots are collected; past balances are not reconstructed from today’s holdings.</p>:<>
 <p aria-live="polite"><b>{new Date(chosen.time).toLocaleString()}</b> · Value {usd(chosen.value)} · Unrealized P/L {chosen.pnl===null?'Cost basis unavailable':usd(chosen.pnl)}{chosen.basis>0&&chosen.pnl!==null?` (${(chosen.pnl/chosen.basis*100).toFixed(2)}% of recorded cost)`:''}</p>
 {mode==='pnl'&&!valid.length&&<p>No recorded purchase costs for this stock in this period. Historical gain/loss cannot be calculated; select holding value to explore its recorded value.</p>}
 <div style={{position:'relative'}} onKeyDown={e=>{if(e.key==='Escape')setTooltip(null)}}>
 <svg tabIndex={0} onFocus={()=>setTooltip({left:0,top:24})} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setIndex(Math.max(0,Math.min(points.length-1,(index??points.length-1)+(e.key==='ArrowLeft'?-1:1))));setTooltip({left:0,top:24})}}} viewBox="0 0 900 270" role="img" aria-label={`${stock||'Account'} ${mode==='value'?'value':'unrealized gain and loss'} history; use the timeline slider for exact values`} style={{display:'block',width:'100%',height:'auto',background:'white',borderRadius:8}} onPointerDown={e=>{const rect=e.currentTarget.getBoundingClientRect(),time=start+Math.max(0,Math.min(1,((e.clientX-rect.left)/rect.width*900-60)/800))*(end-start);setTooltip({left:Math.max(0,Math.min(rect.width-330,e.clientX-rect.left+14)),top:24});setIndex(points.reduce((best:number,p:any,i:number)=>Math.abs(p.time-time)<Math.abs(points[best].time-time)?i:best,0))}} onPointerMove={e=>{const rect=e.currentTarget.getBoundingClientRect(),time=start+Math.max(0,Math.min(1,((e.clientX-rect.left)/rect.width*900-60)/800))*(end-start);setTooltip({left:Math.max(0,Math.min(rect.width-330,e.clientX-rect.left+14)),top:24});setIndex(points.reduce((best:number,p:any,i:number)=>Math.abs(p.time-time)<Math.abs(points[best].time-time)?i:best,0))}}>
 {[0,.5,1].map(f=>{const value=low+(high-low)*f;return <g key={f}><line x1="60" x2="860" y1={y(value)} y2={y(value)} stroke="#d5e3dc"/><text x="4" y={y(value)-4} fontSize="12">{usd(value)}</text></g>})}
 <path d={points.map((p:any,i:number)=>{const v=mode==='value'?p.value:p.pnl;if(v===null)return '';const prev=points[i-1];return `${i===0||(mode==='pnl'&&prev?.pnl===null)?'M':'L'}${x(p.time)},${y(v)}`}).join(' ')} fill="none" stroke="#087856" strokeWidth="3"/>
 {valid.map((p:any)=><circle key={p.time} cx={x(p.time)} cy={y(mode==='value'?p.value:p.pnl)} r="3" fill="#087856"/>)}
 {events.filter((t:any)=>['BUY','SELL'].includes(t.transaction_type)).map((t:any)=><circle key={t.id} cx={x(Date.parse(t.trade_at))} cy="235" r="5" fill={t.transaction_type==='BUY'?'#087856':'#b35429'}><title>{t.transaction_type} {t.quantity} {t.ticker} · {new Date(t.trade_at).toLocaleString()} · {usd(Math.abs(Number(t.amount_cents))/100)}</title></circle>)}
 <line x1={x(chosen.time)} x2={x(chosen.time)} y1="30" y2="225" stroke="#667c72" strokeDasharray="4 4"/><text x="60" y="263" fontSize="12">{new Date(start).toLocaleDateString()}</text><text x="860" y="263" textAnchor="end" fontSize="12">{new Date(end).toLocaleDateString()}</text></svg>
 {tooltip&&<MovableStockPanel onClose={()=>setTooltip(null)}><strong>{new Date(chosen.time).toLocaleString()}</strong><div>Unrealized gain/loss vs purchase cost</div>{groupedPositions.map(group=><div key={group.name} role="group" aria-label={group.name}><h4 style={{margin:'12px 0 4px',fontSize:14}}>{group.name} · {group.rows.length}</h4>{group.rows.map((h:any,i:number)=>{const {basis,value,pnl}=h,color=pnl===null||pnl===0?'#2168af':pnl>0?'#087856':'#b42332';return <div key={i} data-testid="stock-hover-row" style={{borderTop:'1px solid #e0e8ee',padding:'8px 0',color}}><b>{pnl===null?'●':pnl>0?'▲':pnl<0?'▼':'—'} {h.ticker||'Unmapped holding'}</b><div>Value {usd(value)}</div><strong>{pnl===null?'Purchase cost unavailable':(pnl>0?'+':'')+usd(pnl)+(basis>0?' ('+(pnl/basis*100).toFixed(2)+'%)':'')}</strong></div>})}</div>)} {!positions(chosen).length&&<div style={{color:'#2168af',marginTop:8}}>Stock breakdown was not recorded for this date.</div>}<small>Green: gain · Red: loss · Blue: unchanged or unavailable. Recorded snapshot, not a live quote.</small></MovableStockPanel>}
 </div><small>Move over or touch the chart to open the stock popup. Drag its handle to move it, or optionally dock below the chart. Keyboard: focus the chart and use arrow keys; Escape closes the popup.</small>
 <label style={{display:'block'}}>Explore valuation date<input aria-label="Explore valuation date" type="range" min="0" max={Math.max(0,points.length-1)} value={Math.min(index??points.length-1,points.length-1)} onChange={e=>setIndex(Number(e.target.value))} style={{display:'block',width:'100%'}}/></label><small>Green markers: purchases · Orange: sales. One recorded valuation per UTC day. {points.length===1?'Only one valuation is available; a trend needs more history.':''} Recorded values can be delayed. Account value includes cash and deposits; it is not investment return. P/L uses recorded cost basis for held positions and excludes realized gains, dividends and taxes; incomplete basis may distort it.</small>
 <details><summary>Transaction timeline · {events.length} events in chart period</summary>{events.length?<div style={{maxHeight:300,overflow:'auto'}}>{events.map((t:any)=><p key={t.id}>{new Date(t.trade_at).toLocaleDateString()} · <b>{t.transaction_type} {t.ticker||''}</b> {t.quantity?`${t.quantity} shares`:''} · {usd(Math.abs(Number(t.amount_cents))/100)}</p>)}</div>:<p>No recorded transactions within the displayed valuations.</p>}</details></>}
 <small>Shows up to 1,500 daily valuations and the latest 1,000 transactions.</small></details>
}
