"use client";
import{useEffect,useMemo,useState}from"react";
type Action={rank:number;priority:string;action:string;symbol:string|null;quantity:string;amountCents:string;priceCondition:string;when:string;why:string;capitalSource:string;lifecycle:string};
type Guidance={accountId:string;accountName:string;goalName:string;horizonMonths:number;onTrack:boolean;availableCashPlan:{cashCents:string;monthlyContributionCents:string;safeInvestmentCapacityCents:string;untouchedCashCents:string};today:Action[];thisMonth:Action[];queue:Action[]};
const money=(value:string)=>`$${(Number(value)/100).toLocaleString(undefined,{maximumFractionDigits:0})}`;
const section=(a:Action)=>["SELL","REDUCE"].includes(a.action)?"SELL / REDUCE":a.action==="TAKE_PROFIT"?"TAKE PROFIT":["BUY_NOW","BUY_ON_CONFIRMATION","WAIT_FOR_PRICE"].includes(a.action)?"BUY / ACCUMULATE":a.action==="HOLD"||a.action==="DO_NOTHING"?"NO ACTION":"WATCH / BE READY";
const readiness=(a:Action)=>a.lifecycle==="READY"||a.lifecycle==="TRIGGERED"?"READY NOW":a.priority==="READY_IF_PRICE_TRIGGERS"?"GET READY":a.lifecycle==="INVALIDATED"?"INVALIDATED":a.lifecycle==="EXPIRED"?"EXPIRED":"PLANNED";
export default function ActionGuidancePanel({accountId,accessToken,mode="today",marketOpen=false}:{accountId:string;accessToken:string;mode?:"today"|"month";marketOpen?:boolean}){
 const[data,setData]=useState<Guidance|null>(null),[notice,setNotice]=useState(""),[error,setError]=useState(""),[updated,setUpdated]=useState<Date|null>(null);
 const headers=()=>{const householdId=localStorage.getItem("northstar-household-id");return{...(accessToken?{Authorization:`Bearer ${accessToken}`}:{}) ,...(householdId?{"X-Household-ID":householdId}:{})}};
 const load=async(evaluate=false)=>{if(!accountId)return;try{if(evaluate)await fetch("/api/planned-actions/evaluate",{method:"POST",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({accountId})});const response=await fetch(`/api/action-guidance?accountId=${encodeURIComponent(accountId)}`,{cache:"no-store",headers:headers()}),body=await response.json();if(!response.ok)throw new Error(body.error||"Guidance unavailable");setData(body.guidance);setUpdated(new Date());setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Guidance unavailable")}};
 useEffect(()=>{if(!accountId){setData(null);return}load();const marketUpdate=()=>{if(marketOpen&&document.visibilityState==="visible")void load(true)},portfolioUpdate=()=>void load();window.addEventListener("northstar:realtime",marketUpdate);window.addEventListener("northstar:portfolio-changed",portfolioUpdate);return()=>{window.removeEventListener("northstar:realtime",marketUpdate);window.removeEventListener("northstar:portfolio-changed",portfolioUpdate)}},[accountId,accessToken,marketOpen]);
 const save=async(action:Action)=>{setNotice(`Saving ${action.symbol||action.action}…`);try{const response=await fetch("/api/planned-actions",{method:"POST",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify({accountId,actionType:action.action,priority:action.priority,lifecycle:action.lifecycle,symbol:action.symbol,suggestedQuantity:action.quantity,conditions:{priceCondition:action.priceCondition,when:action.when},capitalSource:{summary:action.capitalSource},rationale:action.why,evidenceSnapshot:{amountCents:action.amountCents,goalName:data?.goalName,horizonMonths:data?.horizonMonths},modelVersion:"northstar-action-guidance-v2",evidenceAsOf:new Date().toISOString(),expiresAt:new Date(Date.now()+(mode==="today"?2:35)*86400000).toISOString()})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Plan could not be saved");setNotice(`✓ Planned action saved · ${body.lifecycle}`)}catch(reason){setNotice(reason instanceof Error?reason.message:"Plan could not be saved")}};
 const actions=data?(mode==="today"?data.queue:data.thisMonth):[],groups=useMemo(()=>["SELL / REDUCE","TAKE PROFIT","BUY / ACCUMULATE","WATCH / BE READY","NO ACTION"].map(name=>({name,actions:actions.filter(action=>section(action)===name)})).filter(group=>group.actions.length),[actions]),counts={action:actions.filter(x=>["CRITICAL","ACTION_NOW"].includes(x.priority)).length,watch:actions.filter(x=>["READY_IF_PRICE_TRIGGERS","WATCH"].includes(x.priority)).length,risk:actions.filter(x=>x.priority==="CRITICAL"||["SELL","REDUCE"].includes(x.action)).length};
 if(!accountId)return <section className="action-guidance empty"><b>Select a Swing or Options account</b><span>The Daily Action Plan requires its own account, cash, positions, and risk limits.</span></section>;if(error)return <section className="action-guidance empty"><b>Action guidance unavailable</b><span>{error}</span><button onClick={()=>load(true)}>Retry live evaluation</button></section>;if(!data)return <section className="action-guidance empty"><b>Building account action plan…</b></section>;
 return <section className="action-guidance execution-board"><header><div><span>DAILY ACTION PLAN · EXECUTION GUIDANCE BOARD</span><h2>{data.accountName}: what requires attention</h2><p>{data.goalName} · {Math.round(data.horizonMonths/12*10)/10} years · suggestions only; no order is sent</p></div><aside><b>{counts.action} Actions · {counts.watch} Watch · {counts.risk} Risk</b><small>{updated?`Updated ${updated.toLocaleTimeString()} · ${marketOpen?"market-open sync":"on demand"}`:"Calculating…"}</small><button onClick={()=>load(true)}>Refresh now</button></aside></header><div className="guidance-cash"><span>Allocated account cash <b>{money(data.availableCashPlan.cashCents)}</b></span><span>Monthly contribution <b>{money(data.availableCashPlan.monthlyContributionCents)}</b></span><span>Keep untouched <b>{money(data.availableCashPlan.untouchedCashCents)}</b></span></div>{counts.action===0&&<div className="no-trades-required"><b>NO TRADES REQUIRED TODAY</b><span>{counts.watch} setup{counts.watch===1?" is":"s are"} being monitored.</span></div>}<div className="action-groups">{groups.map(group=><section key={group.name}><h3>{group.name}<small>{group.actions.length}</small></h3>{group.actions.map(action=><details className={`action-card priority-${action.priority.toLowerCase().replaceAll("_","-")}`} key={`${action.rank}-${action.symbol}-${action.action}`}><summary><em>{readiness(action)}</em><strong>{action.symbol?`${action.symbol} — `:""}{action.action.replaceAll("_"," ")}{Number(action.quantity)>0?` ${action.quantity} SHARE${Number(action.quantity)===1?"":"S"}`:""}</strong><span>{action.priceCondition}</span><i>{action.when}</i><button type="button" onClick={event=>{event.preventDefault();save(action)}}>Save plan</button></summary><div className="action-evidence"><article><b>Exact condition</b><p>{action.priceCondition}</p></article><article><b>Validity / timing</b><p>{action.when}</p></article><article><b>Why this action</b><p>{action.why}</p></article><article><b>Capital source or proceeds</b><p>{action.capitalSource}</p></article><article><b>Estimated capital impact</b><p>{money(action.amountCents)} · {action.quantity||"0"} shares</p></article><article><b>Risk and invalidation</b><p>Cancel if its stored thesis, evidence gate, allocated cash, or price condition no longer passes.</p></article><footer>Full price, bid/ask, chart, prediction, fundamentals, valuation, news, and event checks remain on the linked live evaluation. Northstar never sends an order.</footer></div></details>)}</section>)}</div>{notice&&<footer role="status">{notice}</footer>}</section>}
