"use client";
import {useEffect,useMemo,useRef,useState} from "react";
type Bar={o:number;h:number;l:number;c:number};
const series=()=>{let p=112;return Array.from({length:220},(_,i)=>{const drift=i<105?.11:i<155?-.2:.16;const move=drift+Math.sin(i/7)*.48+((i*13)%7-3)*.1,o=p,c=p+move,h=Math.max(o,c)+.5+(i%4)*.13,l=Math.min(o,c)-.45-(i%5)*.1;p=c;return{o,h,l,c}})};
export default function AdvancedStudyChart(){
 const canvas=useRef<HTMLCanvasElement>(null),bars=useMemo(series,[]);
 const [zoom,setZoom]=useState(1),[offset,setOffset]=useState(0),[tool,setTool]=useState("Crosshair"),[ema,setEma]=useState(true),[fib,setFib]=useState(true),[cursor,setCursor]=useState<{x:number;y:number}|null>(null),[anchor,setAnchor]=useState<{x1:number;y1:number;x2:number;y2:number}|null>(null),drag=useRef<{x:number;offset:number}|null>(null);
 const count=Math.max(32,Math.floor(100/zoom)),end=Math.max(count,bars.length-offset),shown=bars.slice(end-count,end),first=shown[0],last=shown.at(-1)!;
 const slope=(last.c-first.c)/(shown.length-1),direction=slope>.035?"ALCISTA":slope<-.035?"BAJISTA":"LATERAL",breakout=last.c>Math.max(...shown.slice(-21,-1).map(x=>x.h)),breakdown=last.c<Math.min(...shown.slice(-21,-1).map(x=>x.l));
 useEffect(()=>{const el=canvas.current;if(!el)return;const r=el.getBoundingClientRect(),dpr=devicePixelRatio||1;el.width=r.width*dpr;el.height=r.height*dpr;const g=el.getContext("2d")!;g.scale(dpr,dpr);const w=r.width,h=r.height,pad=34,lo=Math.min(...shown.map(x=>x.l)),hi=Math.max(...shown.map(x=>x.h)),span=hi-lo,py=(v:number)=>pad+(hi-v)/span*(h-pad*2),cw=(w-pad*2)/shown.length;g.fillStyle="#08110e";g.fillRect(0,0,w,h);g.strokeStyle="#1e3029";g.lineWidth=1;for(let y=25;y<h;y+=40){g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke()}for(let x=40;x<w;x+=72){g.beginPath();g.moveTo(x,0);g.lineTo(x,h);g.stroke()}
 shown.forEach((b,i)=>{const x=pad+i*cw+cw/2,up=b.c>=b.o;g.strokeStyle=g.fillStyle=up?"#35c990":"#f36b63";g.beginPath();g.moveTo(x,py(b.h));g.lineTo(x,py(b.l));g.stroke();g.fillRect(x-Math.max(2,cw*.3),Math.min(py(b.o),py(b.c)),Math.max(4,cw*.6),Math.max(2,Math.abs(py(b.o)-py(b.c))))});
 if(ema){let v=shown[0].c;g.strokeStyle="#f1b94d";g.lineWidth=2;g.beginPath();shown.forEach((b,i)=>{v=b.c*.2+v*.8;const x=pad+i*cw+cw/2,y=py(v);i?g.lineTo(x,y):g.moveTo(x,y)});g.stroke()}
 g.strokeStyle=direction==="ALCISTA"?"#49d7a0":direction==="BAJISTA"?"#ff7b72":"#b8c6c0";g.setLineDash([7,5]);g.beginPath();g.moveTo(pad,py(first.c));g.lineTo(w-pad,py(first.c+slope*(shown.length-1)));g.stroke();g.setLineDash([]);
 if(fib){const swingHi=Math.max(...shown.map(x=>x.h)),swingLo=Math.min(...shown.map(x=>x.l));[0,.236,.382,.5,.618,.786,1].forEach((level,i)=>{const price=direction==="BAJISTA"?swingLo+(swingHi-swingLo)*level:swingHi-(swingHi-swingLo)*level,y=py(price);g.strokeStyle=["#52675f","#467c70","#528f7d","#d1a646","#49a886","#467c70","#52675f"][i];g.globalAlpha=.75;g.beginPath();g.moveTo(pad,y);g.lineTo(w-pad,y);g.stroke();g.globalAlpha=1;g.fillStyle="#b9ccc4";g.font="11px Arial";g.fillText(`${(level*100).toFixed(1)}%  $${price.toFixed(2)}`,pad+4,y-3)})}
 if(anchor){g.strokeStyle="#f7df78";g.lineWidth=2;g.beginPath();g.moveTo(anchor.x1,anchor.y1);g.lineTo(anchor.x2,anchor.y2);g.stroke()}
 if(cursor){g.strokeStyle="#dce7e2";g.setLineDash([3,4]);g.beginPath();g.moveTo(cursor.x,0);g.lineTo(cursor.x,h);g.moveTo(0,cursor.y);g.lineTo(w,cursor.y);g.stroke();g.setLineDash([])}
 },[shown,ema,fib,cursor,anchor,direction,slope,first.c]);
 const move=(e:React.MouseEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect(),p={x:e.clientX-r.left,y:e.clientY-r.top};setCursor(p);if(drag.current&&tool==="Pan")setOffset(Math.max(0,Math.min(115,drag.current.offset+Math.round((e.clientX-drag.current.x)/7))));if(drag.current&&tool==="Trend line")setAnchor(x=>x?{...x,x2:p.x,y2:p.y}:null)};
 return <section className="study-terminal advanced"><header><div><span>LABORATORIO GRÁFICO INTERACTIVO</span><h3>Fibonacci · tendencia · retroceso · ruptura</h3></div><strong className={`trend-badge ${direction.toLowerCase()}`}>{direction}</strong></header><div className="study-toolbar"><div>{["Crosshair","Trend line","Pan"].map(x=><button className={tool===x?"active":""} key={x} onClick={()=>setTool(x)}>{x}</button>)}</div><label><input type="checkbox" checked={ema} onChange={e=>setEma(e.target.checked)}/> EMA 9</label><label><input type="checkbox" checked={fib} onChange={e=>setFib(e.target.checked)}/> Fibonacci</label><button onClick={()=>{setZoom(1);setOffset(0);setAnchor(null)}}>Restablecer</button></div><canvas ref={canvas} onWheel={e=>{e.preventDefault();setZoom(z=>Math.max(.55,Math.min(3,z+(e.deltaY<0?.15:-.15))))}} onMouseMove={move} onMouseDown={e=>{const r=e.currentTarget.getBoundingClientRect(),p={x:e.clientX-r.left,y:e.clientY-r.top};drag.current={x:e.clientX,offset};if(tool==="Trend line")setAnchor({x1:p.x,y1:p.y,x2:p.x,y2:p.y})}} onMouseUp={()=>drag.current=null} onMouseLeave={()=>{drag.current=null;setCursor(null)}} aria-label="Gráfico interactivo de velas con Fibonacci y tendencia"/><div className="trend-read"><article><span>TENDENCIA</span><b>{direction}</b><p>Pendiente calculada: {slope.toFixed(3)} por vela.</p></article><article><span>RUPTURA</span><b>{breakout?"Posible ruptura alcista":breakdown?"Posible ruptura bajista":"Sin ruptura confirmada"}</b><p>Requiere cierre, volumen, aceptación y seguimiento.</p></article><article><span>REGLA DE DECISIÓN</span><b>No predecir; confirmar</b><p>Fibonacci marca zonas probables, nunca precios garantizados.</p></article></div><footer><span>Rueda: zoom</span><span>Pan: arrastrar historia</span><span>Trend line: dibujar</span><span>Fibonacci: retrocesos 23.6–78.6%</span></footer></section>
}
