"use client";
import {useEffect,useState} from "react";

type Candidate={symbol:string;name?:string;price:number;dayChange:number;score:number;setup:string;action:string;tier?:string;companyStage?:string;portfolioRole?:string;trend:string;ema20:number;sma50:number;sma100?:number|null;sma200?:number|null;rsi:number;relVol:number;support:number;resistance:number;invalidation:number;riskPct:number;asOf:string;forecast?:string;missingData?:boolean;fairValue?:number|null;fairValueLow?:number|null;fairValueHigh?:number|null;fairValueSource?:string;fairValueAsOf?:string|null;fundamentals?:{revenueGrowth3Y:number|null;revenueGrowth5Y:number|null;epsGrowth3Y:number|null;epsGrowth5Y:number|null;pe:number|null;forwardPE:number|null;peg:number|null;grossMargin:number|null;operatingMargin:number|null;marketCap:number|null};news?:Array<{headline?:string;source?:string}>};
type Strategy="swing"|"long-term";

const securityNames:Record<string,string>={
 AAPL:"Apple Inc.",ABNB:"Airbnb, Inc.",AMD:"Advanced Micro Devices, Inc.",AMZN:"Amazon.com, Inc.",AVGO:"Broadcom Inc.",BND:"Vanguard Total Bond Market ETF",CAT:"Caterpillar Inc.",CAVA:"CAVA Group, Inc.",COST:"Costco Wholesale Corporation",CRM:"Salesforce, Inc.",CRWD:"CrowdStrike Holdings, Inc.",CVX:"Chevron Corporation",DDOG:"Datadog, Inc.",DIA:"SPDR Dow Jones Industrial Average ETF Trust",DUOL:"Duolingo, Inc.",GOOGL:"Alphabet Inc.",HD:"The Home Depot, Inc.",IWM:"iShares Russell 2000 ETF",JPM:"JPMorgan Chase & Co.",LLY:"Eli Lilly and Company",MA:"Mastercard Incorporated",MELI:"MercadoLibre, Inc.",META:"Meta Platforms, Inc.",MSFT:"Microsoft Corporation",NET:"Cloudflare, Inc.",NFLX:"Netflix, Inc.",NVDA:"NVIDIA Corporation",ORCL:"Oracle Corporation",PLTR:"Palantir Technologies Inc.",QQQ:"Invesco QQQ Trust",SCHD:"Schwab U.S. Dividend Equity ETF",SHOP:"Shopify Inc.",SOFI:"SoFi Technologies, Inc.",SPY:"SPDR S&P 500 ETF Trust",UBER:"Uber Technologies, Inc.",UNH:"UnitedHealth Group Incorporated",V:"Visa Inc.",VTI:"Vanguard Total Stock Market ETF",VOO:"Vanguard S&P 500 ETF",VXUS:"Vanguard Total International Stock ETF",WMT:"Walmart Inc.",XOM:"Exxon Mobil Corporation"
};

export default function AutomaticMarketCopilot({onSelect,onPrepare,accessToken="",initialStrategy="swing"}:{onSelect:(symbol:string)=>void;onPrepare?:(symbol:string,action:string)=>void;accessToken?:string;initialStrategy?:Strategy}){
 const [data,setData]=useState<{provider?:string;feed?:string;asOf?:string;universeSize?:number;method?:string;candidates?:Candidate[];error?:string}>({});
 const [loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[strategy,setStrategy]=useState<Strategy>(initialStrategy);
 const [accountSize,setAccountSize]=useState(25000),[riskPercent,setRiskPercent]=useState(.5),[holdingPeriod,setHoldingPeriod]=useState("2–10 trading days"),[monthly,setMonthly]=useState(500),[accountType,setAccountType]=useState("Roth IRA");
 const [plannedActions,setPlannedActions]=useState<Record<string,string>>({}),[prepareStatus,setPrepareStatus]=useState("");
 const prepareAction=async(symbol:string,suggestedAction:string,reason:string)=>{const action=plannedActions[symbol]||suggestedAction,householdId=localStorage.getItem("northstar-household-id");setPrepareStatus(`Saving ${symbol}…`);try{const response=await fetch("/api/watchlist",{method:"POST",headers:{"Content-Type":"application/json",...(accessToken?{Authorization:`Bearer ${accessToken}`}:{}) ,...(householdId?{"X-Household-ID":householdId}:{})},body:JSON.stringify({symbol,purpose:action,notes:`Northstar suggestion: ${suggestedAction}. ${reason} · ${strategy} · ${holdingPeriod}`})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to prepare action");sessionStorage.setItem("northstar-prepared-action",JSON.stringify({symbol,action,suggestedAction,reason,strategy,holdingPeriod,createdAt:new Date().toISOString()}));setPrepareStatus(`✓ ${symbol} added as “${action}”${action!==suggestedAction?` (Northstar suggested “${suggestedAction}”)`:""}`);onPrepare?.(symbol,action)}catch(error){setPrepareStatus(error instanceof Error?error.message:"Unable to prepare action")}};
 useEffect(()=>{let active=true;setLoading(true);fetch(`/api/market/candidates?strategy=${strategy}`,{cache:"no-store"}).then(async response=>({ok:response.ok,body:await response.json()})).then(({ok,body})=>{if(active)setData(ok?body:{error:body.error||"Market scan unavailable"})}).catch(()=>{if(active)setData({error:"Market scan unavailable"})}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[refresh,strategy]);
 useEffect(()=>{const update=()=>setRefresh(value=>value+1);window.addEventListener("northstar:realtime",update);return()=>window.removeEventListener("northstar:realtime",update)},[]);
 useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==="visible")setRefresh(value=>value+1)},60000);return()=>window.clearInterval(timer)},[]);
 return <section className="auto-copilot">
  <header><div><span>✦ LIVE PROVIDER-BACKED MARKET ANALYSIS</span><h2>{strategy==="swing"?"Swing opportunities and defined-risk proposals":"Long-term, 401(k), and Roth decision candidates"}</h2><p>This scanner analyzes current data returned by the connected market providers—not educational sample prices. Northstar then proposes an action, trigger, and invalidation. Forecasts remain probabilistic and never guarantee the next price move.</p></div><button disabled={loading} onClick={()=>setRefresh(x=>x+1)}>{loading?"Analyzing…":"Run fresh analysis ↻"}</button></header>
  <nav className="portfolio-mode"><button className={strategy==="swing"?"active":""} onClick={()=>setStrategy("swing")}><b>SWING PORTFOLIO</b><span>Days to weeks · entry, stop, target, size</span></button><button className={strategy==="long-term"?"active":""} onClick={()=>setStrategy("long-term")}><b>LONG-TERM / RETIREMENT</b><span>401(k), Roth, IRA · allocation and future-growth research</span></button></nav>
  {data.error?<div className="auto-error"><b>Live shortlist unavailable</b><span>{data.error}</span></div>:<><div className="auto-method"><b><i className="live-market-dot" />{data.provider||"Provider"} {data.feed?.toUpperCase()} · {data.universeSize||0} securities screened</b><span>{data.method}</span><time>{data.asOf?`Updated ${new Date(data.asOf).toLocaleString()} · auto-refresh 60s`:"Calculating…"}</time></div>
  <div className="proposal-settings"><div><span>{strategy==="swing"?"READ-ONLY TRADE PREPARATION MODEL":"LONG-TERM CONTRIBUTION MODEL"}</span><b>{strategy==="swing"?"Compare buy, sell, or wait using confirmation, risk, reward, and time":"Build a diversified core before emerging-growth satellites"}</b></div>{strategy==="swing"?<><label>Planning capital $<input type="number" min="1000" step="1000" value={accountSize} onChange={e=>setAccountSize(Math.max(0,+e.target.value))}/><small>Used only to calculate maximum position size</small></label><label>Maximum risk / idea<select value={riskPercent} onChange={e=>setRiskPercent(+e.target.value)}><option value="0.25">0.25%</option><option value="0.5">0.50%</option><option value="0.75">0.75%</option><option value="1">1.00%</option></select></label><label>Planned holding period<select value={holdingPeriod} onChange={e=>setHoldingPeriod(e.target.value)}><option>1–3 trading days</option><option>2–10 trading days</option><option>2–6 weeks</option><option>Until invalidation or target</option></select></label><strong>${(accountSize*riskPercent/100).toFixed(0)} maximum planned loss · {holdingPeriod}</strong></>:<><label>Monthly contribution $<input type="number" min="0" step="50" value={monthly} onChange={e=>setMonthly(Math.max(0,+e.target.value))}/></label><label>Account type<select value={accountType} onChange={e=>setAccountType(e.target.value)}><option>401(k)</option><option>Roth IRA</option><option>Traditional IRA</option><option>Taxable brokerage</option></select></label><strong>${monthly.toFixed(0)} monthly · {accountType}</strong></>}</div>
  <div className="auto-grid">
   {(data.candidates||[]).slice(0,6).map((item,index)=>{
    const riskPerShare=Math.max(.01,item.price-item.invalidation),target=item.price+2*riskPerShare,shares=Math.floor((accountSize*riskPercent/100)/riskPerShare),isFund=["VTI","VOO","SCHD","VXUS","BND","QQQ","IWM"].includes(item.symbol),displayName=item.name&&item.name!==item.symbol?item.name:securityNames[item.symbol]||"Company or fund name unavailable",valuationGap=item.fairValue?((item.price-item.fairValue)/item.fairValue)*100:null,suggestedAction=strategy==="long-term"?(valuationGap!==null&&valuationGap>25?"Reduce / sell plan":!item.missingData&&valuationGap!==null&&valuationGap<=-10&&item.trend==="Bullish"?"Prepare conditional buy":item.score>=76&&!item.missingData?"Prepare conditional buy":"No action — monitor"):item.trend==="Bearish"?"Reduce / sell plan":item.action.startsWith("Prepare")&&item.relVol>=1?"Prepare conditional buy":"No action — monitor",suggestionReason=valuationGap!==null&&valuationGap>25?`Model midpoint is ${Math.abs(valuationGap).toFixed(1)}% below price. Do not add; review reducing only if you own it and taxes, concentration and thesis agree.`:strategy==="long-term"&&suggestedAction==="Prepare conditional buy"?`Model favors accumulation: evidence ${item.score}/100, ${item.trend.toLowerCase()} structure${valuationGap!==null?`, and price ${Math.abs(valuationGap).toFixed(1)}% below fair-value midpoint`:""}. Invalidate if business quality deteriorates or price loses $${item.invalidation.toFixed(2)}.`:strategy==="swing"&&suggestedAction==="Prepare conditional buy"?`Bullish continuation is favored at ${item.score}/100 evidence confidence. Entry trigger: hold or close above $${item.resistance.toFixed(2)} with volume; invalidation $${item.invalidation.toFixed(2)}; modeled target $${target.toFixed(2)}.`:item.trend==="Bearish"?`Downside risk is favored. Do not open a new long; if owned, review reduction. A reclaim above $${item.resistance.toFixed(2)} changes the reading.`:`No trade now: evidence is ${item.score}/100 and does not meet the action threshold. Monitor $${item.resistance.toFixed(2)}; invalidate the bullish case below $${item.invalidation.toFixed(2)}.`;
    return <article key={item.symbol}>
     <div className="auto-rank"><i>{index+1}</i><span><b className="security-title"><strong>{item.symbol}</strong><em>{displayName}</em></b><small>${item.price.toFixed(2)} · {item.dayChange>=0?"+":""}{item.dayChange.toFixed(2)}%</small></span><strong>{item.score}<small>/100</small></strong></div>
     <em className={item.action.startsWith("Prepare")?"research":item.action.startsWith("No entry")?"watch":"avoid"}>{item.action}</em><h3>{item.setup}</h3>
     <dl><div><dt>Trend</dt><dd>{item.trend}</dd></div><div><dt>EMA 20 / SMA 50</dt><dd>${item.ema20.toFixed(2)} / ${item.sma50.toFixed(2)}</dd></div><div><dt>SMA 100 / SMA 200</dt><dd>{item.sma100!==null&&item.sma100!==undefined?`$${item.sma100.toFixed(2)}`:"Insufficient history"} / {item.sma200!==null&&item.sma200!==undefined?`$${item.sma200.toFixed(2)}`:"Insufficient history"}</dd></div><div><dt>RSI / relative volume</dt><dd>{item.rsi.toFixed(1)} / {item.relVol.toFixed(2)}×</dd></div><div><dt>Support / resistance</dt><dd>${item.support.toFixed(2)} / ${item.resistance.toFixed(2)}</dd></div></dl>
     {strategy==="swing"?<section className="trade-proposal"><span>READ-ONLY EXECUTION PREPARATION · TARGET 2:1 REWARD/RISK</span><div><b>Entry trigger<small>${item.price.toFixed(2)} only after confirmation</small></b><b>Stop / invalidation<small>${item.invalidation.toFixed(2)}</small></b><b>Target model<small>${target.toFixed(2)}</small></b><b>Maximum size<small>{shares} shares</small></b></div><p>Risk/share ${riskPerShare.toFixed(2)} · maximum modeled loss ${(shares*riskPerShare).toFixed(0)} · modeled reward ${(shares*(target-item.price)).toFixed(0)} · reward/risk 2.00. Overnight gaps and slippage may exceed the planned loss.</p></section>:<section className="trade-proposal long"><span>{item.companyStage||(isFund?"DIVERSIFIED FUND":"CLASSIFICATION PENDING")}</span><div><b>Portfolio role<small>{item.portfolioRole||(isFund?"Core or diversifier":"Satellite pending validation")}</small></b><b>Monthly plan<small>${monthly.toFixed(0)} available</small></b><b>Horizon<small>5–10+ years</small></b><b>Account<small>{accountType}</small></b></div>{!isFund&&<aside className="candidate-fair-value"><b>Fair-price reference</b>{item.fairValue?<><strong>${item.fairValue.toFixed(2)}</strong><span>{item.fairValueLow&&item.fairValueHigh?`Analyst range $${item.fairValueLow.toFixed(2)}–$${item.fairValueHigh.toFixed(2)}`:"Consensus range unavailable"}</span><em className={item.price<=item.fairValue?"below":"above"}>{Math.abs((item.price-item.fairValue)/item.fairValue*100).toFixed(1)}% {item.price<=item.fairValue?"below":"above"} reference</em></>:<><strong>Not available</strong><span>Do not invent a fair price when valuation coverage is missing.</span></>}</aside>}<p>{isFund?"Compare expense ratio, diversification, overlap and plan availability.":"Analyst consensus is a reference—not intrinsic value or a prediction. Validate cash flow, growth, debt, dilution, moat and filings."}</p></section>}
     <div className="suggested-action"><b>Northstar model: {suggestedAction}</b><span>{suggestionReason}</span></div><div className="prepare-action"><label>Proposed action<select value={plannedActions[item.symbol]||suggestedAction} onChange={event=>setPlannedActions(current=>({...current,[item.symbol]:event.target.value}))}><option>Prepare conditional buy</option><option>Add / buy more plan</option><option>Reduce / sell plan</option><option>No action — monitor</option><option>Call setup review</option><option>Put setup review</option></select></label><button type="button" onClick={()=>prepareAction(item.symbol,suggestedAction,suggestionReason)}>+ Add to Prepare Trade</button></div>
     <button type="button" className="open-chart" onClick={()=>onSelect(item.symbol)}>Analyze {item.symbol} on complete chart →</button>
    </article>
   })}
  </div>{prepareStatus&&<div className="prepare-status" role="status">{prepareStatus}</div>}</>}
  <footer><b>Separation rule:</b> Never treat retirement assets as swing-trading capital. Future compounder status is uncertain and must be validated with fundamentals, valuation, filings, diversification and suitability. Northstar never places an order.</footer>
 </section>
}
