"use client";
import {useEffect,useState} from "react";

type Candidate={symbol:string;name?:string;price:number;dayChange:number;score:number;setup:string;action:string;tier?:string;companyStage?:string;portfolioRole?:string;trend:string;ema20:number;sma50:number;sma100?:number|null;sma200?:number|null;rsi:number;relVol:number;support:number;resistance:number;invalidation:number;riskPct:number;asOf:string;forecast?:string;missingData?:boolean;fairValue?:number|null;fairValueLow?:number|null;fairValueHigh?:number|null;fairValueSource?:string;fairValueAsOf?:string|null;fundamentals?:{revenueGrowth3Y:number|null;revenueGrowth5Y:number|null;epsGrowth3Y:number|null;epsGrowth5Y:number|null;pe:number|null;forwardPE:number|null;peg:number|null;grossMargin:number|null;operatingMargin:number|null;marketCap:number|null};news?:Array<{headline?:string;source?:string}>};
type Strategy="swing"|"long-term";

const securityNames:Record<string,string>={
 AAPL:"Apple Inc.",ABNB:"Airbnb, Inc.",AMD:"Advanced Micro Devices, Inc.",AMZN:"Amazon.com, Inc.",AVGO:"Broadcom Inc.",BND:"Vanguard Total Bond Market ETF",CAT:"Caterpillar Inc.",CAVA:"CAVA Group, Inc.",COST:"Costco Wholesale Corporation",CRM:"Salesforce, Inc.",CRWD:"CrowdStrike Holdings, Inc.",CVX:"Chevron Corporation",DDOG:"Datadog, Inc.",DIA:"SPDR Dow Jones Industrial Average ETF Trust",DUOL:"Duolingo, Inc.",GOOGL:"Alphabet Inc.",HD:"The Home Depot, Inc.",IWM:"iShares Russell 2000 ETF",JPM:"JPMorgan Chase & Co.",LLY:"Eli Lilly and Company",MA:"Mastercard Incorporated",MELI:"MercadoLibre, Inc.",META:"Meta Platforms, Inc.",MSFT:"Microsoft Corporation",NET:"Cloudflare, Inc.",NFLX:"Netflix, Inc.",NVDA:"NVIDIA Corporation",ORCL:"Oracle Corporation",PLTR:"Palantir Technologies Inc.",QQQ:"Invesco QQQ Trust",SCHD:"Schwab U.S. Dividend Equity ETF",SHOP:"Shopify Inc.",SOFI:"SoFi Technologies, Inc.",SPY:"SPDR S&P 500 ETF Trust",UBER:"Uber Technologies, Inc.",UNH:"UnitedHealth Group Incorporated",V:"Visa Inc.",VTI:"Vanguard Total Stock Market ETF",VOO:"Vanguard S&P 500 ETF",VXUS:"Vanguard Total International Stock ETF",WMT:"Walmart Inc.",XOM:"Exxon Mobil Corporation"
};

export default function AutomaticMarketCopilot({onSelect,initialStrategy="swing"}:{onSelect:(symbol:string)=>void;initialStrategy?:Strategy}){
 const [data,setData]=useState<{provider?:string;feed?:string;asOf?:string;universeSize?:number;method?:string;candidates?:Candidate[];error?:string}>({});
 const [loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[strategy,setStrategy]=useState<Strategy>(initialStrategy);
 const [accountSize,setAccountSize]=useState(25000),[riskPercent,setRiskPercent]=useState(.5),[holdingPeriod,setHoldingPeriod]=useState("2–10 trading days"),[monthly,setMonthly]=useState(500),[accountType,setAccountType]=useState("Roth IRA");
 useEffect(()=>{let active=true;setLoading(true);fetch(`/api/market/candidates?strategy=${strategy}`,{cache:"no-store"}).then(async response=>({ok:response.ok,body:await response.json()})).then(({ok,body})=>{if(active)setData(ok?body:{error:body.error||"Market scan unavailable"})}).catch(()=>{if(active)setData({error:"Market scan unavailable"})}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[refresh,strategy]);
 useEffect(()=>{const update=()=>setRefresh(value=>value+1);window.addEventListener("northstar:realtime",update);return()=>window.removeEventListener("northstar:realtime",update)},[]);
 useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==="visible")setRefresh(value=>value+1)},60000);return()=>window.clearInterval(timer)},[]);
 return <section className="auto-copilot">
  <header><div><span>✦ TWO-PORTFOLIO AUTOMATIC MARKET ANALYSIS</span><h2>{strategy==="swing"?"Swing opportunities and defined-risk proposals":"Long-term, 401(k), and Roth research candidates"}</h2><p>Northstar keeps short-term trading separate from retirement and multi-year investing. A high rank means investigate—not an automatic buy.</p></div><button disabled={loading} onClick={()=>setRefresh(x=>x+1)}>{loading?"Analyzing…":"Run fresh analysis ↻"}</button></header>
  <nav className="portfolio-mode"><button className={strategy==="swing"?"active":""} onClick={()=>setStrategy("swing")}><b>SWING PORTFOLIO</b><span>Days to weeks · entry, stop, target, size</span></button><button className={strategy==="long-term"?"active":""} onClick={()=>setStrategy("long-term")}><b>LONG-TERM / RETIREMENT</b><span>401(k), Roth, IRA · allocation and future-growth research</span></button></nav>
  {data.error?<div className="auto-error"><b>Live shortlist unavailable</b><span>{data.error}</span></div>:<><div className="auto-method"><b><i className="live-market-dot" />{data.provider||"Provider"} {data.feed?.toUpperCase()} · {data.universeSize||0} securities screened</b><span>{data.method}</span><time>{data.asOf?`Updated ${new Date(data.asOf).toLocaleString()} · auto-refresh 60s`:"Calculating…"}</time></div>
  <div className="proposal-settings"><div><span>{strategy==="swing"?"READ-ONLY TRADE PROPOSAL MODEL":"LONG-TERM CONTRIBUTION MODEL"}</span><b>{strategy==="swing"?"Plan size, risk, and time before considering an entry":"Build a diversified core before emerging-growth satellites"}</b></div>{strategy==="swing"?<><label>Paper account value $<input type="number" min="1000" step="1000" value={accountSize} onChange={e=>setAccountSize(Math.max(0,+e.target.value))}/><small>Used only for position-size calculations</small></label><label>Maximum risk / idea<select value={riskPercent} onChange={e=>setRiskPercent(+e.target.value)}><option value="0.25">0.25%</option><option value="0.5">0.50%</option><option value="0.75">0.75%</option><option value="1">1.00%</option></select></label><label>Planned holding period<select value={holdingPeriod} onChange={e=>setHoldingPeriod(e.target.value)}><option>1–3 trading days</option><option>2–10 trading days</option><option>2–6 weeks</option><option>Until invalidation or target</option></select></label><strong>${(accountSize*riskPercent/100).toFixed(0)} maximum planned loss · {holdingPeriod}</strong></>:<><label>Monthly contribution $<input type="number" min="0" step="50" value={monthly} onChange={e=>setMonthly(Math.max(0,+e.target.value))}/></label><label>Account type<select value={accountType} onChange={e=>setAccountType(e.target.value)}><option>401(k)</option><option>Roth IRA</option><option>Traditional IRA</option><option>Taxable brokerage</option></select></label><strong>${monthly.toFixed(0)} monthly · {accountType}</strong></>}</div>
  <div className="auto-grid">
   {(data.candidates||[]).slice(0,6).map((item,index)=>{
    const riskPerShare=Math.max(.01,item.price-item.invalidation),target=item.price+2*riskPerShare,shares=Math.floor((accountSize*riskPercent/100)/riskPerShare),isFund=["VTI","VOO","SCHD","VXUS","BND","QQQ","IWM"].includes(item.symbol),displayName=item.name&&item.name!==item.symbol?item.name:securityNames[item.symbol]||"Company or fund name unavailable";
    return <button key={item.symbol} onClick={()=>onSelect(item.symbol)}>
     <div className="auto-rank"><i>{index+1}</i><span><b className="security-title"><strong>{item.symbol}</strong><em>{displayName}</em></b><small>${item.price.toFixed(2)} · {item.dayChange>=0?"+":""}{item.dayChange.toFixed(2)}%</small></span><strong>{item.score}<small>/100</small></strong></div>
     <em className={item.action.startsWith("Research")?"research":item.action.startsWith("Watch")?"watch":"avoid"}>{item.action}</em><h3>{item.setup}</h3>
     <dl><div><dt>Trend</dt><dd>{item.trend}</dd></div><div><dt>EMA 20 / SMA 50</dt><dd>${item.ema20.toFixed(2)} / ${item.sma50.toFixed(2)}</dd></div><div><dt>SMA 100 / SMA 200</dt><dd>{item.sma100!==null&&item.sma100!==undefined?`$${item.sma100.toFixed(2)}`:"Insufficient history"} / {item.sma200!==null&&item.sma200!==undefined?`$${item.sma200.toFixed(2)}`:"Insufficient history"}</dd></div><div><dt>RSI / relative volume</dt><dd>{item.rsi.toFixed(1)} / {item.relVol.toFixed(2)}×</dd></div><div><dt>Support / resistance</dt><dd>${item.support.toFixed(2)} / ${item.resistance.toFixed(2)}</dd></div></dl>
     {strategy==="swing"?<section className="trade-proposal"><span>PROPOSED PAPER PLAN · 2:1 REWARD/RISK</span><div><b>Entry reference<small>${item.price.toFixed(2)} after confirmation</small></b><b>Stop / invalidation<small>${item.invalidation.toFixed(2)}</small></b><b>Target model<small>${target.toFixed(2)}</small></b><b>Maximum size<small>{shares} shares</small></b></div><p>Risk/share ${riskPerShare.toFixed(2)} · modeled loss ${(shares*riskPerShare).toFixed(0)}. Gaps may exceed it.</p></section>:<section className="trade-proposal long"><span>{item.companyStage||(isFund?"DIVERSIFIED FUND":"CLASSIFICATION PENDING")}</span><div><b>Portfolio role<small>{item.portfolioRole||(isFund?"Core or diversifier":"Satellite pending validation")}</small></b><b>Monthly plan<small>${monthly.toFixed(0)} available</small></b><b>Horizon<small>5–10+ years</small></b><b>Account<small>{accountType}</small></b></div>{!isFund&&<aside className="candidate-fair-value"><b>Fair-price reference</b>{item.fairValue?<><strong>${item.fairValue.toFixed(2)}</strong><span>{item.fairValueLow&&item.fairValueHigh?`Analyst range $${item.fairValueLow.toFixed(2)}–$${item.fairValueHigh.toFixed(2)}`:"Consensus range unavailable"}</span><em className={item.price<=item.fairValue?"below":"above"}>{Math.abs((item.price-item.fairValue)/item.fairValue*100).toFixed(1)}% {item.price<=item.fairValue?"below":"above"} reference</em></>:<><strong>Not available</strong><span>Do not invent a fair price when valuation coverage is missing.</span></>}</aside>}<p>{isFund?"Compare expense ratio, diversification, overlap and plan availability.":"Analyst consensus is a reference—not intrinsic value or a prediction. Validate cash flow, growth, debt, dilution, moat and filings."}</p></section>}
     <span className="open-chart">Analyze {item.symbol} on complete chart →</span>
    </button>
   })}
  </div></>}
  <footer><b>Separation rule:</b> Never treat retirement assets as swing-trading capital. Future compounder status is uncertain and must be validated with fundamentals, valuation, filings, diversification and suitability. Northstar never places an order.</footer>
 </section>
}
