'use client';
import {useEffect,useState} from 'react';
const money=(n:number)=>n.toLocaleString(undefined,{style:'currency',currency:'USD'});
export default function CapitalRotationPanel({accountId}:{accountId:string}){
 const [notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0),[queuing,setQueuing]=useState(false);
 const requestAnalysis=async()=>{setQueuing(true);try{const r=await fetch('/api/intelligence-loop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accountId}),signal:AbortSignal.timeout(20000)}),body=await r.json();if(!r.ok||!body.queued)throw Error(body.error||'Unable to queue analysis');setNotice('Account analysis queued. Refresh results after the worker completes; missing configuration still needs to be resolved.')}catch(e){setNotice(e instanceof Error?e.message:'Unable to queue analysis')}finally{setQueuing(false)}};
 const [rows,setRows]=useState<any[]>([]),[status,setStatus]=useState('LOADING');
 useEffect(()=>{const control=new AbortController();setRows([]);setStatus('LOADING');if(!accountId){setStatus('EMPTY');return()=>control.abort()}fetch(`/api/investments/rotation?accountId=${encodeURIComponent(accountId)}`,{signal:control.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();const data=await r.json();setRows(data.reviews||[]);setStatus(data.reviews?.length?'SUCCESS':'EMPTY')}).catch(()=>{if(!control.signal.aborted)setStatus('ERROR')});return()=>control.abort()},[accountId,refresh]);
 return <section className="card today-support-panel" style={{minWidth:0,overflowWrap:'anywhere'}}><h2>Hold, rebuy or rotate?</h2><button disabled={queuing||!accountId} onClick={()=>void requestAnalysis()}>{queuing?"Queuing…":"Request fresh comparison"}</button> <button onClick={()=>setRefresh(x=>x+1)}>Refresh results</button>{notice&&<p role="status">{notice}</p>}<p>Compare existing holdings with researched alternatives after estimated taxes, costs and account risk. These reviews never place orders.</p>{status==='LOADING'?<p>Loading account comparisons…</p>:status==='ERROR'?<p>Rotation reviews are unavailable. Try again after the connection recovers.</p>:status==='EMPTY'?<p>Account comparisons are pending the background research worker. No rotation is authorized.</p>:rows.map(row=>{const stale=Date.now()-Date.parse(row.asOf)>5*60000,p=row.choices?.[0]?.comparison?.proposal;return <details key={row.ticker} style={{padding:'12px 0',borderTop:'1px solid #64748b55'}}><summary><strong>{row.ticker} · {stale?'STALE — recheck required':row.action.replaceAll('_',' ')}</strong> · {row.status.replaceAll('_',' ')}</summary><p>{row.status==="INSUFFICIENT_DATA"?"No sell-to-buy comparison is ready for this holding. The app cannot yet establish whether switching would improve the result.":row.reason}</p>{row.status==="INSUFFICIENT_DATA"&&<><p><b>Alternatives awaiting analysis:</b> {row.choices?.map((c:any)=>c.ticker).join(", ")}</p><ul>{[...new Set<string>((row.choices||[]).flatMap((c:any)=>c.comparison?.reasons||[]))].map(reason=><li key={reason}>{reason}</li>)}</ul><a target="_blank" rel="noopener noreferrer" href={`/workspace/charts?symbol=${encodeURIComponent(row.ticker)}&accountId=${encodeURIComponent(accountId)}&timeframe=5m&view=validation#market-charts`}>Review {row.ticker} on chart ↗</a></>}{row.status!=="INSUFFICIENT_DATA"&&row.choices?.map((c:any)=><div key={c.ticker}><b>Compared with {c.ticker}</b><p>{c.comparison.reasons.join(' ')}</p>{c.comparison.rebuyScore!=null&&<p>Also compared with the planned rebuy, conditional on that entry occurring.</p>}</div>)}{p&&<p>Review selling {p.sellShares} {p.sellTicker} at reference {money(p.sellReferencePrice)}; estimated proceeds {money(p.estimatedProceeds)}, estimated gain/loss {money(p.estimatedRealizedPL)}, tax {money(p.estimatedTax)}. Then buy at most {p.buyShares} {p.buyTicker} with limit {money(p.orderPrice)}, stop {money(p.stop)}, targets {p.targets.map(money).join(' / ')}. Estimated cash: {money(p.cashBefore)} → {money(p.cashAfterSale)} after sale → {money(p.cashAfter)} after purchase. {p.cancelConditions.join('. ')}.</p>}<small>Reviewed {new Date(row.asOf).toLocaleString()} · {stale?'Not actionable until refreshed.':'User confirmation required.'}</small>{row.outcome&&<p>Hypothetical comparison: {row.outcome.note}</p>}</details>})}</section>
}
