"use client";
import {useEffect,useState} from 'react';
const usd=(value:unknown)=>value==null?'Unavailable':Number(value).toLocaleString('en-US',{style:'currency',currency:'USD'});
export default function ChartOptionPositions({accountId,symbol}:{accountId:string;symbol:string}){
 const[state,setState]=useState<{key:string;data:any;error:string}>({key:'',data:null,error:''}),[revision,setRevision]=useState(0);
 const key=accountId+':'+symbol,data=state.key===key?state.data:null,error=state.key===key?state.error:'';
 useEffect(()=>{let active=true,busy=false;const controller=new AbortController();
 const load=async()=>{if(busy||!accountId)return;busy=true;try{const r=await fetch('/api/market/option-positions?accountId='+encodeURIComponent(accountId)+'&symbol='+encodeURIComponent(symbol),{cache:'no-store',signal:controller.signal});const body=await r.json();if(!r.ok)throw Error(body.error||'Option positions unavailable');if(active)setState({key,data:body,error:''});}catch(e){if(active)setState(old=>({key,data:old.key===key?old.data:null,error:'Refresh failed; any displayed values are from the previous check.'}));}finally{busy=false;}};
 void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};const timer=setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);return()=>{active=false;controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};
 },[accountId,symbol,revision]);
 return <section className="chart-option-positions" aria-label={`${symbol} option positions`}><div className="chart-option-heading"><h3>{symbol} · Your option positions</h3><button type="button" onClick={()=>setRevision(n=>n+1)}>Refresh positions</button></div>
 {error&&<p role="status">{error}</p>}{data?.quoteError&&<p role="status">{data.quoteError}</p>}
 {!data&&!error?<p>Loading recorded option positions…</p>:data&&!data.positions.length?<p>No open option positions recorded for this stock in the selected account. <a href={'/workspace/options?accountId='+encodeURIComponent(accountId)+'&symbol='+encodeURIComponent(symbol)}>Open Options Analysis →</a></p>:null}
 {!!data?.positions.length&&<><p>Refreshes every 15 seconds while visible · {data.feed==='opra'?'OPRA feed':'Indicative feed — modified quotes, not an executable live price'} · Checked {new Date(data.checkedAt).toLocaleTimeString()}</p><div className="chart-option-grid">{data.positions.map((p:any)=><article key={p.symbol}><b>{p.type} · {usd(p.strike)} · {p.expiration}</b><p>{p.quantity<0?'Short':'Long'} {Math.abs(p.quantity)} contracts · {p.source}</p><dl><div><dt>Average premium / share</dt><dd>{usd(p.average)}</dd></div><div><dt>{p.quoteStatus==='QUOTE_MIDPOINT'?'Quote midpoint / share':'Saved premium / share'}</dt><dd>{usd(p.premium)}</dd></div><div><dt>Position value</dt><dd>{usd(p.value)}</dd></div><div><dt>Unrealized gain / loss</dt><dd>{usd(p.pnl)}</dd></div></dl><p>{p.asOf?'Price as of '+new Date(p.asOf).toLocaleString():'No dated price available'}. {p.multiplier==null?'Adjusted contract: multiplier must be verified before valuing.':'Standard 100-share contract.'}</p>{p.greeks&&<small>Delta {p.greeks.delta??'—'} · Theta {p.greeks.theta??'—'} · Vega {p.greeks.vega??'—'}</small>}</article>)}</div><small>Option premiums are separate from the underlying stock’s price axis. Midpoint values are estimates, not executable prices.</small></>}
 </section>;
}
