"use client";
import OptionBreakEvenCalculator from './option-break-even-calculator';
import {getCognitoSession} from '@/lib/cognito-client';
import {useEffect,useState} from 'react';
type R=Record<string,any>;
const money=(v:unknown)=>v==null||!Number.isFinite(Number(v))?'Unavailable':Number(v).toLocaleString('en-US',{style:'currency',currency:'USD'});
export default function ChartOptionResearch({accountId,symbol,contractSymbol='',onPlan}:{accountId:string;symbol:string;contractSymbol?:string;onPlan?:(c:R|null)=>void}){
 const key=[accountId,symbol,contractSymbol].join(':'),[state,setState]=useState<{key:string;data:R|null}>({key:'',data:null}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false);const data=state.key===key?state.data:null;
 const headers=()=>({'Content-Type':'application/json',...(getCognitoSession()?.idToken?{Authorization:'Bearer '+getCognitoSession()!.idToken}:{}),...(localStorage.getItem('northstar-household-id')?{'X-Household-ID':localStorage.getItem('northstar-household-id')!}:{})});
 useEffect(()=>{let active=true;const controller=new AbortController();setError('');setNotice('');onPlan?.(null);const load=async()=>{if(!accountId)return;try{const q=new URLSearchParams({accountId,symbol,...(contractSymbol?{contract:contractSymbol}:{})}),r=await fetch('/api/market/options/contract?'+q,{headers:headers(),cache:'no-store',signal:controller.signal}),d=await r.json();if(!r.ok)throw Error(d.error);if(active){setState({key,data:d});setError('');onPlan?.(contractSymbol?d.contracts[0]||null:null);}}catch(e){if(active)setError(e instanceof Error?e.message:'Contract research unavailable')}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},15000);return()=>{active=false;controller.abort();clearInterval(timer)}},[key,revision,onPlan]);
 const refresh=async()=>{setBusy(true);try{const r=await fetch('/api/market/options/scan',{method:'POST',headers:headers(),body:JSON.stringify({accountId,symbol})}),d=await r.json();if(!r.ok)throw Error(d.error);setNotice('Fresh '+symbol+' contract research queued. Saved contract details remain visible and update as the worker finishes.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section id="selected-option-research" className="selected-option-research" aria-label="Selected option contract"><header><div><span>OPTIONS · {data?.accountName||'Selected account'}</span><h3>{contractSymbol?'Selected contract · '+symbol:'CALL / PUT research · '+symbol}</h3>{contractSymbol&&<small>{contractSymbol}</small>}</div><button type="button" disabled={busy||!accountId} onClick={refresh}>{busy?'Queuing…':'Refresh contract research'}</button></header>{error&&<p role="alert">{error} <button onClick={()=>setRevision(n=>n+1)}>Retry loading</button></p>}{notice&&<p role="status">{notice}</p>}{!data&&!error&&<p>Loading the selected account’s saved contract analysis…</p>}{data?.message&&<p>{data.message}</p>}
 {data?.contracts.map((c:R)=><article key={c.contractSymbol}><h4>{c.symbol} {c.type} · {money(c.strike)} strike · {c.expiration} · {c.dte} DTE</h4><p><b>{c.stale?'Saved research · revalidation required':c.decision||'Research candidate'}</b> · {c.executionReady?'Execution checks passed in the saved analysis; reconfirm current quotes.':'Conditional research; no execution approval.'}</p><p>{c.expectation?.replaceAll('_',' ')} · {c.whyContract}</p><dl>{[['Bid / ask / mid',`${money(c.bid)} / ${money(c.ask)} / ${money(c.mid)}`],['Bid–ask spread',c.ask>0&&c.bid>=0?`${money(c.ask-c.bid)} · ${(((c.ask-c.bid)/((c.ask+c.bid)/2))*100).toFixed(2)}%`:'Refresh two-sided quote'],['Maximum entry premium / share',money(c.maximumEntryPremium??c.ask)],['Proposed / modeled contracts',`${c.stale?0:c.contracts??0} / ${c.expectedContracts??c.contracts??0}`],['Modeled total premium / maximum loss',money(Number(c.expectedContracts??c.contracts??0)*Number(c.premium||0))],['Break-even at expiration',money(c.breakEven)],['Underlying trigger',money(c.trigger)],['Underlying invalidation',money(c.invalidation)],['Underlying target',money(c.target)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{c.levelBasis&&<p><b>Level calculation:</b> {c.levelBasis}</p>}<p><b>Confirmation:</b> {c.confirmation||'Not supplied; refresh research.'}</p><p><b>Why it is not ready:</b> {[...(c.readinessBlockers||[]),...(c.reasons||[])].join('; ')||'Recheck live underlying, quote, account capacity and confirmation.'}</p><p>Delta {c.delta??'Unavailable'} · Gamma {c.gamma??'Unavailable'} · Theta {c.theta??'Unavailable'} · Vega {c.vega??'Unavailable'} · IV {c.iv==null?'Unavailable':(c.iv*100).toFixed(1)+'%'} · expected move ±{money(c.expectedMove)}</p><p><b>Exit rule:</b> {c.optionExitRule||'Not supplied'} · <b>Time stop:</b> {c.timeStop||'Not supplied'}</p><p><b>Cancel:</b> {c.cancelConditions?.join('; ')||'Refresh missing cancellation conditions before acting.'}</p><p>{c.whyAlternative}</p><small>Option quote {c.quoteAsOf||'Unavailable'} · underlying {c.underlyingAsOf||'Unavailable'} · analysis {c.asOf||data.updatedAt||'Unavailable'}. Premiums are separate from the underlying chart’s price axis.</small><OptionBreakEvenCalculator key={c.contractSymbol} contract={c}/></article>)}
 </section>;
}
