"use client";
import BuildVersion from "./build-version";
import {useEffect,useState} from "react";
import {getCognitoSession,startCognitoLogin} from "@/lib/cognito-client";
import {GLOBAL_DEFAULTS,type GlobalSettings} from "@/lib/app-configuration";
import type {TradingPolicy} from "@/lib/trading-policy";
import AiHealthPanel from "@/app/ai-health-panel";
type Account={accountId:string;name:string;value:number;cash:number;recommended:TradingPolicy;effective:TradingPolicy};
type Data={settings:GlobalSettings;accounts:Account[];configurationHealth:string;providers:{name:string;status:string;lastSuccess:string|null;lastError:string|null;environment:string|null}[]};
const words=(text:string)=>text.replace(/([A-Z])/g," $1").replace(/Bps/g,"basis points").replace(/^./,s=>s.toUpperCase());
const explanations:Record<string,string>={swingRiskBps:"Maximum loss to the stop for each swing entry; sizes the trade.",dayRiskBps:"Lower risk budget for each intraday entry; separate from swing ownership.",combinedRiskBps:"Caps total open risk across strategies in this account.",maxPositionBps:"Limits a single ticker’s share of account value.",maxSectorBps:"Limits exposure to one industry sector.",dailyLossBps:"New entries stop when the daily day-trade loss limit is reached.",weeklyDrawdownBps:"Blocks additional risk when the weekly drawdown threshold is reached.",fridaySwing:"Friday swing entries need unusually strong independent evidence.",requireConfirmation:"Touching a trigger never authorizes an order.",timezone:"Used for your notification and review displays; exchange calculations remain New York time.",marketTimezone:"The U.S. exchange timezone is fixed to America/New_York.",quoteFreshnessSeconds:"Maximum quote age; stale information must not authorize entry.",defaultAccountId:"Account selected when opening account-specific plans.",morningReview:"Desired exchange-time morning review schedule.",preCloseReview:"Desired exchange-time review before the closing bell.",afterCloseReview:"Desired exchange-time after-close analysis schedule."};
export default function ConfigurationCenter(){
  const[data,setData]=useState<Data|null>(null),[settings,setSettings]=useState<GlobalSettings>(GLOBAL_DEFAULTS),[error,setError]=useState(""),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[auth,setAuth]=useState(false),[higher,setHigher]=useState(false),[message,setMessage]=useState("");
  const headers=()=>({"Content-Type":"application/json",...(getCognitoSession()?.idToken?{Authorization:`Bearer ${getCognitoSession()!.idToken}`}:{}) ,...(localStorage.getItem("northstar-household-id")?{"X-Household-ID":localStorage.getItem("northstar-household-id")!}:{})});
  const load=async()=>{try{const r=await fetch("/api/configuration",{headers:headers(),cache:"no-store"});if(r.status===401){setAuth(true);return;}const value=await r.json();if(!r.ok)throw Error(value.error);setData(value);setSettings(value.settings);setError("");localStorage.setItem("northstar-display-settings",JSON.stringify(value.settings));}catch(e){setError(String(e));}};
  useEffect(()=>{void load();},[]);
  const save=async(body:unknown)=>{setBusy(true);setMessage("");try{const r=await fetch("/api/configuration",{method:"PUT",headers:headers(),body:JSON.stringify(body)}),v=await r.json();if(!r.ok)throw Error(v.error);await load();setMessage(v.status?`Provider test: ${v.status}${v.error?" · "+v.error:""}`:"Saved. Risk changes invalidate prior recommendations and queue a fresh review.");window.dispatchEvent(new Event("northstar:configuration-changed"));}catch(e){setError(String(e));}finally{setBusy(false);}};
  const matches=(s:string)=>s.toLowerCase().includes(query.toLowerCase());
  return <main style={{maxWidth:1000,width:"100%",padding:16,margin:"0 auto",boxSizing:"border-box",overflowWrap:"anywhere"}}><a href="/workspace/settings">Back to Settings</a><h1>Configuration Center</h1><BuildVersion/><p>{data?.configurationHealth||"Checking configuration…"}</p>{auth&&<button onClick={()=>void startCognitoLogin()}>Sign in</button>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<label>Search settings <input style={{maxWidth:"100%"}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Timezone, risk, provider…"/></label>
  <details><summary>First-time setup checklist</summary><ol><li>Choose your timezone below.</li><li>Test required data providers; credentials stay on the server.</li><li><a href="/workspace/notifications">Review notification channels</a> and grant push permission in Settings.</li><li><a href="/workspace/accounts">Create or import investment accounts</a>.</li><li>Review account goals and recommended risk defaults below.</li><li>Resolve Missing Provider or Needs Attention before using trade recommendations.</li></ol></details>
  <section><h2>Global App, Market &amp; Data Settings</h2><p>Review schedule and data settings must be supported by the server worker. Exchange-time calculations remain separate from display time.</p>{Object.entries(settings).filter(([k])=>matches(words(k))).map(([key,value])=><label key={key} style={{display:"block",padding:"10px 0"}}><b>{words(key)}</b><br/>{typeof value==="boolean"?<input type="checkbox" checked={value} onChange={e=>setSettings(s=>({...s,[key]:e.target.checked}))}/>:<input style={{maxWidth:"100%",minWidth:0}} type={typeof value==="number"?"number":"text"} value={String(value)} disabled={["marketTimezone","holidayCalendar","currency"].includes(key)} onChange={e=>setSettings(s=>({...s,[key]:typeof value==="number"?Number(e.target.value):e.target.value}))}/>}<small style={{display:"block"}}>{explanations[key]||`Controls ${words(key).toLowerCase()} for your workspace. Stored per user.`}</small></label>)}<button disabled={busy} onClick={()=>void save({settings})}>Save global settings</button> <button disabled={busy} onClick={()=>void save({restore:true})}>Restore recommended defaults</button></section>
  <section><h2>API / Provider Connections</h2><p>Secrets are configured only on the server. A successful connection test does not prove Fidelity authorization or completed delivery.</p>{data?.providers.filter(p=>matches(p.name)).map(p=><article key={p.name} style={{padding:12,borderBottom:"1px solid #ccd8d2"}}><h3>{p.name} — {p.status}</h3><p>Environment {p.environment||"Provider default"} · Last successful test {p.lastSuccess||"Never"}</p><p>{p.lastError}</p><button disabled={busy} onClick={()=>void save({testProvider:p.name})}>Test connection</button></article>)}</section>
  <section><h2>Account-Level Trading &amp; Risk</h2><p>100 basis points = 1% of account value. Recommended amounts scale with account equity, cash and concentration; unknown liquidity uses conservative defaults.</p><label><input type="checkbox" checked={higher} onChange={e=>setHigher(e.target.checked)}/>I reviewed and accept materially higher custom risk.</label>{data?.accounts.map(a=><details key={a.accountId}><summary>{a.name} · ${a.value.toFixed(2)} account value</summary>{Object.entries(a.effective).filter(([k])=>!["version","label"].includes(k)&&matches(words(k))).map(([key,value])=><label key={key} style={{display:"block",padding:10}}><b>{words(key)}</b><br/>{typeof value==="boolean"?<input type="checkbox" checked={value} disabled={key==="requireConfirmation"||key==="extendedHours"} onChange={e=>setData(d=>d&&({...d,accounts:d.accounts.map(x=>x.accountId===a.accountId?{...x,effective:{...x.effective,[key]:e.target.checked}}:x)}))}/>:<input style={{maxWidth:"100%"}} type={typeof value==="number"?"number":"text"} value={String(value)} onChange={e=>setData(d=>d&&({...d,accounts:d.accounts.map(x=>x.accountId===a.accountId?{...x,effective:{...x.effective,[key]:typeof value==="number"?Number(e.target.value):e.target.value}}:x)}))}/>}<small style={{display:"block"}}>RECOMMENDED DEFAULTS: {String(a.recommended[key as keyof TradingPolicy])}{key.endsWith("Bps")?` (${(a.value*Number(a.recommended[key as keyof TradingPolicy])/10000).toFixed(2)} USD)`:""}. {explanations[key]||`Controls ${words(key).toLowerCase()} for this account.`}</small>{typeof value==="number"&&value>Number(a.recommended[key as keyof TradingPolicy])*1.5&&<strong>Materially higher risk than recommended</strong>}</label>)}<button disabled={busy} onClick={()=>void save({accountId:a.accountId,policy:a.effective,acceptHigherRisk:higher})}>Save account risk</button> <button disabled={busy} onClick={()=>void save({accountId:a.accountId,restore:true})}>Restore recommended defaults</button></details>)}</section>
  <section><h2>AI / Model Settings</h2><AiHealthPanel accessToken={typeof window!=="undefined"?getCognitoSession()?.idToken:null}/></section><section><h2>Notifications, Security &amp; System Health</h2><p><a href="/workspace/notifications">Notification Center and channel preferences</a> · <a href="/workspace/system-health">Workers, queues, provider health and security</a></p><p>No API keys, provider tokens or broker credentials are returned by this page. Trading remains separately authorized.</p></section>
  </main>;
}
