"use client";
import {useMemo,useState} from "react";
type Holding=Record<string,any>;
type Result={symbol:string;account:string;purpose:string;shares:number;averageCost:number|null;marketValue:number;unrealized:number|null;weight:number;price:number|null;ema20:number|null;sma50:number|null;rsi:number|null;relVol:number|null;pe:number|null;news:number;state:"favorable"|"review"|"risk"|"missing";action:string;evidence:string;risk:string;invalidation:string;missing:string[];riskLevel:number|null;riskDollars:number|null;rewardLevel:number|null;rewardDollars:number|null;buyMoreShares:number;trimShares:number;decision:string;asOf:string};
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const ema=(a:number[],p:number)=>a.length?a.slice(1).reduce((x,y)=>y*(2/(p+1))+x*(1-2/(p+1)),a[0]):null;
const calcRsi=(a:number[])=>{if(a.length<15)return null;const s=a.slice(-15),d=s.slice(1).map((v,i)=>v-s[i]),g=avg(d.map(v=>Math.max(v,0))),l=avg(d.map(v=>Math.max(-v,0)));return l?100-100/(1+g/l):100};
const money=(value:number|null)=>value===null?"—":`$${Math.abs(value).toLocaleString(undefined,{maximumFractionDigits:2})}`;

export default function ConnectedHoldingsAnalysis({holdings,mode,onOpen}:{holdings:Holding[];mode:"swing"|"long-term";onOpen:(symbol:string)=>void}){
 const unique=useMemo(()=>[...new Map(holdings.filter(h=>h.ticker).map(h=>[String(h.ticker).toUpperCase(),h])).values()],[holdings]);
 const portfolioValue=useMemo(()=>holdings.reduce((sum,h)=>sum+Number(h.market_value_cents||0)/100,0),[holdings]);
 const[results,setResults]=useState<Result[]>([]),[busy,setBusy]=useState(false),[status,setStatus]=useState("Not analyzed yet");
 const analyze=async()=>{setBusy(true);setStatus(`Analyzing ${unique.length} current connected or manual holdings…`);const values=await Promise.all(unique.slice(0,30).map(async h=>{
  const symbol=String(h.ticker).toUpperCase(),missing:string[]=[],shares=Number(h.quantity||0),storedMarket=Number(h.market_value_cents||0)/100,costBasis=h.cost_basis_cents==null?null:Number(h.cost_basis_cents)/100,averageCost=costBasis!==null&&shares>0?costBasis/shares:null,weight=portfolioValue?storedMarket/portfolioValue*100:0;
  try{const[bRes,rRes]=await Promise.all([fetch(`/api/market/bars?symbol=${encodeURIComponent(symbol)}&range=1Y`,{cache:"no-store"}),fetch(`/api/market/research?symbol=${encodeURIComponent(symbol)}`,{cache:"no-store"})]),b=await bRes.json(),r=await rRes.json(),bars=Array.isArray(b.bars)?b.bars:[],closes=bars.map((x:any)=>Number(x.close)).filter(Number.isFinite),volumes=bars.map((x:any)=>Number(x.volume)).filter(Number.isFinite),price=closes.at(-1)||Number(r.quote?.c)||null,e20=ema(closes.slice(-80),20),s50=closes.length>=50?avg(closes.slice(-50)):null,rsi=calcRsi(closes),relVol=volumes.length>20&&volumes.at(-1)?Number(volumes.at(-1))/avg(volumes.slice(-21,-1)):null,m=r.metrics||{},pe=Number.isFinite(Number(m.peTTM))?Number(m.peTTM):Number.isFinite(Number(m.peBasicExclExtraTTM))?Number(m.peBasicExclExtraTTM):null,news=Array.isArray(r.news)?r.news.length:0,trend=price&&e20&&s50?price>e20&&e20>s50?"bullish":price<s50?"bearish":"mixed":"unknown",marketValue=price?price*shares:storedMarket,unrealized=costBasis===null?null:marketValue-costBasis;
  if(!bRes.ok||closes.length<50)missing.push("sufficient price history");if(!rRes.ok)missing.push("fundamentals/news");if(pe===null)missing.push("valuation");if(costBasis===null)missing.push("purchase cost for profit/loss");
  let state:Result["state"]="review",action="WAIT / REVIEW",risk="Confirm size, liquidity, account constraints and news before acting.",invalidation="Define the exact price or thesis condition that proves the idea wrong.";
  if(mode==="swing"){if(trend==="bullish"&&rsi!==null&&rsi<70){state="favorable";action="HOLD / BUY-MORE REVIEW"}else if(trend==="bearish"){state="risk";action="REDUCE / EXIT REVIEW"}invalidation=`A ${trend==="bearish"?"reclaim":"close"} ${e20?`around EMA20 ($${e20.toFixed(2)})`:"at the defined trend level"} changes this reading.`}else{if(trend==="bullish"&&(pe===null||pe<45)){state="favorable";action="HOLD / CONTRIBUTION REVIEW"}else if(pe!==null&&pe>60){state="risk";action="VALUATION / TRIM REVIEW";risk="Valuation is demanding; verify growth, cash flow, taxes and alternatives."}invalidation="Material deterioration in revenue, earnings, cash flow, debt or long-term trend weakens the thesis."}
  if(missing.filter(x=>x!=="purchase cost for profit/loss").length>=3){state="missing";action="DATA REQUIRED"}
  const reference=price?(mode==="swing"?(e20||s50):(s50?Math.min(price,s50*.9):null)):null,riskLevel=reference&&reference<price?reference:null,riskDollars=riskLevel?Math.max(0,(price!-riskLevel)*shares):null,rewardLevel=riskLevel?price!+2*(price!-riskLevel):null,rewardDollars=rewardLevel?Math.max(0,(rewardLevel-price!)*shares):null,isFund=/ETF|FUND|TRUST|INDEX/.test(String(h.name||"").toUpperCase())||/^(VTI|VOO|SPY|IVV|ITOT|VXUS|SPGP|FFLC|SCHD|VYM|DGRO)$/.test(symbol),maxWeight=isFund?25:10,maxValue=portfolioValue*maxWeight/100,buyMoreShares=state==="favorable"&&price&&marketValue<maxValue?Math.max(0,Math.floor((maxValue-marketValue)/price)):0,trimShares=price&&marketValue>maxValue?Math.max(0,Math.ceil((marketValue-maxValue)/price)):0;
  const decision=state==="missing"?"Do not buy or sell from an incomplete analysis. Retry when market, valuation, and news evidence are available.":state==="risk"?`Do not add. Review selling${trimShares?` up to ${trimShares.toLocaleString()} shares to return near the ${maxWeight}% position guide`:" or exiting"} only if the price/valuation signal and original thesis confirm each other.`:state==="favorable"?buyMoreShares?`Evidence permits considering up to ${buyMoreShares.toLocaleString()} additional shares before reaching the ${maxWeight}% position guide. Use staged purchases; do not buy solely from this signal.`:`Hold or redirect new contributions elsewhere; this position is already at or above the ${maxWeight}% sizing guide.`:"Hold and wait. Buy only after trend/valuation confirmation; sell only if the invalidation or investment thesis fails.";
  return{symbol,account:String(h.nickname||h.name||"Connected account"),purpose:String(h.investment_purpose||"Unassigned"),shares,averageCost,marketValue,unrealized,weight,price,ema20:e20,sma50:s50,rsi,relVol,pe,news,state,action,evidence:`${trend.toUpperCase()} structure · ${rsi===null?"RSI unavailable":`RSI ${rsi.toFixed(1)}`} · ${relVol===null?"relative volume unavailable":`${relVol.toFixed(2)}× relative volume`}`,risk,invalidation,missing,riskLevel,riskDollars,rewardLevel,rewardDollars,buyMoreShares,trimShares,decision,asOf:new Date().toISOString()}
  }catch{return{symbol,account:String(h.nickname||h.name||"Connected account"),purpose:String(h.investment_purpose||"Unassigned"),shares,averageCost,marketValue:storedMarket,unrealized:costBasis===null?null:storedMarket-costBasis,weight,price:null,ema20:null,sma50:null,rsi:null,relVol:null,pe:null,news:0,state:"missing" as const,action:"DATA REQUIRED",evidence:"Live analysis failed.",risk:"Do not decide from missing evidence.",invalidation:"Retry when providers are available.",missing:["market, technical and fundamental data"],riskLevel:null,riskDollars:null,rewardLevel:null,rewardDollars:null,buyMoreShares:0,trimShares:0,decision:"Do not buy or sell until live evidence is available.",asOf:new Date().toISOString()}}
 }));setResults(values);setStatus(`Completed ${new Date().toLocaleString()} · ${values.length} holdings`);setBusy(false)};
 return <section className="connected-analysis"><header><div><span>LIVE PORTFOLIO HOLDING REVIEW · {mode.toUpperCase()}</span><h3>Shares, profit, loss, risk and next action</h3><p>Uses current holdings with technical, valuation, and news evidence. Targets are scenarios—not guaranteed prices.</p></div><button disabled={busy||!unique.length} onClick={analyze}>{busy?"Analyzing…":"Analyze all current holdings"}</button></header><div className="analysis-status">{status}</div>{results.map(x=><article className={x.state} key={x.symbol}><div><span>{x.action}</span><h4>{x.symbol} · {x.account}</h4><small>{x.purpose} · {x.weight.toFixed(1)}% of portfolio</small></div><dl className="position-metrics"><div><dt>Shares owned</dt><dd>{x.shares.toLocaleString()}</dd></div><div><dt>Average cost</dt><dd>{x.averageCost===null?"Not provided":`$${x.averageCost.toFixed(2)}`}</dd></div><div><dt>Market value</dt><dd>{money(x.marketValue)}</dd></div><div><dt>Unrealized P/L</dt><dd className={x.unrealized!==null&&x.unrealized<0?"loss":"gain"}>{x.unrealized===null?"Cost needed":`${x.unrealized>=0?"+":"−"}${money(x.unrealized)}`}</dd></div><div><dt>Live price</dt><dd>{x.price?`$${x.price.toFixed(2)}`:"—"}</dd></div><div><dt>Risk reference</dt><dd>{x.riskLevel?`$${x.riskLevel.toFixed(2)}`:"—"}</dd></div><div><dt>Scenario loss</dt><dd>{x.riskDollars===null?"—":`−${money(x.riskDollars)}`}</dd></div><div><dt>2:1 scenario profit</dt><dd>{x.rewardDollars===null?"—":`+${money(x.rewardDollars)}`}</dd></div></dl><p className="decision-line"><b>Position decision:</b> {x.decision}</p><p><b>Evidence:</b> {x.evidence} · {x.pe?`P/E ${x.pe.toFixed(1)}×`:"P/E unavailable"} · {x.news} news items checked</p><p><b>Risk:</b> {x.risk}</p><p><b>Sell/trim trigger:</b> {x.invalidation}</p>{x.missing.length>0&&<p className="missing"><b>Missing:</b> {x.missing.join(", ")}</p>}<footer><time>{new Date(x.asOf).toLocaleString()}</time><button onClick={()=>onOpen(x.symbol)}>Open full chart analysis →</button></footer></article>)}{!unique.length&&<div className="analysis-empty">No purpose-matched holdings. Add a manual holding or synchronize Plaid, then assign the account purpose.</div>}</section>
}
