"use client";
import {useEffect,useState} from "react";
const lessons=[
 {title:"Connect your real investment account",screen:"SECURE CONNECTION",text:"Open Accounts or Portfolio, choose Connect retirement account, complete Plaid Link, then press Sync now. Northstar receives read-only account and holding data; it never receives your bank password.",route:"/workspace/portfolio",action:"Open Portfolio"},
 {title:"Name it and choose its purpose",screen:"ACCOUNT CONTEXT",text:"Expand the connected investment account. Add a nickname and select Swing, Options, Long-term, Retirement, Dividend income, or Mixed. This prevents retirement money from being evaluated with short-term trading rules.",route:"/workspace/portfolio",action:"Classify accounts"},
 {title:"Clean and evaluate the portfolio",screen:"CURRENT VS TARGET",text:"Review current allocation against the target. Green means research an underweight area, blue means near target, and red means an overweight or concentration review. Verify any unrecognized mutual-fund classification.",route:"/workspace/portfolio",action:"Review allocation"},
 {title:"Understand each suggestion",screen:"EVIDENCE BEFORE ACTION",text:"Read the reason, dollar gap, fees, tax and restriction warnings. Prefer directing new contributions to underweight categories before selling. A red card starts a review; it is not an automatic sell order.",route:"/workspace/portfolio",action:"See recommendations"},
 {title:"Research the holdings",screen:"MARKET + FUNDAMENTALS",text:"Use Smart Suggestions and Chart Analysis to review price structure, moving averages, volume, fundamentals, valuation, dividends, news, confidence, confirmation and invalidation.",route:"/workspace/markets",action:"Open Smart Suggestions"},
 {title:"Track the plan over time",screen:"WATCHLIST + JOURNAL",text:"Add candidates to the live watchlist, set target and invalidation review levels, then record the decision. Return later to compare the original thesis with the actual outcome.",route:"/workspace/journal",action:"Open Decision Journal"}
];
export default function HelpVideoGuides(){const[index,setIndex]=useState(0),[playing,setPlaying]=useState(false),lesson=lessons[index];useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setIndex(value=>{if(value>=lessons.length-1){setPlaying(false);return value}return value+1}),6500);return()=>clearInterval(timer)},[playing]);return <section className="help-video-guides"><header><div><span>GUIDED VIDEO WALKTHROUGH</span><h3>Connect, clean, evaluate, and improve your portfolio</h3><p>Six short in-app chapters. Pause at any time and open the exact feature being demonstrated.</p></div><button onClick={()=>setPlaying(value=>!value)}>{playing?"Ⅱ Pause":"▶ Play guide"}</button></header><div className="guide-player"><aside><b>{lesson.screen}</b><strong>{String(index+1).padStart(2,"0")}</strong><div className="demo-window"><i/><i/><i/><span>{lesson.title}</span><em style={{width:`${((index+1)/lessons.length)*100}%`}}/></div></aside><article><span>CHAPTER {index+1} OF {lessons.length}</span><h4>{lesson.title}</h4><p>{lesson.text}</p><a href={lesson.route}>{lesson.action} →</a></article></div><nav aria-label="Tutorial chapters">{lessons.map((item,itemIndex)=><button key={item.title} className={itemIndex===index?"active":""} onClick={()=>{setIndex(itemIndex);setPlaying(false)}}><i>{itemIndex+1}</i><span>{item.title}</span></button>)}</nav><footer><b>Safety check:</b> Suggestions are explanations for your review. Northstar cannot rebalance accounts, change payroll elections, transfer funds, or submit trades.</footer></section>}
