"use client";
import {useEffect,useMemo,useRef,useState} from "react";

type Bar={time:string;open:number;high:number;low:number;close:number;volume:number};
type Props={symbol:string;entryLow:number;entryHigh:number;stop:number;target1:number;target2:number;support:number;resistance:number;confidence:number;action:string;strategy:string};
const avg=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;
const series=(values:number[],period:number,ema=false)=>{let prior=values[0]||0,k=2/(period+1);return values.map((value,index)=>{prior=ema?(index?value*k+prior*(1-k):value):index+1<period?NaN:avg(values.slice(index-period+1,index+1));return prior})};

export default function IntegratedResearchChart(props:Props){
 const canvas=useRef<HTMLCanvasElement>(null),preferencesLoaded=useRef(false),[timeframe,setTimeframe]=useState("1D"),[bars,setBars]=useState<Bar[]>([]),[status,setStatus]=useState("Loading candles…"),[zoom,setZoom]=useState(1),[cursor,setCursor]=useState<{x:number;y:number}|null>(null),[studies,setStudies]=useState({ema20:true,ema50:true,bands:true,fib:true,volume:true,levels:true,scenarios:true});
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(`northstar-chart:${props.strategy}`)||"{}");if(saved.timeframe)setTimeframe(saved.timeframe);if(saved.studies)setStudies(current=>({...current,...saved.studies}))}catch{}finally{preferencesLoaded.current=true}},[props.strategy]);
 useEffect(()=>{if(!preferencesLoaded.current)return;try{localStorage.setItem(`northstar-chart:${props.strategy}`,JSON.stringify({timeframe,studies}))}catch{}},[props.strategy,timeframe,studies]);
 useEffect(()=>{let active=true;setStatus("Loading provider candles…");fetch(`/api/market/bars?symbol=${encodeURIComponent(props.symbol)}&range=${timeframe}`,{cache:"no-store"}).then(async response=>({ok:response.ok,data:await response.json()})).then(({ok,data})=>{if(!active)return;if(!ok){setBars([]);setStatus(data.error||"Candle data unavailable");return}setBars(data.bars||[]);setStatus(`${data.provider||"Alpaca"} · ${data.feed||"market feed"} · ${data.asOf?new Date(data.asOf).toLocaleString():"timestamp unavailable"}`)}).catch(()=>active&&setStatus("Candle data unavailable")).finally(()=>active&&setZoom(1));return()=>{active=false}},[props.symbol,timeframe]);
 const view=useMemo(()=>bars.slice(-Math.max(30,Math.round(Math.min(bars.length,120)/zoom))),[bars,zoom]);
 const setup=useMemo(()=>{if(view.length<20)return null;const closes=view.map(x=>x.close),last=view.at(-1)!,ema20=series(closes,20,true).at(-1)!,ema50=series(closes,50,true).at(-1)!,recent=view.slice(-20),mid=avg(recent.map(x=>x.close)),sd=Math.sqrt(avg(recent.map(x=>(x.close-mid)**2))),atr=avg(view.slice(-14).map((x,i,a)=>Math.max(x.high-x.low,Math.abs(x.high-(a[i-1]?.close||x.open)),Math.abs(x.low-(a[i-1]?.close||x.open))))),trend=last.close>ema20&&ema20>ema50?"Bullish":last.close<ema20&&ema20<ema50?"Bearish":"Neutral",bull=Math.max(10,Math.min(70,Math.round(props.confidence*.35+(trend==="Bullish"?28:14)))),bear=Math.max(10,Math.min(55,Math.round((100-props.confidence)*.35+(trend==="Bearish"?28:12)))),base=100-bull-bear;return{last,ema20,ema50,mid,upper:mid+2*sd,lower:mid-2*sd,atr,trend,bull,base,bear,high:Math.max(...recent.map(x=>x.high)),low:Math.min(...recent.map(x=>x.low))}},[view,props.confidence]);
 useEffect(()=>{const el=canvas.current;if(!el||!view.length||!setup)return;const rect=el.getBoundingClientRect(),dpr=devicePixelRatio||1;el.width=rect.width*dpr;el.height=rect.height*dpr;const g=el.getContext("2d")!;g.scale(dpr,dpr);const w=rect.width,h=rect.height,left=58,right=16,top=22,bottom=studies.volume?72:30,levels=[props.stop,props.target1,props.target2,props.support,props.resistance,props.entryLow,props.entryHigh],lo=Math.min(...view.map(x=>x.low),...levels.filter(Number.isFinite),setup.low-setup.atr*2),hi=Math.max(...view.map(x=>x.high),...levels.filter(Number.isFinite),setup.high+setup.atr*2),span=Math.max(.01,hi-lo),py=(value:number)=>top+(hi-value)/span*(h-top-bottom),cw=(w-left-right)/view.length;g.fillStyle="#07130f";g.fillRect(0,0,w,h);g.strokeStyle="#193028";for(let i=0;i<6;i++){const y=top+i*(h-top-bottom)/5;g.beginPath();g.moveTo(left,y);g.lineTo(w-right,y);g.stroke();g.fillStyle="#9db2a9";g.font="11px Arial";g.fillText((hi-i*span/5).toFixed(2),4,y+4)}
 const closes=view.map(x=>x.close),draw=(values:number[],color:string,width=1.6)=>{g.strokeStyle=color;g.lineWidth=width;g.beginPath();let began=false;values.forEach((v,i)=>{if(!Number.isFinite(v))return;const x=left+(i+.5)*cw,y=py(v);began?g.lineTo(x,y):g.moveTo(x,y);began=true});g.stroke()};if(studies.bands){const mids=series(closes,20),upper=mids.map((m,i)=>Number.isFinite(m)?m+2*Math.sqrt(avg(closes.slice(Math.max(0,i-19),i+1).map(v=>(v-m)**2))):NaN),lower=mids.map((m,i)=>Number.isFinite(m)?m-2*Math.sqrt(avg(closes.slice(Math.max(0,i-19),i+1).map(v=>(v-m)**2))):NaN);draw(upper,"#8068c9",1);draw(lower,"#8068c9",1)}if(studies.ema20)draw(series(closes,20,true),"#f0b84b",2);if(studies.ema50)draw(series(closes,50,true),"#62aee8",2);
 if(studies.levels){const zone=(low:number,high:number,color:string,label:string)=>{const y1=py(high),y2=py(low);g.fillStyle=color;g.fillRect(left,y1,w-left-right,Math.max(3,y2-y1));g.fillStyle="#eaf5ef";g.fillText(label,left+6,y1+12)};zone(Math.min(props.entryLow,props.entryHigh),Math.max(props.entryLow,props.entryHigh),"rgba(44,151,109,.20)","ENTRY ZONE");zone(props.support-setup.atr*.12,props.support+setup.atr*.12,"rgba(50,137,213,.16)","SUPPORT");zone(props.resistance-setup.atr*.12,props.resistance+setup.atr*.12,"rgba(222,170,66,.16)","RESISTANCE");[[props.stop,"#ee7468","STOP / INVALIDATION"],[props.target1,"#69d2a5","TARGET 1"],[props.target2,"#3bbf85","TARGET 2"]].forEach(([value,color,label])=>{const y=py(Number(value));g.strokeStyle=String(color);g.setLineDash([6,4]);g.beginPath();g.moveTo(left,y);g.lineTo(w-right,y);g.stroke();g.setLineDash([]);g.fillStyle=String(color);g.fillText(String(label),w-right-112,y-3)})}
 if(studies.fib&&setup.high>setup.low)[.236,.382,.5,.618,.786].forEach(level=>{const value=setup.high-(setup.high-setup.low)*level,y=py(value);g.strokeStyle="rgba(116,201,166,.28)";g.beginPath();g.moveTo(left,y);g.lineTo(w-right,y);g.stroke();g.fillStyle="#75bea1";g.fillText(`FIB ${(level*100).toFixed(1)}%`,left+4,y-2)});
 if(studies.scenarios){const start=w-right-105,x2=w-right,project=(center:number,width:number,color:string,label:string)=>{const y1=py(center+width),y2=py(center-width);g.fillStyle=color;g.beginPath();g.moveTo(start,py(setup.last.close));g.lineTo(x2,y1);g.lineTo(x2,y2);g.closePath();g.fill();g.fillStyle="#dcebe4";g.fillText(label,start+4,(y1+y2)/2)};project(setup.last.close+setup.atr*1.25,setup.atr*.65,"rgba(47,177,126,.18)",`BULL ${setup.bull}%`);project(setup.last.close,setup.atr*.7,"rgba(216,173,72,.13)",`BASE ${setup.base}%`);project(setup.last.close-setup.atr*1.25,setup.atr*.65,"rgba(224,91,81,.16)",`BEAR ${setup.bear}%`)}
 const maxVol=Math.max(...view.map(x=>x.volume));view.forEach((bar,i)=>{const x=left+(i+.5)*cw,color=bar.close>=bar.open?"#35c98e":"#f06d65";g.strokeStyle=g.fillStyle=color;g.beginPath();g.moveTo(x,py(bar.high));g.lineTo(x,py(bar.low));g.stroke();g.fillRect(x-Math.max(1.5,cw*.25),Math.min(py(bar.open),py(bar.close)),Math.max(3,cw*.5),Math.max(2,Math.abs(py(bar.open)-py(bar.close))));if(studies.volume){const vh=bar.volume/maxVol*48;g.globalAlpha=.5;g.fillRect(x-Math.max(1,cw*.28),h-18-vh,Math.max(2,cw*.56),vh);g.globalAlpha=1}});if(cursor){g.strokeStyle="#d9e8e1";g.setLineDash([3,3]);g.beginPath();g.moveTo(cursor.x,top);g.lineTo(cursor.x,h-bottom+48);g.moveTo(left,cursor.y);g.lineTo(w-right,cursor.y);g.stroke();g.setLineDash([])}},[view,setup,studies,cursor,props]);
 const toggle=(key:keyof typeof studies)=>setStudies(current=>({...current,[key]:!current[key]}));return <section className="integrated-research-chart"><header><div><span>ANALYSIS VISUALIZED · {props.strategy.toUpperCase()}</span><h4>{props.symbol} evidence map</h4><p>{status}</p></div><b>{setup?.trend||"Loading"}<small>{props.action}</small></b></header><nav className="chart-timeframes">{["1m","5m","15m","30m","1h","4h","1D","1W","1M","3M","1Y","5Y"].map(value=><button className={timeframe===value?"active":""} onClick={()=>setTimeframe(value)} key={value}>{value}</button>)}<button onClick={()=>setZoom(1)}>Reset</button></nav><div className="chart-study-controls">{Object.entries(studies).map(([key,on])=><button className={on?"active":""} onClick={()=>toggle(key as keyof typeof studies)} key={key}>{on?"✓ ":"+ "}{key.replace(/([A-Z0-9])/g," $1")}</button>)}</div><div className="integrated-chart-canvas">{view.length?<canvas ref={canvas} aria-label={`${props.symbol} candlestick analysis with recommendation levels`} onWheel={event=>{event.preventDefault();setZoom(value=>Math.max(.65,Math.min(3,value+(event.deltaY<0?.15:-.15))))}} onMouseMove={event=>{const rect=event.currentTarget.getBoundingClientRect();setCursor({x:event.clientX-rect.left,y:event.clientY-rect.top})}} onMouseLeave={()=>setCursor(null)}/>:<p>{status}</p>}</div>{setup&&<footer><span><b>Trend</b>{setup.trend}</span><span><b>EMA20 / EMA50</b>${setup.ema20.toFixed(2)} / ${setup.ema50.toFixed(2)}</span><span><b>ATR</b>${setup.atr.toFixed(2)}</span><span><b>Scenarios · 1–5 sessions</b>Bull {setup.bull}% · Base {setup.base}% · Bear {setup.bear}%</span><small>Scenario bands are volatility ranges, not guaranteed prices. Invalidation: ${props.stop.toFixed(2)}.</small></footer>}</section>
}
