"use client";

import {useEffect,useState,type ReactNode} from "react";
import {ConfirmationModal} from "./confirmation-modal";

type Draft={ticker:string;name:string;quantity:string;averageCost:string;currentPrice:string;currentValue:string;acquisitionDate:string};
const empty:Draft={ticker:"",name:"",quantity:"",averageCost:"",currentPrice:"",currentValue:"",acquisitionDate:""};
type Props={account:Record<string,any>;holdings:Array<Record<string,any>>;onSave:(id:string,nickname:string,purpose:string,cashBalance?:number)=>Promise<boolean>;onSaveTactical?:(account:Record<string,any>,allowed:boolean)=>Promise<boolean>;onAddHolding:(id:string,holding:{ticker:string;name:string;quantity:number;averageCost:number|null;currentPrice:number|null;currentValue:number|null;acquisitionDate:string|null;mode?:'ADD'|'REPLACE'|'MERGE'|'DELETE'})=>Promise<boolean>;onDeleteManual?:(account:Record<string,any>)=>Promise<boolean>;children?:ReactNode};
const cleanIdentity=(value:unknown)=>{const seen=new Set<string>();return String(value||'').split(/[·,]/).map(part=>part.trim()).filter(part=>{const key=part.toLowerCase();if(!key||seen.has(key))return false;seen.add(key);return true}).join(' · ')};

export default function InvestmentAccountProfile({account,holdings,onSave,onSaveTactical,onAddHolding,onDeleteManual,children}:Props){
 const[pendingRemoval,setPendingRemoval]=useState<Record<string,any>|null>(null);
 const[expanded,setExpanded]=useState(false),[nickname,setNickname]=useState(String(account.nickname||"")),[purpose,setPurpose]=useState(String(account.investment_purpose||"")),[cashBalance,setCashBalance]=useState(String(Number(account.available_balance_cents||0)/100)),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const readPolicy=()=>{try{return typeof account.policy_json==="string"?JSON.parse(account.policy_json):account.policy_json||{}}catch{return{}}},[tacticalSwingAllowed,setTacticalSwingAllowed]=useState(Boolean(readPolicy().tacticalSwingAllowed)),[tacticalSaving,setTacticalSaving]=useState(false),[tacticalMessage,setTacticalMessage]=useState("");
 const[holding,setHolding]=useState<Draft>(empty),[editingTicker,setEditingTicker]=useState<string|null>(null),[holdingBusy,setHoldingBusy]=useState(false),[deleting,setDeleting]=useState(false);
 useEffect(()=>{setNickname(String(account.nickname||""));setPurpose(String(account.investment_purpose||""));setCashBalance(String(Number(account.available_balance_cents||0)/100));setTacticalSwingAllowed(Boolean(readPolicy().tacticalSwingAllowed))},[account.nickname,account.investment_purpose,account.available_balance_cents,account.policy_json]);
 useEffect(()=>{const requested=sessionStorage.getItem("northstar-manage-investment-account");if(requested!==String(account.id))return;setExpanded(true);const timer=window.setTimeout(()=>{document.getElementById(`tactical-swing-policy-${account.id}`)?.scrollIntoView({behavior:"smooth",block:"center"});sessionStorage.removeItem("northstar-manage-investment-account")},250);return()=>window.clearTimeout(timer)},[account.id]);
 const value=holdings.reduce((sum,item)=>sum+Number(item.market_value_cents||0),0)/100,isManual=!account.connection_id,providerAge=account.last_provider_update_at?Date.now()-new Date(account.last_provider_update_at).getTime():Infinity,syncLabel=isManual?"MANUAL":account.investment_sync_error?"ERROR":String(account.investment_sync_status)==="WAITING_PROVIDER"?"WAITING FOR PROVIDER":String(account.investment_sync_status)==="REFRESHING"?"SYNCING":providerAge>36*60*60*1000?"STALE":"CONNECTED",sourceName=String(account.official_name||account.name||"Investment account"),ownerName=cleanIdentity(account.owner_name||account.manual_owner_name||"Household"),sourceDetail=cleanIdentity([account.subtype||account.type,account.mask?`ending ${account.mask}`:null,ownerName].filter(Boolean).join(" · "));
 const coaching=purpose==="Swing"?"Prioritize price structure, liquidity, volume, entry, stop, target and short holding period.":purpose==="Options"?"Prioritize contract liquidity, spread, expiration, Greeks, volatility, maximum premium loss and underlying trend.":purpose==="Dividend income"?"Prioritize dividend coverage, free cash flow, payout ratio, growth history, yield traps and diversification.":purpose==="Retirement"?"Prioritize diversification, fees, employer match, contribution plan, long horizon and tax restrictions—not short-term signals.":purpose==="Long-term"?"Prioritize 3–5 year revenue, EPS and cash-flow growth, valuation, moat, debt, dilution and contribution-based rebalancing.":purpose==="Mixed"?"Separate every holding by objective before applying swing, options, income, or long-term rules.":"Choose a purpose so recommendations use the correct timeframe and risk rules.";
 const save=async()=>{if(!nickname.trim()||!purpose){setMessage("Enter a nickname and select a purpose.");return}setSaving(true);setMessage("Saving…");const cash=Number(cashBalance);if(isManual&&(!Number.isFinite(cash)||cash<0)){setMessage("Enter cash of zero or greater.");setSaving(false);return}const ok=await onSave(String(account.id),nickname.trim(),purpose,isManual?cash:undefined);setMessage(ok?`✓ Saved ${isManual?"as a manual account":"and attached to this Plaid account"}.`:"Save failed. Review the message above.");setSaving(false)};
 const saveTactical=async()=>{setTacticalSaving(true);setTacticalMessage("Saving Tactical Swing policy…");let ok=false;if(onSaveTactical)ok=await onSaveTactical(account,tacticalSwingAllowed);else try{let policy:Record<string,any>={};try{policy=readPolicy()}catch{}const accountPurpose=String(account.investment_purpose||"").toLowerCase(),token=localStorage.getItem("northstar-access-token")||"",household=localStorage.getItem("northstar-household-id")||"",response=await fetch("/api/investment-accounts",{method:"PUT",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`} :{}),...(household?{"X-Household-ID":household}:{})},body:JSON.stringify({accountId:account.id,strategyType:account.strategy_type||(/swing|option/.test(accountPurpose)?"SWING":"GROWTH_5_7"),shareMode:account.share_mode||"WHOLE",benchmarkSymbol:account.benchmark_symbol||(/swing|option/.test(accountPurpose)?"SPY":"VTI"),goalName:account.goal_name||account.investment_purpose||"Investment growth",horizonMonths:Number(account.horizon_months||(/swing|option/.test(accountPurpose)?6:72)),riskProfile:account.risk_profile||"BALANCED",maximumPositionBps:Number(account.maximum_position_bps??1000),maximumRiskBps:Number(account.maximum_risk_bps??50),availableCashCents:String(account.available_cash_cents??account.available_balance_cents??0),policy:{...policy,tacticalSwingAllowed}})});ok=response.ok;if(!ok){const data=await response.json().catch(()=>({}));setTacticalMessage(data.error||"Tactical Swing policy could not be saved.")}}catch{ok=false}if(ok)setTacticalMessage(`✓ Tactical Swing ${tacticalSwingAllowed?"enabled":"disabled"} for this account only.`);else if(!tacticalMessage)setTacticalMessage("Tactical Swing policy could not be saved. Review the account message above.");setTacticalSaving(false)};
 const edit=(item:Record<string,any>)=>{const quantity=Number(item.quantity||0),averageCost=item.cost_basis_cents==null||quantity<=0?"":(Number(item.cost_basis_cents)/100/quantity).toFixed(2),currentPrice=item.market_value_cents!=null&&quantity>0?(Number(item.market_value_cents||0)/100/quantity).toFixed(2):"";setHolding({ticker:String(item.ticker||""),name:String(item.name||""),quantity:String(quantity),averageCost,currentPrice,currentValue:item.market_value_cents==null?"":(Number(item.market_value_cents)/100).toFixed(2),acquisitionDate:String(item.acquisition_date||"").slice(0,10)});setEditingTicker(String(item.ticker||""));setMessage(`Editing ${item.ticker}. Add the average purchase cost and save.`)};
 const saveHolding=async()=>{setHoldingBusy(true);const ok=await onAddHolding(String(account.id),{ticker:holding.ticker.trim().toUpperCase(),name:holding.name.trim(),quantity:Number(holding.quantity),averageCost:holding.averageCost.trim()===""?null:Number(holding.averageCost),currentPrice:holding.currentPrice.trim()===""?null:Number(holding.currentPrice),mode:editingTicker?'REPLACE':'ADD',currentValue:holding.currentValue.trim()===""?null:Number(holding.currentValue),acquisitionDate:holding.acquisitionDate||null});if(ok){setHolding(empty);setEditingTicker(null);setMessage("✓ Manual holding saved.")}setHoldingBusy(false)};
 return <section className={`investment-account-profile ${expanded?"is-expanded":"is-collapsed"}`}>
  <header><button aria-expanded={expanded} aria-controls={`investment-account-${account.id}`} aria-label={`${expanded?"Collapse":"Open"} ${account.nickname||sourceName}`} onClick={()=>setExpanded(current=>!current)}>{expanded?"▾":"▸"}</button><div><b>{account.nickname||sourceName}</b><span>{cleanIdentity(`${account.subtype||"Investment account"} · ${ownerName}`)}</span></div><em>{account.investment_purpose||"Purpose required"}</em><strong>${value.toLocaleString(undefined,{maximumFractionDigits:0})}<small>{holdings.length} holding{holdings.length===1?"":"s"}</small></strong></header>
  {expanded&&<><div className="investment-account-settings" id={`investment-account-${account.id}`}><label>Account nickname<input value={nickname} placeholder="Example: Jose Roth Growth" onChange={event=>setNickname(event.target.value)}/><small className="plaid-account-identity"><b>{isManual?"Manual account":"Plaid source"}</b><span>{isManual?sourceDetail:cleanIdentity(`${sourceName} · ${sourceDetail}`)}</span></small></label><label>What is this account for?<select value={purpose} onChange={event=>setPurpose(event.target.value)}><option value="" disabled>Select purpose</option>{["Swing","Options","Long-term","Retirement","Dividend income","Mixed"].map(value=><option key={value}>{value}</option>)}</select><small className="plaid-account-identity">This purpose controls where the account and holdings are analyzed.</small>{isManual&&<span className="manual-cash-editor"><b>Uninvested cash $</b><input type="number" min="0" step="0.01" value={cashBalance} onChange={event=>setCashBalance(event.target.value)}/><small>Cash is analyzed together with this account holdings.</small></span>}</label><div><b>How Northstar will coach it</b><p>{coaching}</p></div><div className="account-profile-save"><button disabled={saving||!nickname.trim()||!purpose} onClick={save}>{saving?"Saving…":"Save account profile"}</button><small>{message||`${holdings.length} ${isManual?"manually maintained":"synchronized"} holdings · read-only`}</small></div></div>
   {/Swing|Mixed/i.test(purpose)&&<section className="account-profile-tactical" id={`tactical-swing-policy-${account.id}`}><div><span>ACCOUNT POLICY</span><b>Configure Tactical Swing</b><p>Allow Northstar to evaluate temporary partial trim-and-rebuy opportunities for this account. It remains analysis only and requires stronger confirmation than an ordinary HOLD, TRIM or SELL review.</p></div><label><input type="checkbox" checked={tacticalSwingAllowed} onChange={event=>setTacticalSwingAllowed(event.target.checked)}/> Allow Tactical Swing for {nickname||sourceName}</label><button type="button" disabled={tacticalSaving} onClick={saveTactical}>{tacticalSaving?"Saving…":"Save Tactical Swing setting"}</button><small>{tacticalMessage||`Currently ${tacticalSwingAllowed?"enabled":"disabled"} for this account.`}</small></section>}
   {!isManual&&<section className="account-sync-status"><b>{syncLabel}</b><span>Holdings {account.last_investment_sync_at?new Date(account.last_investment_sync_at).toLocaleString():"never"} · provider refresh {account.last_provider_update_at?new Date(account.last_provider_update_at).toLocaleString():"waiting"}</span>{account.investment_sync_error&&<small>{account.investment_sync_error}</small>}</section>}{isManual&&<section className="account-sync-status manual"><b>MANUAL</b><span>Owner {ownerName} · cash ${(Number(account.available_balance_cents||0)/100).toLocaleString()}</span></section>}
   {children}
   {isManual&&<section className="manual-holdings"><header><b>{editingTicker?`Edit ${editingTicker}`:"Fill this account’s portfolio"}</b><span>Select Edit to add purchase cost or correct a manually entered position.</span></header><div className="manual-holding-form"><label>Ticker<input value={holding.ticker} disabled={Boolean(editingTicker)} placeholder="AAPL" onChange={event=>setHolding(value=>({...value,ticker:event.target.value.toUpperCase()}))}/></label><label>Company or fund name<input value={holding.name} placeholder="Apple Inc." onChange={event=>setHolding(value=>({...value,name:event.target.value}))}/></label><label>Quantity<input type="number" min="0" step="0.0001" value={holding.quantity} onChange={event=>setHolding(value=>({...value,quantity:event.target.value}))}/></label><label>Average cost / share<input type="number" min="0" step="0.01" value={holding.averageCost} placeholder="Optional" onChange={event=>setHolding(value=>({...value,averageCost:event.target.value}))}/></label><label>Saved price / share (optional)<input type="number" min="0" step="0.01" value={holding.currentPrice} placeholder="Or enter current value" onChange={event=>setHolding(value=>({...value,currentPrice:event.target.value}))}/></label><label>Current position value $<input type="number" min="0" step="0.01" value={holding.currentValue} placeholder="Optional alternative" onChange={event=>setHolding(value=>({...value,currentValue:event.target.value}))}/></label><label>Acquisition date<input type="date" value={holding.acquisitionDate} onChange={event=>setHolding(value=>({...value,acquisitionDate:event.target.value}))}/></label><button disabled={holdingBusy||!holding.ticker||Number(holding.quantity)<=0||Number(holding.averageCost)<0||Number(holding.currentPrice)<0} onClick={saveHolding}>{holdingBusy?"Saving…":editingTicker?"Save changes":"Add holding"}</button>{editingTicker&&<button className="secondary" disabled={holdingBusy} onClick={()=>{setHolding(empty);setEditingTicker(null);setMessage("")}}>Cancel</button>}</div><div className="manual-holding-list">{holdings.map(item=><article key={item.holding_id||item.ticker}><b>{item.ticker}<small>{item.name}</small></b><span>{Number(item.quantity).toLocaleString()} shares</span><span>{item.cost_basis_cents==null?"Cost basis not shown":`Avg $${item.quantity?((Number(item.cost_basis_cents)/100)/Number(item.quantity)).toFixed(2):"0.00"}`}</span><strong>{item.market_value_cents==null?"Price unavailable":`${(Number(item.market_value_cents)/100).toLocaleString(undefined,{maximumFractionDigits:2})}`}</strong><button className="edit-holding" onClick={()=>edit(item)}>Edit</button><button disabled={holdingBusy} onClick={()=>setPendingRemoval(item)}>Remove</button></article>)}{!holdings.length&&<p>No holdings entered yet.</p>}</div></section>}
   {isManual&&onDeleteManual&&<section className="manual-account-actions"><div><b>Manual account controls</b><span>Delete this account only when you no longer need its holdings, history, or goal links.</span></div><button type="button" disabled={deleting} onClick={async()=>{setDeleting(true);const deleted=await onDeleteManual(account);if(!deleted)setDeleting(false)}}>{deleting?"Deleting…":"Delete manual account"}</button></section>}
  </>}
 <ConfirmationModal open={Boolean(pendingRemoval)} title={`Remove ${pendingRemoval?.ticker||"holding"}?`} description="Remove this record from the manual account. This does not sell shares." confirmLabel="Remove holding" variant="danger" loading={holdingBusy} error={message.startsWith("Remove failed")?message:undefined} onCancel={()=>setPendingRemoval(null)} onSubmit={async()=>{if(!pendingRemoval)return;setHoldingBusy(true);try{const ok=await onAddHolding(String(account.id),{ticker:pendingRemoval.ticker,name:pendingRemoval.name,quantity:0,averageCost:null,currentPrice:null,currentValue:null,acquisitionDate:null,mode:"DELETE"});if(ok){setPendingRemoval(null);setMessage("Holding removed.")}else setMessage("Remove failed. Review the account error and retry.")}catch{setMessage("Remove failed. Please retry.")}finally{setHoldingBusy(false)}}}/>
 </section>;
}
