"use client";
import{useEffect,useMemo,useState}from"react";

type Holding=Record<string,any>;
type Action={rank:number;priority:string;action:string;symbol:string|null;quantity:string;amountCents:string;priceCondition:string;when:string;why:string;capitalSource:string;lifecycle:string};
type Guidance={accountName:string;goalName:string;horizonMonths:number;onTrack:boolean;availableCashPlan:{cashCents:string;monthlyContributionCents:string;safeInvestmentCapacityCents:string;untouchedCashCents:string};today:Action[];queue:Action[]};
type Portfolio={totalValueCents:string;healthScore:number;categories:Array<{category:string;currentBps:number;targetBps:number;gapCents:string;status:string}>;holdings:Array<{symbol:string;weightBps:number;unrealizedPnlCents:string|null;action:string;suggestedQuantity:string}>;projections:{bearCents:string;baseCents:string;bullCents:string};goalProgressBps:number|null};
type Clock={status:string;isOpen?:boolean;nextOpen?:string;nextClose?:string};
const money=(cents:unknown,digits=0)=>Number.isFinite(Number(cents))?`$${(Number(cents)/100).toLocaleString(undefined,{minimumFractionDigits:digits,maximumFractionDigits:digits})}`:"—";
const label=(value:string)=>value.replaceAll("_"," ");
const authHeaders=(token:string)=>{const householdId=typeof window!=="undefined"?localStorage.getItem("northstar-household-id"):null;return{...(token?{Authorization:`Bearer ${token}`}:{}) ,...(householdId?{"X-Household-ID":householdId}:{})}};

export default function InvestmentCommandCenter({accountId,accessToken,holdings,netWorth,investmentValue,householdCash,totalDebt,monthlyIncome,monthlySpending,onNavigate}:{accountId:string;accessToken:string;holdings:Holding[];netWorth:number;investmentValue:number;householdCash:number;totalDebt:number;monthlyIncome:number;monthlySpending:number;onNavigate:(page:string)=>void}){
 const[guidance,setGuidance]=useState<Guidance|null>(null),[portfolio,setPortfolio]=useState<Portfolio|null>(null),[clock,setClock]=useState<Clock>({status:"loading"}),[quotes,setQuotes]=useState<Record<string,{last:number|null;bid:number|null;ask:number|null;freshness?:string}>>({}),[macro,setMacro]=useState<Array<{id:string;value:number|null;date:string|null}>>([]),[density,setDensity]=useState<"simple"|"pro">("simple"),[error,setError]=useState("");
 useEffect(()=>{const saved=localStorage.getItem("northstar-dashboard-density");if(saved==="pro")setDensity("pro")},[]);
 useEffect(()=>{let active=true;setError("");const headers=authHeaders(accessToken),symbols=[...new Set(holdings.map(item=>String(item.ticker||"").toUpperCase()).filter(Boolean))];Promise.all([accountId?fetch(`/api/action-guidance?accountId=${encodeURIComponent(accountId)}`,{cache:"no-store",headers}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Guidance unavailable");return b}):Promise.resolve(null),fetch("/api/market/clock",{cache:"no-store"}).then(r=>r.json()),symbols.length?fetch(`/api/market/quotes?symbols=${encodeURIComponent(symbols.join(","))}`,{cache:"no-store"}).then(r=>r.json()):Promise.resolve({quotes:{}}),fetch("/api/market/macro",{cache:"no-store"}).then(r=>r.json()).catch(()=>({series:[]}))]).then(([g,c,q,m])=>{if(!active)return;if(g){setGuidance(g.guidance);setPortfolio(g.portfolio)}setClock(c);setQuotes(q.quotes||{});setMacro(m.series||[])}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Command center unavailable")});return()=>{active=false}},[accountId,accessToken,holdings]);
 const now=new Date(),target=clock.isOpen?clock.nextClose:clock.nextOpen,remaining=target?Math.max(0,Date.parse(target)-now.getTime()):0,hours=Math.floor(remaining/3600000),minutes=Math.floor(remaining%3600000/60000),marketLabel=clock.status!=="connected"?"MARKET DATA SETUP REQUIRED":clock.isOpen?`OPEN · CLOSES IN ${hours}H ${minutes}M`:`CLOSED · OPENS IN ${hours}H ${minutes}M`,et=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(now),local=new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(now);
 const incomeGap=monthlyIncome-monthlySpending,emergencyMonths=monthlySpending>0?householdCash/monthlySpending:null,financialHealth=Math.max(0,Math.min(100,Math.round(50+(incomeGap>0?20:-20)+(totalDebt===0?15:-10)+(emergencyMonths!==null?Math.min(15,emergencyMonths*3):0)))),actions=guidance?.today||[],actionBySymbol=new Map((guidance?.queue||[]).filter(a=>a.symbol).map(a=>[a.symbol!,a])),portfolioRows=new Map((portfolio?.holdings||[]).map(h=>[h.symbol,h])),vix=macro.find(item=>item.id==="VIXCLS"),tenYear=macro.find(item=>item.id==="DGS10");
 const risks=useMemo(()=>{const result:Array<{tone:string;title:string;action:string}>=[];(portfolio?.categories||[]).filter(row=>row.status==="OVERWEIGHT").forEach(row=>result.push({tone:"caution",title:`${label(row.category)} ${(row.currentBps/100).toFixed(1)}% vs ${(row.targetBps/100).toFixed(1)}% target`,action:"Direct new contributions elsewhere before considering a sale."}));for(const row of portfolio?.holdings||[])if(row.weightBps>1000)result.push({tone:"danger",title:`${row.symbol} is ${(row.weightBps/100).toFixed(1)}% of this account`,action:"Do not add; review concentration, taxes, and thesis before reducing."});if(totalDebt>0)result.push({tone:"danger",title:`Household debt ${money(totalDebt*100)}`,action:"Confirm interest rates and protect household cash before aggressive investing."});if(emergencyMonths!==null&&emergencyMonths<6)result.push({tone:"caution",title:`Emergency cash covers ${emergencyMonths.toFixed(1)} months`,action:"Build toward the configured reserve before funding optional purchases."});return result.slice(0,5)},[portfolio,totalDebt,emergencyMonths]);
 const setMode=(mode:"simple"|"pro")=>{setDensity(mode);localStorage.setItem("northstar-dashboard-density",mode)};
 return <div className={`command-center ${density}`}>
  <section className="command-market-bar"><div><i/><b>U.S. MARKET {marketLabel}</b><span>Local {local} · Market {et}</span></div><span><small>S&amp;P 500</small><b>Live index feed pending</b></span><span><small>NASDAQ</small><b>Live index feed pending</b></span><span><small>VIX</small><b>{vix?.value?.toFixed(2)||"—"}</b></span><span><small>10Y YIELD</small><b>{tenYear?.value?.toFixed(2)||"—"}%</b></span><span><small>REGIME</small><b>{vix?.value==null?"Needs data":vix.value>=25?"Risk-off":vix.value<=17?"Constructive":"Mixed"}</b></span></section>
  <div className="command-heading"><div><span>INVESTMENT COMMAND CENTER</span><h2>What matters and what to do next</h2><p>One account-aware decision queue. Suggestions only; you confirm every transaction.</p></div><div className="density-toggle" aria-label="Dashboard density"><button className={density==="simple"?"active":""} onClick={()=>setMode("simple")}>Simple</button><button className={density==="pro"?"active":""} onClick={()=>setMode("pro")}>Pro</button></div></div>
  {error&&<div className="command-error">{error}</div>}
  <section className="command-metrics" aria-label="Financial summary"><article><small>NET WORTH</small><strong>{money(netWorth*100)}</strong><span>Assets minus debt</span></article><article><small>INVESTMENTS</small><strong>{money(investmentValue*100)}</strong><span>Current holding value</span></article><article><small>TODAY’S P&amp;L</small><strong>—</strong><span>Needs fresh prior-close marks</span></article><article><small>INVESTMENT CASH</small><strong>{money(guidance?.availableCashPlan.cashCents||0)}</strong><span>{money(guidance?.availableCashPlan.safeInvestmentCapacityCents||0)} safe capacity</span></article><article><small>HOUSEHOLD CASH</small><strong>{money(householdCash*100)}</strong><span>{emergencyMonths===null?"Reserve needs spending data":`${emergencyMonths.toFixed(1)} months coverage`}</span></article><article><small>TOTAL DEBT</small><strong>{money(totalDebt*100)}</strong><span>{totalDebt>0?"Review rate and payment priority":"No connected debt"}</span></article><article><small>PORTFOLIO HEALTH</small><strong>{portfolio?.healthScore??"—"}<em>/100</em></strong><span>Allocation and concentration</span></article><article><small>FINANCIAL HEALTH</small><strong>{financialHealth}<em>/100</em></strong><span>Cash flow, reserve, and debt</span></article></section>
  <section className="today-guidance command-panel"><header><div><span>TODAY’S GUIDANCE</span><h3>{guidance?.accountName||"Select an investment account"}</h3></div><button onClick={()=>onNavigate("Portfolio")}>Open full plan →</button></header>{actions.length?<ol>{actions.slice(0,density==="pro"?7:4).map(action=><li key={`${action.rank}-${action.symbol}-${action.action}`} className={`tone-${action.priority.toLowerCase()}`}><i>{action.rank}</i><div><strong>{action.symbol?`${action.symbol} — `:""}{label(action.action)}{Number(action.quantity)>0?` ${action.quantity} share${Number(action.quantity)===1?"":"s"}`:""}</strong><p>{action.priceCondition}</p><small>{action.why}</small></div><em>{label(action.priority)}</em></li>)}</ol>:<p className="command-empty">No account action is justified yet. Complete the selected account settings and evidence checks.</p>}</section>
  <div className="command-grid"><section className="allocation-command command-panel"><header><div><span>PORTFOLIO COMMAND CENTER</span><h3>Current allocation → required action</h3></div><b>{portfolio?.healthScore??"—"}/100</b></header><div>{portfolio?.categories.map(row=><article key={row.category} className={row.status.toLowerCase()}><div><b>{label(row.category)}</b><small>{(row.currentBps/100).toFixed(1)}% current / {(row.targetBps/100).toFixed(1)}% target</small></div><meter min="0" max="100" value={row.currentBps/100}/><strong>{row.status==="UNDERWEIGHT"?`Add ${money(row.gapCents)}`:row.status==="OVERWEIGHT"?`Stop adding · ${money(Math.abs(Number(row.gapCents)))} over`:"Near target"}</strong></article>)||<p>Choose an account to calculate its allocation.</p>}</div></section>
  <section className="cash-deployment command-panel"><header><div><span>CASH DEPLOYMENT</span><h3>What should available cash do?</h3></div></header><strong>{money(guidance?.availableCashPlan.safeInvestmentCapacityCents||0)}<small> safe to evaluate for investing</small></strong><ul>{actions.filter(a=>a.capitalSource&&a.action!=="HOLD").slice(0,3).map(a=><li key={`${a.rank}-${a.symbol}`}><b>{a.symbol||label(a.action)}</b><span>{a.capitalSource}</span></li>)}</ul><p>Keep {money(guidance?.availableCashPlan.untouchedCashCents||0)} untouched. Household reserves override optional buying.</p></section></div>
  <section className="holdings-terminal command-panel"><header><div><span>HOLDINGS ACTION TABLE</span><h3>Every position, one next decision</h3></div><button onClick={()=>onNavigate("Portfolio")}>Full holding review →</button></header><div className="terminal-scroll"><table><thead><tr><th>Ticker</th><th>Current</th><th>Shares</th><th>Average cost</th><th>Gain/loss</th><th>Portfolio</th><th>Thesis</th><th>AI action</th><th>Next trigger</th></tr></thead><tbody>{holdings.map(item=>{const symbol=String(item.ticker||"—").toUpperCase(),quantity=Number(item.quantity||0),value=Number(item.market_value_cents||0),cost=Number(item.cost_basis_cents||0),current=quantity>0?value/quantity:0,average=quantity>0?cost/quantity:0,pnl=cost>0?(value-cost)/cost*100:null,row=portfolioRows.get(symbol),action=actionBySymbol.get(symbol),quote=quotes[symbol];return <tr key={`${item.account_id}-${symbol}`}><td><b>{symbol}</b><small>{item.name}</small></td><td className="number">{quote?.last?`$${quote.last.toFixed(2)}`:money(current,2)}<small>{quote?.freshness||"stored"}</small></td><td className="number">{quantity.toLocaleString()}</td><td className="number">{money(average,2)}</td><td className={`number ${pnl==null?"neutral":pnl>=0?"positive":"negative"}`}>{pnl==null?"—":`${pnl>=0?"+":""}${pnl.toFixed(1)}%`}</td><td className="number">{row?`${(row.weightBps/100).toFixed(1)}%`:"—"}</td><td>Not reviewed</td><td><b>{action?label(action.action):row?label(row.action):"HOLD"}</b></td><td>{action?.priceCondition||"Continue monitoring"}</td></tr>})}</tbody></table></div>{!holdings.length&&<p className="command-empty">No holdings are recorded for the selected account.</p>}</section>
  <div className="command-grid"><section className="risk-radar command-panel"><header><div><span>RISK RADAR</span><h3>Risks that require attention</h3></div></header>{risks.length?<ul>{risks.map((risk,index)=><li className={risk.tone} key={index}><b>{risk.title}</b><span>{risk.action}</span></li>)}</ul>:<p className="command-empty">No material account or household risk is currently identified from available data.</p>}</section><section className="goal-progress command-panel"><header><div><span>GOAL PROGRESS</span><h3>{guidance?.goalName||"Account goal not configured"}</h3></div></header><div className="goal-score"><strong>{portfolio?.goalProgressBps==null?"—":`${Math.min(100,portfolio.goalProgressBps/100).toFixed(0)}%`}</strong><span>{guidance?.onTrack?"Base scenario on track":"Plan adjustment required"}</span></div><div className="goal-scenarios"><span><small>CONSERVATIVE</small><b>{money(portfolio?.projections.bearCents||0)}</b></span><span><small>BASE</small><b>{money(portfolio?.projections.baseCents||0)}</b></span><span><small>STRONG</small><b>{money(portfolio?.projections.bullCents||0)}</b></span></div><p>{guidance?.onTrack?"Keep contributions and allocation aligned; this remains a modeled scenario.":"Increase contributions, extend the horizon, or reduce the goal—do not force it by taking excessive risk."}</p></section></div>
  {density==="pro"&&<section className="pro-placeholder command-panel"><header><div><span>PRO ANALYTICS</span><h3>Additional verified intelligence</h3></div></header><div><button onClick={()=>onNavigate("Daily Action Plan")}>Best swing opportunities →</button><button onClick={()=>onNavigate("Growth Finder")}>Find Them Early →</button><button onClick={()=>onNavigate("Professional Charts")}>Prediction summaries →</button><button onClick={()=>onNavigate("Journal")}>Decision history →</button></div></section>}
 </div>
}
