"use client";
import {useEffect,useState} from 'react';
export default function InvestmentCashSettings({accountId}:{accountId:string}){
 const [data,setData]=useState<any>(null),[symbols,setSymbols]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const headers=()=>({'Content-Type':'application/json',Authorization:'Bearer '+(localStorage.getItem('northstar-access-token')||''),'X-Household-ID':localStorage.getItem('northstar-household-id')||''});
 useEffect(()=>{let active=true;setData(null);fetch('/api/investment-cash?accountId='+encodeURIComponent(accountId),{headers:headers()}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);if(active){setData(b);setSymbols(b.symbols.join(', '));}}).catch(e=>{if(active)setMessage(e.message)});return()=>{active=false}},[accountId]);
 const save=async()=>{setBusy(true);try{const r=await fetch('/api/investment-cash',{method:'PUT',headers:headers(),body:JSON.stringify({accountId,symbols:symbols.split(',').map(s=>s.trim().toUpperCase()).filter(Boolean)})}),b=await r.json();if(!r.ok)throw Error(b.error);setData(b);setMessage('Cash mapping saved. New analyses will use this cash; refresh account analysis for updated plans.');window.dispatchEvent(new Event('northstar:portfolio-changed'));}catch(e){setMessage(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}};
 return <section className="grid! min-w-0! gap-3! rounded-xl! border! border-cyan-300! bg-cyan-50! p-4! text-cyan-950!"><h3>Cash &amp; sweep holdings</h3><p>QDERQ (Chase) and SPAXX (Fidelity) are treated as cash for planning, not stock trade candidates. Provider-labeled cash is included automatically even when no ticker is supplied.</p><label>Cash symbols for this account<input className="w-full! rounded-lg! border! bg-white! p-3!" value={symbols} onChange={e=>setSymbols(e.target.value)} placeholder="QDERQ, SPAXX"/></label>{data&&<p>Cash for planning: ${(data.cashCents/100).toFixed(2)} · Mapped sweep holdings: ${(data.mappedCents/100).toFixed(2)}. Overlapping balances are counted once.</p>}<p>Cash is considered for qualified purchases after reserves and account risk limits. If nothing qualifies, keep it in cash. Verify settled buying power and any required fund redemption at your broker before entering an order.</p><button className="min-h-11! rounded-lg! bg-cyan-900! px-4! py-2! font-semibold! text-white!" disabled={busy||!data} onClick={save}>{busy?'Saving…':'Save cash mapping'}</button>{message&&<p role="status">{message}</p>}</section>
}
