"use client";
import {useState} from 'react';
const parse=(v:any)=>{try{return typeof v==='string'?JSON.parse(v):v||{}}catch{return {}}};
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
export default function KidsHoldingActions({rows,rotations,accessToken,onRefresh}:{rows:any[];rotations:any[];accessToken?:string;onRefresh:()=>Promise<void>}){
 const [busy,setBusy]=useState(''),[error,setError]=useState('');
 async function analyze(accountId:string,ticker:string){setBusy(accountId+ticker);setError('');try{const r=await fetch('/api/ai/decision',{method:'POST',headers:{'Content-Type':'application/json',...(accessToken?{Authorization:`Bearer ${accessToken}`}:{ }),...(localStorage.getItem('northstar-household-id')?{'X-Household-ID':localStorage.getItem('northstar-household-id')!}:{})},body:JSON.stringify({accountId,ticker,refresh:true})});const d=await r.json();if(!r.ok)throw Error(d.error||'Analysis unavailable');await onRefresh()}catch(e){setError(e instanceof Error?e.message:'Analysis unavailable')}finally{setBusy('')}}
 return <section className="kids-holding-actions"><h4>Hold, trim or replace</h4><p>These are the account’s central decisions. A higher target alone does not justify selling. A replacement needs a material advantage after risk, taxes, costs, diversification and the child’s goal are considered.</p>{error&&<p role="status">{error}</p>}
 {rows.map(row=>{const d=parse(row.output_json),available=Boolean(d.action)&&d.providerStatus==='AVAILABLE',action=available?String(d.action).replaceAll('_',' '):'WAIT · ANALYSIS REQUIRED';return <article key={row.account_id+row.ticker}><header><b>{row.ticker} · {row.quantity} shares held</b><strong>{action}</strong></header><p>{d.interpretation||'No current verified decision is available for this holding. Keep the existing position pending review.'}</p>{available&&<dl><div><dt>Proposed shares</dt><dd>{d.shares}</dd></div><div><dt>Trigger</dt><dd>{d.trigger==null?'—':money(d.trigger)}</dd></div><div><dt>Order price</dt><dd>{d.entryPlan?.orderPrice==null?'Not ready':money(d.entryPlan.orderPrice)}</dd></div><div><dt>Stop / invalidation</dt><dd>{d.stop==null?'—':money(d.stop)}</dd></div></dl>}{d.sellReason&&<p>Sale reason: {d.sellReason}</p>}<small>{d.dataTimestamp?`Evidence: ${new Date(d.dataTimestamp).toLocaleString()}`:'Fresh account-specific analysis is required.'}</small><button disabled={Boolean(busy)} onClick={()=>void analyze(row.account_id,row.ticker)}>{busy===row.account_id+row.ticker?'Analyzing…':'Refresh holding analysis'}</button></article>})}
 {!rows.length&&<p>Link an account with holdings to review its decisions.</p>}
 {rotations.map((row,index)=>{const p=parse(row.allocation_json),valid=p.choice==='ROTATE'&&Number(p.shares)>0&&Number(p.price)>0&&Date.parse(p.expiresAt)>Date.now()&&[p.cost,p.cashAfter,p.stop].every(v=>typeof v==='number'&&Number.isFinite(v));return valid?<article key={index}><header><b>{row.sold_ticker} sale proceeds → {p.ticker}</b><strong>REPLACEMENT REVIEW</strong></header><p>{p.reason}</p><p>After the recorded sale: consider {p.shares} shares of {p.ticker} near {money(p.price)}. Estimated cost {money(p.cost)}; cash after {money(p.cashAfter)}.</p><p>Stop / invalidation {money(p.stop)}. Revalidate entry confirmation and price before placing any order.</p><small>Reviewed {new Date(p.proposedAt).toLocaleString()} · expires {new Date(p.expiresAt).toLocaleString()}. This is a saved scenario, not a guaranteed return or an order.</small></article>:null})}
 <p className="kids-rotation-note">A paired “trim/sell → buy replacement” suggestion appears only when the lifecycle engine has a verified allocation plan. If no plan is shown, no replacement trade is ready. Use new contributions before unnecessary sales.</p></section>;
}
