"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
type SessionRow={symbol:string;price:number;changePct:number;above20Day:boolean};
export default function MarketSessionReport({marketOpen=false}:{marketOpen?:boolean}){
 const[rows,setRows]=useState<SessionRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updated,setUpdated]=useState<Date|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const symbols=["SPY","QQQ","IWM","DIA"],results=await Promise.all(symbols.map(async symbol=>{const response=await fetch(`/api/market/bars?symbol=${symbol}&range=1Y`,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||`${symbol} history unavailable`);const bars=Array.isArray(body.bars)?body.bars:[],latest=bars.at(-1),previous=bars.at(-2);if(!latest||!previous)throw new Error(`${symbol} does not have enough completed sessions`);const close=Number(latest.close),previousClose=Number(previous.close),recent=bars.slice(-20).map((bar:{close?:number})=>Number(bar.close)).filter(Number.isFinite),average=recent.reduce((sum:number,value:number)=>sum+value,0)/Math.max(1,recent.length);return{symbol,price:close,changePct:previousClose?(close-previousClose)/previousClose*100:0,above20Day:close>=average}}));setRows(results);setUpdated(new Date())}catch(reason){setError(reason instanceof Error?reason.message:"Market report unavailable")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const refresh=()=>{if(marketOpen&&document.visibilityState==="visible")void load()};window.addEventListener("northstar:realtime",refresh);return()=>window.removeEventListener("northstar:realtime",refresh)},[load,marketOpen]);
 const outlook=useMemo(()=>{const positive=rows.filter(row=>row.changePct>0).length,aboveTrend=rows.filter(row=>row.above20Day).length;if(positive>=3&&aboveTrend>=3)return{state:"constructive",label:"CONSTRUCTIVE, CONFIRM FIRST",text:"Broad indexes finished with positive breadth and most remain above their 20-session trend. Require the opening range and volume to confirm before adding risk."};if(positive<=1&&aboveTrend<=1)return{state:"defensive",label:"DEFENSIVE / CAPITAL PROTECTION",text:"Breadth and short-term trend are weak. Avoid automatic dip buying; protect cash and require a confirmed reversal before new entries."};return{state:"balanced",label:"MIXED / WAIT FOR CONFIRMATION",text:"The major indexes are not aligned. Let the opening range establish direction, then favor only account-qualified setups with sector confirmation and defined downside."}},[rows]);
 return <section className={`market-session-report card ${outlook.state}`}><header><div><span>{marketOpen?"LIVE U.S. MARKET CHECK":"COMPLETED SESSION REPORT"}</span><h2>{marketOpen?"Current market evidence":"Today’s market close and next-session outlook"}</h2><p>{marketOpen?"This evidence refreshes with the selected live interval.":"Completed-session data stays on demand while closed. The outlook is conditional, not a promised prediction."}</p></div><button onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"Refresh report"}</button></header>{loading&&!rows.length?<div className="session-report-skeleton" aria-label="Loading market report"><i/><i/><i/><i/></div>:error?<div className="session-report-error"><b>Report unavailable</b><span>{error}</span></div>:<><div className="session-index-grid">{rows.map(row=><article key={row.symbol}><span>{row.symbol}</span><b>${row.price.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</b><em className={row.changePct>=0?"up":"down"}>{row.changePct>=0?"+":""}{row.changePct.toFixed(2)}%</em><small>{row.above20Day?"Above":"Below"} 20-session trend</small></article>)}</div><div className="next-session-outlook"><span>TOMORROW / NEXT SESSION</span><b>{outlook.label}</b><p>{outlook.text}</p><ol><li>Check overnight news, earnings, rates, and index gaps.</li><li>Compare index direction with the account holding’s sector and volume.</li><li>Act only if the account trigger, position size, and invalidation still pass.</li></ol></div></>}{updated&&<footer>Provider session data · evaluated {updated.toLocaleString()}</footer>}</section>
}
