"use client";
import {useEffect,useState} from 'react';
export default function NextSessionResearch({accountId}:{accountId:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ticker,setTicker]=useState(''),[revision,setRevision]=useState(0);
 const headers=()=>({'Content-Type':'application/json',...(localStorage.getItem('northstar-access-token')?{Authorization:'Bearer '+localStorage.getItem('northstar-access-token')}:{ }),...(localStorage.getItem('northstar-household-id')?{'X-Household-ID':localStorage.getItem('northstar-household-id')!}:{})});
 useEffect(()=>{let live=true,busy=false;setData(null);const load=async()=>{if(busy||!accountId)return;busy=true;try{const r=await fetch('/api/next-session?accountId='+encodeURIComponent(accountId),{headers:headers(),signal:AbortSignal.timeout(20000)}),d=await r.json();if(!r.ok)throw Error(d.error);if(live){setData(d.cycle);setError('');}}catch{if(live)setError('Research progress could not load. Retry; the saved account plan remains available.');}finally{busy=false;}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);return()=>{live=false;clearInterval(timer)};},[accountId,revision]);
 const refresh=async(action:string)=>{setBusy(true);try{const r=await fetch('/api/next-session',{method:'POST',headers:headers(),body:JSON.stringify({accountId,action,symbol:ticker}),signal:AbortSignal.timeout(25000)}),d=await r.json();if(!r.ok)throw Error(d.error);setRevision(v=>v+1);}catch(e){setError((e instanceof Error?e.message:'Refresh timed out')+' — Retry');}finally{setBusy(false);}};
 return <details open className="account-research-results"><summary><span><span className="research-eyebrow">NEXT SESSION INTELLIGENCE</span><b>Next Session Research</b></span></summary><div className="research-panel-body"><p>{data?'Close '+new Date(data.close_at).toLocaleString()+' · '+data.stage.replaceAll('_',' ')+' · '+data.status:'The server builds research from the latest completed session.'}</p>{error&&<p role="status">{error}</p>}<div className="research-candidate-actions"><button disabled={busy} onClick={()=>void refresh('REFRESH_MARKET')}>Refresh Market Research</button><button disabled={busy} onClick={()=>void refresh('REFRESH_ACCOUNT')}>Refresh Account Plan</button><button disabled={busy} onClick={()=>void refresh('RETRY')}>Retry Failed Research</button><label>Ticker <input aria-label="Prioritize ticker" value={ticker} onChange={e=>setTicker(e.target.value.toUpperCase())} maxLength={12}/></label><button disabled={busy||!ticker} onClick={()=>void refresh('PRIORITIZE')}>Prioritize / Refresh Ticker</button></div>{busy&&<p role="status">Queuing server research…</p>}
 <div className="research-metrics">{Object.entries(data?.counts_json||{}).filter(([,v])=>typeof v==='number').map(([key,value])=><div key={key}><strong>{Number(value).toLocaleString()}</strong><span>{key.replaceAll('_',' ')}</span></div>)}</div><p>Last scan: {data?.counts_json?.last_scan?new Date(data.counts_json.last_scan).toLocaleString():'Not yet recorded'}. Unknown sector/cap classifications are excluded from coverage totals.</p>
 {data?.last_error&&<p role="status">{data.last_error} · Retry is available above.</p>}
 <details><summary>Macro evidence, sector rotation &amp; event-linked research</summary><div className="research-price-grid">{data?.context_json?.series?.map((r:any)=><div key={r.id}><dt>{r.label}</dt><dd>{r.value??'Unavailable'} {r.unit}</dd><small>{r.status} · {r.date||'No observation date'}</small>{r.source&&<p><a href={r.source} target="_blank" rel="noreferrer">Source ↗</a></p>}</div>)}</div><p>{data?.context_json?.markets?.map((r:any)=>r.symbol+': '+(r.changePct==null?'unavailable':r.changePct.toFixed(2)+'%')).join(' · ')}</p>{data?.edges?.map((e:any,index:number)=><p key={e.symbol+index}><b>{e.symbol}</b> · {e.evidence_json.reason} <a href={e.evidence_json.source} target="_blank" rel="noreferrer">{e.evidence_json.headline}</a></p>)}{data?.context_json?.limitations?.map((s:string)=><p key={s}>{s}</p>)}</details></div></details>;
}
