"use client";
import {useCallback,useEffect,useState} from "react";
import {getCognitoSession,startCognitoLogin} from "@/lib/cognito-client";
import EntryPlanDetails from "@/app/entry-plan-details";
import type {EntryPlan} from "@/lib/entry-plan";
type Snapshot={ticker:string;account:string;strategy:string|null;action:string;reason:string;immediateAction:boolean;entryPlan?:EntryPlan;[key:string]:unknown};
type Event={id:string;title:string;category:string;severity:string;summary:string;updated_at:string;unread:boolean;dismissed_at:string|null;snapshot_json:Snapshot};
type Preference={category:string;in_app:boolean;push:boolean;email:boolean};
type Data={events:Event[];timeline:{snapshot_json:Snapshot;created_at:string}[];deliveries:{channel:string;status:string;error_code:string|null}[];categories:string[];preferences:Preference[]};
export default function NotificationEventCenter({eventId,accessToken}:{eventId?:string;accessToken?:string|null}){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[filter,setFilter]=useState("All"),[auth,setAuth]=useState(false),[push,setPush]=useState("Checking push status"),[busy,setBusy]=useState(false);
  const headers=useCallback(()=>{const token=accessToken||getCognitoSession()?.idToken;return {"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...(localStorage.getItem("northstar-household-id")?{"X-Household-ID":localStorage.getItem("northstar-household-id")!}:{})};},[accessToken]);
  const load=useCallback(async()=>{try{const response=await fetch(`/api/notifications/events${eventId?`?id=${encodeURIComponent(eventId)}`:""}`,{headers:headers(),cache:"no-store"});if(response.status===401){setAuth(true);return;}const value=await response.json();if(!response.ok)throw Error(value.error);setData(value);setError("");}catch(e){setError(e instanceof Error?e.message:"Notifications unavailable");}},[eventId,headers]);
  const mutate=async(body:unknown)=>{setBusy(true);try{const response=await fetch("/api/notifications/events",{method:"PATCH",headers:headers(),body:JSON.stringify(body)});if(!response.ok)throw Error("Unable to save notification state");await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
  useEffect(()=>{void load();const update=()=>void load();window.addEventListener("focus",update);const timer=setInterval(update,30000);return()=>{clearInterval(timer);window.removeEventListener("focus",update);};},[load]);
  useEffect(()=>{if(!eventId||!data?.events[0]?.unread)return;void fetch("/api/notifications/events",{method:"PATCH",headers:headers(),body:JSON.stringify({eventId,action:"READ"})}).then(r=>{if(!r.ok)setError("Could not mark notification read; retry on this device.");});},[eventId,data,headers]);
  useEffect(()=>{if(!("Notification" in window)||!("serviceWorker" in navigator)||!("PushManager" in window)){setPush("Push Unsupported — in-app notifications remain available; enable email in Settings.");return;}if(Notification.permission!=="granted"){setPush(`Push ${Notification.permission==="denied"?"Denied":"Disconnected"} — enable permission in Settings; in-app remains available.`);return;}void fetch("/api/notifications/push-subscription",{headers:headers()}).then(r=>r.json()).then(async v=>{const registration=await navigator.serviceWorker.getRegistration(),subscription=await registration?.pushManager.getSubscription();setPush(v.configured&&v.devices?.length&&subscription?"Push Connected":"Push Disconnected — this device needs a registered subscription");}).catch(()=>setPush("Push status unavailable"));},[headers]);
  const event=data?.events[0];
  return <main style={{width:"100%",maxWidth:900,margin:"0 auto",padding:16,boxSizing:"border-box",overflowWrap:"anywhere"}}><a href="/workspace/notifications">Notification Center</a> · <a href="/workspace/daily-action-plan">Back to Today</a><h1>{eventId?"Notification Detail":"Notification Center"}</h1><p role="status">{push}</p>{auth&&<button onClick={()=>void startCognitoLogin()}>Sign in to view this event</button>}{error&&<p role="alert">{error} <button onClick={()=>void load()}>Retry</button></p>}{!data&&!auth&&!error&&<p>Loading notifications…</p>}
  {eventId&&event?<><h2>{event.snapshot_json.action}</h2><strong>{event.severity} · {event.snapshot_json.immediateAction?"Review now":"No immediate action"}</strong><h3>{event.title}</h3><p>{event.snapshot_json.reason}</p><p>{event.snapshot_json.account} · {event.snapshot_json.strategy} · {event.snapshot_json.ticker}</p><p>Event snapshot: {new Date(event.updated_at).toLocaleString()}. This is historical evidence; recheck the current account recommendation before acting.</p><EntryPlanDetails plan={event.snapshot_json.entryPlan}/><dl>{Object.entries(event.snapshot_json).filter(([k])=>k!=="entryPlan").map(([key,value])=><div key={key}><dt><b>{key}</b></dt><dd style={{margin:0}}>{value==null?"Not supplied":typeof value==="object"?JSON.stringify(value):String(value)}</dd></div>)}</dl><h3>Event timeline</h3>{data?.timeline.map((u,i)=><article key={i}><b>{new Date(u.created_at).toLocaleString()} · {u.snapshot_json.action}</b><p>{u.snapshot_json.reason}</p></article>)}<h3>Delivery state</h3>{data?.deliveries.map((d,i)=><p key={i}>{d.channel} · {d.status} {d.error_code}</p>)}<button disabled={busy} onClick={()=>void mutate({eventId,action:"DISMISSED"})}>Dismiss event</button></>:data&&<><label>Filter <select value={filter} onChange={e=>setFilter(e.target.value)}>{["All","Critical",...data.categories].map(c=><option key={c}>{c}</option>)}</select></label>{!data.events.length&&<p>No notification events yet. Server monitoring continues independently of this page.</p>}{data.events.filter(e=>!e.dismissed_at&&(filter==="All"||filter==="Critical"&&e.severity==="CRITICAL"||e.category===filter)).map(e=><article key={e.id} style={{border:"1px solid #ccd8d2",borderRadius:10,padding:12,marginTop:12}}><a href={`/workspace/notifications/${encodeURIComponent(e.id)}`}><b>{e.unread?"Unread · ":"Read · "}{e.severity} · {e.title}</b></a><p>{e.snapshot_json.account} · {e.snapshot_json.ticker} · {new Date(e.updated_at).toLocaleString()}</p><p>{e.summary}</p></article>)}<details><summary>Category and channel preferences</summary>{data.categories.map(c=>{const p=data.preferences.find(p=>p.category===c)||{category:c,in_app:true,push:true,email:false};return <fieldset key={c}><legend>{c}</legend>{(["in_app","push","email"] as const).map(key=><label key={key} style={{display:"inline-block",padding:8}}><input disabled={busy} type="checkbox" checked={p[key]} onChange={e=>void mutate({category:c,inApp:key==="in_app"?e.target.checked:p.in_app,push:key==="push"?e.target.checked:p.push,email:key==="email"?e.target.checked:p.email})}/>{key}</label>)}</fieldset>;})}<a href="/workspace/settings">Push permission, email fallback and quiet hours</a></details></>}
  </main>;
}
