"use client";
import {useState} from 'react';
import {modeledOptionPrice,optionBreakEven} from '@/lib/option-break-even';
type R=Record<string,any>;
const usd=(n:number)=>Number.isFinite(n)?n.toLocaleString('en-US',{style:'currency',currency:'USD'}):'Enter valid inputs';
export default function OptionBreakEvenCalculator({contract:c}:{contract:R}){
 const defaults=()=>({entry:String(c.ask||c.maximumEntryPremium||''),contracts:String(c.contracts||c.expectedContracts||1),days:String(Math.max(0,Math.floor(Number(c.dte||0)/2))),iv:c.iv>0?String(Number((c.iv*100).toFixed(2))):'',spot:String(c.underlyingPrice||c.trigger||c.strike||''),fees:'0',discount:String(Math.max(0,(Number(c.ask||0)-Number(c.bid||0))/2).toFixed(2)),rate:'0',dividend:'0'});
 const [values,setValues]=useState(defaults);const v=Object.fromEntries(Object.entries(values).map(([k,x])=>[k,x.trim()===''?NaN:Number(x)]));
 const model={type:c.type as 'CALL'|'PUT',strike:Number(c.strike),days:v.days,iv:v.iv/100,rate:v.rate/100,dividend:v.dividend/100};
 const valid=Object.values(v).every(Number.isFinite)&&v.days>=0&&v.days<=Math.max(0,Number(c.dte))&&v.iv>0&&v.iv<=500&&v.spot>0&&v.entry>0&&Number.isInteger(v.contracts)&&v.contracts>0&&v.fees>=0&&v.discount>=0&&Math.abs(v.rate)<=25&&v.dividend>=0&&v.dividend<=25;
 const answer=valid?optionBreakEven(model,v.entry,v.contracts,v.fees,v.discount):null,mark=valid?modeledOptionPrice(v.spot,model):NaN,proceeds=Math.max(0,mark-v.discount),pnl=(proceeds-v.entry)*100*v.contracts-v.fees;
 const expiry=valid?c.type==='CALL'?Number(c.strike)+v.entry+v.fees/(100*v.contracts):Number(c.strike)-v.entry-v.fees/(100*v.contracts):NaN;
 const fields:[keyof typeof values,string,string][]=[['entry','Entry premium / share','0.01'],['contracts','Contracts','1'],['days','Days remaining at planned exit','1'],['spot','Stock price at planned exit','0.01'],['iv','IV at exit (%)','0.1'],['fees','Total entry + exit fees ($)','0.01'],['discount','Exit discount from model / share ($)','0.01'],['rate','Annual interest assumption (%)','0.1'],['dividend','Annual dividend yield assumption (%)','0.1']];
 return <section className="option-break-even" aria-label="Option break-even calculator" style={{padding:20,marginTop:16,border:'1px solid #b6d4c7',borderRadius:12,background:'#fff'}}><header><div><h4>Can this option break even before expiration?</h4><p>Model selling {c.symbol} {c.type} before {c.expiration}. Change any assumption; saved research stays unchanged.</p></div><button type="button" onClick={()=>setValues(defaults())}>Reset to contract data</button></header><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}>{fields.map(([key,label,step])=><label key={key}>{label}<input aria-label={label} type="number" step={step} value={values[key]} onChange={e=>setValues({...values,[key]:e.target.value})} style={{display:'block',width:'100%'}}/></label>)}</div>{answer?<div aria-live="polite"><h4>{answer.stockPrice==null?answer.reason:`Estimated stock break-even: ${usd(answer.stockPrice)}`}</h4><p>With {v.days} days left, modeled sale proceeds must reach <b>{usd(answer.requiredPremium)} per share</b> to recover entry premium and fees. {answer.stockPrice!=null&&`Stock must be ${c.type==='CALL'?'at or above':'at or below'} this modeled level under these assumptions.`}</p><dl><div><dt>Estimated sale price at your stock scenario</dt><dd>{usd(proceeds)} / share</dd></div><div><dt>Estimated net profit / loss</dt><dd>{usd(pnl)}</dd></div><div><dt>Expiration break-even including fees</dt><dd>{expiry>0?usd(expiry):'No positive stock price reaches break-even'}</dd></div><div><dt>Maximum premium loss plus entered fees</dt><dd>{usd(v.entry*100*v.contracts+v.fees)}</dd></div></dl><table><thead><tr><th>Stock at exit</th><th>Modeled sale / share</th><th>Net profit / loss</th></tr></thead><tbody>{[-.05,0,.05].map(change=>{const stock=v.spot*(1+change),sale=Math.max(0,modeledOptionPrice(stock,model)-v.discount);return <tr key={change}><td>{usd(stock)}</td><td>{usd(sale)}</td><td>{usd((sale-v.entry)*100*v.contracts-v.fees)}</td></tr>})}</tbody></table></div>:<p role="status">Enter valid contract inputs. Planned days remaining must be between 0 and {Math.max(0,Number(c.dte||0))}.</p>}<p><small>American-option binomial estimate, standard 100-share contracts. IV defaults to the saved chain; entry defaults to ask; exit discount defaults to half the saved spread. Fees, interest and dividend yield start at explicit zero assumptions—edit them for your trade. Continuous dividend yield does not model discrete dividend dates. Model prices are not executable quotes or a probability of profit. <a href="https://www.optionseducation.org/advancedconcepts/black-scholes-formula" target="_blank" rel="noreferrer">How option-pricing models work</a></small></p></section>;
}
