"use client";
import {useEffect,useMemo,useState} from "react";
type AssetType="stock"|"call"|"put";
type PracticeMode="swing"|"long-term"|"options";
type Contract={contractSymbol:string;type:"call"|"put";expiration:string;strike:number;dte:number;bid:number;ask:number;premium:number;maxLoss:number;breakeven:number;delta:number;iv:number|null;spreadPct:number};
type FakeTransaction={id:string;side:"BUY"|"SELL";symbol:string;instrument:string;assetType:AssetType;quantity:number;unitPrice:number;multiplier:number;total:number;createdAt:string;note:string;contract?:Contract};
type DailyMark={instrument:string;symbol:string;market_date:string;price:number;source:string;marked_at:string};
const storageKey="northstar-paper-trading-v2";
const futureValue=(principal:number,monthly:number,years:number,annual:number)=>{const rate=annual/12,months=years*12;return principal*Math.pow(1+rate,months)+(rate?monthly*(Math.pow(1+rate,months)-1)/rate:monthly*months)};

export default function PaperTradingSimulator({initialSymbol,initialCash,accessToken=""}:{initialSymbol:string;initialCash:number;accessToken?:string}){
 const [symbol,setSymbol]=useState(initialSymbol),[quantity,setQuantity]=useState(1),[price,setPrice]=useState<number|null>(null),[quoteTime,setQuoteTime]=useState(""),[side,setSide]=useState<"BUY"|"SELL">("BUY"),[assetType,setAssetType]=useState<AssetType>("stock"),[practiceMode,setPracticeMode]=useState<PracticeMode>("swing"),[note,setNote]=useState(""),[contract,setContract]=useState<Contract|null>(null),[targetDte,setTargetDte]=useState(45),[maxPremium,setMaxPremium]=useState(1000);
 const [currentAge,setCurrentAge]=useState(35),[goalAge,setGoalAge]=useState(65),[monthlyContribution,setMonthlyContribution]=useState(500),[learner,setLearner]=useState("Adult learner");
 const [transactions,setTransactions]=useState<FakeTransaction[]>([]),[dailyMarks,setDailyMarks]=useState<DailyMark[]>([]),[ready,setReady]=useState(false),[databaseConnected,setDatabaseConnected]=useState(false),[notice,setNotice]=useState("Load a live quote or option contract before recording a simulated trade.");
 const apiHeaders=()=>({"Content-Type":"application/json",...(accessToken?{Authorization:`Bearer ${accessToken}`}:{}) ,...(localStorage.getItem("northstar-household-id")?{"X-Household-ID":localStorage.getItem("northstar-household-id")!}:{})});
 const loadLedger=async()=>{try{const response=await fetch("/api/paper-trades",{headers:apiHeaders(),cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Database ledger unavailable");const loaded:FakeTransaction[]=data.trades.map((tx:any)=>({id:tx.id,side:tx.side,symbol:tx.symbol,instrument:tx.instrument,assetType:tx.asset_type,quantity:Number(tx.quantity),unitPrice:Number(tx.unit_price),multiplier:Number(tx.multiplier),total:Number(tx.total),createdAt:tx.executed_at,note:tx.note,contract:tx.contract_json?JSON.parse(tx.contract_json):undefined}));setTransactions(loaded);setDailyMarks(data.marks||[]);setDatabaseConnected(true);localStorage.removeItem(storageKey);setNotice(data.market?.status==="live"?`✓ Database ledger synchronized. Daily comparison marked from ${data.market.source}.`:`✓ Database ledger synchronized. Live daily marks will appear when market data is available.`)}catch(error){try{const saved=localStorage.getItem(storageKey);if(saved)setTransactions(JSON.parse(saved))}catch{}setDatabaseConnected(false);setNotice(`${error instanceof Error?error.message:"Database unavailable"}. Browser fallback is active.`)}finally{setReady(true)}};
 useEffect(()=>{loadLedger()},[accessToken]);
 useEffect(()=>{if(ready&&!databaseConnected)localStorage.setItem(storageKey,JSON.stringify(transactions))},[transactions,ready,databaseConnected]);
 const positions=useMemo(()=>{const map:Record<string,{quantity:number;cost:number;assetType:AssetType;symbol:string}>={};for(const tx of transactions.slice().reverse()){const p=map[tx.instrument]||={quantity:0,cost:0,assetType:tx.assetType,symbol:tx.symbol};if(tx.side==="BUY"){p.cost+=tx.total;p.quantity+=tx.quantity}else{const average=p.quantity?p.cost/p.quantity:0;p.cost=Math.max(0,p.cost-average*tx.quantity);p.quantity-=tx.quantity}}return Object.entries(map).filter(([,p])=>p.quantity>0)},[transactions]);
 const spent=transactions.reduce((sum,tx)=>sum+(tx.side==="BUY"?tx.total:-tx.total),0),cash=initialCash-spent,equity=cash+positions.reduce((sum,[instrument,p])=>sum+(instrument===(contract?.contractSymbol||symbol)&&price?price*(p.assetType==="stock"?1:100):p.cost/Math.max(1,p.quantity))*p.quantity,0),years=Math.max(1,goalAge-currentAge);
 const projections=[{label:"Cautious",rate:.04,value:futureValue(equity,monthlyContribution,years,.04)},{label:"Planning",rate:.07,value:futureValue(equity,monthlyContribution,years,.07)},{label:"Strong market",rate:.10,value:futureValue(equity,monthlyContribution,years,.10)}];
 const changeMode=(mode:PracticeMode)=>{setPracticeMode(mode);if(mode==="options"&&assetType==="stock")setAssetType("call");if(mode!=="options"&&assetType!=="stock")setAssetType("stock");setPrice(null);setContract(null);setNotice(mode==="long-term"?"Load a live stock value, record a hypothetical contribution, and study long-horizon scenarios.":mode==="options"?"Select a call or put and find a live contract for practice.":"Load a live quote and document entry, invalidation, target, and size.")};
 const changeType=(value:AssetType)=>{setAssetType(value);setPrice(null);setContract(null);setNotice(value==="stock"?"Load a live stock quote.":`Find a live long ${value} contract for simulation.`)};
 const loadMarket=async()=>{setNotice(assetType==="stock"?"Loading live stock quote…":"Ranking live option contracts…");try{if(assetType==="stock"){const response=await fetch(`/api/market/quotes?symbols=${symbol}`),data=await response.json();if(!response.ok)throw new Error(data.error||"Quote unavailable");const value=data.quotes?.[symbol]?.last||data.quotes?.[symbol]?.ask||data.quotes?.[symbol]?.bid;if(!value)throw new Error("No current quote returned");setPrice(value);setContract(null);setQuoteTime(data.asOf);setNotice(`Live ${data.feed.toUpperCase()} stock reference loaded.`)}else{const response=await fetch("/api/market/options",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol,outlook:assetType==="call"?"bullish":"bearish",maxRisk:maxPremium,targetDte})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Option chain unavailable");setContract(data.contract);setPrice(data.contract.ask);setQuoteTime(data.asOf);setNotice(`Live ${data.feed.toUpperCase()} ${assetType} candidate loaded. Options can lose 100% of premium.`)}}catch(error){setPrice(null);setContract(null);setNotice(error instanceof Error?error.message:"Market data unavailable")}};
 const record=async()=>{if(!price||quantity<=0)return setNotice("Load market data and enter a positive quantity.");const instrument=contract?.contractSymbol||symbol,multiplier=assetType==="stock"?1:100,total=price*multiplier*quantity,current=positions.find(([key])=>key===instrument)?.[1].quantity||0;if(side==="BUY"&&total>cash)return setNotice("Not enough simulated cash.");if(side==="SELL"&&quantity>current)return setNotice(`Only ${current} simulated units of this instrument are available.`);const tx:FakeTransaction={id:crypto.randomUUID(),side,symbol,instrument,assetType,quantity,unitPrice:price,multiplier,total,createdAt:new Date().toISOString(),note:note.trim()||"No thesis recorded",contract:contract||undefined};setNotice("Saving simulated transaction…");try{const response=await fetch("/api/paper-trades",{method:"POST",headers:apiHeaders(),body:JSON.stringify({...tx,practiceMode})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Could not save simulation");setTransactions(items=>[{...tx,id:data.id,createdAt:data.executedAt},...items]);setDatabaseConnected(true);setNote("");setNotice(`✓ Simulated ${side.toLowerCase()} saved to the household practice database. No brokerage order was sent.`)}catch(error){setNotice(error instanceof Error?error.message:"Could not save simulation")}};
 const resetAccount=async()=>{if(!window.confirm("Reset all simulated positions, fake transactions, and daily comparisons?"))return;try{const response=await fetch("/api/paper-trades",{method:"DELETE",headers:apiHeaders()}),data=await response.json();if(!response.ok)throw new Error(data.error||"Reset failed");setTransactions([]);setDailyMarks([]);localStorage.removeItem(storageKey);setNotice("Paper account and daily comparison history reset.")}catch(error){setNotice(error instanceof Error?error.message:"Reset failed")}};
 const latestMarks=useMemo(()=>Object.values(dailyMarks.reduce<Record<string,DailyMark>>((map,mark)=>{if(!map[mark.instrument])map[mark.instrument]=mark;return map},{})),[dailyMarks]);
 return <section className="paper-simulator card">
  <header><div><span>◎ EDUCATIONAL PAPER TRADING</span><h2>Professional practice lab with real market references</h2><p>Practice swing trades, long-term investing, calls, and puts with fake money and a permanent decision journal.</p></div><strong>SIMULATION ONLY<small>No real money · no orders</small></strong></header>
  <nav className="practice-mode"><button className={practiceMode==="swing"?"active":""} onClick={()=>changeMode("swing")}><b>SWING PRACTICE</b><span>Entry · stop · target · risk</span></button><button className={practiceMode==="long-term"?"active":""} onClick={()=>changeMode("long-term")}><b>LONG-TERM PRACTICE</b><span>Contributions · age · scenarios</span></button><button className={practiceMode==="options"?"active":""} onClick={()=>changeMode("options")}><b>OPTIONS PRACTICE</b><span>Calls · puts · premium · expiry</span></button></nav>
  {practiceMode==="options"&&<nav className="instrument-tabs"><button className={assetType==="call"?"active":""} onClick={()=>changeType("call")}>LONG CALL</button><button className={assetType==="put"?"active":""} onClick={()=>changeType("put")}>LONG PUT</button></nav>}
  <div className="paper-summary"><div><small>Starting cash</small><b>${initialCash.toLocaleString()}</b></div><div><small>Available fake cash</small><b>${cash.toLocaleString(undefined,{maximumFractionDigits:2})}</b></div><div><small>Estimated paper equity</small><b>${equity.toLocaleString(undefined,{maximumFractionDigits:2})}</b></div><div><small>{databaseConnected?"Database transactions":"Browser fallback"}</small><b>{transactions.length}</b></div></div>
  {practiceMode==="long-term"&&<section className="growth-projection"><div className="projection-settings"><label>Learner<select value={learner} onChange={e=>setLearner(e.target.value)}><option>Adult learner</option><option>Teen learner</option><option>Child with guardian</option></select></label><label>Current age<input type="number" min="8" max="90" value={currentAge} onChange={e=>setCurrentAge(Math.max(8,+e.target.value))}/></label><label>Goal age<input type="number" min={currentAge+1} max="100" value={goalAge} onChange={e=>setGoalAge(Math.max(currentAge+1,+e.target.value))}/></label><label>Monthly fake contribution $<input type="number" min="0" step="25" value={monthlyContribution} onChange={e=>setMonthlyContribution(Math.max(0,+e.target.value))}/></label></div><div className="projection-cards">{projections.map(item=><article key={item.label}><span>{item.label} scenario</span><b>${item.value.toLocaleString(undefined,{maximumFractionDigits:0})}</b><small>{(item.rate*100).toFixed(0)}% assumed annual return · {years} years</small></article>)}</div><p><b>Educational forecast:</b> Calculations assume monthly compounding and regular contributions. Returns, inflation, taxes, fees and losses will change results. The 10% case is not a promise or planning guarantee. A guardian must control all real accounts for minors.</p></section>}
  <div className="paper-ticket"><label>Underlying<input value={symbol} onChange={e=>{setSymbol(e.target.value.toUpperCase().replace(/[^A-Z.]/g,"").slice(0,10));setPrice(null);setContract(null)}}/></label>{assetType!=="stock"&&<><label>Target DTE<select value={targetDte} onChange={e=>setTargetDte(+e.target.value)}><option value="21">21 days</option><option value="45">45 days</option><option value="60">60 days</option><option value="90">90 days</option></select></label><label>Max premium $<input type="number" min="50" step="50" value={maxPremium} onChange={e=>setMaxPremium(+e.target.value)}/></label></>}<button className="quote-button" onClick={loadMarket}>{assetType==="stock"?"Get live quote":"Find contract"}</button><div className="paper-price"><small>{assetType==="stock"?"Share price":"Option ask"}</small><b>{price?`$${price.toFixed(2)}`:"—"}</b><span>{quoteTime?new Date(quoteTime).toLocaleString():"Not loaded"}</span></div><label>Action<select value={side} onChange={e=>setSide(e.target.value as "BUY"|"SELL")}><option>BUY</option><option>SELL</option></select></label><label>{assetType==="stock"?"Shares":"Contracts"}<input type="number" min="1" step="1" value={quantity} onChange={e=>setQuantity(Math.max(1,Math.floor(+e.target.value)))}/></label><label className="paper-note">Reason / rule<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Thesis, confirmation, invalidation…"/></label><button className={`record-paper ${side.toLowerCase()}`} onClick={record}>Record fake {side.toLowerCase()}</button></div>
  {contract&&<div className="option-paper-card"><b>{contract.contractSymbol}</b><span>{contract.expiration} · ${contract.strike.toFixed(2)} {contract.type.toUpperCase()} · {contract.dte} DTE</span><span>Ask ${contract.ask.toFixed(2)} · ${contract.premium.toFixed(0)} per contract</span><span>Max loss ${contract.maxLoss.toFixed(0)}</span><span>Expiration breakeven ${contract.breakeven.toFixed(2)}</span><span>Delta {contract.delta.toFixed(2)} · Spread {contract.spreadPct.toFixed(1)}% · IV {contract.iv===null?"N/A":`${(contract.iv*100).toFixed(1)}%`}</span></div>}
  <div className="paper-notice">{notice}</div><section className="daily-comparison"><header><div><span>DAILY MARKET COMPARISON</span><h3>Practice performance marked against the market</h3></div><button onClick={loadLedger}>Refresh market marks</button></header>{latestMarks.length?<div>{latestMarks.map(mark=>{const position=positions.find(([instrument])=>instrument===mark.instrument)?.[1],basis=position&&position.quantity?position.cost/position.quantity:0,change=basis?((Number(mark.price)-basis)/basis)*100:null;return <article key={mark.instrument}><b>{mark.symbol}</b><span>{mark.market_date}</span><span>Market ${Number(mark.price).toFixed(2)}</span><strong className={change!==null&&change<0?"loss":"gain"}>{change===null?"No open position":`${change>=0?"+":""}${change.toFixed(2)}% vs cost`}</strong><small>{mark.source} · {new Date(mark.marked_at).toLocaleString()}</small></article>})}</div>:<p>No daily marks yet. Record a stock simulation, then refresh while Alpaca market data is available.</p>}</section><div className="paper-ledger"><section><h3>Open simulated positions</h3>{positions.length?positions.map(([instrument,p])=><article key={instrument}><b>{p.assetType.toUpperCase()}</b><span>{p.quantity} {p.assetType==="stock"?"shares":"contracts"}</span><span>{instrument}</span><em>Cost ${p.cost.toFixed(2)}</em></article>):<p>No open fake positions yet.</p>}</section><section><h3>Fake transaction history</h3>{transactions.slice(0,12).map(tx=><article key={tx.id}><b className={tx.side.toLowerCase()}>{tx.side}</b><span>{tx.quantity} {tx.assetType==="stock"?tx.symbol:tx.instrument}</span><span>{new Date(tx.createdAt).toLocaleString()}</span><em>${tx.total.toFixed(2)}</em><small>{tx.assetType.toUpperCase()} · {tx.note}</small></article>)}{!transactions.length&&<p>Your practice activity will be saved to the household database.</p>}</section></div>
  <footer><span>Live references may be delayed. Options involve decay, volatility and possible 100% premium loss. Every transaction is simulated, database-audited, and separate from Plaid.</span><button onClick={resetAccount}>Reset paper account</button></footer>
 </section>
}
