"use client";
import {useEffect,useState} from "react";
import {useConfirm} from "./confirmation-modal";
type Row=Record<string,any>;
const roles=["PRIMARY_INCOME","MORTGAGE_PAYMENT","OPERATING_EXPENSE","RESERVE","CREDIT_CARD","SECURITY_DEPOSIT","TAX_INSURANCE","LOAN","OTHER"];
const title=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
export default function PropertyAccountManager({properties}:{properties:Row[]}){
 const confirmAction=useConfirm(),[accounts,setAccounts]=useState<Row[]>([]),[links,setLinks]=useState<Row[]>([]),[propertyId,setPropertyId]=useState(""),[accountId,setAccountId]=useState(""),[role,setRole]=useState("OPERATING_EXPENSE"),[notice,setNotice]=useState("Loading central payment accounts…"),[busy,setBusy]=useState(false);
 const load=async()=>{try{const[a,l]=await Promise.all([fetch("/api/connections/plaid",{cache:"no-store"}),fetch("/api/properties/account-links",{cache:"no-store"})]),ad=await a.json(),ld=await l.json();if(!a.ok)throw new Error(ad.error||"Accounts unavailable");if(!l.ok)throw new Error(ld.error||"Property account links unavailable");const eligible=(ad.accounts||[]).filter((x:Row)=>!/investment|brokerage|401|ira|retirement/i.test(`${x.type} ${x.subtype} ${x.name}`));setAccounts(eligible);setLinks(Array.isArray(ld)?ld:[]);setPropertyId(v=>v||String(properties[0]?.id||""));setAccountId(v=>v||String(eligible[0]?.id||""));setNotice(`${eligible.length} central accounts · ${Array.isArray(ld)?ld.length:0} active property links`)}catch(e){setNotice(e instanceof Error?e.message:"Payment accounts unavailable")}};
 useEffect(()=>{void load()},[properties.length]);
 const save=async()=>{if(!propertyId||!accountId)return setNotice("Select both a property and a central account.");setBusy(true);try{const r=await fetch("/api/properties/account-links",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertyId,accountId,role})}),data=await r.json();if(!r.ok)throw new Error(data.error||"Account could not be linked");await load();setNotice("✓ Central account linked without duplicating transactions.")}catch(e){setNotice(e instanceof Error?e.message:"Account could not be linked")}finally{setBusy(false)}};
 const remove=async(linkId:string)=>{const link=links.find(x=>String(x.id)===linkId);if(!await confirmAction({title:"Remove property account context?",description:"The central account and original transactions remain intact. Only this property classification link will be removed.",confirmLabel:"Remove context",variant:"warning",context:<strong>{link?.property_name||link?.address||"Property"} · {link?.account_name||"Account"}</strong>}))return;setBusy(true);try{const r=await fetch("/api/properties/account-links",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({linkId})}),data=await r.json();if(!r.ok)throw new Error(data.error||"Link could not be removed");await load();setNotice("✓ Property context removed; the central account and its transactions remain intact.")}catch(e){setNotice(e instanceof Error?e.message:"Link could not be removed")}finally{setBusy(false)}};
 return <section className="card property-account-manager"><header><div><span>CENTRAL MONEY CONNECTIONS</span><h3>Property payment accounts</h3><p>Accounts and original transactions stay in Household Finance. Real Estate adds property roles and classifications only.</p></div><a href="/workspace/accounts">Manage Payment Accounts →</a></header><div className="property-link-form"><label>Property<select value={propertyId} onChange={e=>setPropertyId(e.target.value)}><option value="">Select property</option>{properties.map(x=><option key={x.id} value={x.id}>{x.entity_name||x.address||"Property"}</option>)}</select></label><label>Central account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Select account</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.institution_name||"Manual"} · {x.name} {x.mask?`••${x.mask}`:""}</option>)}</select></label><label>Property role<select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(x=><option key={x} value={x}>{title(x)}</option>)}</select></label><button disabled={busy||!properties.length||!accounts.length} onClick={save}>{busy?"Saving…":"Link account"}</button></div><p className="property-link-notice">{notice}</p><div className="property-link-list">{links.map(x=><article key={x.id}><span><b>{x.property_name||x.address||"Property"}</b><small>{title(x.role)}</small></span><span><b>{x.institution_name||"Manual"} · {x.account_name}</b><small>{x.account_subtype||x.account_type} {x.mask?`· •••• ${x.mask}`:""}</small></span><button disabled={busy} onClick={()=>remove(String(x.id))}>Remove context</button></article>)}{!links.length&&<p>No central account has been assigned to a property yet.</p>}</div></section>;
}
