"use client";

import {useEffect,useRef,useState} from "react";
import {ConfirmationModal,useConfirm} from "./confirmation-modal";

type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};
type PwaState={standalone:boolean;ios:boolean;online:boolean;installable:boolean;version:string;notificationPermission:NotificationPermission|"unsupported"};
const initial:PwaState={standalone:false,ios:false,online:true,installable:false,version:"loading",notificationPermission:"unsupported"};
const detectStandalone=()=>window.matchMedia("(display-mode: standalone)").matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone);

export default function PwaManager(){
 const[state,setState]=useState<PwaState>(initial),installPrompt=useRef<InstallPromptEvent|null>(null),[modal,setModal]=useState<"install"|"update"|null>(null),[dismissed,setDismissed]=useState(true);
 useEffect(()=>{
  const ios=/iPad|iPhone|iPod/.test(navigator.userAgent),standalone=detectStandalone();
  setState(current=>({...current,ios,standalone,online:navigator.onLine,notificationPermission:"Notification" in window?Notification.permission:"unsupported"}));
  setDismissed(localStorage.getItem("northstar-install-dismissed")==="true");
  fetch("/api/app-version",{cache:"no-store"}).then(r=>r.json()).then(data=>setState(current=>({...current,version:String(data.version||"unknown")}))).catch(()=>setState(current=>({...current,version:"unknown"})));
  const online=()=>setState(current=>({...current,online:true})),offline=()=>setState(current=>({...current,online:false}));
  const before=(event:Event)=>{event.preventDefault();installPrompt.current=event as InstallPromptEvent;setState(current=>({...current,installable:true}))};
  const installed=()=>{installPrompt.current=null;setModal(null);setState(current=>({...current,standalone:true,installable:false}))};
  const requestInstall=()=>{if(detectStandalone())return;const prompt=installPrompt.current;if(prompt){prompt.prompt();prompt.userChoice.then(choice=>{if(choice.outcome==="accepted")installed()});return}setModal("install")};
  const deepLink=(event:MessageEvent)=>{if(event.data?.type==="NOTIFICATION_DEEP_LINK"&&typeof event.data.url==="string")location.assign(event.data.url)};
  window.addEventListener("online",online);window.addEventListener("offline",offline);window.addEventListener("beforeinstallprompt",before);window.addEventListener("appinstalled",installed);window.addEventListener("northstar:pwa-install",requestInstall);navigator.serviceWorker?.addEventListener("message",deepLink);
  if("serviceWorker" in navigator){let refreshing=false;navigator.serviceWorker.register("/sw.js").then(registration=>{const offer=(worker:ServiceWorker|null)=>{if(worker&&navigator.serviceWorker.controller)setModal("update")};offer(registration.waiting);registration.addEventListener("updatefound",()=>{const worker=registration.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="installed")offer(worker)})});const check=()=>{if(document.visibilityState==="visible")registration.update().catch(()=>undefined)};document.addEventListener("visibilitychange",check);window.addEventListener("focus",check);navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!refreshing){refreshing=true;location.reload()}});return()=>{document.removeEventListener("visibilitychange",check);window.removeEventListener("focus",check)}}).catch(()=>undefined)}
  return()=>{window.removeEventListener("online",online);window.removeEventListener("offline",offline);window.removeEventListener("beforeinstallprompt",before);window.removeEventListener("appinstalled",installed);window.removeEventListener("northstar:pwa-install",requestInstall);navigator.serviceWorker?.removeEventListener("message",deepLink)};
 },[]);
 const closeInstall=()=>{localStorage.setItem("northstar-install-dismissed","true");setDismissed(true);setModal(null)};
 const applyUpdate=()=>navigator.serviceWorker.getRegistration().then(registration=>registration?.waiting?.postMessage({type:"SKIP_WAITING"}));
 return <>
  {!state.online&&<div className="pwa-offline-banner" role="status"><b>Offline mode</b><span>Live financial and market data is paused. No private account data is cached.</span></div>}
  {!state.standalone&&!dismissed&&state.online&&<aside className="pwa-install-banner"><div><b>Install Northstar</b><span>Open it from your Home Screen in a standalone app window.</span></div><button onClick={()=>window.dispatchEvent(new Event("northstar:pwa-install"))}>Install</button><button aria-label="Dismiss install suggestion" onClick={closeInstall}>×</button></aside>}
  <ConfirmationModal open={modal==="install"} title="Install Northstar on this device" description={state.ios?"On iPhone or iPad, install the HTTPS production site from Safari—not Chrome, an in-app browser, or localhost.":"Install Northstar for a focused app window and Home Screen access."} icon="N" confirmLabel="Got it" cancelLabel="Not now" context={state.ios?<ol className="pwa-install-steps"><li>Open <b>master.d1vom0cqe4pf3y.amplifyapp.com</b> in Safari.</li><li>Tap <b>Share</b> in the Safari toolbar.</li><li>Choose <b>Add to Home Screen</b>, not Add Bookmark.</li><li>Turn on <b>Open as Web App</b> if Safari shows that option.</li><li>Tap <b>Add</b>, close Safari, then launch the Northstar icon.</li><li>If an older Northstar icon still opens Safari, remove it and add it again once.</li></ol>:<p className="pwa-install-help">Use your browser menu and choose <b>Install app</b> or <b>Add to Home Screen</b>.</p>} onCancel={closeInstall} onSubmit={closeInstall}/>
  <ConfirmationModal open={modal==="update"} title="A new Northstar version is ready" description="Update now to load the latest production build. Your secure authenticated session will be preserved." icon="↻" confirmLabel="Update now" cancelLabel="Later" onCancel={()=>setModal(null)} onSubmit={applyUpdate}/>
 </>;
}

export function PwaSettingsPanel({accessToken}:{accessToken?:string}){
 const confirmAction=useConfirm(),[state,setState]=useState<PwaState>(initial),[devices,setDevices]=useState<Array<{id:string;device_name:string|null;platform:string|null;updated_at:string}>>([]),[notice,setNotice]=useState("");
 const headers=()=>({"Content-Type":"application/json",...(accessToken?{Authorization:`Bearer ${accessToken}`}:{}) ,...(localStorage.getItem("northstar-household-id")?{"X-Household-ID":localStorage.getItem("northstar-household-id")!}:{})});
 const refresh=async()=>{const standalone=detectStandalone(),ios=/iPad|iPhone|iPod/.test(navigator.userAgent),permission:"unsupported"|NotificationPermission="Notification" in window?Notification.permission:"unsupported";setState(current=>({...current,standalone,ios,online:navigator.onLine,notificationPermission:permission}));try{const [versionResponse,deviceResponse]=await Promise.all([fetch("/api/app-version",{cache:"no-store"}),fetch("/api/notifications/push-subscription",{headers:headers(),cache:"no-store"})]),version=await versionResponse.json(),deviceData=await deviceResponse.json();setState(current=>({...current,version:version.version||"unknown"}));setDevices(deviceResponse.ok?deviceData.devices||[]:[])}catch{setNotice("Device status is temporarily unavailable.")}};
 useEffect(()=>{refresh()},[accessToken]);
 const removeDevice=async(id:string,name:string)=>{const approved=await confirmAction({title:"Remove push device?",description:"Northstar will stop sending transaction and suspicious-activity push notifications to this device.",confirmLabel:"Remove device",variant:"danger",context:<b>{name}</b>});if(!approved)return;setNotice("Removing device…");const response=await fetch(`/api/notifications/push-subscription?id=${encodeURIComponent(id)}`,{method:"DELETE",headers:headers()});setNotice(response.ok?"Device notifications removed.":"Device could not be removed.");await refresh()};
 return <section className="pwa-device-settings" id="installed-app-settings"><header><div><span>INSTALLED APP &amp; DEVICES</span><h2>Northstar on this device</h2><p>Install status, secure push capability, and production build information.</p></div><strong className={state.standalone?"installed":"browser"}>{state.standalone?"INSTALLED":"BROWSER"}</strong></header><div className="pwa-device-grid"><article><small>Launch mode</small><b>{state.standalone?"Standalone app":"Web browser"}</b><span>{state.standalone?"No Safari address bar or browser chrome":"Install once for Home Screen launch"}</span></article><article><small>Notifications</small><b>{state.notificationPermission}</b><span>Permission is requested only when you choose Enable.</span></article><article><small>App build</small><b>{state.version}</b><span>Checked on launch and resume</span></article><article><small>Network</small><b>{state.online?"Online":"Offline"}</b><span>Private finance data remains network-only</span></article></div>{!state.standalone&&<button className="pwa-install-action" onClick={()=>window.dispatchEvent(new Event("northstar:pwa-install"))}>Install Northstar</button>}<div className="pwa-device-list"><b>Registered push devices</b>{devices.length?devices.map(device=>{const name=device.device_name||"Northstar device";return <article key={device.id}><span><b>{name}</b><small>{device.platform||"Web Push"} · last registered {new Date(device.updated_at).toLocaleDateString()}</small></span><button onClick={()=>removeDevice(device.id,name)}>Remove</button></article>}):<p>No push device is registered for this user yet.</p>}</div>{notice&&<small role="status">{notice}</small>}<p className="pwa-platform-note">iPhone Web Push requires iOS/iPadOS 16.4 or later and an installed Home Screen app. Web apps cannot claim Apple’s native Critical Alerts entitlement or unrestricted background execution.</p></section>;
}
