"use client";
import {useEffect,useState} from 'react';
import {validateFlow,flowForStrategy,type FlowEvidence} from '@/lib/flow-evidence';
const requests=new Map<string,{expires:number;promise:Promise<FlowEvidence>}>();
export function useQuantData(symbol:string){const [data,setData]=useState<FlowEvidence|null>(null),[revision,setRevision]=useState(0);useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')setRevision(v=>v+1)};const timer=setInterval(refresh,60000);window.addEventListener('northstar:realtime',refresh);return()=>{clearInterval(timer);window.removeEventListener('northstar:realtime',refresh)}},[]);useEffect(()=>{let active=true;setData(null);if(!symbol)return;let entry=requests.get(symbol);if(!entry||entry.expires<Date.now()){const promise=fetch(`/api/market/quant-data?symbol=${encodeURIComponent(symbol)}`).then(r=>{if(!r.ok)throw Error('Flow unavailable');return r.json().then(d=>{if(!Array.isArray(d.prints)||!Array.isArray(d.markers))throw Error('Invalid flow response');return d})});entry={expires:Date.now()+60000,promise};requests.set(symbol,entry)}entry.promise.then(d=>{if(active)setData(d)}).catch(()=>{if(active)setData({provider:'Quant Data',symbol,status:'UNAVAILABLE',retrievedAt:null,prints:[],markers:[],conviction:null,direction:'UNKNOWN',datasets:{},limitations:['Flow provider unavailable.'],canAuthorizeTrade:false})});return()=>{active=false}},[symbol,revision]);return data}
export default function QuantDataEvidence({symbol,compact=false,strategy='SWING_SHARES'}:{symbol:string;compact?:boolean;strategy?:string}){const raw=useQuantData(symbol),data=raw?flowForStrategy(raw,strategy):null;return <section className="quant-evidence" aria-label={`${symbol} market structure evidence`}><h3>Options flow · {symbol}</h3><p>{data?.status==='NOT_CONFIGURED'?'Flow data unavailable':data?.status||'Loading flow evidence…'} · Flow conviction: {data?.conviction==null?'Not scored':`${data.conviction}/100 · ${data.conviction>=60?'High':data.conviction>=35?'Medium':'Low'}`}</p><small>Conviction measures data strength, not probability of profit. CALL/PUT alone does not establish direction.</small>{data?.retrievedAt&&<p>Retrieved {new Date(data.retrievedAt).toLocaleString()} · {data.direction}</p>}{data?.status==='NOT_CONFIGURED'&&<p>The connected feeds do not currently supply verified sweep executions, dark-pool prints or dealer positioning here. Price, volume, technical and company research remain independent. No flow conviction is assigned without those inputs.</p>}{!compact&&data&&<><details><summary>Flow prints and context ({data.prints.length})</summary>{data.prints.map(p=><article key={p.id}><b>{p.kind} · {p.optionType} · {p.execution}</b><p>{p.time?new Date(p.time).toLocaleString():'Time unavailable'} · Premium {p.premium==null?'unavailable':`$${p.premium.toLocaleString()}`} · DTE {p.dte??'unknown'} · IV {p.iv??'unknown'} · {p.moneyness||'Moneyness unknown'}</p><p>Volume {p.volume??'unknown'} / OI {p.openInterest??'unknown'} · {p.direction} · conviction {p.conviction??'unavailable'}</p><small>{p.reasons.join(' ')}</small></article>)}</details><p>{data.limitations.join(" ")}</p><details><summary>Market structure and provider datasets</summary>{Object.entries(data.datasets).map(([name,d])=><details key={name}><summary>{name} · {d.status}</summary>{d.error&&<p>{d.error}</p>}<EvidenceValues value={d.data}/></details>)}</details></>}</section>}
export function FlowValidation({symbol,thesis}:{symbol:string;thesis:'BULLISH'|'BEARISH'|'UNKNOWN'}){const flow=useQuantData(symbol),[selected,setSelected]=useState(thesis),check=validateFlow(flow,selected);return <section className="quant-evidence"><h3>Validate This Trade · Flow · {check.status}</h3><label>Underlying thesis <select value={selected} onChange={e=>setSelected(e.target.value as typeof selected)}><option value="UNKNOWN">Not established</option><option value="BULLISH">Bullish</option><option value="BEARISH">Bearish</option></select></label><p>{check.alignment} · {check.reason}</p></section>}
export function QuantDataHealth(){const[data,setData]=useState<Record<string,any>|null>(null);useEffect(()=>{let active=true;fetch('/api/market/quant-data?health=true').then(r=>r.json()).then(d=>{if(active)setData(d)}).catch(()=>{if(active)setData({error:'Health unavailable'})});return()=>{active=false}},[]);return <section className="quant-evidence"><h3>Quant Data · System Health</h3><p>{data?(data.configured?'Configured':'Not configured'):'Loading…'}</p><p>Last success: {data?.lastSuccess||'No successful request recorded'}</p><p>Latency: {data?.latencyMs==null?'Unknown':`${data.latencyMs} ms`} · Rate limit remaining: {data?.remaining??'Unknown'}</p><p>Last error: {data?.lastError||data?.error||'None recorded'}</p></section>}

function EvidenceValues({value,depth=0}:{value:unknown;depth?:number}){if(value==null)return <p>No verified data</p>;if(typeof value!=='object')return <span>{String(value)}</span>;if(depth>5)return <small>Additional nested context available in the stored provider snapshot.</small>;return <dl className="security-metrics">{Object.entries(value).slice(0,30).map(([key,v])=><div key={key}><dt>{key.replace(/([a-z])([A-Z])/g,'$1 $2')}</dt><dd><EvidenceValues value={v} depth={depth+1}/></dd></div>)}{Object.keys(value).length>30&&<div>Showing 30 entries; full dataset retained in the research snapshot.</div>}</dl>}

export function LazyFlowEvidence({symbol}:{symbol:string}){const [open,setOpen]=useState(false);return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Market Structure / Flow</summary>{open&&<QuantDataEvidence symbol={symbol}/>}</details>}
