"use client";
import {useEffect,useRef,useState} from 'react';
type Row=Record<string,any>;
const money=(v:any)=>v==null||!Number.isFinite(Number(v))?'Unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v));
const time=(v:any)=>v?new Date(v).toLocaleString():'Not yet available';
export default function SwingOptionsAdvisor({accountId,accountName,accessToken,initialSymbol='SPY',sessionOnly=false,cashLimitCents=Infinity,onSessionAllocation}:{accountId:string;accountName:string;accessToken?:string|null;initialSymbol?:string;sessionOnly?:boolean;cashLimitCents?:number;onSessionAllocation?:(v:{symbol:string;amountCents:number}|null)=>void;accountStatus?:string;onConfigureAccount?:()=>void;onRefreshAccounts?:()=>void;universeSymbols?:string[]}){
 const [data,setData]=useState<Row>({results:[],jobs:[],stages:[]}),[symbol,setSymbol]=useState(initialSymbol),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[requests,setRequests]=useState<Row>({}),[tick,setTick]=useState(Date.now());const generation=useRef(0);
 const headers=()=>{const household=localStorage.getItem('northstar-household-id');return {'Content-Type':'application/json',...(accessToken?{Authorization:`Bearer ${accessToken}`} :{}),...(household?{'X-Household-ID':household}:{})};};
 const load=async()=>{const current=generation.current;try{const response=await fetch('/api/market/options/scan?accountId='+encodeURIComponent(accountId),{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(20000)});const body=await response.json();if(!response.ok)throw Error(body.error);if(current===generation.current)setData(body);}catch(e){if(current===generation.current)setNotice('Refresh timed out or failed — Retry. Last saved research remains visible.');}};
 useEffect(()=>{generation.current++;setData({results:[],jobs:[],stages:[]});setRequests({});setNotice('');setSymbol(initialSymbol);if(accountId)void load();const timer=setInterval(()=>{setTick(Date.now());if(accountId)void load()},5000);return()=>{generation.current++;clearInterval(timer)};},[accountId,accessToken]);
 const refresh=async(ticker='')=>{const current=generation.current;setBusy(ticker||'all');try{const response=await fetch('/api/market/options/scan',{method:'POST',headers:headers(),body:JSON.stringify({accountId,symbol:ticker}),signal:AbortSignal.timeout(30000)}),body=await response.json();if(!response.ok)throw Error(body.error);if(current!==generation.current)return;setNotice(body.message);setRequests(old=>({...old,...Object.fromEntries((body.jobs||[]).map((j:Row)=>[j.symbol,{...j,requestedAt:Date.now()}]))}));await load();}catch(e){if(current===generation.current)setNotice('Refresh timed out — Retry. Saved results have not been removed.');}finally{if(current===generation.current)setBusy('');}};
 const results:Row[]=data.results||[],contracts=results.flatMap(r=>(r.researchDecisions||[]).map((c:Row)=>({...c,holding:r.holdingComparison}))).sort((a,b)=>Number(b.qualified)-Number(a.qualified)||b.quality-a.quality);
 const top=(type:string)=>{const seen=new Set();return contracts.filter(c=>c.type===type&&!seen.has(c.symbol)&&Boolean(seen.add(c.symbol))).slice(0,5);};
 const calls=top('CALL'),puts=top('PUT'),session=contracts.find(c=>c.qualified&&c.freshness!=='STALE'&&c.contracts>0&&c.totalPremium*100<=cashLimitCents);
 useEffect(()=>{if(sessionOnly&&onSessionAllocation)onSessionAllocation(session?{symbol:session.symbol,amountCents:Math.ceil(session.totalPremium*100)}:null);},[sessionOnly,session?.contractSymbol,session?.totalPremium,onSessionAllocation]);
 const button=(ticker='',label='Refresh / Retry')=><button type="button" disabled={Boolean(busy)||!accountId} onClick={()=>void refresh(ticker)}>{busy===(ticker||'all')?'Refreshing…':label}</button>;
 const jobState=(ticker:string)=>{const job=(data.jobs||[]).find((j:Row)=>j.symbol===ticker),request=requests[ticker];if(request&&job?.id===request.jobId&&job.status==='SUCCEEDED')return 'COMPLETE';if(request&&tick-request.requestedAt>120000)return 'TIMED_OUT';return job?.status==='RUNNING'?'REFRESHING':job?.status==='DEAD'?'FAILED':job?.status||'PARTIAL';};
 const card=(c:Row)=><article key={c.contractSymbol} className="rounded-xl border border-line bg-surface p-4 min-w-0"><h3>{c.symbol} · {c.type} · {money(c.strike)} · {c.expiration}</h3><p><b>{c.decision}</b> · {c.expectation?.replaceAll('_',' ')} · quality {c.quality}/100</p><p>{c.freshness==='STALE'?'STALE — revalidation required':c.researchOnly?'Next-session / indicative research; reconfirm live quotes':'Conditional plan; confirm underlying trigger before entry'}</p><p>Quote {time(c.quoteAsOf)} · underlying {time(c.underlyingAsOf)} · analyzed {time(c.asOf)}</p><p>{c.dte} DTE · {c.contracts} proposed contracts{!c.contracts?' · '+c.expectedContracts+' contract(s) modeled only':''} · bid / ask / mid {money(c.bid)} / {money(c.ask)} / {money(c.mid)}</p><p>Maximum entry {money(c.ask)} per share · premium {money(c.premium)} per contract · total premium / max risk {money(c.totalPremium)} / {money(c.maxRisk)} · break-even {money(c.breakEven)}</p><p><b>Underlying trigger:</b> {money(c.trigger)} · <b>invalidation:</b> {money(c.invalidation)} · <b>target:</b> {money(c.target)}</p>{c.reasons?.length>0&&<p>{c.reasons.join(' · ')}</p>}{button(c.symbol,'Refresh contract research')} <a href={'/workspace/research/'+c.symbol.toLowerCase()+'?accountId='+encodeURIComponent(accountId)}>Chart &amp; refresh analysis →</a><details><summary>Greeks, evidence, alternatives and exit conditions</summary><p>Delta {c.delta??'Unavailable'} · Gamma {c.gamma??'Unavailable'} · Theta {c.theta??'Unavailable'} · Vega {c.vega??'Unavailable'}</p><p>IV {c.iv?Number(c.iv*100).toFixed(1)+'%':'Unavailable'} · IV rank {c.ivRank??'Unavailable'} · expected move ±{money(c.expectedMove)} · volume {c.volume} · OI {c.openInterest} · spread {Number(c.spreadPct).toFixed(1)}%</p>{c.why?.map((s:string)=><p key={s}>{s}</p>)}<p>{c.whyContract}</p><p>{c.whyAlternative}</p><p>Time stop: {c.timeStop}</p><p>Cancel: {c.cancelConditions?.join('; ')}</p>{c.holding?.shares>0&&<p>Owned stock: {c.holding.shares} shares · stock average cost {money(c.holding.stockAverageCost)}. Option premium is separate. {c.holding.decision}</p>}<p>Quality and expectation confidence are evidence scores, not calibrated win probabilities. Same-day contracts are not enabled.</p></details></article>;
 if(sessionOnly)return session?<article className="my-3 rounded-lg border border-line p-3"><b>OPTION PREPARE · {session.symbol} {session.type}</b><p>{session.contracts} contracts if confirmed · {money(session.strike)} · {session.expiration} · premium cap {money(session.totalPremium)}</p><p>Underlying trigger {money(session.trigger)}; invalidate {money(session.invalidation)}.</p><a href={'/workspace/options?accountId='+encodeURIComponent(accountId)}>Full Options Research →</a></article>:<p>Option research: {data.coverage?.deep_researched||0} stocks evaluated for this account. <a href={'/workspace/options?accountId='+encodeURIComponent(accountId)}>Review CALL / PUT decisions →</a></p>;
 return <section className="option-contract-advisor swing-options-advisor"><header className="option-advisor-head"><div><h2>Options research · {accountName}</h2><p>Ranked directional research across the supported market. Each contract is compared with shares and waiting.</p></div>{button('','Refresh Options Research')}</header><div className="option-fields"><label>Ticker<input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label>{button(symbol,'Research ticker')}</div>{notice&&<p role="status">{notice}</p>}<p>Account premium cap {money(data.policy?.premiumCap)} · {data.policy?.optionsEnabled?'Options permission enabled':'Options entries disabled; research remains available'} · checked {time(data.checkedAt)}</p>
 {(['CALL','PUT'] as const).map(type=><section key={type} className="my-4"><header><h2>Best {type} Candidates</h2>{button('','Refresh '+type+' research')}</header><div className="option-research-grid">{(type==='CALL'?calls:puts).map(card)}</div>{!(type==='CALL'?calls:puts).length&&<p>No evaluated {type} contracts yet. {data.coverage?.queued||0} account reviews are in progress; stage-level progress appears below. Candidates will appear automatically as research completes.</p>}</section>)}
 <section className="my-4"><h2>Emerging / Preparing</h2>{results.filter(r=>r.expectation?.direction&&!r.researchDecisions?.some((c:Row)=>c.qualified)).slice(0,10).map(r=><article key={r.underlying}><b>{r.underlying} · {r.expectation.expectation.replaceAll('_',' ')}</b><p>{r.decision?.interpretation}</p><small>{time(r.updatedAt)}</small>{button(r.underlying)}</article>)}</section>
 <section className="my-4"><h2>Shares Preferred</h2>{results.filter(r=>r.decisionLabel==='SHARES PREFERRED').slice(0,10).map(r=><article key={r.underlying}><b>{r.underlying} · Compare shares with option premium</b><p>{r.decision?.interpretation}</p>{button(r.underlying)}</article>)}{!results.some(r=>r.decisionLabel==='SHARES PREFERRED')&&<p>No completed shares-preferred comparison yet.</p>}</section>
 <section className="my-4 rounded-xl border border-line p-4"><h2>Research Coverage</h2><div className="flex flex-wrap gap-4">{Object.entries(data.coverage||{}).map(([k,v])=><span key={k}><b>{k==='last_scan'?time(v):String(v??'Unavailable')}</b> {k.replaceAll('_',' ')}</span>)}</div><p>Counts distinguish stock screening, deep account research, contract candidates and executable-now conditions. They do not imply the entire market has finished research.</p></section>
 <section className="my-4"><h2>Research In Progress</h2>{button('','Refresh section')}<p>Provider retries use exponential backoff. Queue position and provider latency vary; no reliable completion ETA is available until a worker claims the job.</p>{(data.jobs||[]).filter((j:Row)=>j.status!=='SUCCEEDED'||requests[j.symbol]).sort((a:Row,b:Row)=>Number(Boolean(requests[b.symbol]))-Number(Boolean(requests[a.symbol]))).slice(0,40).map((j:Row)=>{const stages=(data.stages||[]).filter((s:Row)=>s.symbol===j.symbol),pending=stages.filter((s:Row)=>s.status!=='COMPLETE');return <article key={j.id} className="my-2 rounded-lg border border-line p-3"><b>{j.symbol} · {jobState(j.symbol)}</b><p>{jobState(j.symbol)==='TIMED_OUT'?'Refresh timed out — Retry. Last saved results remain above.':pending[0]?'Current stage: '+pending[0].stage.replaceAll('_',' '):'Queued for underlying research'}</p><p>{stages.filter((s:Row)=>s.status==='COMPLETE').length}/{stages.length||12} stages · attempt {j.attempts} · updated {time(j.updated_at)} · next eligible {time(j.available_at)}</p>{button(j.symbol)}<details><summary>Stage progress and errors</summary>{stages.map((s:Row)=><p key={s.stage}>{s.stage.replaceAll('_',' ')} · {s.status} · started {time(s.started_at)} · completed {time(s.completed_at)} · retries {s.retry_count} · {s.last_error||'No error'} · next retry {time(s.next_retry_at)}</p>)}</details></article>})}</section>
 <details className="my-4"><summary>WAIT / rejected setups and diagnostic evidence</summary>{results.slice(0,50).map(r=><article key={r.underlying}><b>{r.underlying} · {r.decisionLabel||'WAIT'}</b><p>{r.decision?.interpretation}</p><p>{Object.entries(r.stageErrors||{}).map(([k,v])=>k+': '+v).join('; ')}</p><small>{time(r.updatedAt)}</small>{button(r.underlying)}{(r.lastValidResearch||[]).slice(0,2).map(card)}</article>)}</details></section>;
}
