"use client";
import {useEffect,useState} from "react";
import type {Action,PositionState,ReentryPlan} from "@/lib/trade-lifecycle";
import type {DecisionOutput} from "@/lib/ai-investment-decision-engine";
import AiAnalysisEvidence from "@/app/ai-analysis-evidence";
type Exit={id:string;ticker:string;sell_reason:string|null;status:string;exit_json:{shares:number;price:number;tradeAt:string;netProceeds:number};outcome_json:{postSaleMaximumUpside:number;subsequentDrawdown:number;missedUpside:number;avoidedLoss:number;excessVsHold:number;reentryImprovement:number|null}};
type Audit={id:string;ticker:string;sell_reason:string|null;pipeline_status:string;reason:string;lifecycle_audit_json:Partial<Action>};
type CashDeployment={ticker:string;status:string;plan:Partial<ReentryPlan>;allocation:{choice?:string;reason?:string;ticker:string;price:number;shares:number;cost:number;cashBefore:number;cashAfter:number;stop:number;reservedCash:number;expiresAt:string}};
type View={pipeline:string;actions:{state:PositionState;action:Action&{aiEvidence?:DecisionOutput};lastAnalysisAt:string}[];exits:Exit[];audits:Audit[];cashDeployment:CashDeployment[];outcomesByReason:{reason:string;decisions:number;excessVsHold:number;reentries:number;rotations:number}[];unreservedCash:number;cashReason:string};
const usd=(n:number)=>Number(n||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
export default function TradeLifecyclePanel({accountId,accessToken}:{accountId:string;accessToken?:string|null}){
  const [view,setView]=useState<View|null>(null),[error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();setView(null);setError("");const load=async()=>{try{const response=await fetch(`/api/trade-lifecycle?accountId=${encodeURIComponent(accountId)}`,{signal:controller.signal,cache:"no-store",headers:accessToken?{Authorization:`Bearer ${accessToken}`}:{}});const data=await response.json();if(!response.ok)throw new Error(data.error);setView(data);setError("");}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Lifecycle unavailable");}};void load();const timer=setInterval(()=>void load(),60000);return()=>{controller.abort();clearInterval(timer);};},[accountId,accessToken]);
  return <section className="card trade-lifecycle-panel" style={{padding:20,display:"grid",gap:16}}><header><h2>Account Action Plan · Trade Lifecycle</h2><p>Positions stay monitored after a sale. Orders below are recommendations; execution is reconciled from the investment ledger.</p><strong>{view?.pipeline||"Loading monitoring status"}</strong></header>{error&&<p role="alert">{error}</p>}{view&&<>
    {!view.actions.length&&<p>NO ACTION — waiting for the scheduled account analysis. Monitoring is not yet verified.</p>}
    {view.actions.map(({state:p,action:a,lastAnalysisAt})=><article key={p.ticker} style={{border:"1px solid #bccfc5",borderRadius:10,padding:16}}><h3>{p.ticker} — {a.action} {a.shares>0?`${a.shares} shares`:""}</h3><p>{p.strategy} · {p.positionState} · Thesis: {p.thesisStatus} · {a.pipeline}</p><p>{a.reason}</p><p>Price / limit {usd(a.price)} · Estimated {a.proceeds>0?`proceeds ${usd(a.proceeds)}`:`cost ${usd(a.cost)}`} · Shares remaining {a.remainingShares} · Estimated realized gain/loss {usd(a.realizedGain)}</p><p>Cash before {usd(a.cashBefore)} → after {usd(a.cashAfter)} · Stop / invalidation {a.stop?usd(a.stop):"Research required"} · Targets {a.targets.length?a.targets.map(usd).join(" / "):"Research required"}</p>
      {a.reentry?<p>Reserve {usd(a.reentry.reservedCash)} for {p.ticker}. Rebuy {a.reentry.estimatedShares} estimated shares in {usd(a.reentry.low)}–{usd(a.reentry.high)}, or a confirmed breakout above {usd(a.reentry.breakout)} up to {usd(a.reentry.breakoutLimit)}. {a.reentry.trigger} Cancel below {usd(a.reentry.invalidation)} or on thesis deterioration. Maximum wait: {new Date(a.reentry.expiresAt).toLocaleDateString()}. {a.reentry.reason}</p>:<p>No planned rebuy: {a.reason} Proceeds allocation: {a.allocation}.</p>}
      <details><summary>Decision audit</summary><p>Sale classification: {a.sellReason||"No sale"} · {a.sellReason==="THESIS BROKEN"||a.sellReason==="GOAL/REBALANCE"?"Permanent exit / research required":"Tactical / account-specific"}</p><p>Supporting evidence: {a.supporting.join("; ")||a.reason}</p><p>Evidence against selling: {a.opposing.join("; ")||"No counterevidence recorded"}</p><p>Last analysis: {new Date(lastAnalysisAt).toLocaleString()} · Strategy {a.strategyVersion} · Model {p.modelVersion}</p><AiAnalysisEvidence evidence={a.aiEvidence}/></details></article>)}
    <section><h3>Cash Deployment</h3><p>{usd(view.unreservedCash)} unreserved. {view.cashReason}</p>{view.cashDeployment.map((c,i)=><p key={`${c.ticker}:${i}`}><b>{c.ticker} · {c.status}</b> — {c.allocation.choice||"HOLD CASH"}: {c.allocation.reason} {Number(c.plan.reservedCash)>0?`Reserved ${usd(Number(c.plan.reservedCash))}; ${c.plan.trigger}`:""} {c.status==="ROTATION_READY"?`BUY IF ${c.allocation.ticker} confirms at or below ${usd(c.allocation.price)}: ${c.allocation.shares} shares, estimated cost ${usd(c.allocation.cost)}, cash ${usd(c.allocation.cashBefore)} → ${usd(c.allocation.cashAfter)}, stop ${usd(c.allocation.stop)}. Reserve ${usd(c.allocation.reservedCash)} until ${new Date(c.allocation.expiresAt).toLocaleDateString()}.`:""}</p>)}</section>
    <details><summary>Every SELL / TRIM audit ({view.audits.length})</summary>{view.audits.map(r=><article key={r.id}><h4>{r.ticker} · {r.sell_reason||"UNCLASSIFIED"} · {r.pipeline_status}</h4><p>{r.reason}</p><p>For: {r.lifecycle_audit_json?.supporting?.join("; ")||"Evidence audit missing"}</p><p>Against: {r.lifecycle_audit_json?.opposing?.join("; ")||"Counterevidence missing"}</p><p>Reentry: {r.lifecycle_audit_json?.reentry?"Plan recorded":"No plan — review allocation and thesis"}. Proceeds: {r.lifecycle_audit_json?.allocation||"INCOMPLETE — capital allocation required"}.</p></article>)}</details>
    <details><summary>Outcomes by sell reason</summary>{view.outcomesByReason.map(r=><p key={r.reason}><b>{r.reason}</b> · {r.decisions} exits · {r.reentries} reentries · {r.rotations} rotations · {usd(r.excessVsHold)} versus HOLD</p>)}<p>After five completed tactical decisions with negative cumulative excess and fewer than 40% wins, the versioned policy raises the required tactical advantage by 100 basis points. Further strategy changes require review.</p></details>
    <details><summary>Preserved exit history and results versus HOLD</summary>{view.exits.map(x=><article key={x.id}><h4>{x.ticker} · {x.sell_reason||"Classification required"} · {x.status}</h4><p>Sold {x.exit_json.shares} at {usd(x.exit_json.price)} on {new Date(x.exit_json.tradeAt).toLocaleDateString()}. Net proceeds {usd(x.exit_json.netProceeds)}.</p><p>Post-sale maximum upside {usd(x.outcome_json.postSaleMaximumUpside)} · Subsequent drawdown {usd(x.outcome_json.subsequentDrawdown)} · Missed upside {usd(x.outcome_json.missedUpside)} · Avoided loss {usd(x.outcome_json.avoidedLoss)} · Excess versus HOLD {usd(x.outcome_json.excessVsHold)} · Reentry improvement {x.outcome_json.reentryImprovement==null?"Pending":usd(x.outcome_json.reentryImprovement)}</p></article>)}</details>
  </>}</section>;
}
