"use client";
import {useEffect,useState} from 'react';
const time=(s:string)=>s?new Date(s).toLocaleString():'Not recorded';
export default function TransactionPipelineHealth({accessToken}:{accessToken?:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 const load=async()=>{try{const household=localStorage.getItem('northstar-household-id');const r=await fetch('/api/notifications/transaction-health',{headers:{...(accessToken?{Authorization:`Bearer ${accessToken}`} :{}),...(household?{'X-Household-ID':household}:{})},cache:'no-store'});if(!r.ok)throw Error('Could not load transaction notification diagnostics');setData(await r.json());setError('');}catch(e){setError(String(e));}};
 useEffect(()=>{void load()},[accessToken]);
 return <section className="rounded-xl border border-line p-4"><h2>Household finance · transaction notification health</h2><button onClick={()=>void load()}>Refresh delivery diagnostics</button>{error&&<p role="alert">{error}</p>}{data&&<><p>Checked {time(data.checkedAt)} · Push service {data.pushConfigured?'configured':'not configured'} · {data.devices.filter((d:any)=>d.active).length} active devices</p><p>Push “SENT / ACCEPTED” means the push service accepted it; it does not prove the device displayed it. Browser/OS permission and focus modes can suppress display.</p>{data.devices.map((d:any)=><p key={d.id}>{d.device_name||d.platform||'Registered device'}: {d.active?'Active subscription':'Inactive or expired subscription'} · {time(d.updated_at)}</p>)}{data.connections.map((c:any)=><p key={c.id}><b>{c.institution_name}</b> · Sync {time(c.last_synced_at)} · Webhook received {time(c.last_webhook)} · processed {time(c.last_webhook_processed)} · {c.sync_pending} pending syncs · {c.sync_error||c.webhook_error||c.error_code||c.status}</p>)}<p>A bank purchase can be notified only after the institution supplies it to Plaid and Northstar ingests it. Search recent imported transactions below; a purchase absent here has not reached this transaction ledger.</p>{data.transactions.map((t:any)=><details key={t.id} className="my-2 rounded-lg border border-line p-3"><summary>{t.merchant||t.description} · {t.category} · {t.pending?'Pending':'Posted'} · {time(t.posted_at)}</summary><p>Ingested/updated {time(t.updated_at)} · classification {t.event_type||'No notification event recorded'}</p><p>{t.rule_reason||(t.event_id?'Legacy event: rule decision was not recorded; delivery history below is authoritative.':'No event was created for this imported transaction. This may predate transaction notifications; it has not been marked delivered.')}</p><p>In-app history: {t.in_app_persisted?'Persisted':'Awaiting indexing / no event'}</p>{(t.deliveries||[]).map((d:any)=><p key={d.channel}>{d.channel}: {d.status} · {d.error||d.providerCode||'No provider response yet'} · {d.attempts} attempts · eligible {time(d.availableAt)} · next retry {time(d.nextRetryAt)}{d.status==='QUEUED'&&Date.parse(d.availableAt)>Date.now()?' · Deferred by quiet hours':''}{d.attempts>=5&&d.status==='FAILED'?' · Retry limit reached; restore channel configuration':''}</p>)}</details>)}</>}</section>;
}
