export const actionTypes=["BUY_NOW","PLACE_ON_WATCH","WAIT_FOR_PRICE","BUY_ON_CONFIRMATION","SELL","REDUCE","TAKE_PROFIT","HOLD","DO_NOTHING"]as const;
export const actionLifecycles=["PROPOSED","MONITORING","READY","TRIGGERED","INVALIDATED","EXPIRED","COMPLETED","MISSED"]as const;
export const actionPriorities=["CRITICAL","ACTION_NOW","READY_IF_PRICE_TRIGGERS","WATCH","NO_ACTION"]as const;
export type ActionType=(typeof actionTypes)[number];export type ActionLifecycle=(typeof actionLifecycles)[number];export type ActionPriority=(typeof actionPriorities)[number];
type Category={category:string;currentBps:number;targetBps:number;gapCents:string;status:string};
type Holding={id:string;symbol:string;name:string;category:string;weightBps:number;marketValueCents:string;action:"BUY_MORE"|"HOLD"|"REDUCE";amountCents:string;suggestedQuantity:string};
export type GuidanceInput={account:{id:string;name:string;strategyType:string;shareMode:"WHOLE"|"FRACTIONAL";goalName:string;horizonMonths:number;goalTargetCents:string|null;monthlyContributionCents:string;maximumPositionBps:number};portfolio:{totalValueCents:string;cashCents:string;categories:Category[];holdings:Holding[];projections:{bearCents:string;baseCents:string;bullCents:string};goalProgressBps:number|null};safety:{status:string;highInterestDebtCents:string;reserveGapCents:string;safeInvestmentCapacityCents:string}};
export type ActionGuidance={rank:number;priority:ActionPriority;action:ActionType;symbol:string|null;quantity:string;amountCents:string;priceCondition:string;when:string;why:string;capitalSource:string;lifecycle:ActionLifecycle};
const money=(cents:bigint)=>`$${(Number(cents)/100).toLocaleString(undefined,{maximumFractionDigits:0})}`;
export function buildActionGuidance(input:GuidanceInput){
 const cash=BigInt(input.portfolio.cashCents),safe=BigInt(input.safety.safeInvestmentCapacityCents),monthly=BigInt(input.account.monthlyContributionCents),blocked=input.safety.status!=="READY",actions:ActionGuidance[]=[];
 if(blocked){const debt=BigInt(input.safety.highInterestDebtCents),reserve=BigInt(input.safety.reserveGapCents);actions.push({rank:0,priority:"CRITICAL",action:"DO_NOTHING",symbol:null,quantity:"0",amountCents:"0",priceCondition:"Do not fund a purchase",when:"Now",why:debt>0n?`High-interest debt of ${money(debt)} takes priority.`:`Emergency reserve is short by ${money(reserve)}.`,capitalSource:debt>0n?"Direct available cash toward expensive debt.":"Keep available cash in the emergency reserve.",lifecycle:"READY"})}
 for(const holding of input.portfolio.holdings){const amount=BigInt(holding.amountCents),quantity=holding.suggestedQuantity,sameSleeve=input.portfolio.holdings.filter(item=>item.category===holding.category).length;if(holding.action==="REDUCE"&&amount>0n)actions.push({rank:0,priority:"ACTION_NOW",action:"REDUCE",symbol:holding.symbol,quantity,amountCents:amount.toString(),priceCondition:"Review at the current verified market price",when:"After tax, fee, overlap, and thesis review",why:`${holding.symbol} is ${holding.weightBps/100}% of this account or its ${holding.category} sleeve is overweight.${sameSleeve>1?` It overlaps with ${sameSleeve-1} other holding${sameSleeve===2?"":"s"} in the same portfolio sleeve.`:""}`,capitalSource:"Keep proceeds as account cash or redirect them to the largest underweight sleeve; do not remove emergency reserves.",lifecycle:"PROPOSED"});else if(holding.action==="BUY_MORE"&&amount>0n&&!blocked&&(safe>0n||monthly>0n))actions.push({rank:0,priority:"READY_IF_PRICE_TRIGGERS",action:"WAIT_FOR_PRICE",symbol:holding.symbol,quantity,amountCents:amount.toString(),priceCondition:"Use the security's validated Buy Zone; do not chase above it",when:"Only after valuation, technical, event, and thesis checks pass",why:`${holding.category} is underweight and ${holding.symbol} remains below the account position limit.`,capitalSource:cash>0n?`Use up to ${money(amount<cash?amount:cash)} of existing opportunity cash.`:monthly>0n?`Use up to ${money(amount<monthly?amount:monthly)} from the next monthly contribution.`:"No funded purchase until cash or a contribution is recorded.",lifecycle:"MONITORING"});else actions.push({rank:0,priority:"NO_ACTION",action:"HOLD",symbol:holding.symbol,quantity:"0",amountCents:"0",priceCondition:"No transaction condition",when:"Continue monitoring",why:`${holding.symbol} does not currently require an allocation change.`,capitalSource:"No cash required.",lifecycle:"MONITORING"})}
 const starter:Record<string,string|null>={CORE:"VTI",QUALITY:"QUAL",AGGRESSIVE:"QQQM",INCOME:"SCHD",BONDS:"BND",CASH:null},funding=cash>0n?safe:monthly;for(const gapRow of input.portfolio.categories.filter(category=>BigInt(category.gapCents)>0n).sort((a,b)=>Number(BigInt(b.gapCents)-BigInt(a.gapCents)))){if(blocked||funding<=0n)break;const gap=BigInt(gapRow.gapCents),budget=gap<funding?gap:funding;if(budget<=0n)continue;const candidate=starter[gapRow.category]??null;actions.push({rank:0,priority:"WATCH",action:"PLACE_ON_WATCH",symbol:candidate,quantity:"0",amountCents:budget.toString(),priceCondition:candidate?`Evaluate ${candidate} completely and use its validated Buy Zone; confirm the exact eligible fund in an employer plan`:"Keep this amount liquid; no security purchase is required",when:"This month",why:`${gapRow.category} is underweight by ${(gapRow.targetBps-gapRow.currentBps)/100}%. ${candidate?`${candidate} is a diversified starting candidate, not an automatic buy.`:"This is the target cash reserve."}`,capitalSource:cash>0n?`${money(budget)} from available account cash.`:`Up to ${money(budget)} from this month's contribution.`,lifecycle:"PROPOSED"})}
 if(!input.portfolio.holdings.length&&!blocked){if(monthly>0n){for(const sleeve of input.portfolio.categories.filter(category=>category.targetBps>0).sort((a,b)=>b.targetBps-a.targetBps)){const budget=monthly*BigInt(sleeve.targetBps)/10000n,candidate=starter[sleeve.category]??null;if(budget<=0n)continue;actions.push({rank:0,priority:sleeve.category==="CASH"?"NO_ACTION":"WATCH",action:sleeve.category==="CASH"?"DO_NOTHING":"PLACE_ON_WATCH",symbol:candidate,quantity:"0",amountCents:budget.toString(),priceCondition:candidate?`Complete the ${candidate} evaluation, confirm account eligibility, then calculate shares from a fresh ask price`:"Keep this allocation as account cash",when:"With the next contribution",why:`Empty-account starter allocation: ${(sleeve.targetBps/100).toFixed(1)}% to ${sleeve.category}. ${candidate?`${candidate} is the diversified research starting point for this sleeve, subject to full validation.`:"This cash is intentionally not invested."}`,capitalSource:`${money(budget)} of the configured ${money(monthly)} monthly contribution.`,lifecycle:"PROPOSED"})}}else actions.push({rank:0,priority:"ACTION_NOW",action:"DO_NOTHING",symbol:null,quantity:"0",amountCents:"0",priceCondition:"Enter available cash or a monthly contribution before calculating shares",when:"Before building the portfolio",why:"This account has no holdings and no recorded funding amount. Northstar will not invent purchasing power.",capitalSource:"Add the real contribution or account-cash amount; do not use emergency reserves.",lifecycle:"PROPOSED"})}
 const goal= input.account.goalTargetCents?BigInt(input.account.goalTargetCents):null,base=BigInt(input.portfolio.projections.baseCents),onTrack=!goal||base>=goal;if(goal&&!onTrack){const shortfall=goal-base,months=Math.max(1,input.account.horizonMonths),extraMonthly=(shortfall+BigInt(months)-1n)/BigInt(months);actions.push({rank:0,priority:"ACTION_NOW",action:"DO_NOTHING",symbol:null,quantity:"0",amountCents:"0",priceCondition:"Do not increase risk merely to force the target",when:"Update the account plan this month",why:`The reasonable base scenario is ${money(base)}, below the ${money(goal)} goal.`,capitalSource:`Consider adding about ${money(extraMonthly)}/month, extending the horizon, or reducing the goal.`,lifecycle:"PROPOSED"})}
 const order:Record<ActionPriority,number>={CRITICAL:0,ACTION_NOW:1,READY_IF_PRICE_TRIGGERS:2,WATCH:3,NO_ACTION:4};actions.sort((a,b)=>order[a.priority]-order[b.priority]||Number(BigInt(b.amountCents)-BigInt(a.amountCents))).forEach((action,index)=>action.rank=index+1);
 return{accountId:input.account.id,accountName:input.account.name,goalName:input.account.goalName,horizonMonths:input.account.horizonMonths,onTrack,availableCashPlan:{cashCents:cash.toString(),monthlyContributionCents:monthly.toString(),safeInvestmentCapacityCents:safe.toString(),untouchedCashCents:blocked?cash.toString():(cash>safe?cash-safe:0n).toString()},today:actions.filter(action=>action.priority!=="NO_ACTION").slice(0,7),thisMonth:actions.filter(action=>action.priority!=="NO_ACTION"&&["PLACE_ON_WATCH","WAIT_FOR_PRICE","DO_NOTHING"].includes(action.action)).slice(0,7),queue:actions};
}
