export type FinanceTransaction=Record<string,any>;
export type TransactionKind="INCOME"|"PURCHASE"|"TRANSFER"|"CARD_PAYMENT"|"REFUND"|"FEE"|"ATM"|"OTHER";
export type ReviewStatus="NORMAL"|"REVIEW"|"SUSPICIOUS"|"HIGH_RISK";

const words=(row:FinanceTransaction)=>`${row.merchant||""} ${row.description||""} ${row.category||""} ${row.subcategory||""}`.toLowerCase();
export function transactionKind(row:FinanceTransaction):TransactionKind{const text=words(row);if(row.direction==="inflow")return /refund|reversal|cashback|reimbursement/.test(text)?"REFUND":"INCOME";if(/payment thank you|credit card payment|card payment|autopay payment/.test(text))return"CARD_PAYMENT";if(/transfer|ach transfer|internal transfer|online transfer|wire transfer/.test(text))return"TRANSFER";if(/overdraft|service fee|maintenance fee|late fee|interest charge|atm fee/.test(text))return"FEE";if(/\batm\b|cash withdrawal/.test(text))return"ATM";if(row.direction==="outflow")return"PURCHASE";return"OTHER"}
export function excludedFromSpending(row:FinanceTransaction){const kind=transactionKind(row);return Boolean(row.excluded)||kind==="TRANSFER"||kind==="CARD_PAYMENT"||kind==="REFUND"||kind==="INCOME"}
export function analyzeTransaction(row:FinanceTransaction,history:FinanceTransaction[]){const amount=Math.abs(Number(row.amount_cents||0)),merchant=String(row.merchant||row.description||"Unknown merchant").trim(),kind=transactionKind(row),prior=history.filter(item=>item.id!==row.id&&String(item.merchant||item.description||"").trim().toLowerCase()===merchant.toLowerCase()),priorAmounts=prior.map(item=>Math.abs(Number(item.amount_cents||0))).filter(value=>value>0),average=priorAmounts.length?priorAmounts.reduce((a,b)=>a+b,0)/priorAmounts.length:0,reasons:string[]=[];let score=0;if(amount>=100000){score+=25;reasons.push("Large transaction of at least $1,000")};if(prior.length===0&&amount>=25000){score+=18;reasons.push("New merchant with a transaction of at least $250")};if(average>0&&amount>average*3&&amount-average>=10000){score+=30;reasons.push(`Amount is more than 3× this merchant’s prior average`)}const duplicate=history.some(item=>item.id!==row.id&&String(item.account_id)===String(row.account_id)&&String(item.merchant||item.description||"").trim().toLowerCase()===merchant.toLowerCase()&&Math.abs(Number(item.amount_cents||0))===amount&&Math.abs(Date.parse(String(item.posted_at||""))-Date.parse(String(row.posted_at||"")))<=86400000);if(duplicate){score+=35;reasons.push("Possible duplicate charge within 24 hours")};if(kind==="ATM"&&amount>=40000){score+=25;reasons.push("Unusually large ATM withdrawal")};if(kind==="FEE"){score+=10;reasons.push("Bank, card, overdraft, late, or interest fee")};const text=words(row);if(/foreign|international transaction|currency conversion/.test(text)){score+=20;reasons.push("Possible foreign or international transaction")};score=Math.min(100,score);const status:ReviewStatus=score>=70?"HIGH_RISK":score>=45?"SUSPICIOUS":score>=20?"REVIEW":"NORMAL";return{kind,excludedFromSpending:excludedFromSpending(row),riskScore:score,reviewStatus:status,riskReasons:reasons,confidence:priorAmounts.length>=3?"HIGH":priorAmounts.length?"MEDIUM":"LOW",dataBasis:{merchantHistoryCount:prior.length,merchantAverageCents:Math.round(average)}}}

export function enrichTransactions<T extends FinanceTransaction>(rows:T[]):Array<T&ReturnType<typeof analyzeTransaction>>{return rows.map(row=>({...row,...analyzeTransaction(row,rows)}))}
