export type KidGrowthInput={childAge:number;collegeStartAge:number;collegeNeedCents:number;annualCollegeCostCents:number;collegeYears:number;currentBalanceCents:number;monthlyContributionCents:number;longTermTargetCents:number};
export type KidReadiness="ON TRACK"|"SLIGHTLY BEHIND"|"UNDERFUNDED"|"OVERFUNDED"|"COLLEGE RESERVE READY";
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,Number.isFinite(value)?value:min));
const futureValue=(principal:number,monthly:number,years:number,annualRate:number)=>{const months=Math.max(0,Math.round(years*12)),rate=annualRate/12;return principal*Math.pow(1+rate,months)+(rate?monthly*((Math.pow(1+rate,months)-1)/rate):monthly*months)};
const paymentForGoal=(goal:number,principal:number,years:number,annualRate:number)=>{const months=Math.max(1,Math.round(years*12)),rate=annualRate/12,remaining=Math.max(0,goal-principal*Math.pow(1+rate,months));return rate?remaining*rate/(Math.pow(1+rate,months)-1):remaining/months};
export function buildKidGrowthPlan(raw:KidGrowthInput){
 const input={childAge:clamp(raw.childAge,0,30),collegeStartAge:clamp(raw.collegeStartAge,1,40),collegeNeedCents:Math.max(0,raw.collegeNeedCents),annualCollegeCostCents:Math.max(0,raw.annualCollegeCostCents),collegeYears:Math.round(clamp(raw.collegeYears,1,8)),currentBalanceCents:Math.max(0,raw.currentBalanceCents),monthlyContributionCents:Math.max(0,raw.monthlyContributionCents),longTermTargetCents:Math.max(0,raw.longTermTargetCents)};
 const yearsToCollege=Math.max(0,input.collegeStartAge-input.childAge),projectedAtCollege=Math.round(futureValue(input.currentBalanceCents,input.monthlyContributionCents,yearsToCollege,.06)),coverage=input.collegeNeedCents?projectedAtCollege/input.collegeNeedCents:1,requiredMonthlyCents=Math.round(paymentForGoal(input.collegeNeedCents,input.currentBalanceCents,yearsToCollege,.06));
 const reservePct=yearsToCollege>=10?5:yearsToCollege>=5?Math.round(15+(10-yearsToCollege)*5):Math.round(clamp(45+(5-yearsToCollege)*10,45,85));
 const core=Math.round(65-(reservePct-5)*.55),quality=Math.round(20-(reservePct-5)*.25),allocation={core,quality,aggressive:Math.max(0,100-reservePct-core-quality),collegeReserve:reservePct};
 const protectedCents=Math.min(input.collegeNeedCents,Math.round(input.currentBalanceCents*reservePct/100));
 const readiness:KidReadiness=protectedCents>=input.collegeNeedCents&&yearsToCollege<=3?"COLLEGE RESERVE READY":coverage>=1.2?"OVERFUNDED":coverage>=.95?"ON TRACK":coverage>=.75?"SLIGHTLY BEHIND":"UNDERFUNDED";
 const phase=yearsToCollege>=10?"GROWTH":yearsToCollege>=5?"SEPARATION":"TUITION PROTECTION",annual=input.annualCollegeCostCents||Math.round(input.collegeNeedCents/input.collegeYears);
 const ladder=Array.from({length:input.collegeYears},(_,index)=>{const yearsUntil=Math.max(0,yearsToCollege+index),protectRatio=clamp((4-yearsUntil)/3,0,1),protectedForYear=Math.min(annual,Math.round(protectedCents*protectRatio/Math.max(1,input.collegeYears-index)));return{year:index+1,age:input.collegeStartAge+index,neededCents:annual,protectedCents:protectedForYear,exposedCents:Math.max(0,annual-protectedForYear)}});
 const projectedExcess=Math.max(0,projectedAtCollege-input.collegeNeedCents),wealthAges=[18,21,25,30].filter(age=>age>=input.childAge).map(age=>({age,valueCents:Math.round(Math.max(0,age<=input.collegeStartAge?futureValue(input.currentBalanceCents,input.monthlyContributionCents,age-input.childAge,.07):futureValue(projectedExcess,0,age-input.collegeStartAge,.07)))}));
 const contributionAllocation=Object.entries(allocation).map(([bucket,pct])=>({bucket,pct,amountCents:Math.round(input.monthlyContributionCents*pct/100)})),healthScore=Math.round(clamp(35+Math.min(30,coverage*25)+(yearsToCollege>=5?10:5)+(allocation.core>=40?10:4)+(allocation.aggressive<=10?8:3),0,100));
 return{...input,yearsToCollege,phase,projectedAtCollege,coveragePct:Math.round(coverage*100),requiredMonthlyCents,readiness,allocation,protectedCents,ladder,wealthAges,contributionAllocation,healthScore};
}
