export type AcademyBar={time:string;open:number;high:number;low:number;close:number;volume:number};
export type Exercise={id:string;module:string;concept:string;title:string;level:string;explanation:string;task:string;mode:'choice'|'number'|'price'|'candle';choices:string[];answer:number;tolerance:number;reason:string;wrong:string[];bars:AcademyBar[];future:AcademyBar[];source:string;timeframe:string;connection:string;unit?:string;anchor?:number;facts?:Record<string,string|number>;outcome?:unknown};
export const academyModules=[
 ['foundations','Market Foundations','Beginner',['spread','liquidity','limit','slippage','risk']],
 ['candles','Candlesticks & Price Action','Beginner',['body','wick','doji','engulf','false-break']],
 ['structure','Market Structure','Beginner',['trend','support','resistance','bos','choch']],
 ['smc','Smart Money Concepts','Intermediate',['buy-liquidity','sell-liquidity','order-block','fvg','sweep']],
 ['volume','Volume & Momentum','Intermediate',['rvol','confirmation','absorption','gap','pullback']],
 ['indicators','Indicators','Intermediate',['ema','vwap','rsi','macd','atr']],
 ['risk','Risk Management','Beginner',['size','stop','reward-risk','target','cash']],
 ['swing','Swing Trading','Intermediate',['trend','pullback','entry','invalidation','weekend']],
 ['day','Day Trading','Advanced',['vwap','false-break','size','confirmation','time-stop']],
 ['options','Options Foundations','Intermediate',['call','put','shares','max-loss','break-even']],
 ['contracts','Options Contract Selection','Advanced',['contract','dte','spread','liquidity','delta']],
 ['volatility','Volatility & IV','Advanced',['iv','crush','expected-move','vega','atr']],
 ['advanced-options','Advanced Options','Professional Practice',['gamma','assignment','defined-risk','theta','reject']],
 ['portfolio','Portfolio Management','Intermediate',['hold','trim','sell','rotate','rebalance']],
 ['etf','Long-Term / ETF Investing','Intermediate',['allocation','fees','overlap','contribution','horizon']],
 ['news','Market / News Analysis','Advanced',['earnings','guidance','oil','rates','uncertainty']],
 ['finance','Household Finance','Beginner',['budget','reserve','debt','transaction','insurance']],
 ['real-estate','Real Estate Financial Analysis','Professional Practice',['mortgage','cash-flow','ltv','dscr','vacancy']],
] as const;
export const academyReferences=[{title:'OIC · Greeks y volatilidad',url:'https://prd-web.optionseducation.org/advancedconcepts/volatility-the-greeks'},{title:'Investor.gov · Asset allocation',url:'https://www.investor.gov/introduction-investing/getting-started/asset-allocation'},{title:'CFPB · Loan Estimate',url:'https://www.consumerfinance.gov/owning-a-home/loan-estimate/'}];
const round=(v:number)=>Math.round(v*100)/100;
/** Original, reproducible scenarios. These are never labelled historical prices. */
export function trainingBars(seed:number,pattern='trend'):AcademyBar[]{
 const base=60+(seed%13)*7,down=['put','sell','choch'].includes(pattern),range=/support|resistance|liquidity|sweep|false-break/.test(pattern);
 return Array.from({length:38},(_,i)=>{let close=base+(range?Math.sin(i*Math.PI/6)*3:(down?-1:1)*i*.34+Math.sin(i*1.4)*.9),open=close+Math.sin(i+seed)*.65;
 if(['fvg','order-block'].includes(pattern)&&i>=10){close=base+(i===10?-2:i===11?5:6+(i-12)*.18);open=i===10?base:i===11?base-1:close-.4;}
 const low=Math.min(open,close)-.5,high=Math.max(open,close)+.5;
 return {time:'C'+(i+1),open:round(open),high:round(high),low:round(low),close:round(close),volume:1000+(i%4)*150+(i===29?1000:0)};
 });
}
type Task={task:string;mode?:Exercise['mode'];answer:number;choices?:string[];reason:string;wrong?:string[];tolerance?:number;anchor?:number;facts?:Exercise['facts'];unit?:string};
function taskFor(concept:string,b:AcademyBar[],seed:number):Task{
 const last=b.at(-1)!,price=last.close,support=Math.min(...b.map(x=>x.low)),resistance=Math.max(...b.map(x=>x.high)),risk=50+(seed%5)*25,stop=round(price-2),premium=round(1.5+(seed%4)*.5);
 const choice=(task:string,answer:string,a:string,c:string,reason:string):Task=>({task,mode:'choice',answer:0,choices:[answer,a,c],reason,wrong:['',`${a}: ${reason} Esta alternativa no respeta ese criterio.`,`${c}: ${reason} Esta alternativa omite esa condición.`]});
 const number=(task:string,answer:number,reason:string,unit='$'):Task=>({task,mode:'number',answer,tolerance:.01,reason,unit});
 const line=(task:string,answer:number,reason:string):Task=>({task,mode:'price',answer,tolerance:.65,reason});
 switch(concept){
 case 'support':case 'sell-liquidity':return line(concept==='support'?'Marca el límite inferior de Support en el rango visible.':'Marca el pool de sell-side liquidity bajo los mínimos visibles.',support,'La zona corresponde a los mínimos del rango. Los stops pueden concentrarse allí; el gráfico no demuestra quién los colocó.');
 case 'resistance':case 'buy-liquidity':return line(concept==='resistance'?'Marca Resistance sobre el rango visible.':'Marca el pool de buy-side liquidity sobre los máximos.',resistance,'Los máximos delimitan la zona de referencia. Un toque o barrido no confirma por sí mismo una entrada.');
 case 'order-block':return {task:'Selecciona la última vela bajista antes del desplazamiento alcista del escenario.',mode:'candle',answer:10,tolerance:0,anchor:10,reason:'C11 es la última vela bajista antes del impulso C12. Es una zona candidata bajo este marco, no prueba de órdenes institucionales.'};
 case 'fvg':return line('Marca el centro del bullish FVG entre el High de C11 y el Low de C13.',(b[10].high+b[12].low)/2,'La zona sin solapamiento está entre el High de la primera vela y el Low de la tercera. Puede no rellenarse; exige contexto y riesgo.');
 case 'body':return number('Calcula el tamaño absoluto del body de la última vela.',round(Math.abs(last.close-last.open)),'Body = |Close − Open|. Las mechas no forman parte del body.');
 case 'wick':return number('Calcula la upper wick de la última vela.',round(last.high-Math.max(last.open,last.close)),'Upper wick = High − max(Open, Close). No revela por sí sola la dirección futura.');
 case 'doji':return choice('Una vela tiene Open ≈ Close dentro de un rango amplio. ¿Qué puedes afirmar?','Hay equilibrio relativo en el cierre; falta contexto','Es BUY confirmado','Siempre comienza un downtrend','Un doji describe el cuerpo, no garantiza una reversión. Support, volumen y confirmación siguen siendo necesarios.');
 case 'engulf':return choice('Un bullish engulfing aparece bajo Resistance semanal. ¿Qué harías primero?','Evaluar espacio hasta Resistance y confirmación','Comprar sin stop','Ignorar Resistance','El patrón de dos velas no elimina la resistencia del timeframe superior. Compara espacio, riesgo y volumen.');
 case 'trend':return choice('Compara el inicio y el final de la secuencia. ¿Cuál es el sesgo visible?',price>b[0].close?'Uptrend':'Downtrend',price>b[0].close?'Downtrend':'Uptrend','No hay datos de precio','La dirección se apoya en la secuencia de precios. El sesgo no garantiza que continúe después del corte.');
 case 'bos':return choice('El Close rompe un swing high previo con volumen confirmado. ¿Cómo lo clasificarías?','BOS alcista, sujeto a seguimiento','BOS bajista','Prueba de compra institucional','BOS describe una ruptura estructural; necesita un nivel previo definido. La identidad de compradores no se deduce de una vela.');
 case 'choch':return choice('En un downtrend, el precio rompe el último lower high. ¿Qué cambia?','Posible CHOCH; todavía falta confirmar una tendencia nueva','BUY garantizado','La estructura nunca cambia','CHOCH plantea un cambio de carácter. Un higher low y continuidad aportan evidencia adicional.');
 case 'sweep':case 'false-break':return choice('El precio supera Resistance y cierra de nuevo dentro del rango con 0.7× RVOL. ¿Qué decisión corresponde?','WAIT: posible false breakout','BUY por superar el High','CALL sin invalidation','La recuperación del rango y baja participación debilitan la ruptura. Espera aceptación fuera del rango antes de aumentar riesgo.');
 case 'spread':return number(`Bid ${premium.toFixed(2)}, Ask ${(premium+.2).toFixed(2)}. Calcula el spread absoluto.`,.2,'Spread = Ask − Bid. Un contrato barato puede tener un coste relativo de entrada alto.');
 case 'liquidity':return choice('Contrato A: OI 15, spread 25%. B: OI 2,000, spread 3%. ¿Cuál merece investigar primero?','B, si tesis y riesgo también pasan','A porque tiene menos contratos','Cualquiera sin comprobar volumen','B ofrece mejor evidencia de liquidez. OI no garantiza una ejecución ni revela intención; confirma también volumen y quotes.');
 case 'limit':return choice('Necesitas controlar el precio máximo de entrada. ¿Qué orden modelarías?','Limit, aceptando que puede no ejecutarse','Market garantiza el precio','Stop elimina el slippage','Una Limit fija el precio máximo de compra, pero no garantiza ejecución. Un gap puede impedir la entrada.');
 case 'slippage':return number(`Planeabas comprar 10 acciones a ${price}. Pagaste ${(price+.15).toFixed(2)}. ¿Cuánto slippage total hubo?`,1.5,'Diferencia por acción × acciones: $0.15 × 10 = $1.50. Comisiones se calculan por separado.');
 case 'rvol':return number('Volumen actual 2,400; promedio comparable 1,200. Calcula RVOL.',2,'RVOL = volumen observado / volumen comparable. Compara la misma franja temporal en Day Trading.','×');
 case 'confirmation':return choice('Breakout con 2× RVOL y Close sobre el nivel; el sector acompaña. ¿Qué sigue?','Validar stop, espacio al target y tamaño','Entrar con todo el cash','Eliminar el stop','El volumen mejora la evidencia de participación, pero no sustituye el cálculo de riesgo o la validación del precio de entrada.');
 case 'absorption':return choice('Volumen alto, rango estrecho junto a Support. ¿Qué puedes inferir?','Posible absorción; dirección todavía no confirmada','Los bancos están comprando con certeza','SELL garantizado','Precio y volumen permiten formular hipótesis, pero no identificar participantes o garantizar el siguiente movimiento.');
 case 'gap':return choice('Un gap alcista abre encima del Target 1 previsto. ¿Qué cambia?','Recalcular reward/risk y considerar rechazar la entrada','Comprar con el plan anterior','Subir el riesgo para compensar','El gap cambia el precio de entrada, el riesgo hasta invalidation y la recompensa restante. El plan anterior puede dejar de ser válido.');
 case 'pullback':return choice('Uptrend diario; retroceso de menor volumen conserva el higher low. ¿Qué prepararías?','Entrada condicionada a recuperación y confirmación','SELL automático por una vela roja','BUY sin invalidation','Un pullback puede ser constructivo si respeta estructura. No equivale a una señal ejecutable hasta confirmar el disparador.');
 case 'ema':return number('EMA previa 100, Close nuevo 102, período 9. Calcula la EMA nueva.',100.4,'α = 2/(9+1) = 0.2. EMA = 100 + 0.2 × (102−100).');
 case 'vwap':return number('Trades: 100 acciones a $20 y 300 a $22. Calcula VWAP.',21.5,'VWAP = Σ(precio × volumen)/Σ(volumen) = 8,600/400. El VWAP diario se reinicia según la sesión definida.');
 case 'rsi':return choice('RSI 76 en un uptrend fuerte. ¿Qué concluyes?','Momentum elevado; no es SELL automático','PUT garantizado','RSI predice la próxima vela','RSI puede permanecer elevado durante una tendencia. Usa estructura, divergencia, contexto e invalidation.');
 case 'macd':return choice('MACD cruza al alza mientras el precio sigue bajo Resistance. ¿Qué falta?','Confirmación de precio y espacio suficiente','Nada; la señal garantiza beneficio','Conocer quién compró','MACD resume relaciones entre medias y es rezagado. Un cruce aislado no elimina obstáculos de precio.');
 case 'atr':return number('High 105, Low 101, Close anterior 98. Calcula True Range.',7,'TR = max(High−Low, |High−Close previo|, |Low−Close previo|) = max(4,7,3). ATR promedia TR; no predice dirección.');
 case 'size':case 'risk':return number(`Riesgo permitido $${risk}. Entry ${price}, Stop ${stop}. Sin fees en este ejercicio. ¿Cuántas acciones enteras como máximo?`,Math.floor(risk/2),'Acciones = floor(riesgo permitido / distancia al stop). Después limita por cash, concentración y liquidez. Un gap puede superar la pérdida prevista.','acciones');
 case 'stop':case 'invalidation':return line('El plan define invalidation $2 debajo del último Close. Márcala en el gráfico.',stop,'Marca el nivel antes de entrar. No amplíes el stop para evitar aceptar una pérdida; revisa la tesis y el riesgo.');
 case 'reward-risk':return number('Entry 100, Stop 96, Target 112. Calcula reward/risk.',3,'Recompensa/riesgo = (112−100)/(100−96) = 3. No es probabilidad ni expectancy.','R');
 case 'target':return line('Con riesgo de $2 por acción, marca Target 2 a +2R desde el último Close.',price+4,'2R equivale a $4 con riesgo inicial de $2. Un target matemático debe contrastarse con Resistance y liquidez.');
 case 'cash':return number('Cash $415; reserva $115; precio $60; whole shares only. ¿Cuántas acciones permite el cash?',5,'Cash invertible = 415−115 = 300. floor(300/60) = 5; otros límites pueden reducir la cantidad.','acciones');
 case 'entry':return choice('El setup requiere Close sobre Resistance y retest que aguante. Solo hay una mecha por encima. ¿Qué haces?','PREPARE y esperar confirmación','BUY de inmediato','Cambiar la regla después de ver la vela','El trigger escrito requiere cierre y retest. Una mecha no satisface ese plan.');
 case 'weekend':case 'earnings':return choice('Hay earnings antes de la siguiente sesión y el plan no permite event trades. ¿Qué haces?','WAIT y revalidar después del evento','Aumentar la posición','Suponer que earnings será favorable','El catalyst puede producir gaps e IV crush. Respetar una exclusión escrita evita asumir riesgo no aprobado.');
 case 'time-stop':return choice('Un Day Trade no alcanza el target; llega la hora de salida del plan. ¿Qué corresponde?','Aplicar el time stop y registrar la ejecución','Convertirlo en inversión sin revisión','Doblar la posición','Cambiar el horizonte para evitar cerrar altera el riesgo original. La excepción debe planificarse y aprobarse antes.');
 case 'call':return choice('Tesis alcista confirmada; contrato líquido y pérdida máxima dentro del presupuesto. ¿Qué instrumento investigarías?','CALL, comparando también SHARES','PUT por ser más barato','CALL sin mirar IV','La dirección del subyacente precede a la selección del contrato. Aún debes comparar IV, DTE, precio y coste con shares.');
 case 'put':return choice('Tesis bajista confirmada y riesgo de long premium aceptable. ¿Qué contrato investigas?','PUT','CALL porque el precio cayó','Cualquier strike barato','Un PUT comprado expresa una tesis bajista. Una caída sola no demuestra que vaya a continuar.');
 case 'shares':return choice('Tesis alcista a largo plazo, IV cara y contrato de 7 DTE. ¿Qué alternativa comparas?','SHARES o WAIT según cash y valoración','El CALL más OTM','0DTE para reducir premium','Shares no expiran ni pagan Theta de una opción, aunque siguen teniendo riesgo de precio. Compara horizonte y capital.');
 case 'max-loss':return number(`Compras 2 CALL estándar de 100 acciones a premium $${premium}. Sin fees. ¿Cuál es la pérdida máxima del long premium?`,premium*200,'Long option: premium × multiplicador × contratos, más costes si existen. Stock cost basis es independiente.');
 case 'break-even':return number(`Long CALL con strike 100 y premium ${premium}. ¿Break-even al vencimiento sin fees?`,100+premium,'CALL: strike + premium al vencimiento. Antes del vencimiento, valor temporal e IV también afectan el precio.');
 case 'contract':return choice('A: 3 DTE, Delta .10, spread 25%. B: 21 DTE, Delta .50, spread 3%. Tesis de dos semanas y ambos dentro del cap. ¿Cuál investigar?','B','A porque es más barato','Ambos son equivalentes','B se ajusta mejor al horizonte y tiene menor fricción. No garantiza beneficio: verifica IV, OI, volumen y max risk.');
 case 'dte':return choice('Tesis de 10 sesiones; compara 0DTE, 21 DTE y un contrato ya vencido.','Investigar 21 DTE','Elegir 0DTE por precio','Elegir el vencido','La duración debe dar tiempo a la tesis. DTE corto aumenta sensibilidad temporal y exige controles más estrictos.');
 case 'delta':return number('Delta .50, subyacente sube $2, otros factores constantes. Cambio aproximado del premium por acción.',1,'Delta × movimiento = .50 × $2. Es aproximación local; Gamma, IV y tiempo cambian el resultado.');
 case 'iv':return choice('IV 80%, realized 25%, sin catalyst que justifique el premium. ¿Qué comparas?','Premium caro: SHARES, WAIT o más investigación','CALL seguro porque IV es alta','IV equivale a una dirección','La comparación sugiere premium elevado, no una certeza de sobrevaloración. Revisa eventos, horizonte y datos comparables.');
 case 'crush':return choice('Compras CALL antes de earnings; después el precio sube poco e IV cae mucho. ¿Puede perder valor?','Sí, por IV crush y Theta','No, porque subió el stock','Solo si Delta es negativa','Una opción depende de más que dirección. Menor IV y tiempo pueden superar la ganancia por Delta.');
 case 'expected-move':return number('Stock $100, IV 20%, horizonte 30/365 años. Aproxima expected move: S × IV × √T.',round(100*.2*Math.sqrt(30/365)),'Es un rango modelado de volatilidad, no una predicción ni un límite de pérdida.');
 case 'vega':return number('Vega .12 por punto de IV; IV cae 5 puntos. Cambio aproximado por acción, con signo.',-.6,'0.12 × −5 = −0.60. Sensibilidad local; no sustituye repricing completo.');
 case 'gamma':return number('Delta .40, Gamma .03, stock sube $2. Delta aproximada nueva.',.46,'Delta nueva ≈ .40 + .03 × 2 = .46. Gamma cambia al moverse el precio.','Delta');
 case 'theta':return number('Theta −.04 por día y por acción. Aproxima 3 días de decay sin otros cambios.',-.12,'−.04 × 3 = −.12. Theta no es constante, especialmente cerca de expiración.');
 case 'assignment':return choice('Una short CALL puede asignarse. ¿Qué debes comprobar antes de abrir?','Obligación de entrega, cobertura, dividendos y permiso','Solo el premium cobrado','Que nunca se asignará antes del vencimiento','Una opción short con ejercicio americano puede asignarse antes. Riesgo y obligaciones difieren de una long option.');
 case 'defined-risk':return number('Call debit spread 100/105, debit $2, multiplicador 100, una unidad. Máxima pérdida sin fees.',200,'Un debit spread intacto limita la pérdida teórica al debit. Ejercicio, asignación y ejecución de las legs requieren gestión.');
 case 'reject':return choice('Falta OI, el spread es 20% y no hay invalidation. ¿Qué decisión es defendible?','NO TRADE: faltan condiciones esenciales','Comprar porque es barato','Inventar OI desde volumen','La falta de evidencia se mantiene explícita. No se rellena con cero ni con una suposición favorable.');
 case 'hold':return choice('Tesis intacta, peso dentro de objetivo y sin trigger de venta. ¿Qué acción encaja?','HOLD y monitorizar','SELL por una vela roja','ADD sin revisar cash','HOLD es una decisión activa cuando la tesis y el riesgo siguen válidos. Define qué cambiaría esa decisión.');
 case 'trim':return choice('Una posición subió al 35%; el límite documentado es 15%. ¿Qué revisar?','TRIM, impuestos y concentración','ADD por su rendimiento reciente','Ignorar el límite','El exceso de peso merece revisión aunque haya beneficios. Una venta real debe considerar impuestos, costes y restricciones.');
 case 'sell':return choice('La tesis se invalidó con evidencia confirmada; el plan exige salir. ¿Qué corresponde?','SELL según el plan y registrar resultado','HOLD solo para recuperar cost basis','Duplicar la posición','Cost basis sirve para P/L e impuestos; no restaura una tesis rota.');
 case 'rotate':return choice('B parece mejor que A, pero no has incluido impuestos ni costes de salida. ¿Qué falta?','Comparar valor esperado neto de costes y riesgo','ROTATE de inmediato','Comparar solo el último retorno','Una rotación debe superar mantener A después de costes, impuestos, riesgo y concentración.');
 case 'rebalance':case 'allocation':case 'contribution':return number('Portfolio $10,000; target CORE 60%; CORE actual $5,400. Calcula el gap de CORE.',600,'Objetivo $6,000 menos actual $5,400 = $600. Dirige contribuciones al déficit sujeto a cash, valoración y límites.');
 case 'fees':return number('ETF A cobra 0.05% anual; B 0.50%. Sobre $10,000 constantes, diferencia anual aproximada.',45,'$10,000 × (0.005−0.0005) = $45. Rentabilidad, tracking y fiscalidad también importan.');
 case 'overlap':return choice('Dos ETFs tienen muchas de las mismas posiciones principales. ¿Qué revisas?','Exposición agregada y overlap','Suponer diversificación por tener dos tickers','Solo el precio unitario','Contar tickers no mide diversificación. Revisa los holdings subyacentes y pesos combinados.');
 case 'horizon':return choice('El dinero se necesita para vivienda en 12 meses. ¿Qué domina la decisión?','Horizonte, liquidez y tolerancia a pérdida','Maximizar volatilidad','Convertirlo en options especulativas','Un plazo corto reduce capacidad para absorber pérdidas. El objetivo de la cuenta importa más que una señal intradía.');
 case 'guidance':return choice('EPS superó consenso pero guidance se recorta. ¿Cómo actualizas la tesis?','Reevaluar expectativas futuras y calidad del beat','BUY por el titular de EPS','Ignorar el guidance','Separa resultados realizados de expectativas futuras. Compara causa, recurrencia y valoración antes de concluir.');
 case 'oil':return choice('Petróleo sube con fuerza. ¿Cómo usas la noticia?','Investigar impacto específico en costes e ingresos','Comprar todas las aerolíneas','Asumir el mismo efecto en todos los sectores','El impacto depende de exposición, hedges y capacidad de precios. Una relación macro es hipótesis, no señal suficiente.');
 case 'rates':return choice('Suben yields; el modelo de valoración usa una tasa de descuento fija antigua. ¿Qué revisas?','Supuestos y sensibilidad de valoración','Solo el color de la última vela','Eliminar el riesgo del modelo','Los tipos pueden cambiar financiación y valor presente. Modela escenarios sin atribuir todo movimiento a una sola causa.');
 case 'uncertainty':return choice('Hay un rumor sin fuente primaria y volumen normal. ¿Qué hacer?','Marcar incertidumbre y verificar la fuente','Clasificarlo como catalyst confirmado','Añadir una probabilidad inventada','Distingue hecho, interpretación y dato faltante. No conviertas una narrativa en confirmación.');
 case 'budget':return number('Ingreso $4,000; esenciales $2,300; deuda $400; ahorro comprometido $500. Cash libre presupuestado.',800,'4,000−2,300−400−500 = 800. El presupuesto no equivale al saldo bancario disponible.');
 case 'reserve':return number('Gastos esenciales $2,000/mes. Objetivo de reserva del escenario: 4 meses. Reserva actual $5,000. Gap.',3000,'Objetivo $8,000 menos $5,000 = $3,000. Ajusta el objetivo a la situación del hogar; no uses reservas como capital de trading.');
 case 'debt':return choice('Tarjeta al 25% APR; una inversión ofrece retorno incierto. ¿Qué comparar primero?','Coste de deuda, reserva y liquidez del hogar','Asumir que la inversión ganará más','Invertir todo el fondo de emergencia','El interés contractual y un retorno incierto no son equivalentes. Evalúa prioridades sin prometer rendimientos.');
 case 'transaction':return choice('Una compra de restaurante aparece como pending y luego posted con nuevo ID. ¿Cómo evitar doble alerta?','Conciliar la identidad antes de aplicar deduplicación','Alertar dos veces por defecto','Borrar todos los gastos','La clasificación y la identidad canónica deben reconciliar pending y posted; conserva auditoría de entrega.');
 case 'insurance':return choice('Una pérdida imprevista supera el deducible. ¿Qué dato falta para estimar cobertura?','Póliza, exclusiones y límite aplicable','El último precio de SPY','El saldo de la tarjeta','Cobertura depende del contrato y del hecho concreto. Un presupuesto no sustituye la póliza.');
 case 'mortgage':return number('Pago principal/interés $1,400, impuestos $300, seguro $120 y HOA $80. Coste mensual antes de mantenimiento.',1900,'Suma todos los componentes conocidos. Añade mantenimiento, utilities y otros costes para evaluar asequibilidad.');
 case 'cash-flow':return number('Renta $2,000; gastos operativos $600; deuda $1,000; reserva $150. Cash flow mensual.',250,'2,000−600−1,000−150 = 250. Incluye vacancy y capex antes de usar esta cifra en una decisión real.');
 case 'ltv':return number('Préstamo $240,000; valor $300,000. LTV en porcentaje.',80,'LTV = deuda / valor × 100 = 80%. No mide por sí solo la capacidad de pago.','%');
 case 'dscr':return number('NOI anual $24,000; debt service anual $20,000. DSCR.',1.2,'DSCR = NOI / debt service = 1.2. Revisa definiciones, estabilidad de rentas y condiciones del préstamo.','×');
 case 'vacancy':return number('Renta potencial anual $24,000; vacancy modelada 5%. Ingreso esperado antes de otros gastos.',22800,'24,000 × (1−0.05) = 22,800. Es una hipótesis de escenario, no una garantía de ocupación.');
 default:throw Error('Unsupported Academy concept: '+concept);
 }
}
export function makeExercise(moduleId:string,index:number,variant=0):Exercise{
 const module=academyModules.find(m=>m[0]===moduleId);if(!module||!Number.isInteger(index)||index<0||index>=module[3].length)throw Error('EXERCISE_NOT_FOUND');
 const concept=module[3][index],seed=academyModules.indexOf(module)*100+index*7+variant*17,bars=trainingBars(seed,concept),visible=bars.slice(0,30),task=taskFor(concept,visible,seed);
 // Deterministic choice rotation avoids teaching "always pick the first option".
 let choices=task.choices||[],wrong=task.wrong||[],answer=task.answer;
 if(choices.length){const n=(seed+index)%choices.length;choices=[...choices.slice(n),...choices.slice(0,n)];wrong=[...wrong.slice(n),...wrong.slice(0,n)];answer=(choices.length-n)%choices.length;}
 return {id:moduleId+':'+index+':'+variant,module:moduleId,concept,title:concept.replaceAll('-',' '),level:module[2],explanation:task.reason,task:task.task,mode:task.mode||'choice',choices,answer,tolerance:task.tolerance??0,reason:task.reason,wrong,bars:visible,future:bars.slice(30),source:'NORTHSTAR-SIM · escenario original generado; no son precios históricos',timeframe:moduleId==='day'?'5m simulado':moduleId==='etf'?'1W simulado':'1D simulado',connection:moduleId.includes('option')||['contracts','volatility'].includes(moduleId)?'Options: tesis → contrato → riesgo → confirmación.':'Trading: usa evidencia, condiciones e invalidation antes de ejecutar.',unit:task.unit,anchor:task.anchor,facts:task.facts};
}
export function publicExercise(e:Exercise){const {answer,tolerance,reason,wrong,future,outcome,anchor,...question}=e;return {...question,explanation:conceptIntro(e.concept)};}
function conceptIntro(concept:string){
 if(['buy-liquidity','sell-liquidity','order-block','fvg','sweep','bos','choch'].includes(concept))return 'Smart Money Concepts es un marco de Price Action. Una zona no prueba intención institucional. Combina trend, volumen, volatilidad, contexto y riesgo.';
 if(['size','risk','cash','stop','target','invalidation'].includes(concept))return 'Define riesgo antes de calcular tamaño. Cash disponible, concentración y liquidez pueden reducir la posición. Un stop no garantiza el precio de salida.';
 return 'Observa los datos disponibles antes del corte. Toma una decisión usando el concepto '+concept.replaceAll('-',' ')+'. El resultado posterior no convierte una mala decisión en un buen proceso.';
}
export function gradeExercise(e:Exercise,value:unknown){const numeric=typeof value==='number'?value:typeof value==='string'&&value.trim()?Number(value):NaN;if(!Number.isFinite(numeric))throw Error('ANSWER_REQUIRED');const correct=Math.abs(numeric-e.answer)<=e.tolerance;return {correct,answer:e.mode==='choice'?e.choices[e.answer]:e.answer,answerValue:e.answer,reason:e.reason,alternatives:e.choices.map((choice,i)=>({choice,reason:i===e.answer?e.reason:e.wrong[i]})),future:e.future,solution:{mode:e.mode,value:e.answer,tolerance:e.tolerance,anchor:e.anchor},outcome:e.outcome||{first:e.bars.at(-1)?.close,last:e.future.at(-1)?.close,label:'Continuación sintética revelada; evalúa el proceso por separado del resultado.'}};}

/** One coherent ten-decision case; no later candles until the final stage. */
export function makeMarketCase(step:number):Exercise{
 if(!Number.isInteger(step)||step<0||step>9)throw Error('EXERCISE_NOT_FOUND');
 const base=makeExercise('options',0,4),raw=trainingBars(74),scale=100/raw[29].close,all=raw.map(b=>({...b,open:round(b.open*scale),high:round(b.high*scale),low:round(b.low*scale),close:round(b.close*scale)})),bars=all.slice(0,30);
 const cases=[
 ['trend','La estructura diaria hace higher highs/higher lows. El sector acompaña, pero el trigger todavía no se confirma. ¿Qué tesis investigar?',['Alcista condicional: PREPARE','PUT porque toda subida debe caer','BUY sin confirmar'],0,'Trend y sector sostienen una hipótesis alcista. El precio aún debe confirmar el trigger.'],
 ['dte','Horizonte 10 sesiones; earnings en 45 días. ¿Qué vencimiento comparar primero?',['2 DTE porque cuesta menos','28 DTE, contrastando liquidez y time stop','0DTE sin confirmación'],1,'28 DTE permite desarrollar la tesis multi-day. La prima más baja no compensa por sí sola el vencimiento demasiado corto.'],
 ['contract','A: CALL 110, 2 DTE, Delta .08, bid .05 / ask .20, OI 12. B: CALL 100, 28 DTE, Delta .52, bid 1.90 / ask 2.10, OI 2,500. ¿Cuál merece deep research?',['A por ser barato','Ambos son equivalentes','B, sujeto a IV, trigger y presupuesto'],2,'B tiene más tiempo, mejor exposición direccional y menor spread relativo. Todavía no es autorización para comprar.'],
 ['spread','Contrato B: bid $1.90, ask $2.10. Calcula el spread absoluto por acción.',[],.2,'2.10−1.90 = $0.20, o $20 por contrato estándar. Un limit order no garantiza fill.'],
 ['delta','Delta .52, Gamma .04, Theta −.05, Vega .10. Aproxima el cambio por acción ante +$1 del subyacente usando solo Delta.',[],.52,'Delta × movimiento = .52 × 1. Es aproximación local; Gamma, IV y tiempo cambian el resultado.'],
 ['iv','IV 32%; expected move de la ventana ±$6, próximo earnings fuera de la ventana. ¿Qué falta antes de afirmar que IV es barata?',['Comparar con historia comparable e implied/realized volatility','Nada: 32% siempre es barato','Usar el precio nominal del contrato'],0,'Un nivel absoluto de IV no basta. IV rank/percentile e historia comparable pueden faltar; marca esa incertidumbre.'],
 ['max-loss','Cap de premium $500; máximo entry premium $2.10; multiplicador 100. ¿Cuántos contratos enteros caben?',[],2,'floor(500/(2.10×100)) = 2. Coste $420 antes de fees; reserva para costes puede reducir tamaño.'],
 ['break-even','CALL strike $100; fill hipotético $2.10. Break-even a expiración antes de fees.',[],102.1,'100+2.10 = 102.10. Antes de expiración el valor depende también de tiempo e IV.'],
 ['time-stop','El plan exige salida tras 10 sesiones si no desarrolla la tesis, aunque queden 18 DTE. ¿Qué hacer al alcanzar el time stop?',['Esperar siempre a expiración','Aplicar el time stop; registrar fill y razones','Doblar para compensar Theta'],1,'El time stop controla el coste de esperar. DTE disponible no obliga a mantener una tesis que no se desarrolla.'],
 ['reject','Falta confirmación del trigger; el spread se amplía a 30%. ¿Cuál es la decisión final?',['READY: el contrato era bueno antes','PREPARE / NO TRADE: revalidar trigger, spread e IV','Comprar A para gastar menos'],1,'La calidad de un contrato cambia. No ejecutes con trigger ausente o liquidez fuera del límite. Revalida o cancela el plan.'],
 ] as const;
 const [concept,task,choices,answer,reason]=cases[step];return {...base,id:'market-case:'+step,module:'advanced-options',concept,title:'Caso integral · '+(step+1)+'/10',task,choices:[...choices],answer,mode:choices.length?'choice':'number',tolerance:choices.length?0:.01,reason,wrong:choices.map((c,i)=>i===answer?'':c+': '+reason),bars,future:step===9?all.slice(30):[],facts:{Case:'NORTHSTAR-SIM',Underlying:100,Trigger:101,Invalidation:97,Target:106,'Premium cap':500,'Contract B':'CALL 100 · 28 DTE · bid 1.90 / ask 2.10','Option exit':'Exit if underlying closes below invalidation; revalidate spread; no stop fill guarantee'},outcome:step===9?undefined:{label:'El caso continúa. Las velas posteriores se revelan solo al completar la última decisión.'}};
}
