import {id,type PostgresDatabase} from '@/lib/db';
import {accountRiskSettings} from '@/lib/account-risk-settings';
import {marketResearchInputs} from '@/lib/market-research-inputs';
import {opportunityExpectancy} from '@/lib/market-expectation';
type Row=Record<string,any>;
export async function startAccountSearch(db:PostgresDatabase,householdId:string,accountId:string,force=false){
 return db.transaction(async tx=>{
 const account=await tx.prepare("SELECT a.id,COALESCE(s.strategy_type,'LONG_TERM') strategy FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=? AND a.hidden=0 AND a.type='investment' FOR UPDATE OF a").bind(accountId,householdId).first<Row>();if(!account)throw Error('ACCOUNT_NOT_FOUND');
 const active=await tx.prepare("SELECT id FROM account_search_runs WHERE account_id=? AND status='RUNNING' AND created_at>CURRENT_TIMESTAMP-INTERVAL '2 hours' ORDER BY created_at DESC LIMIT 1").bind(accountId).first<Row>();if(active){if(force)await tx.prepare("UPDATE background_jobs SET available_at=CURRENT_TIMESTAMP,payload_json=payload_json||'{\"force\":true,\"manual\":true}'::jsonb WHERE payload_json->>'runId'=? AND status IN ('QUEUED','FAILED') AND attempts<6").bind(active.id).run();return {runId:active.id,status:'RUNNING',deduplicated:true};}
 const rows=(await tx.prepare("SELECT d.symbol,d.seed_json,d.last_screened_at,c.business_quality,c.valuation,c.strategy_fit FROM discovery_queue d LEFT JOIN market_discovery_candidates c USING(symbol) WHERE d.active").all<Row>()).results;
 const holdings=(await tx.prepare("SELECT DISTINCT s.ticker symbol FROM holdings h JOIN securities s ON s.id=h.security_id WHERE h.account_id=? AND h.quantity>0 AND s.ticker IS NOT NULL AND COALESCE(s.type,'') NOT IN ('cash','money_market') UNION SELECT s.ticker symbol FROM position_states p JOIN securities s ON s.id=p.security_id WHERE p.account_id=? AND p.state_json->>'positionState' IN ('REENTRY_WATCH','REENTRY_READY')").bind(accountId,accountId).all<Row>()).results;
 const longTerm=!/SWING|MIXED/.test(account.strategy),reasons:Row={},ranked:Row[]=[];let screened=0,stale=0,unavailable=0,rejected=0;
 for(const row of rows){const seed=row.seed_json?.seed,m=seed?.metrics;if(!m){unavailable++;continue;}screened++;if(!row.last_screened_at||Date.now()-Date.parse(row.last_screened_at)>2*86400000){stale++;continue;}if(Number(m.averageDollarVolume)<2_000_000||!(Number(m.price)>0)){rejected++;reasons.LIQUIDITY_OR_PRICE=(reasons.LIQUIDITY_OR_PRICE||0)+1;continue;}const score=longTerm?Number(seed.buckets?.quiet||0)*.3+Number(row.business_quality||0)*.4+Number(row.valuation||0)*.3:Number(seed.buckets?.swing||seed.seed||0)*.5+Math.min(40,Number(m.relativeVolume||0)*10)+Math.min(20,Math.abs(Number(m.dayChange||0))*2);ranked.push({...row,score});}
 ranked.sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));const selected=[...new Set([...holdings.map(h=>h.symbol),...ranked.slice(0,24).map(r=>r.symbol)])],runId=id('account_search');
 const counts={universe:rows.length,screened,shortlisted:selected.length,deepResearched:0,rejected,stale,failed:0,unavailable,rejectionReasons:reasons,source:'Full supported discovery universe snapshot; provider screening rotates continuously',strategy:account.strategy};
 await tx.prepare("INSERT INTO account_search_runs(id,household_id,account_id,status,stage,counts_json) VALUES(?,?,?,'RUNNING','DEEP_RESEARCH',?::jsonb)").bind(runId,householdId,accountId,JSON.stringify(counts)).run();
 for(const symbol of selected){const rank=ranked.find(r=>r.symbol===symbol)?.score||0;await tx.prepare("INSERT INTO account_search_candidates(run_id,symbol,rank_score) VALUES(?,?,?)").bind(runId,symbol,rank).run();const jobId=id('opportunity');await tx.prepare("INSERT INTO background_jobs(id,household_id,job_type,idempotency_key,payload_json) VALUES(?,?,'ACCOUNT_OPPORTUNITY_REVIEW',?,?::jsonb)").bind(jobId,householdId,runId+':'+symbol,JSON.stringify({accountId,symbol,runId,force,manual:force,priority:rank})).run();}
 if(!selected.length)await tx.prepare("UPDATE account_search_runs SET status='PARTIAL',stage='FULL_UNIVERSE',last_error='Broad screening has not supplied eligible candidates yet' WHERE id=?").bind(runId).run();
 await tx.prepare("INSERT INTO background_jobs(id,job_type,idempotency_key,payload_json) VALUES(?,'MARKET_DISCOVERY',?,'{}'::jsonb) ON CONFLICT DO NOTHING").bind('account-discovery-'+runId,'account-discovery-'+runId).run();
 return {runId,status:'RUNNING',counts,deduplicated:false};
 });
}
export async function reviewAccountOpportunity(db:PostgresDatabase,householdId:string,body:Row){
 const {accountId,symbol,runId}=body;await db.prepare("UPDATE account_search_candidates SET status='RUNNING',updated_at=CURRENT_TIMESTAMP WHERE run_id=? AND symbol=?").bind(runId,symbol).run();
 const research=await marketResearchInputs(db,symbol,Boolean(body.force)),risk=await accountRiskSettings(db,householdId,accountId),technical=research.technical;
 const settings=await db.prepare('SELECT strategy_type,share_mode,policy_json FROM investment_account_settings WHERE account_id=?').bind(accountId).first<Row>();
 const held=await db.prepare("SELECT COALESCE(SUM(h.quantity),0)::text shares,SUM(h.cost_basis_cents)::text basis FROM holdings h JOIN securities s ON s.id=h.security_id WHERE h.account_id=? AND s.ticker=?").bind(accountId,symbol).first<Row>();
 const reserved=await db.prepare("SELECT COALESCE(SUM(CASE WHEN status='ROTATION_READY' THEN (allocation_json->>'reservedCash')::numeric ELSE (plan_json->>'reservedCash')::numeric END),0)::text amount FROM trade_lifecycle_exits WHERE account_id=? AND status IN ('REENTRY_WATCH','REENTRY_READY','ROTATION_READY')").bind(accountId).first<Row>();
 const owned=Number(held?.shares||0),price=Number(research.quote.last||0),reserve=risk.value*risk.effective.cashReserveBps/10000+Number(reserved?.amount||0),cash=Math.max(0,risk.cash-reserve),positionRoom=Math.max(0,risk.value*risk.effective.maxPositionBps/10000-owned*price),fractional=settings?.share_mode==='FRACTIONAL',loss=technical.direction==='CALL'?Math.max(0,price-Number(technical.invalidation)):0;
 const raw=price&&loss?Math.max(0,Math.min(cash/price,positionRoom/price,risk.value*risk.effective.swingRiskBps/10000/loss)):0,scale=fractional?10000:1,modeledShares=Math.floor(raw*scale)/scale;
 const expectancy=opportunityExpectancy(technical,{catalystClear:research.catalystGate?.pass===true,fundamentals:!research.stageErrors.FUNDAMENTAL_ANALYSIS,valuation:Number(research.fundamentals.metrics?.peNormalizedAnnual)>0,liquid:technical.averageDollarVolume>=2_000_000,concentrated:positionRoom===0});
 const reasons:string[]=[];if(!research.marketFresh)reasons.push('Stale underlying quote');if(!technical.complete)reasons.push('Technical evidence incomplete');if(technical.direction!=='CALL')reasons.push('No confirmed long-entry expectation');if(!research.catalystGate?.pass)reasons.push('News/catalyst risk not cleared');if(!modeledShares)reasons.push(cash<=0?'Cash is reserved under account policy':!fractional&&price>cash?`Whole-share minimum ${price.toFixed(2)} exceeds investable cash ${cash.toFixed(2)}`:'Position or risk capacity insufficient');if(expectancy.score==null||expectancy.score<=0)reasons.push('Non-positive or unavailable modeled expectancy');if((expectancy.rewardRisk||0)<risk.effective.minimumRewardRisk)reasons.push('Reward/risk below account requirement');
 const missing=Object.keys(research.stageErrors);if(missing.length)reasons.push('Missing evidence: '+missing.join(', '));
 const decision=owned>0?(technical.direction==='PUT'?'HOLD / TRIM REVIEW':positionRoom===0?'HOLD / STOP ADDING':'HOLD / ADD IF'):technical.direction==='CALL'?'PREPARE':'HOLD CASH';
 const output={symbol,decision,asOf:research.asOf,analyzedAt:new Date().toISOString(),expectation:technical.expectation,confidence:technical.confidence,confidenceBasis:technical.confidenceBasis,price,trigger:technical.trigger,confirmation:'Reclaim/hold the trigger with volume confirmation, fresh quotes, cleared catalyst risk and final sector/open-risk checks',entryType:'Conditional limit after confirmation',shares:modeledShares,sharesAreConditional:true,totalCost:modeledShares*price,stop:technical.invalidation,targets:technical.atr?[price+3*technical.atr,price+4.5*technical.atr]:[],holdingPeriod:/SWING|MIXED/.test(settings?.strategy_type||'')?risk.effective.maxSwingDays+' days':'Account long-term horizon',rewardRisk:expectancy.rewardRisk,expectancy,reason:reasons.join('; ')||'Directional setup passes initial research; execution confirmation still required',evidenceFor:technical.evidence,evidenceAgainst:reasons,cancelConditions:['Thesis or catalyst risk changes','Price breaks invalidation','Cash, concentration or risk capacity changes','Quote or confirmation expires'],minimumCash:price>0?fractional?Math.ceil(price/10000*100)/100:price:null,availableCash:risk.cash,investableCash:cash,reservedCash:Math.min(risk.cash,reserve),fractional,ownedShares:owned,stockAverageCost:owned&&held?.basis!=null?Number(held.basis)/100/owned:null,executionReady:false,mandatoryConfirmation:['Sector concentration and combined open-risk capacity must be verified by the central execution engine'],stageErrors:research.stageErrors};
 await db.prepare("UPDATE account_search_candidates SET status=?,decision_json=?::jsonb,rank_score=?,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE run_id=? AND symbol=?").bind(missing.length?'PARTIAL':'COMPLETE',JSON.stringify(output),Number(expectancy.score??-100),missing.join('; ')||null,runId,symbol).run();
 const counts=await db.prepare("SELECT count(*)::int shortlisted,count(*) FILTER(WHERE status IN ('COMPLETE','PARTIAL'))::int deep_researched,count(*) FILTER(WHERE status='FAILED')::int failed,count(*) FILTER(WHERE status='PARTIAL')::int partial,count(*) FILTER(WHERE status IN ('QUEUED','RUNNING'))::int pending FROM account_search_candidates WHERE run_id=?").bind(runId).first<Row>();
 await db.prepare("UPDATE account_search_runs SET counts_json=counts_json||?::jsonb,status=?,stage=?,completed_at=CASE WHEN ?=0 THEN CURRENT_TIMESTAMP ELSE NULL END WHERE id=?").bind(JSON.stringify({deepResearched:counts?.deep_researched,failed:counts?.failed,partial:counts?.partial,pending:counts?.pending}),counts?.pending?'RUNNING':counts?.partial||counts?.failed?'PARTIAL':'RESEARCHED',counts?.pending?'DEEP_RESEARCH':'COMPARE_ALTERNATIVES',counts?.pending||0,runId).run();
 if(technical.direction==='CALL'&&modeledShares>0&&!missing.length)await db.prepare("INSERT INTO background_jobs(id,household_id,job_type,idempotency_key,payload_json) VALUES(?,?,'AI_EVENT_REVIEW',?,?::jsonb) ON CONFLICT DO NOTHING").bind(id('confirm_opportunity'),householdId,'confirm:'+runId+':'+symbol,JSON.stringify({accountId,symbol,reason:'RANKED_ACCOUNT_SEARCH'})).run();
 return {partial:missing.length>0};
}
export async function accountSearchStatus(db:PostgresDatabase,householdId:string,accountId:string){
 const run=await db.prepare('SELECT * FROM account_search_runs WHERE household_id=? AND account_id=? ORDER BY created_at DESC LIMIT 1').bind(householdId,accountId).first<Row>();if(!run)return null;
 const candidates=(await db.prepare("SELECT symbol,status,rank_score,decision_json,last_error,updated_at FROM account_search_candidates WHERE run_id=? ORDER BY rank_score DESC,symbol").bind(run.id).all<Row>()).results;
 const previous=await db.prepare("SELECT completed_at FROM account_search_runs WHERE account_id=? AND completed_at IS NOT NULL ORDER BY completed_at DESC LIMIT 1").bind(accountId).first<Row>();
 if(!candidates.some(c=>c.decision_json?.symbol)){const saved=await db.prepare("SELECT c.symbol,c.status,c.rank_score,c.decision_json,c.last_error,c.updated_at FROM account_search_candidates c JOIN account_search_runs r ON r.id=c.run_id WHERE r.account_id=? AND r.id<>? AND c.decision_json->>'symbol' IS NOT NULL ORDER BY r.created_at DESC,c.rank_score DESC LIMIT 10").bind(accountId,run.id).all<Row>();for(const row of saved.results)candidates.push({...row,status:'SAVED · REVALIDATION REQUIRED',decision_json:{...row.decision_json,shares:0,executionReady:false,stageErrors:{...row.decision_json.stageErrors,revalidation:'Saved result; fresh research pending'}}});}
 return {...run,lastCompletedAt:previous?.completed_at,candidates,wholeShareCashBlocked:candidates.some(c=>c.decision_json.price>0&&!c.decision_json.fractional)&&candidates.filter(c=>c.decision_json.price>0&&!c.decision_json.fractional).every(c=>c.decision_json.minimumCash>c.decision_json.investableCash)};
}
