import {evaluateCatalystEntryGate} from '@/lib/catalyst-entry-gate';
import {isLongTermStrategy,strategyResearchScore,longTermCapacity} from '@/lib/account-strategy-research';
import {id,type PostgresDatabase} from '@/lib/db';
import {accountRiskSettings} from '@/lib/account-risk-settings';
import {marketResearchInputs} from '@/lib/market-research-inputs';
import {sessionWindow,researchMarketFresh} from '@/lib/research-market-freshness';
import {exchangeDay} from '@/lib/exchange-calendar';
import {opportunityExpectancy} from '@/lib/market-expectation';
type Row=Record<string,any>;
export async function startAccountSearch(db:PostgresDatabase,householdId:string,accountId:string,force=false,cycleId?:string){
 return db.transaction(async tx=>{
 const account=await tx.prepare("SELECT a.id,CASE WHEN a.investment_purpose='Mixed' THEN 'MIXED' ELSE COALESCE(s.strategy_type,'LONG_TERM') END strategy FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=? AND a.hidden=0 AND a.type='investment' FOR UPDATE OF a").bind(accountId,householdId).first<Row>();if(!account)throw Error('ACCOUNT_NOT_FOUND');
 const active=await tx.prepare("SELECT r.id FROM account_search_runs r WHERE r.account_id=? AND r.status<>'SUPERSEDED' AND EXISTS(SELECT 1 FROM background_jobs j WHERE j.payload_json->>'runId'=r.id AND j.job_type='ACCOUNT_OPPORTUNITY_REVIEW' AND j.status IN ('QUEUED','RUNNING','FAILED') AND j.attempts<6) ORDER BY r.created_at DESC LIMIT 1").bind(accountId).first<Row>();if(active){if(force)await tx.prepare("UPDATE background_jobs SET status='QUEUED',attempts=CASE WHEN attempts>=6 THEN 0 ELSE attempts END,available_at=CURRENT_TIMESTAMP,payload_json=payload_json||jsonb_build_object('refreshRequestedAt',CURRENT_TIMESTAMP)||'{\"force\":true,\"manual\":true}'::jsonb WHERE payload_json->>'runId'=? AND error_code IS DISTINCT FROM 'SUPERSEDED_BY_NEWER_ACCOUNT_RUN' AND status IN ('QUEUED','FAILED','DEAD')").bind(active.id).run();return {runId:active.id,status:'RUNNING',deduplicated:true};}
 const rows=(await tx.prepare("SELECT d.symbol,COALESCE(n.seed_json,d.seed_json) seed_json,d.asset_json,COALESCE(n.screened_at,d.last_screened_at) last_screened_at,c.business_quality,c.valuation,c.strategy_fit,c.sector,c.cap_bucket,COALESCE((SELECT sum((e.evidence_json->>'rankingAdjustment')::numeric) FROM next_session_edges e WHERE e.cycle_id=? AND e.symbol=d.symbol),0) event_priority FROM discovery_queue d LEFT JOIN market_discovery_candidates c USING(symbol) LEFT JOIN next_session_symbols n ON n.symbol=d.symbol AND n.cycle_id=? WHERE d.active AND (?::text IS NULL OR n.status='SCREENED')").bind(cycleId||null,cycleId||null,cycleId||null).all<Row>()).results;
 const holdings=(await tx.prepare("SELECT DISTINCT s.ticker symbol FROM holdings h JOIN securities s ON s.id=h.security_id WHERE h.account_id=? AND h.quantity>0 AND s.ticker IS NOT NULL AND COALESCE(s.type,'') NOT IN ('cash','money_market') UNION SELECT s.ticker symbol FROM position_states p JOIN securities s ON s.id=p.security_id WHERE p.account_id=? AND p.state_json->>'positionState' IN ('REENTRY_WATCH','REENTRY_READY')").bind(accountId,accountId).all<Row>()).results;
 const reasons:Row={},ranked:Row[]=[];let screened=0,stale=0,unavailable=0,rejected=0;
 for(const row of rows){if(account.strategy==='LONG_TERM_ETF'&&!/\b(etf|exchange.traded fund)\b/i.test(row.asset_json?.name||'')){rejected++;reasons.ETF_ONLY_POLICY=(reasons.ETF_ONLY_POLICY||0)+1;continue;}const seed=row.seed_json?.seed,m=seed?.metrics;if(!m){unavailable++;continue;}screened++;if(!row.last_screened_at||Date.now()-Date.parse(row.last_screened_at)>2*86400000){stale++;continue;}if(Number(m.averageDollarVolume)<2_000_000||!(Number(m.price)>0)){rejected++;reasons.LIQUIDITY_OR_PRICE=(reasons.LIQUIDITY_OR_PRICE||0)+1;continue;}const score=strategyResearchScore(account.strategy,row);ranked.push({...row,score:score+Math.min(12,Number(row.event_priority||0))});}
 ranked.sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));const selected=[...new Set([...holdings.map(h=>h.symbol),...ranked.slice(0,cycleId?48:24).map(r=>r.symbol)])],runId=id('account_search');
 const counts={cycleId:cycleId||null,universe:rows.length,screened,shortlisted:selected.length,deepResearched:0,rejected,stale,failed:0,unavailable,rejectionReasons:reasons,source:cycleId?'Completed next-session universe pass; eligible candidates ranked for this account':'Full supported discovery universe snapshot; provider screening rotates continuously',strategy:account.strategy};
 const cycleCoverage=cycleId?await tx.prepare('SELECT counts_json FROM next_session_cycles WHERE id=?').bind(cycleId).first<Row>():null;
 if(cycleCoverage)Object.assign(counts,cycleCoverage.counts_json,{shortlisted:selected.length,deepResearched:0,strategyEligible:ranked.length});
 await tx.prepare("INSERT INTO account_search_runs(id,household_id,account_id,status,stage,counts_json) VALUES(?,?,?,'RUNNING','DEEP_RESEARCH',?::jsonb)").bind(runId,householdId,accountId,JSON.stringify(counts)).run();
 for(const symbol of selected){const rank=ranked.find(r=>r.symbol===symbol)?.score||0;await tx.prepare("INSERT INTO account_search_candidates(run_id,symbol,rank_score) VALUES(?,?,?)").bind(runId,symbol,rank).run();const jobId=id('opportunity');await tx.prepare("INSERT INTO background_jobs(id,household_id,job_type,idempotency_key,payload_json) VALUES(?,?,'ACCOUNT_OPPORTUNITY_REVIEW',?,?::jsonb)").bind(jobId,householdId,runId+':'+symbol,JSON.stringify({accountId,symbol,runId,cycleId,force,manual:force,priority:holdings.some(h=>h.symbol===symbol)?200:rank,lane:holdings.some(h=>h.symbol===symbol)?'OWNED':'ROTATION'})).run();}
 if(!selected.length)await tx.prepare("UPDATE account_search_runs SET status='PARTIAL',stage='FULL_UNIVERSE',last_error='Broad screening has not supplied eligible candidates yet' WHERE id=?").bind(runId).run();
 await tx.prepare("INSERT INTO background_jobs(id,job_type,idempotency_key,payload_json) VALUES(?,'MARKET_DISCOVERY',?,'{}'::jsonb) ON CONFLICT DO NOTHING").bind('account-discovery-'+runId,'account-discovery-'+runId).run();
 return {runId,status:'RUNNING',counts,deduplicated:false};
 });
}
export async function reviewAccountOpportunity(db:PostgresDatabase,householdId:string,body:Row){
 const {accountId,symbol,runId}=body;await db.prepare("UPDATE account_search_candidates SET status='RUNNING',updated_at=CURRENT_TIMESTAMP WHERE run_id=? AND symbol=?").bind(runId,symbol).run();
 const research=await marketResearchInputs(db,symbol,Boolean(body.force),undefined,body.requestedAt),risk=await accountRiskSettings(db,householdId,accountId),technical=research.technical;
 const settings=await db.prepare("SELECT CASE WHEN a.investment_purpose='Mixed' THEN 'MIXED' ELSE s.strategy_type END strategy_type,s.share_mode,s.policy_json,s.horizon_months,s.goal_name FROM investment_account_settings s JOIN accounts a ON a.id=s.account_id WHERE s.account_id=?").bind(accountId).first<Row>();
 const held=await db.prepare("SELECT COALESCE(SUM(h.quantity),0)::text shares,SUM(h.cost_basis_cents)::text basis FROM holdings h JOIN securities s ON s.id=h.security_id WHERE h.account_id=? AND s.ticker=?").bind(accountId,symbol).first<Row>();
 const reserved=await db.prepare("SELECT COALESCE(SUM(CASE WHEN status='ROTATION_READY' THEN (allocation_json->>'reservedCash')::numeric ELSE (plan_json->>'reservedCash')::numeric END),0)::text amount FROM trade_lifecycle_exits WHERE account_id=? AND status IN ('REENTRY_WATCH','REENTRY_READY','ROTATION_READY')").bind(accountId).first<Row>();
 const owned=Number(held?.shares||0),price=Number(research.quote.last||0),plannedEntry=technical.direction==='CALL'?Math.max(price,Number(technical.trigger)||price):price,reserve=risk.value*risk.effective.cashReserveBps/10000+Number(reserved?.amount||0),cash=Math.max(0,risk.cash-reserve),positionRoom=Math.max(0,risk.value*risk.effective.maxPositionBps/10000-owned*price),fractional=settings?.share_mode==='FRACTIONAL',loss=technical.direction==='CALL'?Math.max(0,plannedEntry-Number(technical.invalidation)):0;
 const raw=price&&loss?Math.max(0,Math.min(cash/plannedEntry,positionRoom/plannedEntry,risk.value*risk.effective.swingRiskBps/10000/loss)):0,scale=fractional?10000:1;
 let modeledShares=Math.floor(raw*scale)/scale;
 const longTerm=isLongTermStrategy(settings?.strategy_type||'LONG_TERM');let allocation:Row|null=null;let allocationRank=0;
 if(longTerm){
 const targets=(await db.prepare('SELECT category,target_bps FROM account_allocation_targets WHERE account_id=?').bind(accountId).all<Row>()).results;
 const holdings=(await db.prepare("SELECT s.ticker symbol,s.name,s.type,SUM(h.quantity*h.price_cents)/100 value FROM holdings h JOIN securities s ON s.id=h.security_id WHERE h.account_id=? GROUP BY s.ticker,s.name,s.type").bind(accountId).all<Row>()).results;
 const asset=await db.prepare('SELECT d.asset_json,d.seed_json,c.business_quality,c.valuation FROM discovery_queue d LEFT JOIN market_discovery_candidates c USING(symbol) WHERE d.symbol=?').bind(symbol).first<Row>();
 allocation=longTermCapacity({strategy:settings?.strategy_type,value:risk.value,cash,positionRoom,price:plannedEntry,name:asset?.asset_json?.name||research.fundamentals.profile?.name||symbol,symbol,fractional,targets:Object.fromEntries(targets.map(r=>[r.category,Number(r.target_bps)])),holdings});modeledShares=allocation.shares;allocationRank=strategyResearchScore(settings?.strategy_type,asset||{})+Math.min(30,Math.max(0,allocation.gap)/Math.max(1,risk.value)*100);
 }
 const shareCatalystGate=evaluateCatalystEntryGate(research.catalysts,{mode:'SHARES'});
 const expectancy=opportunityExpectancy(technical,{entryPrice:plannedEntry,catalystClear:shareCatalystGate.pass===true,fundamentals:!research.stageErrors.FUNDAMENTAL_ANALYSIS,valuation:Number(research.fundamentals.metrics?.peNormalizedAnnual)>0,liquid:technical.averageDollarVolume>=2_000_000,concentrated:positionRoom===0});
 const reasons:string[]=[];if(longTerm&&(!risk.effective.longTermEnabled||risk.effective.combinedRiskBps<=0)){modeledShares=0;reasons.push('Long-term entries disabled by account risk policy');}if(!research.marketFresh)reasons.push('Stale underlying quote');if(!technical.complete)reasons.push('Technical evidence incomplete');if(technical.direction!=='CALL')reasons.push('No confirmed long-entry expectation');if(!shareCatalystGate.pass)reasons.push('News/catalyst risk not cleared');if(!modeledShares)reasons.push(cash<=0?'Cash is reserved under account policy':!fractional&&plannedEntry>cash?`Whole-share minimum ${plannedEntry.toFixed(2)} exceeds investable cash ${cash.toFixed(2)}`:'Position or risk capacity insufficient');if(!longTerm&&(expectancy.score==null||expectancy.score<=0))reasons.push('Non-positive or unavailable modeled expectancy');if(!longTerm&&(expectancy.rewardRisk||0)<risk.effective.minimumRewardRisk)reasons.push('Reward/risk below account requirement');
 if(technical.atr&&technical.sma20&&price-technical.sma20>3*technical.atr)reasons.push('Overextended beyond three ATR above the 20-session average');
 if(longTerm&&allocation&&allocation.gap<=0)reasons.push('Allocation category is at or above target; direct contributions elsewhere');
 if(settings?.strategy_type==='OPTIONS')reasons.push('Options strategy: evaluate contracts in Options Analysis; stock purchase is not authorized by this research');
 const missing=Object.keys(research.stageErrors);if(missing.length)reasons.push('Missing evidence: '+missing.join(', '));
 const decision=owned>0?(positionRoom===0?'HOLD / STOP ADDING':technical.direction==='PUT'&&!missing.length?'REVIEW TRIM':!reasons.length?'PREPARE ADD':'HOLD'):!reasons.length?'PREPARE BUY':technical.direction==='CALL'&&!missing.length?'PREPARE':'HOLD CASH';
 const closeWindow=sessionWindow(Date.now()),closeDate=closeWindow.close?exchangeDay(closeWindow.close).date:null;
 const bars=(research.bars||[]) as Row[],lastClose=bars.filter(b=>closeDate&&exchangeDay(b.time).date<=closeDate).at(-1);
 const cycleEvidence=body.cycleId?(await db.prepare('SELECT evidence_json FROM next_session_edges WHERE cycle_id=? AND symbol=?').bind(body.cycleId,symbol).all<Row>()).results.map(r=>r.evidence_json):[];
 const output={symbol,decision,quoteFresh:research.marketFresh,requiredRewardRisk:longTerm?null:risk.effective.minimumRewardRisk,maxEntryWithoutExtension:technical.atr&&technical.sma20?technical.sma20+3*technical.atr:null,positionRoom,tradeRiskBudget:risk.value*risk.effective.swingRiskBps/10000,shareCapacity:modeledShares,policyReserve:Math.min(risk.cash,risk.value*risk.effective.cashReserveBps/10000),lifecycleReserve:Number(reserved?.amount||0),evidence:research.evidence,benchmarkClassification:research.benchmarkClassification,rankingBasis:longTerm?'Allocation need, business quality and valuation':'Modeled directional expectancy',rankingScore:longTerm?allocationRank:expectancy.score,accountId,allocation,goal:settings?.goal_name,horizonMonths:settings?.horizon_months,strategy:settings?.strategy_type,cycleId:body.cycleId||null,discoveredBy:cycleEvidence.length?'Material event relationship plus independent price/liquidity screen':'Broad-market price/liquidity and technical scan',macroEvidence:cycleEvidence,lastRegularClose:lastClose?.close??null,lastRegularCloseAsOf:lastClose?.time??null,extendedPrice:research.quote.priceBasis==='LATEST_TRADE'?price:null,estimatedCashRemaining:Math.max(0,risk.cash-modeledShares*plannedEntry),maximumPlannedLoss:modeledShares*loss,asOf:research.asOf,analyzedAt:new Date().toISOString(),expectation:technical.expectation,confidence:Math.max(0,technical.confidence-missing.length*10),confidenceBasis:technical.confidenceBasis,price,trigger:technical.trigger,confirmation:'Reclaim/hold the trigger with volume confirmation, fresh quotes, cleared catalyst risk and final sector/open-risk checks',entryType:'Conditional limit after confirmation',shares:modeledShares,sharesAreConditional:true,totalCost:modeledShares*plannedEntry,stop:technical.invalidation,targets:technical.atr?(technical.direction==='PUT'?[price-3*technical.atr,price-4.5*technical.atr]:[price+3*technical.atr,price+4.5*technical.atr]):[],holdingPeriod:longTerm?String(settings?.horizon_months||60)+' months - '+(settings?.goal_name||'Long-term goal'):risk.effective.maxSwingDays+' days',rewardRisk:expectancy.rewardRisk,expectancy,reason:reasons.join('; ')||'Directional setup passes initial research; execution confirmation still required',evidenceFor:technical.evidence,evidenceAgainst:reasons,cancelConditions:['Thesis or catalyst risk changes','Price breaks invalidation','Cash, concentration or risk capacity changes','Quote or confirmation expires'],minimumCash:plannedEntry>0?fractional?Math.ceil(plannedEntry/10000*100)/100:plannedEntry:null,availableCash:risk.cash,investableCash:cash,reservedCash:Math.min(risk.cash,reserve),fractional,ownedShares:owned,stockAverageCost:owned&&held?.basis!=null?Number(held.basis)/100/owned:null,executionReady:false,mandatoryConfirmation:['Sector concentration and combined open-risk capacity must be verified by the central execution engine'],stageErrors:research.stageErrors};
 await db.prepare("UPDATE account_search_candidates SET status=?,decision_json=?::jsonb,rank_score=?,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE run_id=? AND symbol=?").bind(missing.length?'PARTIAL':'COMPLETE',JSON.stringify(output),Number(longTerm?allocationRank:expectancy.score??-100),missing.join('; ')||null,runId,symbol).run();
 const counts=await db.prepare("SELECT count(*)::int shortlisted,count(*) FILTER(WHERE status IN ('COMPLETE','PARTIAL'))::int deep_researched,count(*) FILTER(WHERE status='FAILED')::int failed,count(*) FILTER(WHERE status='PARTIAL')::int partial,count(*) FILTER(WHERE status IN ('QUEUED','RUNNING'))::int pending FROM account_search_candidates WHERE run_id=?").bind(runId).first<Row>();
 await db.prepare("UPDATE account_search_runs SET counts_json=counts_json||?::jsonb,status=?,stage=?,completed_at=CASE WHEN ?=0 THEN CURRENT_TIMESTAMP ELSE NULL END WHERE id=?").bind(JSON.stringify({deepResearched:counts?.deep_researched,failed:counts?.failed,partial:counts?.partial,pending:counts?.pending}),counts?.pending?'RUNNING':counts?.partial||counts?.failed?'PARTIAL':'RESEARCHED',counts?.pending?'DEEP_RESEARCH':'COMPARE_ALTERNATIVES',counts?.pending||0,runId).run();
 if(settings?.strategy_type!=='OPTIONS'&&technical.direction==='CALL'&&modeledShares>0&&!reasons.length)await db.prepare("INSERT INTO background_jobs(id,household_id,job_type,idempotency_key,payload_json) VALUES(?,?,'AI_EVENT_REVIEW',?,?::jsonb) ON CONFLICT DO NOTHING").bind(id('confirm_opportunity'),householdId,'confirm:'+runId+':'+symbol,JSON.stringify({accountId,symbol,reason:'RANKED_ACCOUNT_SEARCH'})).run();
 return {partial:missing.length>0};
}
export async function accountSearchStatus(db:PostgresDatabase,householdId:string,accountId:string){
 const run=await db.prepare('SELECT * FROM account_search_runs WHERE household_id=? AND account_id=? ORDER BY created_at DESC LIMIT 1').bind(householdId,accountId).first<Row>();if(!run)return null;
 const candidates=(await db.prepare("SELECT symbol,status,rank_score,decision_json,last_error,updated_at FROM account_search_candidates WHERE run_id=? ORDER BY rank_score DESC,symbol").bind(run.id).all<Row>()).results;
 const previous=await db.prepare("SELECT completed_at FROM account_search_runs WHERE account_id=? AND completed_at IS NOT NULL ORDER BY completed_at DESC LIMIT 1").bind(accountId).first<Row>();
 const saved=(await db.prepare("SELECT * FROM (SELECT DISTINCT ON(c.symbol) c.symbol,c.status,c.rank_score,c.decision_json,c.last_error,c.updated_at FROM account_search_candidates c JOIN account_search_runs r ON r.id=c.run_id WHERE r.account_id=? AND r.id<>? AND c.decision_json->>'symbol' IS NOT NULL ORDER BY c.symbol,r.created_at DESC) saved ORDER BY CASE WHEN symbol=ANY(?::text[]) THEN 0 ELSE 1 END,updated_at DESC LIMIT 72").bind(accountId,run.id,candidates.map(c=>c.symbol)).all<Row>()).results;
 for(const row of saved){const current=candidates.find(c=>c.symbol===row.symbol);const previous={...row.decision_json,shares:0,executionReady:false,stageErrors:{...row.decision_json.stageErrors,revalidation:'Saved result; fresh research pending'}};
 if(current?.decision_json?.symbol){if(current.status!=='COMPLETE')current.lastValidDecision=previous;continue;}
 if(current)Object.assign(current,{...row,status:'SAVED - REVALIDATION REQUIRED',decision_json:previous});
 else if(candidates.filter(c=>c.decision_json?.symbol).length<24)candidates.push({...row,status:'SAVED - REVALIDATION REQUIRED',decision_json:previous});
 }

 const identities=(await db.prepare("SELECT q.symbol,COALESCE(NULLIF(q.asset_json->>'name',''),NULLIF(p.payload_json->'fundamentals'->'profile'->>'name','')) AS company_name FROM discovery_queue q LEFT JOIN discovery_provider_cache p ON p.cache_key='research-v2:'||q.symbol WHERE q.symbol=ANY(?::text[])").bind(candidates.map(c=>c.symbol)).all<Row>()).results;
 for(const candidate of candidates){candidate.companyName=candidate.decision_json?.companyName||identities.find(i=>i.symbol===candidate.symbol)?.company_name||null;}
 return {...run,lastCompletedAt:previous?.completed_at,candidates,wholeShareCashBlocked:candidates.some(c=>c.decision_json.price>0&&!c.decision_json.fractional)&&candidates.filter(c=>c.decision_json.price>0&&!c.decision_json.fractional).every(c=>c.decision_json.minimumCash>c.decision_json.investableCash)};
}
