import type {EntryPlan} from "@/lib/entry-plan";
import {type PostgresDatabase} from "@/lib/db";
import {runCentralDecision} from "@/lib/ai-decision-core";
import type {AIProvider} from "@/lib/ai-provider";
export type DecisionAction="BUY_NOW"|"SELL_NOW"|"BUY_IF"|"SELL_IF"|"HOLD"|"TRIM"|"ADD"|"WATCH"|"NO_ACTION"|"WAIT"|"INSUFFICIENT_CONFIRMATION"|"REBUY_IF"|"ROTATE_CAPITAL";
export type DecisionStrategy="SWING_SHARES"|"LONG_TERM_SHARES"|"OPTIONS"|"DISCOVERY"|"TACTICAL_REBUY"|"NEXT_DAY_OUTLOOK"|"PORTFOLIO_RISK";
export type EvidenceItem={label:string;value:unknown;sourceType:"PROVIDER"|"CALCULATION"|"USER"|"MODEL_INFERENCE";sourceId?:string;asOf?:string;quality?:"HIGH"|"MEDIUM"|"LOW";conflicts?:string[]};
export type DecisionInput={householdId:string;accountId:string;accountName:string;strategy:DecisionStrategy;ticker:string;requestType:string;features:Record<string,unknown>;evidence:EvidenceItem[];dataTimestamp:string;requiredFacts:string[];conflicts?:string[];candidates?:DecisionCandidate[]};
export type Scenario={probability:number;priceZone:string;confirmation:string;invalidation:string};
export type DecisionOutput={returnEstimate?:{horizonDays:number;expectedReturn:number;downside:number;price:number;asOf:string};entryPlan?:EntryPlan;action:DecisionAction;ticker:string;accountId:string;strategy:DecisionStrategy;shares:number;entry:number|null;trigger:number|null;stop:number|null;targets:number[];confidence:number;confidenceBand:"LOW"|"MEDIUM"|"HIGH"|"VERY_HIGH";bull:Scenario;base:Scenario;bear:Scenario;reasoningFactors:string[];contradictingEvidence:string[];historicalSimilarity:string;interpretation:string;invalidation:string;risk:string;expectedCostProceeds:number|null;whatWouldChange:string[];dataTimestamp:string;dataQuality:number;providerFacts:string[];modelInferences:string[];modelVersion:string;strategyVersion:string;decisionId?:string;snapshotId?:string;schemaVersion?:string;providerStatus?:string;cashBefore?:number|null;cashAfter?:number|null;thesisStatus?:string;sellReason?:string|null;reentryPlan?:unknown;evidenceSources?:EvidenceItem[];instrument?:string;contractSymbol?:string;candidateId?:string;executionAllowed?:false;deterministicCandidates?:DecisionCandidate[]};
export type DecisionModelAdapter=(input:Readonly<DecisionInput>,quality:Readonly<DataQuality>)=>Promise<DecisionOutput>;
type DataQuality={score:number;missing:string[];stale:string[];conflicts:string[]};
const ageMinutes=(iso:string)=>Math.max(0,(Date.now()-Date.parse(iso))/60000);
export function assessDecisionData(input:DecisionInput):DataQuality{const labels=new Set(input.evidence.filter(e=>e.value!==null&&e.value!==undefined&&e.value!=="").map(e=>e.label)),missing=input.requiredFacts.filter(x=>!labels.has(x)),stale=input.evidence.filter(e=>e.asOf&&ageMinutes(e.asOf)>((input.strategy==="SWING_SHARES"||input.strategy==="OPTIONS")?20:1440)).map(e=>e.label),conflicts=[...(input.conflicts||[]),...input.evidence.flatMap(e=>e.conflicts||[])],score=Math.max(0,100-missing.length*14-stale.length*8-conflicts.length*10);return{score,missing,stale,conflicts}}
const scenario=(probability:number):Scenario=>({probability,priceZone:"Not modeled",confirmation:"Fresh independent evidence required",invalidation:"Missing, stale, or conflicting evidence"});
export function safeDecision(input:DecisionInput,q:DataQuality,modelVersion:string,strategyVersion:string):DecisionOutput{return{action:q.score<55?"INSUFFICIENT_CONFIRMATION":"WAIT",ticker:input.ticker,accountId:input.accountId,strategy:input.strategy,shares:0,entry:null,trigger:null,stop:null,targets:[],confidence:Math.min(45,q.score),confidenceBand:"LOW",bull:scenario(0),base:{...scenario(0),priceZone:"No trade"},bear:scenario(0),reasoningFactors:[`Data-quality gate: ${q.score}/100`,...q.missing.map(x=>`Missing ${x}`),...q.stale.map(x=>`Stale ${x}`)],contradictingEvidence:q.conflicts,historicalSimilarity:"Not evaluated without a complete point-in-time feature snapshot.",interpretation:"Northstar will not force an action without complete evidence and an approved model adapter.",invalidation:"Re-evaluate after fresh provider data and independent confirmation are available.",risk:"Acting now could rely on missing or stale facts.",expectedCostProceeds:null,whatWouldChange:["Refresh required provider data","Resolve conflicting evidence","Run an approved versioned model adapter"],dataTimestamp:input.dataTimestamp,dataQuality:q.score,providerFacts:input.evidence.filter(e=>e.sourceType!=="MODEL_INFERENCE").map(e=>`${e.label}: ${String(e.value)}`),modelInferences:["No directional model inference released."],modelVersion,strategyVersion}}
export type DecisionCandidate={entryPlan?:EntryPlan;id:string;action:DecisionAction;shares:number;entry:number|null;trigger:number|null;stop:number|null;targets:number[];cost:number;proceeds:number;cashBefore:number;cashAfter:number;thesisStatus:string;sellReason:string|null;reentryPlan:unknown;instrument:"SHARES"|"CALL"|"PUT"|"NO_TRADE";contractSymbol?:string;eligible:boolean;reason:string};
export async function decideInvestment(input:DecisionInput,options:{db?:PostgresDatabase;persist?:boolean;adapter?:DecisionModelAdapter;aiProvider?:AIProvider}={}):Promise<DecisionOutput>{return runCentralDecision(input,options);}