import {id,type PostgresDatabase} from "@/lib/db";
export type DecisionAction="BUY_NOW"|"SELL_NOW"|"BUY_IF"|"SELL_IF"|"HOLD"|"TRIM"|"ADD"|"WATCH"|"NO_ACTION"|"WAIT"|"INSUFFICIENT_CONFIRMATION";
export type DecisionStrategy="SWING_SHARES"|"LONG_TERM_SHARES"|"OPTIONS"|"DISCOVERY"|"TACTICAL_REBUY"|"NEXT_DAY_OUTLOOK"|"PORTFOLIO_RISK";
export type EvidenceItem={label:string;value:unknown;sourceType:"PROVIDER"|"CALCULATION"|"USER"|"MODEL_INFERENCE";sourceId?:string;asOf?:string;quality?:"HIGH"|"MEDIUM"|"LOW";conflicts?:string[]};
export type DecisionInput={householdId:string;accountId:string;accountName:string;strategy:DecisionStrategy;ticker:string;requestType:string;features:Record<string,unknown>;evidence:EvidenceItem[];dataTimestamp:string;requiredFacts:string[];conflicts?:string[]};
export type Scenario={probability:number;priceZone:string;confirmation:string;invalidation:string};
export type DecisionOutput={action:DecisionAction;ticker:string;accountId:string;strategy:DecisionStrategy;shares:number;entry:number|null;trigger:number|null;stop:number|null;targets:number[];confidence:number;confidenceBand:"LOW"|"MEDIUM"|"HIGH"|"VERY_HIGH";bull:Scenario;base:Scenario;bear:Scenario;reasoningFactors:string[];contradictingEvidence:string[];historicalSimilarity:string;interpretation:string;invalidation:string;risk:string;expectedCostProceeds:number|null;whatWouldChange:string[];dataTimestamp:string;dataQuality:number;providerFacts:string[];modelInferences:string[];modelVersion:string;strategyVersion:string;decisionId?:string};
export type DecisionModelAdapter=(input:Readonly<DecisionInput>,quality:Readonly<DataQuality>)=>Promise<DecisionOutput>;
type DataQuality={score:number;missing:string[];stale:string[];conflicts:string[]};
const ageMinutes=(iso:string)=>Math.max(0,(Date.now()-Date.parse(iso))/60000);
export function assessDecisionData(input:DecisionInput):DataQuality{const labels=new Set(input.evidence.filter(e=>e.value!==null&&e.value!==undefined&&e.value!=="").map(e=>e.label)),missing=input.requiredFacts.filter(x=>!labels.has(x)),stale=input.evidence.filter(e=>e.asOf&&ageMinutes(e.asOf)>((input.strategy==="SWING_SHARES"||input.strategy==="OPTIONS")?20:1440)).map(e=>e.label),conflicts=[...(input.conflicts||[]),...input.evidence.flatMap(e=>e.conflicts||[])],score=Math.max(0,100-missing.length*14-stale.length*8-conflicts.length*10);return{score,missing,stale,conflicts}}
const scenario=(probability:number):Scenario=>({probability,priceZone:"Not modeled",confirmation:"Fresh independent evidence required",invalidation:"Missing, stale, or conflicting evidence"});
const band=(n:number):DecisionOutput["confidenceBand"]=>n>=85?"VERY_HIGH":n>=70?"HIGH":n>=50?"MEDIUM":"LOW";
function safeDecision(input:DecisionInput,q:DataQuality,modelVersion:string,strategyVersion:string):DecisionOutput{return{action:q.score<55?"INSUFFICIENT_CONFIRMATION":"WAIT",ticker:input.ticker,accountId:input.accountId,strategy:input.strategy,shares:0,entry:null,trigger:null,stop:null,targets:[],confidence:Math.min(45,q.score),confidenceBand:"LOW",bull:scenario(25),base:{...scenario(50),priceZone:"No trade"},bear:scenario(25),reasoningFactors:[`Data-quality gate: ${q.score}/100`,...q.missing.map(x=>`Missing ${x}`),...q.stale.map(x=>`Stale ${x}`)],contradictingEvidence:q.conflicts,historicalSimilarity:"Not evaluated without a complete point-in-time feature snapshot.",interpretation:"Northstar will not force an action without complete evidence and an approved model adapter.",invalidation:"Re-evaluate after fresh provider data and independent confirmation are available.",risk:"Acting now could rely on missing or stale facts.",expectedCostProceeds:null,whatWouldChange:["Refresh required provider data","Resolve conflicting evidence","Run an approved versioned model adapter"],dataTimestamp:input.dataTimestamp,dataQuality:q.score,providerFacts:input.evidence.filter(e=>e.sourceType!=="MODEL_INFERENCE").map(e=>`${e.label}: ${String(e.value)}`),modelInferences:["No directional model inference released."],modelVersion,strategyVersion}}
export async function decideInvestment(input:DecisionInput,{db,persist=true,adapter}:{db?:PostgresDatabase;persist?:boolean;adapter?:DecisionModelAdapter}={}):Promise<DecisionOutput>{const q=assessDecisionData(input),modelVersion=process.env.NORTHSTAR_CHAMPION_MODEL_VERSION||"northstar-decision-1.0.0",strategyVersion=process.env.NORTHSTAR_STRATEGY_VERSION||"account-strategy-1.0.0",started=Date.now();let result=safeDecision(input,q,modelVersion,strategyVersion),provider="SAFETY_FALLBACK";if(q.score>=55&&adapter){try{const proposed=await adapter(Object.freeze(input),Object.freeze(q)),raw=Math.max(0,Math.min(100,Number(proposed.confidence)||0)),calibration=await calibrationFactor(db,input.strategy,modelVersion),confidence=Math.round(raw*calibration*q.score/100);result={...proposed,ticker:input.ticker,accountId:input.accountId,strategy:input.strategy,confidence,confidenceBand:band(confidence),dataTimestamp:input.dataTimestamp,dataQuality:q.score,modelVersion,strategyVersion};provider="APPROVED_MODEL_ADAPTER"}catch(error){result.reasoningFactors.push(`Model adapter unavailable: ${error instanceof Error?error.message:"unknown error"}`)}}if(result.bull.probability+result.base.probability+result.bear.probability!==100)result={...safeDecision(input,q,modelVersion,strategyVersion),interpretation:"Scenario probabilities were invalid; no action released."};if(persist&&db){const decisionId=id("decision");await db.prepare("INSERT INTO ai_decision_runs(id,household_id,account_id,ticker,strategy,request_type,input_snapshot_json,evidence_json,output_json,data_quality,model_version,strategy_version,provider,status,latency_ms,data_timestamp) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'COMPLETED',?,?)").bind(decisionId,input.householdId,input.accountId,input.ticker,input.strategy,input.requestType,JSON.stringify(input.features),JSON.stringify(input.evidence),JSON.stringify(result),q.score,modelVersion,strategyVersion,provider,Date.now()-started,input.dataTimestamp).run();result.decisionId=decisionId}return result}
async function calibrationFactor(db:PostgresDatabase|undefined,strategy:string,version:string){if(!db)return .85;try{const row=await db.prepare("SELECT calibration_factor FROM ai_model_versions WHERE version=? AND strategy=? AND status='CHAMPION'").bind(version,strategy).first<{calibration_factor:string|number}>();return Math.max(.5,Math.min(1,Number(row?.calibration_factor||.85)))}catch{return .85}}
