/** Dollar amounts; returns are fractions over the same explicitly stated horizon. */
export type RotationEvidence={ticker:string;price:number;asOf:string;horizonDays:number;expectedReturn:number;downside:number;thesisValid:boolean;valuationValid:boolean;accountFit:boolean;modelVersion:string;strategyVersion:string};
export type RotationInput={original:RotationEvidence|null;replacement:RotationEvidence|null;sharesOwned:number;sharesToSell:number;averageCost:number|null;cash:number;taxRate:number|null;slippageBps:number|null;commission:number|null;riskBudget:number|null;positionCapacity:number|null;cashReserve:number;saleConfirmed:boolean;entryConfirmed:boolean;orderPrice:number|null;stop:number|null;targets:number[];confirmedBuyShares:number|null;rebuyPlan:unknown;now?:number};
export function compareRotation(input:RotationInput){
 const now=input.now??Date.now(),a=input.original,b=input.replacement,missing:string[]=[];
 const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v);
 const valid=(v:RotationEvidence|null)=>v&&v.price>0&&finite(v.price)&&finite(v.expectedReturn)&&finite(v.downside)&&v.downside>0&&v.horizonDays>0&&v.modelVersion&&v.strategyVersion&&Number.isFinite(Date.parse(v.asOf))&&now-Date.parse(v.asOf)>=0&&now-Date.parse(v.asOf)<=5*60000;
 if(!valid(a)||!valid(b))missing.push('Fresh, versioned return/downside estimates with an explicit comparison horizon are required for both stocks.');
 if(a&&b&&(a.horizonDays!==b.horizonDays||a.strategyVersion!==b.strategyVersion||a.modelVersion!==b.modelVersion))missing.push('Compare the same horizon, model and strategy version.');
 if(!finite(input.averageCost)||input.averageCost<0)missing.push('Verified purchase cost is required.');
 if(!finite(input.taxRate)||input.taxRate<0||input.taxRate>1)missing.push('Configure the applicable sale tax estimate (explicit zero for a tax-exempt account).');
 if(!finite(input.slippageBps)||input.slippageBps<0||!finite(input.commission)||input.commission<0)missing.push('Verified spread/slippage and transaction cost estimates are required.');
 if(!finite(input.riskBudget)||input.riskBudget<0||!finite(input.positionCapacity)||input.positionCapacity<0||!finite(input.cash)||input.cash<0||!finite(input.cashReserve)||input.cashReserve<0)missing.push('Current account cash, remaining risk and concentration capacity are required.');
 if(!finite(input.sharesToSell)||input.sharesToSell<=0||input.sharesToSell>input.sharesOwned)missing.push('A valid position-specific sale quantity is required.');
 const base={version:'rotation-review-1',executionAllowed:false as const,alternatives:['HOLD','REBUY_LATER','ROTATE'] as const,rebuyPlan:input.rebuyPlan,asOf:new Date(now).toISOString()};
 if(missing.length)return{...base,status:'INSUFFICIENT_DATA',action:'HOLD',reasons:missing,proposal:null};
 if(a!.ticker===b!.ticker||!b!.thesisValid||!b!.valuationValid||!b!.accountFit)return{...base,status:'NO_ADVANTAGE',action:'HOLD',reasons:['Replacement thesis, valuation or account fit does not pass.'],proposal:null};
 const proceeds=input.sharesToSell*a!.price,tax=Math.max(0,input.sharesToSell*(a!.price-input.averageCost!))*input.taxRate!,saleCosts=proceeds*input.slippageBps!/10000+input.commission!,netProceeds=proceeds-tax-saleCosts;
 const friction=(tax+saleCosts+proceeds*input.slippageBps!/10000+input.commission!)/proceeds;
 const plan=input.rebuyPlan as {high?:number;invalidation?:number;expiresAt?:string}|null;
 const rebuyScore=plan&&finite(plan.high)&&finite(plan.invalidation)&&plan.high>plan.invalidation&&plan.invalidation>0&&Date.parse(plan.expiresAt||'')>now?((a!.price*(1+a!.expectedReturn)/plan.high-1)-friction)/((plan.high-plan.invalidation)/plan.high):null;
 const holdScore=a!.expectedReturn/a!.downside,rotationScore=(b!.expectedReturn-friction)/b!.downside,advantage=rotationScore-Math.max(holdScore,rebuyScore??-Infinity);
 if(advantage<.25||b!.expectedReturn-friction<=Math.max(0,a!.expectedReturn))return{...base,status:'NO_ADVANTAGE',action:'HOLD',reasons:['Replacement does not materially beat HOLD after estimated taxes and costs.'],holdScore,rebuyScore,rotationScore,proposal:null};
 if(!input.saleConfirmed||!input.entryConfirmed||!finite(input.orderPrice)||input.orderPrice<=0||!finite(input.stop)||input.stop<=0||input.stop>=input.orderPrice||!input.targets.length||input.targets.some(x=>!finite(x)||x<=input.orderPrice!)||!finite(input.confirmedBuyShares)||input.confirmedBuyShares<=0)return{...base,status:'MONITOR',action:'HOLD',reasons:['Potential rotation advantage; wait for a confirmed sale and separate confirmed replacement order, stop and targets.'],holdScore,rebuyScore,rotationScore,proposal:null};
 const available=Math.max(0,input.cash+netProceeds-input.cashReserve-input.commission!),buyUnit=input.orderPrice*(1+input.slippageBps!/10000),shares=Math.max(0,Math.floor(Math.min(available/buyUnit,input.positionCapacity!/input.orderPrice,input.riskBudget!/(input.orderPrice-input.stop),input.confirmedBuyShares))),cost=shares*buyUnit+input.commission!;
 if(!shares)return{...base,status:'RISK_BLOCKED',action:'HOLD',reasons:['No replacement shares fit available cash, position capacity and remaining risk.'],holdScore,rebuyScore,rotationScore,proposal:null};
 const cents=(n:number)=>Math.round(n*100)/100;
 return{...base,status:'REVIEW_READY',action:'ROTATE_CAPITAL',reasons:['Material estimated advantage after costs; revalidate both legs before user-confirmed execution.'],holdScore,rebuyScore,rotationScore,proposal:{sellTicker:a!.ticker,buyTicker:b!.ticker,sellShares:input.sharesToSell,sellReferencePrice:a!.price,estimatedProceeds:cents(proceeds),estimatedTax:cents(tax),estimatedRealizedPL:cents(input.sharesToSell*(a!.price-input.averageCost!)),remainingShares:input.sharesOwned-input.sharesToSell,buyShares:shares,orderType:'LIMIT',orderPrice:input.orderPrice,stop:input.stop,targets:input.targets,estimatedCost:cents(cost),cashBefore:input.cash,cashAfterSale:cents(input.cash+netProceeds),cashAfter:cents(input.cash+netProceeds-cost),cancelConditions:['Cancel if either confirmation fails or evidence expires','Cancel if thesis, account cash, risk or tax estimate changes','Do not buy the replacement before sale proceeds are available']}};
}
