import {id,type PostgresDatabase} from '@/lib/db';
import {compareRotation,type RotationEvidence} from '@/lib/capital-rotation-review';
import {entryOrderReady} from '@/lib/entry-plan';
import {saleReadiness} from '@/lib/sale-readiness';
import {rankCandidatesForAccount} from '@/lib/account-candidate-ranking';
const json=(v:any)=>typeof v==='string'?JSON.parse(v):v||{};
const numeric=(v:any)=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?Number(v):null;
function evidence(row:any):RotationEvidence|null{
 const checks=json(row?.checks_json),ai=checks.aiEvidence,estimate=ai?.returnEstimate;
 if(!estimate||ai.providerStatus!=='AVAILABLE'||Date.parse(row.expires_at)<=Date.now())return null;
 return{...estimate,ticker:row.ticker,modelVersion:ai.modelVersion,strategyVersion:ai.strategyVersion,thesisValid:['VALID','INTACT','STRONG'].includes(ai.thesisStatus),valuationValid:Number(checks.fundamentalThesis?.valuationAttractiveness)>=55,accountFit:checks.portfolioFit?.state==='GOOD'};
}
/** This uses persisted central decisions; ranking alone never authorizes a sale. */
export async function reviewAccountRotation(db:PostgresDatabase,householdId:string,accountId:string){
 const account=await db.prepare(`SELECT a.id,COALESCE(s.available_cash_cents,a.available_balance_cents) cash_cents,s.policy_json FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=?`).bind(accountId,householdId).first<any>();if(!account)throw Error('ACCOUNT_NOT_FOUND');
 const all=(await db.prepare(`SELECT * FROM market_discovery_candidates WHERE status<>'REJECTED' AND last_detected_at>CURRENT_TIMESTAMP-INTERVAL '2 days' ORDER BY discovery_confidence DESC LIMIT 160`).all<any>()).results;
 const ranked=await rankCandidatesForAccount(db,householdId,accountId,all),shortlist=(ranked.candidates as any[]).filter(x=>x.existing_weight===0&&x.portfolio_fit>=55).slice(0,3),cycle=new Date().toISOString().slice(0,13);
 for(const candidate of shortlist)await db.prepare(`INSERT INTO background_jobs(id,household_id,job_type,idempotency_key,payload_json) SELECT ?,?,'AI_EVENT_REVIEW',?,?::jsonb WHERE NOT EXISTS(SELECT 1 FROM background_jobs WHERE job_type='AI_EVENT_REVIEW' AND status IN ('QUEUED','RUNNING','FAILED') AND payload_json->>'accountId'=? AND payload_json->>'symbol'=?) ON CONFLICT(idempotency_key) DO NOTHING`).bind(id('rotation_research'),householdId,`rotation-research:${accountId}:${candidate.symbol}:${cycle}`,JSON.stringify({accountId,symbol:candidate.symbol,reason:'CAPITAL_ROTATION_COMPARISON'}),accountId,candidate.symbol).run();
 const recs=(await db.prepare(`SELECT DISTINCT ON(s.ticker) r.*,s.ticker FROM recommendations r JOIN securities s ON s.id=r.security_id WHERE r.account_id=? AND r.household_id=? ORDER BY s.ticker,r.created_at DESC`).bind(accountId,householdId).all<any>()).results;
 const holdings=(await db.prepare(`SELECT s.ticker,SUM(h.quantity)::float8 shares,SUM(h.cost_basis_cents)::float8 basis,COUNT(*) FILTER(WHERE h.cost_basis_cents IS NULL)::int missing_basis FROM holdings h JOIN securities s ON s.id=h.security_id WHERE h.account_id=? AND h.quantity>0 AND s.ticker IS NOT NULL GROUP BY s.ticker`).bind(accountId).all<any>()).results;
 const policy=json(account.policy_json),reviews=[];
 const sectors=(await db.prepare("SELECT s.ticker,d.sector,SUM(h.quantity*h.price_cents)/100 value FROM holdings h JOIN securities s ON s.id=h.security_id LEFT JOIN market_discovery_candidates d ON d.symbol=s.ticker WHERE h.account_id=? AND h.quantity>0 GROUP BY s.ticker,d.sector").bind(accountId).all<any>()).results;
 const open=(await db.prepare("SELECT s.ticker,state_json->>'shares' shares,state_json->>'currentPrice' current_price,state_json->>'stop' stop FROM position_states p JOIN securities s ON s.id=p.security_id WHERE account_id=? AND (state_json->>'shares')::numeric>0").bind(accountId).all<any>()).results;
 const knownRisk=holdings.every(h=>open.some(x=>x.ticker===h.ticker))&&open.every(x=>numeric(x.stop)!==null&&Number(x.stop)>0&&numeric(x.current_price)!==null);
 const openRisk=knownRisk?open.reduce((sum,x)=>sum+Number(x.shares)*Math.max(0,Number(x.current_price)-Number(x.stop)),0):null;

 for(const holding of holdings){const original=recs.find(x=>x.ticker===holding.ticker),sale=saleReadiness(original),checks=json(original?.checks_json),risk=checks.researchSnapshot?.accountRisk,portfolio=checks.researchSnapshot?.position;
 const choices=shortlist.map(candidate=>{const replacement=recs.find(x=>x.ticker===candidate.symbol),entry=json(replacement?.checks_json).aiEvidence?.entryPlan,capacity=json(replacement?.checks_json).researchSnapshot?.accountRisk;
 const input={original:evidence(original),replacement:evidence(replacement),sharesOwned:holding.shares,sharesToSell:sale.shares||Math.floor(holding.shares*.25),averageCost:holding.missing_basis?null:holding.basis/100/holding.shares,cash:numeric(account.cash_cents)===null?NaN:Number(account.cash_cents)/100,taxRate:numeric(policy.taxRatePct)===null?null:Number(policy.taxRatePct)/100,slippageBps:numeric(policy.slippageBps),commission:numeric(policy.commissionCents)===null?null:Number(policy.commissionCents)/100,riskBudget:openRisk!==null&&capacity?.value&&policy.tradingPolicy?.combinedRiskBps?Math.max(0,Math.min(capacity.value*capacity.maxRiskBps/10000,capacity.value*policy.tradingPolicy.combinedRiskBps/10000-openRisk)):null,positionCapacity:capacity?.value&&capacity?.maxPositionBps&&candidate.sector&&sectors.every(x=>x.sector&&numeric(x.value)!==null)&&policy.tradingPolicy?.maxSectorBps?Math.max(0,Math.min(capacity.value*capacity.maxPositionBps/10000,capacity.value*policy.tradingPolicy.maxSectorBps/10000-sectors.filter(x=>x.sector===candidate.sector).reduce((sum,x)=>sum+Number(x.value),0))):null,cashReserve:numeric(risk?.reservedElsewhere)!==null&&policy.tradingPolicy?Number(risk.reservedElsewhere)+Number(risk.value)*Number(policy.tradingPolicy.cashReserveBps)/10000:NaN,saleConfirmed:sale.ready,entryConfirmed:replacement?.actionable===true&&entryOrderReady(entry),orderPrice:entry?.orderPrice??null,stop:entry?.stopAfterEntry??null,targets:entry?.targets||[],confirmedBuyShares:entry?.shares??null,rebuyPlan:sale.audit?.reentry||null};
 return{ticker:candidate.symbol,rank:candidate.account_rank_score,comparison:compareRotation(input),input,decisionIds:{original:original?.id||null,replacement:replacement?.id||null}};});
 choices.sort((a,b)=>(('rotationScore' in b.comparison?b.comparison.rotationScore:undefined)??-Infinity)-(('rotationScore' in a.comparison? a.comparison.rotationScore:undefined)??-Infinity));
 const result={ticker:holding.ticker,accountId,shares:holding.shares,status:choices[0]?.comparison.status||'RESEARCH_PENDING',action:choices[0]?.comparison.action||'HOLD',reason:choices.length?choices[0].comparison.reasons.join(' '):'No fresh account-fitting replacement has completed discovery. Keep monitoring existing exposure.',choices,asOf:new Date().toISOString(),executionAllowed:false};
 await db.prepare(`INSERT INTO rotation_reviews(id,household_id,account_id,ticker,cycle_key,snapshot_json) VALUES(?,?,?,?,?,?::jsonb) ON CONFLICT(account_id,ticker,cycle_key) DO NOTHING`).bind(id('rotation_review'),householdId,accountId,holding.ticker,new Date().toISOString().slice(0,16),JSON.stringify(result)).run();reviews.push(result);}
 return reviews;
}
export async function rotationView(db:PostgresDatabase,householdId:string,accountId:string){return (await db.prepare(`SELECT DISTINCT ON(ticker) snapshot_json,outcome_json,created_at FROM rotation_reviews WHERE household_id=? AND account_id=? ORDER BY ticker,created_at DESC`).bind(householdId,accountId).all<any>()).results.map(x=>({...json(x.snapshot_json),outcome:x.outcome_json}));}
import {marketDataProvider} from '@/lib/providers/alpaca-market-data';
/** Paper evaluation is kept separate from execution-attributed lifecycle outcomes. */
export async function measureRotationReviews(db:PostgresDatabase,householdId:string,accountId:string){
 const rows=(await db.prepare(`SELECT id,snapshot_json FROM rotation_reviews WHERE household_id=? AND account_id=? AND outcome_json IS NULL AND snapshot_json->>'status'='REVIEW_READY' AND created_at<CURRENT_TIMESTAMP-INTERVAL '1 day' ORDER BY created_at LIMIT 2`).bind(householdId,accountId).all<any>()).results;
 for(const row of rows){const review=json(row.snapshot_json),choice=review.choices?.[0],p=choice?.comparison?.proposal,input=choice?.input;if(!p||!input?.original||Date.now()-Date.parse(review.asOf)<input.original.horizonDays*86400000)continue;
 const quotes=await marketDataProvider().getQuotes([p.sellTicker,p.buyTicker]),sell=quotes.quotes[p.sellTicker],buy=quotes.quotes[p.buyTicker];if(!sell?.last||!buy?.last||sell.freshness!=='FRESH'||buy.freshness!=='FRESH'||!sell.timestamp||!buy.timestamp||Date.parse(sell.timestamp)<=Date.parse(review.asOf)||Date.parse(buy.timestamp)<=Date.parse(review.asOf))continue;
 const holdValue=input.cash+p.sellShares*Number(sell.last),rotationValue=p.cashAfter+p.buyShares*Number(buy.last),outcome={kind:'HYPOTHETICAL_LIMIT_FILLS',holdValue,rotationValue,excessVsHold:rotationValue-holdValue,asOf:quotes.asOf,source:quotes.feed,note:'Paper comparison assuming both proposed fills; this is not an executed-trade return. Actual sales/rebuys remain tracked by the Trade Lifecycle Engine.',strategyVersion:'rotation-review-1'};
 await db.prepare('UPDATE rotation_reviews SET outcome_json=?::jsonb WHERE id=? AND outcome_json IS NULL').bind(JSON.stringify(outcome),row.id).run();
 }
}

