import {id,type PostgresDatabase} from "@/lib/db";
import {decideInvestment,type DecisionStrategy} from "@/lib/ai-investment-decision-engine";
import {marketDataProvider} from "@/lib/providers/alpaca-market-data";
import {refreshInvestmentNotificationCoverage} from "@/lib/investment-notification-coverage";

const parse=(value:unknown)=>{if(value&&typeof value==='object')return value as Record<string,any>;try{return JSON.parse(String(value||'{}'))}catch{return{}}};
const decisionStrategy=(strategy:string):DecisionStrategy=>/SWING/i.test(strategy)?'SWING_SHARES':/OPTION/i.test(strategy)?'OPTIONS':'LONG_TERM_SHARES';
const stage=async(db:PostgresDatabase,runId:string,name:string,status:string,input=0,output=0,evidence:Record<string,unknown>={},error:string|null=null)=>db.prepare(`INSERT INTO intelligence_loop_stages(id,run_id,stage,status,input_count,output_count,evidence_json,error_code,completed_at) VALUES(?,?,?,?,?,?,?,?,CASE WHEN ? IN ('SUCCEEDED','SKIPPED','DEGRADED','FAILED') THEN CURRENT_TIMESTAMP END) ON CONFLICT(run_id,stage) DO UPDATE SET status=EXCLUDED.status,input_count=EXCLUDED.input_count,output_count=EXCLUDED.output_count,evidence_json=EXCLUDED.evidence_json,error_code=EXCLUDED.error_code,completed_at=EXCLUDED.completed_at`).bind(id('loop_stage'),runId,name,status,input,output,JSON.stringify(evidence),error,status).run();

export async function runAccountIntelligenceLoop(db:PostgresDatabase,input:{householdId:string;accountId:string;trigger:string;cycleKey:string}){
 const account=await db.prepare(`SELECT a.id,COALESCE(a.nickname,a.name) account_name,a.current_balance_cents,a.last_investment_sync_at,a.last_provider_update_at,a.investment_sync_status,a.investment_sync_error,COALESCE(s.strategy_type,a.investment_purpose,'UNCONFIGURED') strategy,COALESCE(s.available_cash_cents,a.available_balance_cents,a.current_balance_cents,0) cash_cents,COALESCE(s.risk_profile,'BALANCED') risk_profile,COALESCE(s.maximum_position_bps,1000) maximum_position_bps,COALESCE(s.maximum_risk_bps,50) maximum_risk_bps,s.policy_json FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=? AND a.hidden=0`).bind(input.accountId,input.householdId).first<Record<string,any>>();
 if(!account)throw new Error('INVESTMENT_ACCOUNT_NOT_FOUND');
 const runId=id('intelligence_loop');
 const inserted=await db.prepare(`INSERT INTO intelligence_loop_runs(id,household_id,account_id,strategy,status,trigger,cycle_key) VALUES(?,?,?,?, 'RUNNING',?,?) ON CONFLICT(cycle_key) DO NOTHING RETURNING id`).bind(runId,input.householdId,input.accountId,account.strategy,input.trigger,input.cycleKey).first<{id:string}>();
 if(!inserted)return{deduplicated:true,cycleKey:input.cycleKey};
 try{
  const holdings=(await db.prepare(`SELECT h.id,h.security_id,s.ticker,s.name,s.type security_type,h.quantity::text,h.price_cents::text,h.cost_basis_cents::text,(h.quantity*COALESCE(h.price_cents,0))::bigint::text market_value_cents,h.provider_updated_at FROM holdings h LEFT JOIN securities s ON s.id=h.security_id WHERE h.account_id=? ORDER BY s.ticker`).bind(account.id).all<Record<string,any>>()).results;
  const unmapped=holdings.filter(h=>!h.security_id||!h.ticker).length,syncFreshAt=account.last_provider_update_at||account.last_investment_sync_at,syncStale=!syncFreshAt||Date.now()-new Date(syncFreshAt).getTime()>36*60*60_000;
  await stage(db,runId,'SYNC',account.investment_sync_error?'FAILED':syncStale||unmapped?'DEGRADED':'SUCCEEDED',holdings.length,holdings.length-unmapped,{providerStatus:account.investment_sync_status,lastProviderUpdateAt:syncFreshAt,unmapped},account.investment_sync_error||syncStale?'PROVIDER_DATA_STALE':unmapped?'UNMAPPED_HOLDINGS':null);
  const symbols=[...new Set(holdings.map(h=>String(h.ticker||'').toUpperCase()).filter(Boolean))],provider=marketDataProvider();
  let snapshot:Awaited<ReturnType<typeof provider.getQuotes>>|null=null,providerError:string|null=null;
  try{snapshot=symbols.length?await provider.getQuotes(symbols):null}catch(error){providerError=error instanceof Error?error.message:'MARKET_PROVIDER_FAILED'}
  await stage(db,runId,'ANALYZE',providerError?'FAILED':symbols.length?'SUCCEEDED':'SKIPPED',symbols.length,snapshot?Object.keys(snapshot.quotes).length:0,{provider:snapshot?.feed||null,asOf:snapshot?.asOf||null},providerError);
  const capturedAt=new Date().toISOString(),holdingValue=holdings.reduce((sum,h)=>sum+BigInt(String(h.market_value_cents||0)),0n),basis=holdings.reduce((sum,h)=>sum+BigInt(String(h.cost_basis_cents||0)),0n),cash=BigInt(String(account.cash_cents||0));
  await db.prepare(`INSERT INTO portfolio_snapshots(id,household_id,account_id,captured_at,market_value_cents,cash_cents,cost_basis_cents,realized_pnl_cents,unrealized_pnl_cents,allocation_json,source_freshness_json) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,captured_at) DO NOTHING`).bind(id('portfolio_snapshot'),input.householdId,account.id,capturedAt,holdingValue.toString(),cash.toString(),basis.toString(),'0',(holdingValue-basis).toString(),JSON.stringify({positions:holdings.map(h=>({ticker:h.ticker,valueCents:h.market_value_cents}))}),JSON.stringify({provider:snapshot?.feed||null,asOf:snapshot?.asOf||syncFreshAt,status:providerError?'FAILED':syncStale?'STALE':'CURRENT'})).run();
  let decisions=0,waits=0;
  if(snapshot)for(const holding of holdings.filter(h=>h.ticker)){const symbol=String(holding.ticker).toUpperCase(),quote=snapshot.quotes[symbol],asOf=quote?.timestamp||snapshot.asOf||capturedAt,positionValue=Number(holding.market_value_cents||0),accountValue=Number(holdingValue+cash),weightBps=accountValue>0?Math.round(positionValue/accountValue*10000):0;const result=await decideInvestment({householdId:input.householdId,accountId:account.id,accountName:account.account_name,strategy:decisionStrategy(account.strategy),ticker:symbol,requestType:'CONTINUOUS_ACCOUNT_LOOP',features:{account:{name:account.account_name,strategy:account.strategy,riskProfile:account.risk_profile,cashCents:String(cash),maximumPositionBps:account.maximum_position_bps,maximumRiskBps:account.maximum_risk_bps},position:{quantity:holding.quantity,costBasisCents:holding.cost_basis_cents,marketValueCents:holding.market_value_cents,weightBps},quote},evidence:[{label:'currentPrice',value:quote?.last,sourceType:'PROVIDER',sourceId:quote?.source||snapshot.feed,asOf},{label:'accountCash',value:String(cash),sourceType:'CALCULATION',asOf:capturedAt},{label:'position',value:{quantity:holding.quantity,weightBps,costBasisCents:holding.cost_basis_cents},sourceType:'CALCULATION',asOf:capturedAt},{label:'riskLimit',value:{maximumPositionBps:account.maximum_position_bps,maximumRiskBps:account.maximum_risk_bps},sourceType:'USER',asOf:capturedAt}],dataTimestamp:asOf,requiredFacts:['currentPrice','accountCash','position','riskLimit'],conflicts:providerError?[providerError]:[]},{db,persist:true});decisions++;if(['WAIT','NO_ACTION','INSUFFICIENT_CONFIRMATION'].includes(result.action))waits++}
  await stage(db,runId,'PREDICT',providerError?'DEGRADED':decisions?'SUCCEEDED':'SKIPPED',holdings.length,decisions,{safetyGatedWaits:waits,dataTimestamp:snapshot?.asOf||capturedAt,probabilistic:true},providerError);
  const active=await db.prepare(`SELECT COUNT(*) count,MAX(created_at) last_run FROM recommendations WHERE account_id=? AND lifecycle IN ('MONITORING','TRIGGERED')`).bind(account.id).first<Record<string,any>>();
  await stage(db,runId,'RECOMMEND','SUCCEEDED',decisions,Number(active?.count||0),{activeRecommendations:Number(active?.count||0),lastRecommendationAt:active?.last_run||null,note:'Only evidence-gated stored recommendations remain actionable'});
  const alerts=await db.prepare(`SELECT COUNT(*) count,MAX(NULLIF(created_at::text,'')::timestamptz) last_alert FROM alerts WHERE household_id=? AND evidence_json::jsonb->>'accountId'=? AND NULLIF(created_at::text,'')::timestamptz>CURRENT_TIMESTAMP-INTERVAL '1 day'`).bind(input.householdId,account.id).first<Record<string,any>>();
  await stage(db,runId,'ALERT','SUCCEEDED',Number(active?.count||0),Number(alerts?.count||0),{lastAlertAt:alerts?.last_alert||null,deliveryPipeline:'durable alert_deliveries + background_jobs'});
  const old=(await db.prepare(`SELECT d.id,d.ticker,d.output_json,d.input_snapshot_json,d.data_timestamp FROM ai_decision_runs d LEFT JOIN ai_decision_outcomes o ON o.decision_id=d.id WHERE d.account_id=? AND d.status='COMPLETED' AND o.id IS NULL AND d.data_timestamp<CURRENT_TIMESTAMP-INTERVAL '1 day' ORDER BY d.data_timestamp LIMIT 50`).bind(account.id).all<Record<string,any>>()).results;let measured=0;
  if(snapshot)for(const prior of old){const quote=snapshot.quotes[String(prior.ticker)],price=Number(quote?.last||0),features=parse(prior.input_snapshot_json),previous=Number(features?.quote?.last||0);if(!price||!previous)continue;const output=parse(prior.output_json),returnBps=Math.round((price-previous)/previous*10000),direction=['BUY_NOW','BUY_IF','ADD'].includes(String(output.action))?returnBps>0:['SELL_NOW','SELL_IF','TRIM'].includes(String(output.action))?returnBps<0:null;await db.prepare(`INSERT INTO ai_decision_outcomes(id,decision_id,evaluation_horizon,actual_return_bps,direction_correct,false_positive,outcome_json) VALUES(?,?, 'NEXT_AVAILABLE_REVIEW',?,?,?,?) ON CONFLICT(decision_id) DO NOTHING`).bind(id('decision_outcome'),prior.id,returnBps,direction,direction===false,JSON.stringify({previousPrice:previous,currentPrice:price,asOf:snapshot.asOf,immutable:true})).run();measured++}
  await stage(db,runId,'MEASURE','SUCCEEDED',old.length,measured,{immutableOutcomes:true});
  const model=await db.prepare(`SELECT version,strategy,status,calibration_factor,validation_results_json FROM ai_model_versions WHERE strategy=? ORDER BY CASE status WHEN 'CHAMPION' THEN 0 WHEN 'CHALLENGER' THEN 1 ELSE 2 END,created_at DESC LIMIT 1`).bind(decisionStrategy(account.strategy)).first<Record<string,any>>();
  await stage(db,runId,'LEARN',model?'SUCCEEDED':'SKIPPED',measured,model?1:0,{modelVersion:model?.version||null,status:model?.status||'NO_APPROVED_MODEL',calibrationFactor:model?.calibration_factor||null,policy:'No automatic production mutation'});
  await refreshInvestmentNotificationCoverage(db,input.householdId);
  await stage(db,runId,'REANALYZE','SUCCEEDED',1,1,{nextCycle:'scheduled server-side',accountId:account.id});
  const degraded=Boolean(providerError||account.investment_sync_error||syncStale||unmapped);
  await db.prepare(`UPDATE intelligence_loop_runs SET status=?,data_timestamp=?,model_version=?,strategy_version=?,positions_loaded=?,decisions_created=?,recommendations_evaluated=?,alerts_created=?,outcomes_measured=?,summary_json=?,completed_at=CURRENT_TIMESTAMP WHERE id=?`).bind(degraded?'DEGRADED':'SUCCEEDED',snapshot?.asOf||capturedAt,process.env.NORTHSTAR_CHAMPION_MODEL_VERSION||'northstar-decision-1.0.0',process.env.NORTHSTAR_STRATEGY_VERSION||'account-strategy-1.0.0',holdings.length,decisions,Number(active?.count||0),Number(alerts?.count||0),measured,JSON.stringify({accountName:account.account_name,strategy:account.strategy,provider:snapshot?.feed||null,providerError,syncStale,unmapped}),runId).run();
  return{runId,status:degraded?'DEGRADED':'SUCCEEDED',accountId:account.id,accountName:account.account_name,strategy:account.strategy,positions:holdings.length,decisions,recommendations:Number(active?.count||0),alerts:Number(alerts?.count||0),outcomes:measured};
 }catch(error){const code=String(error instanceof Error?error.message:'INTELLIGENCE_LOOP_FAILED').slice(0,120);await db.prepare(`UPDATE intelligence_loop_runs SET status='FAILED',error_code=?,completed_at=CURRENT_TIMESTAMP WHERE id=?`).bind(code,runId).run();throw error}
}
