import {providerSignal} from './work-budget';
import type {PostgresDatabase} from './db';
export async function discoveryCoverage(db:PostgresDatabase){
 const coverage=await db.prepare(`SELECT count(*) FILTER(WHERE active)::int eligible,count(*) FILTER(WHERE active AND last_screened_at IS NOT NULL)::int screened,count(*) FILTER(WHERE active AND last_researched_at IS NOT NULL)::int researched,count(*) FILTER(WHERE active AND stage='NOT_SCANNED')::int not_scanned,count(*) FILTER(WHERE active AND stage='RESEARCH_PENDING')::int research_pending,count(*) FILTER(WHERE active AND stage='RESEARCH_INCOMPLETE')::int incomplete,count(*) FILTER(WHERE active AND stage='REJECTED')::int rejected,count(*) FILTER(WHERE active AND stage='RESEARCHED')::int researched_candidates,min(last_screened_at) FILTER(WHERE active) oldest_screen,max(last_screened_at) newest_screen FROM discovery_queue`).first<Record<string,any>>();
 const groups=(await db.prepare(`SELECT COALESCE(c.sector,'Unknown') sector,COALESCE(c.cap_bucket,'UNKNOWN') cap_bucket,count(*)::int count FROM market_discovery_candidates c JOIN discovery_queue d USING(symbol) WHERE d.active AND c.model_version='discovery-v5-evidence' GROUP BY 1,2 ORDER BY 3 DESC`).all<Record<string,any>>()).results;
 const total=groups.reduce((n,r)=>n+r.count,0),mega=groups.filter(r=>r.cap_bucket==='MEGA').reduce((n,r)=>n+r.count,0);
 return {...coverage,research_groups:groups,current_evidence_researched:total,discovery_concentration:total<10?'INSUFFICIENT_SAMPLE':mega/total>.7?'REVIEW_REQUIRED':'NO_MEGACAP_CONCENTRATION',mega_share:total?Math.round(100*mega/total):null};
}
export async function registerDiscoveryUniverse(db:PostgresDatabase,assets:any[]){
 await db.transaction(async tx=>{await tx.prepare(`INSERT INTO discovery_queue(symbol,asset_json) SELECT x->>'symbol',x FROM jsonb_array_elements(?::jsonb) x ON CONFLICT(symbol) DO UPDATE SET asset_json=EXCLUDED.asset_json,active=TRUE`).bind(JSON.stringify(assets)).run();await tx.prepare(`UPDATE discovery_queue SET active=FALSE WHERE NOT(symbol=ANY(?::text[]))`).bind(assets.map(x=>x.symbol)).run();await tx.prepare(`INSERT INTO discovery_control(id,refreshed_at) VALUES('directory',CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET refreshed_at=CURRENT_TIMESTAMP`).run()});
}
export async function prioritizeDiscovery(db:PostgresDatabase){
 await db.prepare(`UPDATE discovery_queue SET priority=150 WHERE priority<150 AND symbol IN(SELECT s.ticker FROM holdings h JOIN securities s ON s.id=h.security_id WHERE h.quantity>0)`).run();
 // Watchlist schema is shared by all households; priority never exposes household data.
 await db.prepare(`UPDATE discovery_queue SET priority=120 WHERE priority<120 AND symbol IN(SELECT symbol FROM market_watchlist)`).run();
}
export async function claimDiscovery(db:PostgresDatabase,kind:'SCREEN'|'RESEARCH',limit:number){
 const screen=kind==='SCREEN',due=screen?'next_screen_at':'next_research_at',eligible=screen?'TRUE':"seed_json IS NOT NULL AND stage IN ('RESEARCH_PENDING','RESEARCH_INCOMPLETE')";
 // Reserve half the batch for oldest work so priority symbols cannot starve broad coverage.
 return db.transaction(async tx=>{const picks=await tx.prepare(`SELECT symbol,asset_json,seed_json,priority,last_screened_at FROM discovery_queue WHERE active AND ${eligible} AND ${due}<=CURRENT_TIMESTAMP AND (lease_until IS NULL OR lease_until<CURRENT_TIMESTAMP) ORDER BY CASE WHEN priority>=100 THEN 0 ELSE 1 END,priority DESC,${due},symbol FOR UPDATE SKIP LOCKED LIMIT ?`).bind(Math.ceil(limit/2)).all<any>();const rest=await tx.prepare(`SELECT symbol,asset_json,seed_json,priority,last_screened_at FROM discovery_queue WHERE active AND ${eligible} AND ${due}<=CURRENT_TIMESTAMP AND (lease_until IS NULL OR lease_until<CURRENT_TIMESTAMP) AND NOT(symbol=ANY(?::text[])) ORDER BY ${due},symbol FOR UPDATE SKIP LOCKED LIMIT ?`).bind(picks.results.map(x=>x.symbol),limit-picks.results.length).all<any>();const rows=[...picks.results,...rest.results];if(rows.length)await tx.prepare(`UPDATE discovery_queue SET lease_until=CURRENT_TIMESTAMP+INTERVAL '3 minutes' WHERE symbol=ANY(?::text[])`).bind(rows.map(x=>x.symbol)).run();return rows});
}
export async function queueDiscoveryRefresh(db:PostgresDatabase,symbol:string){return db.prepare(`UPDATE discovery_queue SET priority=GREATEST(priority,200),next_screen_at=CURRENT_TIMESTAMP,next_research_at=CURRENT_TIMESTAMP WHERE symbol=? AND active RETURNING symbol`).bind(symbol).first()}
export async function discoveryFinnhub(db:PostgresDatabase,path:string,ttlSeconds:number){
 const cached=await db.prepare(`SELECT payload_json,fetched_at FROM discovery_provider_cache WHERE cache_key=? AND expires_at>CURRENT_TIMESTAMP`).bind(path).first<any>();if(cached)return{data:cached.payload_json,asOf:new Date(cached.fetched_at).toISOString()};
 const paused=await db.prepare(`SELECT 1 blocked FROM discovery_control WHERE id='finnhub' AND cooldown_until>CURRENT_TIMESTAMP`).first();if(paused)throw Error('FINNHUB_RATE_LIMIT_COOLDOWN');
 const response=await fetch('https://finnhub.io/api/v1'+path,{headers:{'X-Finnhub-Token':process.env.FINNHUB_API_KEY||''},signal:providerSignal(10000),cache:'no-store'});
 if(!response.ok){if(response.status===429)await db.prepare(`INSERT INTO discovery_control(id,cooldown_until,last_error) VALUES('finnhub',CURRENT_TIMESTAMP+INTERVAL '2 minutes','FINNHUB_429') ON CONFLICT(id) DO UPDATE SET cooldown_until=EXCLUDED.cooldown_until,last_error=EXCLUDED.last_error`).run();throw Error('FINNHUB_'+response.status)}
 const data=await response.json();if(data?.error)throw Error('FINNHUB_INVALID_RESPONSE');const asOf=new Date().toISOString();await db.prepare(`INSERT INTO discovery_provider_cache(cache_key,payload_json,fetched_at,expires_at) VALUES(?,?::jsonb,?::timestamptz,?::timestamptz+(?::int*INTERVAL '1 second')) ON CONFLICT(cache_key) DO UPDATE SET payload_json=EXCLUDED.payload_json,fetched_at=EXCLUDED.fetched_at,expires_at=EXCLUDED.expires_at`).bind(path,JSON.stringify(data),asOf,asOf,ttlSeconds).run();return{data,asOf};
}
