import {id,type PostgresDatabase} from "@/lib/db";

const investmentAccountsSql=`SELECT a.id,COALESCE(a.nickname,a.name) account_name,COALESCE(s.strategy_type,a.investment_purpose,'UNCONFIGURED') strategy,a.last_investment_sync_at,a.last_provider_update_at,a.investment_sync_status,a.investment_sync_error FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE e.household_id=? AND a.hidden=0 AND (a.type='investment' OR a.subtype IN ('brokerage','401k','ira','roth','retirement') OR s.account_id IS NOT NULL) ORDER BY COALESCE(a.nickname,a.name)`;

export async function refreshInvestmentNotificationCoverage(db:PostgresDatabase,householdId:string){
 const accounts=(await db.prepare(investmentAccountsSql).bind(householdId).all<Record<string,any>>()).results;
 const watch=await db.prepare("SELECT COUNT(DISTINCT symbol) count FROM market_watchlist WHERE household_id=?").bind(householdId).first<{count:string}>();
 const worker=await db.prepare("SELECT status,heartbeat_at FROM worker_heartbeats WHERE worker_name='aws-market-worker'").first<Record<string,any>>();
 const workerFresh=Boolean(worker?.heartbeat_at)&&Date.now()-new Date(worker!.heartbeat_at).getTime()<10*60_000;
 for(const account of accounts){
  const row=await db.prepare(`SELECT COUNT(DISTINCT h.id) positions,COUNT(DISTINCT CASE WHEN h.security_id IS NULL OR s.id IS NULL OR s.ticker IS NULL THEN h.id END) unmapped,COUNT(DISTINCT o.id) options,COUNT(DISTINCT r.id) recommendations,COUNT(DISTINCT rt.id) rules,MAX(r.created_at) last_recommendation,MAX(r.evidence_as_of) last_market_data,MAX(d.created_at) last_ai,MAX(a.created_at) last_notification,MAX(CASE WHEN ad.channel='BROWSER_PUSH' AND ad.status='DELIVERED' THEN ad.delivered_at END) last_push,MAX(CASE WHEN ad.channel='EMAIL' AND ad.status='DELIVERED' THEN ad.delivered_at END) last_email,MAX(CASE WHEN ad.channel='IN_APP' THEN COALESCE(ad.delivered_at,ad.created_at) END) last_in_app FROM accounts ac LEFT JOIN holdings h ON h.account_id=ac.id LEFT JOIN securities s ON s.id=h.security_id LEFT JOIN option_positions o ON o.account_id=ac.id AND o.status='OPEN' LEFT JOIN recommendations r ON r.account_id=ac.id AND r.lifecycle IN ('MONITORING','TRIGGERED') LEFT JOIN recommendation_triggers rt ON rt.recommendation_id=r.id AND rt.status='MONITORING' LEFT JOIN ai_decision_runs d ON d.account_id=ac.id AND d.status='COMPLETED' LEFT JOIN alerts a ON a.household_id=? AND a.evidence_json->>'accountId'=ac.id LEFT JOIN alert_deliveries ad ON ad.alert_id=a.id WHERE ac.id=? GROUP BY ac.id`).bind(householdId,account.id).first<Record<string,any>>();
  const positions=Number(row?.positions||0),unmapped=Number(row?.unmapped||0),syncAt=account.last_provider_update_at||account.last_investment_sync_at,lastAnalysis=row?.last_ai||row?.last_recommendation;
  const stale=!lastAnalysis||Date.now()-new Date(lastAnalysis).getTime()>36*60*60_000;
  const status=account.investment_sync_status==='FAILED'||account.investment_sync_error?'ERROR':unmapped?'DEGRADED':!workerFresh?'STALE':!positions?'NOT_CONFIGURED':stale?'STALE':'HEALTHY';
  const error=status==='ERROR'?String(account.investment_sync_error||'INVESTMENT_SYNC_FAILED'):!workerFresh?'WORKER_HEARTBEAT_STALE':unmapped?'UNMAPPED_HOLDINGS':!positions?'NO_HOLDINGS':'ANALYSIS_STALE';
  await db.prepare(`INSERT INTO investment_notification_coverage(account_id,household_id,strategy,status,positions_monitored,watchlist_symbols_monitored,option_contracts_monitored,price_rules_active,recommendation_rules_active,unmapped_positions,last_provider_sync_at,last_market_data_at,last_ai_analysis_at,last_recommendation_at,last_alert_evaluation_at,last_notification_at,last_push_at,last_email_at,last_in_app_at,worker_status,error_code,details_json,heartbeat_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(account_id) DO UPDATE SET strategy=EXCLUDED.strategy,status=EXCLUDED.status,positions_monitored=EXCLUDED.positions_monitored,watchlist_symbols_monitored=EXCLUDED.watchlist_symbols_monitored,option_contracts_monitored=EXCLUDED.option_contracts_monitored,price_rules_active=EXCLUDED.price_rules_active,recommendation_rules_active=EXCLUDED.recommendation_rules_active,unmapped_positions=EXCLUDED.unmapped_positions,last_provider_sync_at=EXCLUDED.last_provider_sync_at,last_market_data_at=EXCLUDED.last_market_data_at,last_ai_analysis_at=EXCLUDED.last_ai_analysis_at,last_recommendation_at=EXCLUDED.last_recommendation_at,last_alert_evaluation_at=EXCLUDED.last_alert_evaluation_at,last_notification_at=EXCLUDED.last_notification_at,last_push_at=EXCLUDED.last_push_at,last_email_at=EXCLUDED.last_email_at,last_in_app_at=EXCLUDED.last_in_app_at,worker_status=EXCLUDED.worker_status,error_code=EXCLUDED.error_code,details_json=EXCLUDED.details_json,heartbeat_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP`).bind(account.id,householdId,account.strategy,status,positions,Number(watch?.count||0),Number(row?.options||0),Number(row?.rules||0),Number(row?.recommendations||0),unmapped,syncAt||null,row?.last_market_data||null,row?.last_ai||null,row?.last_recommendation||null,new Date().toISOString(),row?.last_notification||null,row?.last_push||null,row?.last_email||null,row?.last_in_app||null,workerFresh?String(worker?.status||'UNKNOWN'):'STALE',status==='HEALTHY'?null:error,JSON.stringify({accountName:account.account_name,investmentSyncStatus:account.investment_sync_status})).run();
 }
 return {accounts:accounts.length,monitored:accounts.filter(Boolean).length,positions:0};
}

export async function createInvestmentTestNotification(db:PostgresDatabase,input:{householdId:string;userId:string;accountId:string;eventType:string;channels:string[];ticker?:string}){
 const account=await db.prepare(`SELECT a.id,COALESCE(a.nickname,a.name) account_name,COALESCE(s.strategy_type,a.investment_purpose,'Investment') strategy FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=?`).bind(input.accountId,input.householdId).first<Record<string,any>>();
 if(!account)throw new Error('Investment account not found');
 const eventId=id('investment_event'),alertId=`alert_${eventId}`,ticker=(input.ticker||'TEST').toUpperCase(),createdAt=new Date().toISOString();
 const evidence={notificationEventId:eventId,accountId:account.id,accountName:account.account_name,strategy:account.strategy,ticker,eventType:input.eventType,triggerReason:'Safe synthetic end-to-end pipeline test',dataTimestamp:createdAt,modelTimestamp:createdAt,deepLink:`/workspace/accounts?accountId=${encodeURIComponent(account.id)}&notificationEventId=${encodeURIComponent(eventId)}`,synthetic:true};
 await db.prepare("INSERT INTO alerts(id,household_id,severity,type,title,explanation,evidence_json) VALUES(?,?,?,?,?,?,?)").bind(alertId,input.householdId,'important','investment_test',`${ticker} — ${account.account_name} (${account.strategy}) — TEST ${input.eventType}`,`Safe synthetic ${input.eventType} event for ${account.account_name}. This validates queue and configured delivery channels; it is not a trade recommendation.`,JSON.stringify(evidence)).run();
 for(const channel of input.channels)await db.prepare("INSERT INTO alert_deliveries(id,alert_id,user_id,channel,status,available_at) VALUES(?,?,?,?, 'QUEUED',CURRENT_TIMESTAMP) ON CONFLICT(alert_id,user_id,channel) DO NOTHING").bind(id('alert_delivery'),alertId,input.userId,channel).run();
 await db.prepare("INSERT INTO background_jobs(id,household_id,job_type,idempotency_key,payload_json) VALUES(?,?,'NOTIFICATION_DELIVERY',?,?) ON CONFLICT(idempotency_key) DO NOTHING").bind(id('job'),input.householdId,`investment-test:${eventId}`,JSON.stringify({eventId,accountId:account.id})).run();
 return {eventId,alertId,accountName:account.account_name,strategy:account.strategy,channels:input.channels,status:'QUEUED'};
}