import {id,type PostgresDatabase} from "@/lib/db";
export type ProjectionInput={currentBalanceCents:number;targetCents:number;months:number;monthlyContributionCents:number;annualReturnBps:number};
export function futureValue(input:ProjectionInput){const n=Math.max(0,input.months),r=input.annualReturnBps/10000/12,growth=(1+r)**n,current=input.currentBalanceCents*growth,contributions=r===0?input.monthlyContributionCents*n:input.monthlyContributionCents*((growth-1)/r);return Math.max(0,Math.round(current+contributions))}
export function requiredMonthly(input:Omit<ProjectionInput,'monthlyContributionCents'>){const n=Math.max(1,input.months),r=input.annualReturnBps/10000/12,growth=(1+r)**n,gap=Math.max(0,input.targetCents-input.currentBalanceCents*growth);return Math.max(0,Math.ceil(r===0?gap/n:gap*r/(growth-1)))}
export function requiredLumpSum(input:Omit<ProjectionInput,'monthlyContributionCents'>){const growth=(1+input.annualReturnBps/10000/12)**Math.max(1,input.months);return Math.max(0,Math.ceil(input.targetCents/growth-input.currentBalanceCents))}
export function collegeCost(currentAnnualCents:number,durationYears:number,yearsUntilStart:number,inflationBps:number){return Math.round(currentAnnualCents*(1+inflationBps/10000)**Math.max(0,yearsUntilStart)*Math.max(1,durationYears))}
export function glidePath(years:number,goal:'EDUCATION'|'FUTURE_WEALTH',satelliteBps=0){if(goal==='FUTURE_WEALTH')return{usEquityBps:6500-satelliteBps/2,internationalBps:2000-satelliteBps/2,bondBps:1000,cashBps:500,satelliteBps};const equity=years>=12?8000:years>=8?7000:years>=5?5500:years>=3?3500:years>=1?1500:500,bonds=years>=8?1500:years>=5?3000:years>=3?4500:years>=1?5500:4500;return{usEquityBps:Math.max(0,equity-1500-satelliteBps),internationalBps:Math.min(1500,equity),bondBps:bonds,cashBps:10000-equity-bonds,satelliteBps}}
export const accountTypeGuidance=[
 {type:'529',ownership:'Account owner controls the account; a beneficiary is designated.',tax:'Qualified distributions can be federally tax-free. State treatment varies.',restrictions:'Designed for qualified education expenses; nonqualified earnings may be taxable and penalized.',aid:'Education savings for the FAFSA student must be reported under current FAFSA instructions.',flexibility:'Beneficiary changes and certain qualified rollovers may be possible when current requirements are met.',source:'IRS Publication 970 (2025) and IRS Topic 313',sourceUrl:'https://www.irs.gov/publications/p970',sourceDate:'2026-09-16'},
 {type:'UTMA_UGMA',ownership:'The asset belongs irrevocably to the minor and transfers at the applicable age.',tax:'Taxable investment account; tax treatment depends on income and current law.',restrictions:'Use must benefit the child; control ultimately transfers to the child.',aid:'Current Federal Student Aid guidance treats UGMA/UTMA owned by the student as student assets.',flexibility:'Broad spending flexibility for the child, but parent control is temporary.',source:'Federal Student Aid FAFSA asset guidance',sourceUrl:'https://studentaid.gov/articles/things-you-need-for-fafsa/',sourceDate:'2026-09-16'},
 {type:'PARENT_TAXABLE',ownership:'Parent owns and controls the assets.',tax:'Taxable dividends, interest and realized gains may apply.',restrictions:'No education-only restriction.',aid:'Generally part of parent investment reporting when required by FAFSA.',flexibility:'High flexibility for education or later wealth transfer.',source:'Federal Student Aid FAFSA parent guidance',sourceUrl:'https://studentaid.gov/articles/fafsa-for-parents/',sourceDate:'2026-09-16'},
 {type:'CUSTODIAL_ROTH_IRA',ownership:'IRA is for the child; a custodian manages it while the child is a minor.',tax:'Roth IRA rules and annual limits apply.',restrictions:'Contributions require the child to have eligible compensation and cannot exceed applicable limits.',aid:'Retirement-account treatment can differ from taxable custodial assets; verify current FAFSA and professional guidance.',flexibility:'Primarily retirement wealth; not a substitute for ordinary college savings.',source:'IRS Publication 590-A (2025)',sourceUrl:'https://www.irs.gov/publications/p590a',sourceDate:'2026-09-16'}
];

export async function reviewKidsPlans(db:PostgresDatabase,householdId:string,reviewType='ON_DEMAND'){
 const children=(await db.prepare('SELECT * FROM child_profiles WHERE household_id=? ORDER BY nickname').bind(householdId).all<Record<string,any>>()).results;let projections=0,recommendations=0,alerts=0;const now=new Date(),year=now.getUTCFullYear();
 for(const child of children){const goals=(await db.prepare(`SELECT g.*,COALESCE(SUM(CASE WHEN a.hidden=0 THEN a.current_balance_cents*cga.allocation_percent/100 ELSE 0 END),0)::text linked_balance_cents FROM child_goals g LEFT JOIN child_goal_accounts cga ON cga.goal_id=g.id LEFT JOIN accounts a ON a.id=cga.account_id WHERE g.child_id=? AND g.status IN ('ACTIVE','PAUSED','FUNDED','WITHDRAWING') GROUP BY g.id ORDER BY g.goal_type`).bind(child.id).all<Record<string,any>>()).results,summary=[];
  for(const goal of goals){const targetYear=goal.goal_type==='EDUCATION'?Number(child.expected_college_start_year||year+18):goal.target_date?new Date(goal.target_date).getUTCFullYear():Number(child.birth_year||year)-0+Number(goal.target_age||30),months=Math.max(1,Math.round((targetYear-year)*12-(now.getUTCMonth()))),years=months/12,current=Number(goal.linked_balance_cents||0)+Number(goal.current_manual_balance_cents||0),target=goal.goal_type==='EDUCATION'&&Number(goal.current_annual_cost_cents||0)>0?collegeCost(Number(goal.current_annual_cost_cents),Number(child.expected_college_duration_years||4),years,Number(goal.education_inflation_bps||500)):Number(goal.target_amount_cents||0),monthly=Number(goal.monthly_contribution_cents||0),rates=[Number(goal.return_conservative_bps||500),Number(goal.return_base_bps||700),Number(goal.return_aggressive_bps||900)],balances=rates.map(rate=>futureValue({currentBalanceCents:current,targetCents:target,months,monthlyContributionCents:monthly,annualReturnBps:rate})),required=rates.map(rate=>requiredMonthly({currentBalanceCents:current,targetCents:target,months,annualReturnBps:rate})),fundingPercent=target?Math.round(balances[1]/target*100):100,status=fundingPercent>=110?'AHEAD':fundingPercent>=90?'ON_TRACK':'BEHIND',gap=Math.max(0,target-balances[1]),principal=current+monthly*months,growth=Math.max(0,balances[1]-principal),assumptions={targetYear,months,returnsBps:rates,educationInflationBps:goal.education_inflation_bps,glidePath:glidePath(years,goal.goal_type,Number(goal.satellite_allocation_bps||0)),returnsUncertain:true};
   await db.prepare(`INSERT INTO child_plan_projections(id,child_id,goal_id,assumption_version,source_date,current_balance_cents,conservative_balance_cents,base_balance_cents,aggressive_balance_cents,required_monthly_conservative_cents,required_monthly_base_cents,required_monthly_aggressive_cents,required_lump_sum_base_cents,funding_percent,funding_status,contribution_principal_cents,projected_growth_cents,funding_gap_cents,assumptions_json) VALUES(?,?,?,?,CURRENT_DATE,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id('child_projection'),child.id,goal.id,'kids-plan-1.0.0',current,...balances,...required,requiredLumpSum({currentBalanceCents:current,targetCents:target,months,annualReturnBps:rates[1]}),fundingPercent,status,principal,growth,gap,JSON.stringify(assumptions)).run();projections++;
   const delta=Math.max(0,required[1]-monthly),action=status==='BEHIND'?`Increase contribution by ${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(delta/100)}/month`:status==='AHEAD'?'No action needed — plan is ahead':'No action needed — plan remains on track',explanation=`${child.nickname} ${goal.name} is ${fundingPercent}% projected funded using the base ${rates[1]/100}% assumption. Current balance ${(current/100).toLocaleString('en-US',{style:'currency',currency:'USD'})}; target ${(target/100).toLocaleString('en-US',{style:'currency',currency:'USD'})}. Returns are uncertain.`;
   await db.prepare(`UPDATE child_plan_recommendations SET status='SUPERSEDED' WHERE goal_id=? AND status='ACTIVE'`).bind(goal.id).run();const recId=id('child_recommendation');await db.prepare(`INSERT INTO child_plan_recommendations(id,child_id,goal_id,action,amount_cents,explanation,impact_json,confidence,data_timestamp) VALUES(?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(recId,child.id,goal.id,action,status==='BEHIND'?delta:0,explanation,JSON.stringify({fundingPercent,gapCents:gap,baseProjectedCents:balances[1],requiredMonthlyCents:required[1],glidePath:assumptions.glidePath}),status==='BEHIND'?85:90).run();recommendations++;
   if(status==='BEHIND'||(goal.goal_type==='EDUCATION'&&years<=5&&assumptions.glidePath.usEquityBps>5500)){const alertId=`alert_${recId}`;await db.prepare(`INSERT INTO alerts(id,household_id,severity,type,title,explanation,evidence_json) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).bind(alertId,householdId,status==='BEHIND'?'important':'warning','kids_plan',`${child.nickname} · ${goal.name} · ${status}`,explanation,JSON.stringify({childId:child.id,goalId:goal.id,eventType:status==='BEHIND'?'GOAL_OFF_TRACK':'COLLEGE_RISK_GUARDRAIL',deepLink:`/workspace/kids-goals?childId=${child.id}`})).run();const members=await db.prepare("SELECT user_id FROM household_members WHERE household_id=? AND status='active'").bind(householdId).all<{user_id:string}>();for(const member of members.results)await db.prepare("INSERT INTO alert_deliveries(id,alert_id,user_id,channel,status,available_at) VALUES(?,?,?,'IN_APP','QUEUED',CURRENT_TIMESTAMP) ON CONFLICT(alert_id,user_id,channel) DO NOTHING").bind(id('alert_delivery'),alertId,member.user_id).run();alerts++}
   summary.push({goalId:goal.id,status,fundingPercent,gapCents:gap})
  }
  await db.prepare(`INSERT INTO child_plan_reviews(id,child_id,review_type,status,summary_json,assumptions_version,source_date) VALUES(?,?,?,?,?,'kids-plan-1.0.0',CURRENT_DATE)`).bind(id('child_review'),child.id,reviewType,summary.some(x=>x.status==='BEHIND')?'ATTENTION':'HEALTHY',JSON.stringify({goals:summary})).run()
 }
 return{children:children.length,projections,recommendations,alerts};
}