import {createHash} from "node:crypto";
import {id,type PostgresDatabase} from "@/lib/db";
import {marketDataProvider} from "@/lib/providers/alpaca-market-data";
import {loadRuntimeSecrets} from "@/lib/runtime-secrets";

export type MarketAlertClass="OPPORTUNITY"|"IMPORTANT_NEWS"|"PRICE_LEVEL"|"BUY_ZONE"|"SELL_REDUCE_ZONE"|"BREAKOUT"|"SUPPORT_BREAK"|"EARNINGS"|"THESIS_CHANGE"|"PORTFOLIO_RISK"|"VOLATILITY";
type Severity="ACTION_NOW"|"IMPORTANT"|"WATCH"|"INFORMATIONAL";
type Candidate={symbol?:string;company?:string;eventClass:MarketAlertClass;severity:Severity;title:string;explanation:string;confidence:number;sourceAsOf:string;evidence:Record<string,unknown>;cooldownMinutes:number};
const parse=(value:unknown)=>{if(value&&typeof value==="object")return value as Record<string,any>;try{return JSON.parse(String(value||"{}"))}catch{return{}}};
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
const materialNews=/(earnings|guidance|forecast|acquisition|merger|antitrust|lawsuit|sec |investigation|recall|approval|contract|partnership|ceo|cfo|bankruptcy|cyber|breach|tariff|regulat|downgrade|upgrade|price target|dividend|buyback|layoff)/i;
const negativeNews=/(miss|cut|downgrade|lawsuit|investigation|recall|breach|bankruptcy|resign|weak|decline|warning)/i;

function quietDelay(quiet:Record<string,any>,timezone:string,bypass:boolean){if(bypass||!quiet.enabled||!quiet.start||!quiet.end)return new Date();const parts=new Intl.DateTimeFormat("en-US",{timeZone:timezone,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date()),now=Number(parts.find(x=>x.type==="hour")?.value||0)*60+Number(parts.find(x=>x.type==="minute")?.value||0),minutes=(v:string)=>{const[h,m]=v.split(":").map(Number);return h*60+m},start=minutes(quiet.start),end=minutes(quiet.end),inside=start<end?now>=start&&now<end:now>=start||now<end;if(!inside)return new Date();return new Date(Date.now()+(((end-now+1440)%1440)||1440)*60000)}

async function persistCandidate(db:PostgresDatabase,householdId:string,candidate:Candidate){
 const recent=await db.prepare("SELECT id FROM market_intelligence_events WHERE household_id=? AND symbol IS NOT DISTINCT FROM ? AND event_class=? AND created_at>CURRENT_TIMESTAMP-(? * INTERVAL '1 minute') LIMIT 1").bind(householdId,candidate.symbol||null,candidate.eventClass,candidate.cooldownMinutes).first();
 if(recent)return{created:false,queued:0};
 const fingerprint=hash(JSON.stringify([householdId,candidate.symbol||"MARKET",candidate.eventClass,candidate.evidence.triggerKey||candidate.title])),eventId=id("market_event");
 const inserted=await db.prepare("INSERT INTO market_intelligence_events(id,household_id,symbol,company_name,event_class,severity,fingerprint,title,explanation,evidence_json,confidence,source_as_of) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(fingerprint) DO NOTHING RETURNING id").bind(eventId,householdId,candidate.symbol||null,candidate.company||candidate.symbol||null,candidate.eventClass,candidate.severity,fingerprint,candidate.title,candidate.explanation,JSON.stringify(candidate.evidence),candidate.confidence,candidate.sourceAsOf).first();
 if(!inserted)return{created:false,queued:0};
 const alertId=`alert_${eventId}`,evidence={...candidate.evidence,eventId,eventClass:candidate.eventClass,symbol:candidate.symbol,company:candidate.company,confidence:candidate.confidence,severity:candidate.severity};
 await db.prepare("INSERT INTO alerts(id,household_id,severity,type,title,explanation,evidence_json) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING").bind(alertId,householdId,candidate.severity.toLowerCase(),"market_intelligence",candidate.title,candidate.explanation,JSON.stringify(evidence)).run();
  const recipients=await db.prepare("SELECT hm.user_id,np.in_app_enabled,np.browser_push_enabled,np.email_enabled,np.quiet_hours_json,np.timezone,mp.enabled,mp.channels_json,mp.severities_json,mp.classes_json,mp.quiet_exceptions_json,mp.max_immediate_per_hour,mp.digest_low_value_news,sp.enabled symbol_enabled,sp.channels_json symbol_channels,sp.classes_json symbol_classes FROM household_members hm LEFT JOIN notification_preferences np ON np.household_id=hm.household_id AND np.user_id=hm.user_id LEFT JOIN market_alert_preferences mp ON mp.household_id=hm.household_id AND mp.user_id=hm.user_id LEFT JOIN symbol_alert_preferences sp ON sp.household_id=hm.household_id AND sp.user_id=hm.user_id AND sp.symbol=? WHERE hm.household_id=? AND hm.status='active'").bind(candidate.symbol||"",householdId).all<Record<string,any>>();
 let queued=0;
 for(const recipient of recipients.results){
  if(recipient.enabled===false||recipient.symbol_enabled===false)continue;
  if(candidate.severity==="INFORMATIONAL"&&candidate.eventClass==="IMPORTANT_NEWS"&&recipient.digest_low_value_news===false)continue;
  const severitySettings=parse(recipient.severities_json),classSettings={...parse(recipient.classes_json),...parse(recipient.symbol_classes)};if(severitySettings[candidate.severity]===false||classSettings[candidate.eventClass]===false)continue;
  const max=Number(recipient.max_immediate_per_hour||8),sent=await db.prepare("SELECT COUNT(*) count FROM alert_deliveries d JOIN alerts a ON a.id=d.alert_id WHERE d.user_id=? AND a.type='market_intelligence' AND d.channel IN ('BROWSER_PUSH','EMAIL') AND d.created_at>CURRENT_TIMESTAMP-INTERVAL '1 hour'").bind(recipient.user_id).first<{count:string}>();
  const important=candidate.severity==="ACTION_NOW"||candidate.severity==="IMPORTANT",rateLimited=important&&Number(sent?.count||0)>=max;
  const globalChannels=parse(recipient.channels_json),symbolChannels=parse(recipient.symbol_channels),channels=[recipient.in_app_enabled!==false&&globalChannels.inApp!==false&&symbolChannels.inApp!==false?"IN_APP":null,!rateLimited&&(symbolChannels.push??globalChannels.push??recipient.browser_push_enabled)?"BROWSER_PUSH":null,!rateLimited&&(symbolChannels.email??globalChannels.email??recipient.email_enabled)?"EMAIL":null].filter(Boolean) as string[];
  const exceptions=parse(recipient.quiet_exceptions_json),available=quietDelay(parse(recipient.quiet_hours_json),recipient.timezone||"America/Phoenix",Boolean(exceptions[candidate.severity]));
  for(const channel of channels){await db.prepare("INSERT INTO alert_deliveries(id,alert_id,user_id,channel,status,available_at) VALUES(?,?,?,?, 'QUEUED',?) ON CONFLICT(alert_id,user_id,channel) DO NOTHING").bind(id("alert_delivery"),alertId,recipient.user_id,channel,available.toISOString()).run();queued++}
 }
 if(queued)await db.prepare("INSERT INTO background_jobs(id,household_id,job_type,idempotency_key,payload_json) VALUES(?,?,'NOTIFICATION_DELIVERY',?,?) ON CONFLICT(idempotency_key) DO NOTHING").bind(id("job"),householdId,`delivery:${eventId}`,JSON.stringify({eventId})).run();
 return{created:true,queued,eventId};
}

export async function evaluateMarketIntelligence(db:PostgresDatabase,householdId:string){
 await loadRuntimeSecrets();
 const watch=(await db.prepare("SELECT symbol,purpose,target_price,invalidation_price,notes FROM market_watchlist WHERE household_id=?").bind(householdId).all<Record<string,any>>()).results,holdings=(await db.prepare("SELECT s.ticker symbol,s.name company,SUM(h.quantity*COALESCE(h.price_cents,0)) value_cents FROM holdings h JOIN securities s ON s.id=h.security_id JOIN accounts a ON a.id=h.account_id JOIN entities e ON e.id=a.entity_id WHERE e.household_id=? AND s.ticker IS NOT NULL GROUP BY s.ticker,s.name").bind(householdId).all<Record<string,any>>()).results,recommendations=(await db.prepare("SELECT s.ticker symbol,s.name company,r.account_id,COALESCE(a.nickname,a.name) account_name,r.action,r.confidence,r.reason,r.suggested_quantity::text quantity,r.entry_low_cents,r.entry_high_cents,r.invalidation_cents,r.evidence_as_of,r.id FROM recommendations r JOIN securities s ON s.id=r.security_id JOIN accounts a ON a.id=r.account_id WHERE r.household_id=? AND r.lifecycle IN ('MONITORING','TRIGGERED') AND r.expires_at>CURRENT_TIMESTAMP ORDER BY r.created_at DESC").bind(householdId).all<Record<string,any>>()).results,theses=(await db.prepare("SELECT s.ticker symbol,s.name company,t.state,t.thesis,t.invalidation,t.reviewed_at FROM investment_theses t JOIN securities s ON s.id=t.security_id JOIN accounts a ON a.id=t.account_id JOIN entities e ON e.id=a.entity_id WHERE e.household_id=? AND t.state IN ('WEAKENING','BROKEN') AND t.updated_at>CURRENT_TIMESTAMP-INTERVAL '7 days'").bind(householdId).all<Record<string,any>>()).results;
 const symbolMap=new Map<string,{company?:string;held:boolean;value:number;watch?:Record<string,any>} >();for(const item of watch){const symbol=String(item.symbol).toUpperCase();symbolMap.set(symbol,{...(symbolMap.get(symbol)||{held:false,value:0}),watch:item})}for(const item of holdings){const symbol=String(item.symbol).toUpperCase();symbolMap.set(symbol,{...(symbolMap.get(symbol)||{}),company:item.company,held:true,value:Number(item.value_cents||0)})}for(const item of recommendations){const symbol=String(item.symbol).toUpperCase();symbolMap.set(symbol,{...(symbolMap.get(symbol)||{held:false,value:0}),company:item.company})}
 const symbols=[...symbolMap.keys()].filter(symbol=>/^[A-Z0-9.-]{1,12}$/.test(symbol)).slice(0,50);if(!symbols.length)return{symbols:0,created:0,queued:0,reason:"No holdings or watchlist symbols"};
 const provider=marketDataProvider(),clock=await provider.getClock();
 if(!clock.isOpen){const previous=await db.prepare("SELECT completed_at FROM background_jobs WHERE household_id=? AND job_type='MARKET_INTELLIGENCE' AND status='SUCCEEDED' AND completed_at IS NOT NULL ORDER BY completed_at DESC LIMIT 1").bind(householdId).first<{completed_at:string}>();if(previous?.completed_at&&Date.now()-new Date(previous.completed_at).getTime()<15*60_000)return{symbols:symbols.length,created:0,queued:0,marketSession:clock.session,reason:"Market closed; next full evaluation is scheduled after the 15-minute closed-market cache window"}}
 const snapshot=await provider.getQuotes(symbols),prefs=(await db.prepare("SELECT symbol,timeframe,price_above,price_below,support_level,resistance_level,move_percent,volume_ratio,minimum_confidence,cooldown_minutes,classes_json FROM symbol_alert_preferences WHERE household_id=? AND enabled=TRUE").bind(householdId).all<Record<string,any>>()).results,prefMap=new Map(prefs.map(value=>[String(value.symbol),value])),technicalSymbols=symbols.filter(symbol=>{const preference=prefMap.get(symbol)||{},quote=snapshot.quotes[symbol];return preference.support_level||preference.resistance_level||Math.abs(Number(quote?.changePct||0))>=Number(preference.move_percent||4)}).slice(0,12),barsMap=new Map<string,Awaited<ReturnType<typeof provider.getBars>>["bars"]>();await Promise.all(technicalSymbols.map(async symbol=>{try{barsMap.set(symbol,(await provider.getBars(symbol,{timeframe:"1Day",start:new Date(Date.now()-45*86400000).toISOString(),limit:35})).bars)}catch{barsMap.set(symbol,[])}}));let created=0,queued=0;
 const emit=async(candidate:Candidate)=>{const result=await persistCandidate(db,householdId,candidate);if(result.created)created++;queued+=result.queued};
 const total=holdings.reduce((sum,item)=>sum+Number(item.value_cents||0),0);
 for(const symbol of symbols){const quote=snapshot.quotes[symbol],context=symbolMap.get(symbol)!,preference=prefMap.get(symbol)||{},watchItem=context.watch||{},price=Number(quote?.last||0);if(!price)continue;const timeframe=preference.timeframe||watchItem.purpose||"Research",move=Math.abs(Number(quote.changePct||0)),moveThreshold=Number(preference.move_percent||4),cooldown=Number(preference.cooldown_minutes||240),base={currentPrice:price,previousClose:quote.previousClose,changePct:quote.changePct,marketSession:clock.session,marketOpen:clock.isOpen,timeframe,dataBasis:`${snapshot.feed} quote · ${quote.freshness}`,source:snapshot.feed,sourceAsOf:quote.timestamp||snapshot.asOf,deepLink:`/workspace/research/${encodeURIComponent(symbol.toLowerCase())}`,triggerKey:`${new Date().toISOString().slice(0,13)}:${Math.round(price*100)}`};
  const levels=[{level:Number(preference.price_above||0),above:true},{level:Number(preference.price_below||0),above:false}];for(const item of levels){if(item.level&&((item.above&&price>=item.level)||(!item.above&&price<=item.level)))await emit({symbol,company:context.company,eventClass:"PRICE_LEVEL",severity:"WATCH",title:`${symbol} reached ${money(item.level)}`,explanation:`${symbol} is ${money(price)} and crossed your configured ${item.above?"upper":"lower"} level of ${money(item.level)}. Review the chart and thesis before acting.`,confidence:100,sourceAsOf:base.sourceAsOf,evidence:{...base,triggerLevel:item.level,condition:item.above?"at_or_above":"at_or_below"},cooldownMinutes:cooldown})}
  const target=Number(watchItem.target_price||0),support=Number(preference.support_level||watchItem.invalidation_price||0),resistance=Number(preference.resistance_level||0),minimumConfidence=Number(preference.minimum_confidence||70);
  const bars=barsMap.get(symbol)||[];
  const averageVolume=bars.length>1?bars.slice(0,-1).reduce((sum,bar)=>sum+bar.volume,0)/(bars.length-1):0,volumeRatio=averageVolume&&quote.volume?quote.volume/averageVolume:0,trendConfirmed=bars.length>=20&&price>bars.slice(-20).reduce((sum,bar)=>sum+bar.close,0)/20;
  if(target&&price<=target&&(!support||price>=support)&&trendConfirmed){const confidence=Math.min(92,70+Math.round(Math.max(0,volumeRatio-1)*8));if(confidence>=minimumConfidence)await emit({symbol,company:context.company,eventClass:"BUY_ZONE",severity:"IMPORTANT",title:`${symbol} entered its configured buy zone`,explanation:`${symbol} reached ${money(price)} near the ${money(target)} research level while remaining above ${support?money(support):"the configured invalidation"}. Trend evidence passed; this starts a review, not an automatic purchase.`,confidence,sourceAsOf:base.sourceAsOf,evidence:{...base,triggerLevel:target,support,volumeRatio,trendConfirmed},cooldownMinutes:cooldown})}
  if(resistance&&price>resistance&&volumeRatio>=Number(preference.volume_ratio||1.8)&&trendConfirmed){const confidence=Math.min(95,72+Math.round((volumeRatio-1.5)*10));if(confidence>=minimumConfidence)await emit({symbol,company:context.company,eventClass:"BREAKOUT",severity:"IMPORTANT",title:`${symbol} confirmed above resistance`,explanation:`${symbol} is ${money(price)}, above ${money(resistance)} resistance with ${volumeRatio.toFixed(1)}× recent volume and a positive 20-session trend. Verify follow-through and invalidation before acting.`,confidence,sourceAsOf:base.sourceAsOf,evidence:{...base,triggerLevel:resistance,volumeRatio,trendConfirmed},cooldownMinutes:cooldown})}
  if(support&&price<support)await emit({symbol,company:context.company,eventClass:"SUPPORT_BREAK",severity:context.held?"ACTION_NOW":"IMPORTANT",title:`${symbol} broke configured support`,explanation:`${symbol} is ${money(price)}, below ${money(support)} support. ${context.held?"Because this is held, review position risk and the thesis now.":"Do not treat the lower price as an opportunity until support and evidence recover."}`,confidence:88,sourceAsOf:base.sourceAsOf,evidence:{...base,triggerLevel:support,held:context.held},cooldownMinutes:cooldown});
  if(move>=moveThreshold)await emit({symbol,company:context.company,eventClass:"VOLATILITY",severity:move>=moveThreshold*1.75?"IMPORTANT":"WATCH",title:`${symbol} moved ${Number(quote.changePct).toFixed(1)}%`,explanation:`The move exceeded your ${moveThreshold.toFixed(1)}% threshold. This is a volatility alert—not an opportunity. Review volume, news, liquidity, and thesis impact.`,confidence:100,sourceAsOf:base.sourceAsOf,evidence:{...base,triggerLevel:moveThreshold,volumeRatio},cooldownMinutes:cooldown});
  if(context.held&&total>0&&context.value/total>.25)await emit({symbol,company:context.company,eventClass:"PORTFOLIO_RISK",severity:context.value/total>.4?"IMPORTANT":"WATCH",title:`${symbol} concentration is ${Math.round(context.value/total*100)}%`,explanation:`This holding represents ${Math.round(context.value/total*100)}% of tracked security value. Concentration is risk context, not by itself a sell instruction; review account purpose, taxes, thesis quality, and diversification.`,confidence:95,sourceAsOf:snapshot.asOf,evidence:{...base,portfolioWeightPct:context.value/total*100,held:true},cooldownMinutes:1440})}
 for(const recommendation of recommendations){const symbol=String(recommendation.symbol),quote=snapshot.quotes[symbol],action=String(recommendation.action),positive=["STRONG_BUY","BUY","BUY_PARTIAL","ACCUMULATE"].includes(action),negative=["TAKE_PARTIAL_PROFIT","REDUCE","SELL","EXIT","THESIS_BROKEN"].includes(action),confidence=Number(recommendation.confidence||0),accountName=String(recommendation.account_name||"Investment account"),held=symbolMap.get(symbol)?.held;if(confidence<70||(!positive&&!negative)||negative&&!held)continue;const price=Number(quote?.last||0),entryLow=Number(recommendation.entry_low_cents||0)/100,entryHigh=Number(recommendation.entry_high_cents||0)/100,inZone=positive&&price&&(!entryLow||price>=entryLow)&&(!entryHigh||price<=entryHigh),quantity=Number(recommendation.quantity||0),estimated=Math.round(quantity*price*100);if(positive&&!inZone)continue;await emit({symbol,company:recommendation.company,eventClass:positive?"OPPORTUNITY":"SELL_REDUCE_ZONE",severity:negative?"ACTION_NOW":"IMPORTANT",title:`${symbol} · ${accountName} · ${positive?"BUY SETUP CONFIRMED":"SELL/TRIM ALERT"} · ${quantity||"size pending"} shares · ${confidence}%`,explanation:`Account: ${accountName}. ${quantity?`${quantity} shares · estimated ${positive?"cost":"proceeds"} ${(estimated/100).toLocaleString("en-US",{style:"currency",currency:"USD"})}. `:""}Northstar’s evidence model says ${recommendation.reason}. ${positive?"Price is inside the modeled entry range; verify cash, allocation, stop and live quote.":"Verify the account thesis, exit classification, taxes and execution before deciding."}`,confidence,sourceAsOf:recommendation.evidence_as_of,evidence:{accountId:recommendation.account_id,accountName,currentPrice:price,quantity,estimatedAmountCents:estimated,triggerLevel:positive?[entryLow,entryHigh]:Number(recommendation.invalidation_cents||0)/100,timeframe:"Account strategy",dataBasis:"Stored account recommendation + current quote",recommendationId:recommendation.id,action,deepLink:`/workspace/daily-action-plan?accountId=${encodeURIComponent(String(recommendation.account_id))}&recommendationId=${encodeURIComponent(String(recommendation.id))}`,triggerKey:`${recommendation.id}:${action}:${quantity}:${confidence}`},cooldownMinutes:1440})}
 for(const thesis of theses)await emit({symbol:thesis.symbol,company:thesis.company,eventClass:"THESIS_CHANGE",severity:thesis.state==="BROKEN"?"ACTION_NOW":"IMPORTANT",title:`${thesis.symbol} thesis is ${String(thesis.state).toLowerCase()}`,explanation:`${thesis.thesis} Invalidation: ${thesis.invalidation}. Review the holding; Northstar does not place an order.`,confidence:90,sourceAsOf:thesis.reviewed_at,evidence:{state:thesis.state,timeframe:"Investment thesis",dataBasis:"Saved account thesis",deepLink:`/workspace/research/${encodeURIComponent(String(thesis.symbol).toLowerCase())}`,triggerKey:`${thesis.symbol}:${thesis.state}:${thesis.reviewed_at}`},cooldownMinutes:10080});
 if(new Date().getUTCMinutes()%15===0)await evaluateFinnhubEvents(db,householdId,symbols.slice(0,12),symbolMap,emit);
 return{symbols:symbols.length,created,queued,marketSession:clock.session,asOf:snapshot.asOf};
}

async function evaluateFinnhubEvents(db:PostgresDatabase,householdId:string,symbols:string[],context:Map<string,{company?:string;held:boolean;value:number;watch?:Record<string,any>}>,emit:(candidate:Candidate)=>Promise<void>){void db;void householdId;const key=process.env.FINNHUB_API_KEY;if(!key||!symbols.length)return;const base="https://finnhub.io/api/v1",today=new Date(),from=new Date(today.getTime()-2*86400000),to=new Date(today.getTime()+14*86400000),date=(value:Date)=>value.toISOString().slice(0,10),get=async(path:string)=>{const response=await fetch(`${base}${path}`,{headers:{"X-Finnhub-Token":key},cache:"no-store",signal:AbortSignal.timeout(9000)});if(!response.ok)throw new Error(`FINNHUB_${response.status}`);return response.json()};
 try{const calendar=await get(`/calendar/earnings?from=${date(today)}&to=${date(to)}`),events=Array.isArray(calendar.earningsCalendar)?calendar.earningsCalendar:[];for(const event of events.filter((value:any)=>symbols.includes(String(value.symbol))).slice(0,30)){const when=new Date(`${event.date}T13:00:00Z`),days=(when.getTime()-Date.now())/86400000;if(days<-.5||days>7)continue;await emit({symbol:event.symbol,company:context.get(event.symbol)?.company,eventClass:"EARNINGS",severity:days<=1?"IMPORTANT":"WATCH",title:`${event.symbol} earnings ${days<=1?"are imminent":`in ${Math.ceil(days)} days`}`,explanation:`Expected EPS ${event.epsEstimate??"is not available"}; expected revenue ${event.revenueEstimate?money(Number(event.revenueEstimate)):"is not available"}. Earnings can materially change price and thesis assumptions.`,confidence:95,sourceAsOf:new Date().toISOString(),evidence:{earningsDate:event.date,epsEstimate:event.epsEstimate,revenueEstimate:event.revenueEstimate,timeframe:"Event risk",dataBasis:"Finnhub earnings calendar",deepLink:`/workspace/research/${encodeURIComponent(String(event.symbol).toLowerCase())}`,triggerKey:`earnings:${event.symbol}:${event.date}`},cooldownMinutes:1440})}}
 catch{}
 try{const economic=await get(`/calendar/economic?from=${date(today)}&to=${date(new Date(today.getTime()+3*86400000))}`),events=Array.isArray(economic.economicCalendar)?economic.economicCalendar:[];for(const event of events.filter((value:any)=>String(value.country||"").toUpperCase()==="US"&&/high|3/i.test(String(value.impact||value.importance||""))).slice(0,12)){const eventName=String(event.event||event.name||"U.S. macroeconomic release"),eventDate=String(event.time||event.date||date(today));await emit({eventClass:"IMPORTANT_NEWS",severity:"IMPORTANT",title:`U.S. macro event · ${eventName}`,explanation:`A high-impact U.S. macroeconomic event is scheduled for ${eventDate}. Review rate, index, sector, and portfolio sensitivity; the event is risk context, not a directional prediction.`,confidence:90,sourceAsOf:new Date().toISOString(),evidence:{macroEvent:eventName,eventDate,country:"US",timeframe:"Macro event",dataBasis:"Finnhub economic calendar",deepLink:"/workspace/markets",triggerKey:`macro:${eventName}:${eventDate}`},cooldownMinutes:1440})}}catch{}
 await Promise.all(symbols.slice(0,8).map(async symbol=>{try{const news=await get(`/company-news?symbol=${encodeURIComponent(symbol)}&from=${date(from)}&to=${date(today)}`),articles=(Array.isArray(news)?news:[]).slice(0,8),lowValue:string[]=[];for(const article of articles){const text=`${article.headline||""} ${article.summary||""}`;if(!materialNews.test(text)){if(article.headline)lowValue.push(String(article.headline));continue}const held=context.get(symbol)?.held,score=55+(held?15:5)+(negativeNews.test(text)?10:0)+(article.source?5:0);if(score<70){if(article.headline)lowValue.push(String(article.headline));continue}const publishedAt=Number(article.datetime);await emit({symbol,company:context.get(symbol)?.company,eventClass:"IMPORTANT_NEWS",severity:held&&negativeNews.test(text)?"ACTION_NOW":"IMPORTANT",title:`${symbol} · ${String(article.headline||"Material company news").slice(0,140)}`,explanation:`${String(article.summary||"A potentially thesis-relevant company event was reported.").slice(0,420)} Review the primary source, financial impact, and whether the price already reflects it.`,confidence:Math.min(90,score),sourceAsOf:new Date(publishedAt?publishedAt*1000:Date.now()).toISOString(),evidence:{headline:article.headline,source:article.source,url:article.url,timeframe:held?"Current holding":"Watchlist",dataBasis:"Finnhub company news + materiality keywords + portfolio relevance",held:Boolean(held),deepLink:`/workspace/research/${encodeURIComponent(symbol.toLowerCase())}?news=${encodeURIComponent(String(article.id||article.url||""))}`,triggerKey:`news:${article.id||hash(String(article.url||article.headline))}`},cooldownMinutes:10080})}if(lowValue.length)await emit({symbol,company:context.get(symbol)?.company,eventClass:"IMPORTANT_NEWS",severity:"INFORMATIONAL",title:`${symbol} lower-priority news summary`,explanation:`${lowValue.slice(0,4).join(" · ")}. These items did not pass the immediate materiality threshold and are collected for review instead of interrupting you.`,confidence:55,sourceAsOf:new Date().toISOString(),evidence:{headlines:lowValue.slice(0,4),timeframe:"Daily summary",dataBasis:"Finnhub company news · below immediate materiality threshold",deepLink:`/workspace/research/${encodeURIComponent(symbol.toLowerCase())}`,triggerKey:`digest:${symbol}:${date(today)}`},cooldownMinutes:1440})}catch{}}));
}
