export type MarketBar={time?:string;open:number;high:number;low:number;close:number;volume:number};
export type TradeMode='day'|'swing';
export type FrameSignal={label:string;range:string;direction:'BULLISH'|'BEARISH'|'NEUTRAL';price:number;ema20:number;ema50:number;support:number;resistance:number;atr:number;relativeVolume:number;score:number;latestTime:string|null;fresh:boolean;evidence:string[]};
export type MultiTimeframeDecision={mode:TradeMode;hierarchy:string;action:string;actionClass:'buy'|'sell'|'wait';currentPrice:number;entryLow:number;entryHigh:number;trigger:number;stop:number;targets:number[];shares:number;plannedCost:number;maximumLoss:number;accountRiskPercent:number;confidence:number;frames:FrameSignal[];reason:string;confirmation:string;invalidation:string};

const average=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;
const ema=(values:number[],period:number)=>{const k=2/(period+1);let value=values[0]||0;for(let index=1;index<values.length;index++)value=values[index]*k+value*(1-k);return value};
const round=(value:number,digits=2)=>Number(value.toFixed(digits));
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));

function analyze(label:string,range:string,bars:MarketBar[]):FrameSignal{
 if(bars.length<20)throw new Error(`${label} requires at least 20 candles`);
 const closes=bars.map(bar=>Number(bar.close)),last=bars.at(-1)!,prior=bars.at(-2)!,ema20=ema(closes.slice(-80),20),ema50=ema(closes.slice(-120),50),atr=average(bars.slice(-14).map((bar,index,items)=>Math.max(bar.high-bar.low,Math.abs(bar.high-(items[index-1]?.close||bar.open)),Math.abs(bar.low-(items[index-1]?.close||bar.open))))),support=Math.min(...bars.slice(-20).map(bar=>bar.low)),resistance=Math.max(...bars.slice(-20).map(bar=>bar.high)),volumeBase=average(bars.slice(-21,-1).map(bar=>bar.volume)),relativeVolume=volumeBase?last.volume/volumeBase:0,latestTime=last.time||null,maxAgeMs=range==="5m"?30*60*1000:range==="1h"?6*60*60*1000:range==="1D"?4*86400000:10*86400000,fresh=Boolean(latestTime)&&Date.now()-Date.parse(String(latestTime))<=maxAgeMs,bullish=last.close>ema20&&ema20>ema50&&last.close>=prior.close,bearish=last.close<ema20&&ema20<ema50&&last.close<=prior.close,direction=bullish?'BULLISH':bearish?'BEARISH':'NEUTRAL',score=clamp(Math.round(50+(last.close>ema20?12:-12)+(ema20>ema50?15:-15)+(last.close>=prior.close?8:-8)+(relativeVolume>=1.2?(last.close>=prior.close?8:-8):0)),5,95),evidence=[`Price $${last.close.toFixed(2)} is ${last.close>=ema20?'above':'below'} EMA20 $${ema20.toFixed(2)}`,`EMA20 is ${ema20>=ema50?'above':'below'} EMA50 $${ema50.toFixed(2)}`,`Relative volume ${relativeVolume.toFixed(2)}x`,`Support $${support.toFixed(2)} / resistance $${resistance.toFixed(2)}`];
 return{label,range,direction,price:round(last.close),ema20:round(ema20),ema50:round(ema50),support:round(support),resistance:round(resistance),atr:round(atr),relativeVolume:round(relativeVolume),score,latestTime,fresh,evidence};
}

export function buildMultiTimeframeDecision(input:{mode:TradeMode;bars:Record<string,MarketBar[]>;accountValue:number;cashAvailable:number;riskPercent?:number}):MultiTimeframeDecision{
 const config=input.mode==='day'?[['Large','1D'],['Medium','1h'],['Entry','5m']]:[['Large','1W'],['Medium','1D'],['Entry','1h']],frames=config.map(([label,range])=>analyze(label,range,input.bars[range]||[])),[large,medium,entry]=frames,currentPrice=entry.price,bullCount=frames.filter(frame=>frame.direction==='BULLISH').length,bearCount=frames.filter(frame=>frame.direction==='BEARISH').length,conflict=bullCount>0&&bearCount>0,riskPercent=clamp(Number(input.riskPercent??.5),.1,1),buyZoneCenter=Math.max(entry.support,entry.ema20),entryLow=round(Math.max(.01,buyZoneCenter-entry.atr*.15)),entryHigh=round(buyZoneCenter+entry.atr*.15),buyTrigger=round(entry.resistance+entry.atr*.08),sellTrigger=round(entry.support-entry.atr*.08);
 let action='NO TRADE',actionClass:'buy'|'sell'|'wait'='wait',trigger=currentPrice,plannedEntry=currentPrice,stop=round(Math.max(.01,Math.min(entry.support,entry.ema50)-entry.atr*.35)),reason='Timeframes do not provide a complete directional setup.',confirmation='Wait for the large, medium, and entry timeframes to stop conflicting.';
 if(!conflict&&bullCount===3&&entry.relativeVolume>=1.2){action='BUY NOW';actionClass='buy';trigger=currentPrice;plannedEntry=currentPrice;reason='All three timeframes are bullish and the entry timeframe has confirming relative volume.';confirmation=`Price must hold above $${Math.max(entry.ema20,entry.support).toFixed(2)} with relative volume at or above 1.20x.`}
 else if(large.direction==='BULLISH'&&medium.direction==='BULLISH'){action=`BUY ABOVE $${buyTrigger.toFixed(2)}`;actionClass='buy';trigger=buyTrigger;plannedEntry=buyTrigger;reason='Higher-timeframe trend is bullish, but the entry timeframe still requires a breakout confirmation.';confirmation=`Entry candle must close above $${buyTrigger.toFixed(2)} with relative volume at or above 1.20x.`}
 else if(large.direction==='BULLISH'&&medium.direction!=='BEARISH'&&entry.direction==='NEUTRAL'){action=`BUY NEAR $${entryLow.toFixed(2)}–$${entryHigh.toFixed(2)}`;actionClass='buy';trigger=entryHigh;plannedEntry=(entryLow+entryHigh)/2;reason='Higher-timeframe bias is constructive; wait for a controlled pullback into entry support.';confirmation=`Require a bullish rejection candle inside $${entryLow.toFixed(2)}–$${entryHigh.toFixed(2)} and a close back above EMA20.`}
 else if(!conflict&&bearCount===3&&entry.relativeVolume>=1.2){action='SELL NOW';actionClass='sell';trigger=currentPrice;plannedEntry=currentPrice;stop=round(entry.resistance+entry.atr*.35);reason='All three timeframes are bearish with confirming entry-timeframe volume.';confirmation='Sell/exit signal remains valid only while price stays below entry EMA20 and no bullish reclaim occurs.'}
 else if(large.direction==='BEARISH'&&medium.direction==='BEARISH'){action=`SELL BELOW $${sellTrigger.toFixed(2)}`;actionClass='sell';trigger=sellTrigger;plannedEntry=sellTrigger;stop=round(entry.resistance+entry.atr*.35);reason='Higher-timeframe structure is bearish; wait for the entry timeframe to confirm the breakdown.';confirmation=`Require an entry candle close below $${sellTrigger.toFixed(2)} with relative volume at or above 1.20x.`}
 else if(conflict){action='WAIT — TIMEFRAMES CONFLICT';reason='At least one timeframe is bullish while another is bearish.'}
 const staleFrames=frames.filter(frame=>!frame.fresh);if(staleFrames.length){action='WAIT — DATA REFRESH REQUIRED';actionClass='wait';reason=`Required timeframe data is stale or missing: ${staleFrames.map(frame=>frame.range).join(', ')}.`;confirmation='Refresh every required timeframe before evaluating an immediate buy or sell.'}
 const riskPerShare=Math.max(.01,Math.abs(plannedEntry-stop)),riskBudget=Math.max(0,input.accountValue*riskPercent/100),byRisk=Math.floor(riskBudget/riskPerShare),byCash=Math.floor(Math.max(0,input.cashAvailable)/Math.max(.01,plannedEntry)),byPosition=Math.floor(Math.max(0,input.accountValue*.1)/Math.max(.01,plannedEntry)),shares=actionClass==='buy'?Math.max(0,Math.min(byRisk,byCash,byPosition)):0,maximumLoss=shares*riskPerShare,plannedCost=shares*plannedEntry,rewardDirection=actionClass==='sell'?-1:1,targets=[round(plannedEntry+rewardDirection*riskPerShare*2),round(plannedEntry+rewardDirection*riskPerShare*3)],confidence=clamp(Math.round((large.score*.4+medium.score*.35+entry.score*.25)*(actionClass==='sell'?-1:1)+(actionClass==='sell'?100:0)-(conflict?20:0)),5,95),hierarchy=config.map(([,range])=>range).join(' → '),invalidation=actionClass==='sell'?`Bearish decision invalidates on a confirmed close above $${stop.toFixed(2)}.`:`Bullish decision invalidates on a confirmed close below $${stop.toFixed(2)}.`;
 return{mode:input.mode,hierarchy,action,actionClass,currentPrice,entryLow,entryHigh,trigger:round(trigger),stop,targets,shares,plannedCost:round(plannedCost),maximumLoss:round(maximumLoss),accountRiskPercent:riskPercent,confidence,frames,reason,confirmation,invalidation};
}