import {nextOpenResearch,optionQuoteResearchFresh,buildNextOpenOptionCandidates} from "@/lib/options-next-open";
import {volatilityContext,assessOptionVolatility,type OptionsVolatilityContext} from "@/lib/options-volatility";
import {accountRiskSettings} from "@/lib/account-risk-settings";
import {authoritativeRecommendation} from "@/lib/authoritative-recommendation";
import {buildOptionCandidates} from "@/lib/ai-options-candidates";
import {id,type PostgresDatabase} from "@/lib/db";
import {optionsChain} from "@/lib/providers/options-chain";
import {loadRuntimeSecrets} from "@/lib/runtime-secrets";
import {marketDataProvider} from "@/lib/providers/alpaca-market-data";
import {decideInvestment,type DecisionModelAdapter,type DecisionOutput} from "@/lib/ai-investment-decision-engine";
import {optionsFlowForSymbol} from "@/lib/options-flow-engine";
import {evaluateCatalystEntryGate,loadCatalystContext} from "@/lib/catalyst-entry-gate";


type J=Record<string,any>;
type Snap={latestQuote?:{bp?:number;ap?:number;t?:string};latestTrade?:{p?:number;t?:string};dailyBar?:{v?:number};greeks?:{delta?:number;gamma?:number;theta?:number;vega?:number;rho?:number};impliedVolatility?:number;openInterest?:number};
const pattern=/^([A-Z.]+)(\d{6})([CP])(\d{8})$/;
const decode=(symbol:string)=>{const m=symbol.match(pattern);if(!m)return null;return{expiration:`20${m[2].slice(0,2)}-${m[2].slice(2,4)}-${m[2].slice(4,6)}`,type:m[3]==="C"?"CALL" as const:"PUT" as const,strike:Number(m[4])/1000}};
const parse=(value:unknown)=>{try{return typeof value==="string"?JSON.parse(value):value||null}catch{return null}};
type MarketSnapshot={underlying:number;asOf:string;quoteSource?:string;volatility:OptionsVolatilityContext;payload:{snapshots?:Record<string,Snap>}};
const snapshotCache=new Map<string,{expires:number;promise:Promise<MarketSnapshot>}>();
async function loadMarketSnapshot(symbol:string){
 const feed=process.env.ALPACA_OPTIONS_FEED||"indicative",key=symbol+":"+feed,cached=snapshotCache.get(key),now=Date.now();
 if(cached&&cached.expires>now)return cached.promise;
 const promise=(async()=>{
  const provider=marketDataProvider(),start=new Date(Date.now()-100*86400000).toISOString();
  const[quotes,response,stockBars,indexBars]=await Promise.all([
   marketDataProvider().getQuotes([symbol]),
   optionsChain(symbol),
   provider.getBars(symbol,{timeframe:"1Day",start,limit:100}).catch(()=>({bars:[]})),
   provider.getBars("SPY",{timeframe:"1Day",start,limit:100}).catch(()=>({bars:[]}))
  ]),underlying=Number(quotes.quotes[symbol]?.last||0);
  if(!underlying)throw new Error("A current underlying price is required before evaluating options.");

  return{underlying,volatility:volatilityContext(stockBars.bars,indexBars.bars),asOf:quotes.asOf,quoteSource:quotes.quotes[symbol]?.source,payload:response as{snapshots?:Record<string,Snap>}};
 })();
 snapshotCache.set(key,{expires:now+30000,promise});
 try{return await promise}catch(error){snapshotCache.delete(key);throw error}
}
export async function analyzeOptions(db:PostgresDatabase,householdId:string,body:J){try{
 await loadRuntimeSecrets();
 const accountId=String(body.accountId||""),symbol=String(body.symbol||"SPY").toUpperCase().trim(),outlook=body.outlook==="bearish"?"bearish":"bullish",targetDte=Math.max(14,Math.min(30,Number(body.targetDte)||21));
 if(!accountId)return Response.json({error:"Select a Swing investment account before analyzing Calls & Puts."},{status:400});
 const account=await db.prepare("SELECT a.id,COALESCE(a.nickname,a.name) name,COALESCE(s.strategy_type,'CUSTOM') strategy_type,COALESCE(s.available_cash_cents,a.available_balance_cents,0) available_cash_cents,s.policy_json,s.maximum_risk_bps FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=? AND a.type='investment'").bind(accountId,householdId).first<J>();
 if(!account)return Response.json({error:"Investment account not found"},{status:404});
 const noOption=(reason:string,changes:string[],status="NO OPTION TRADE")=>Response.json({status:"NO_TRADE",decisionLabel:status,underlying:symbol,underlyingPrice:null,asOf:new Date().toISOString(),account:{id:account.id,name:account.name,strategy:account.strategy_type},contract:null,chain:[],rationale:[reason],warnings:[],decision:{action:"NO_ACTION",confidence:null,confidenceBand:"UNAVAILABLE",interpretation:reason,invalidation:"No option entry is authorized.",reasoningFactors:[reason],whatWouldChange:changes,dataQuality:null}},{headers:{"Cache-Control":"private, no-store"}});
 const researchOnly=nextOpenResearch();
 const limits=await accountRiskSettings(db,householdId,accountId);account.available_cash_cents=Math.round(limits.cash*100);
 const recommendedRisk=Math.max(0,limits.value*limits.effective.optionsRiskBps/10000);
 const requestedRisk=body.maxRisk==null?recommendedRisk:Number(body.maxRisk);
 if(!Number.isFinite(requestedRisk)||requestedRisk<0)return Response.json({error:"Maximum premium risk must be a non-negative number."},{status:400});
 const maxRisk=Math.min(100000,requestedRisk,recommendedRisk);
 if(maxRisk===0&&!researchOnly)return noOption("No option premium is available under this account's risk budget.",["Review available cash and the account's option risk limit."]);

  if(!/^[A-Z.]{1,10}$/.test(symbol))return Response.json({error:"Invalid underlying symbol"},{status:400});
 if(!process.env.ALPACA_API_KEY||!process.env.ALPACA_API_SECRET)return noOption("Option market data is not configured.",["Connect a supported option-chain provider."],"WAIT");
 const accountHoldings=await db.prepare("SELECT COALESCE(SUM(quantity*price_cents),0)::text value FROM holdings WHERE account_id=?").bind(accountId).first<J>();
 const reservations=await db.prepare("SELECT COALESCE(SUM((plan_json->>'reservedCash')::numeric),0)::text value FROM trade_lifecycle_exits WHERE account_id=? AND status IN ('REENTRY_WATCH','REENTRY_READY')").bind(accountId).first<J>();
 const spendableCash=Math.max(0,Number(account.available_cash_cents)/100-Number(reservations?.value||0)-limits.value*limits.effective.cashReserveBps/10000),approvedRisk=Math.min(maxRisk,limits.value*limits.effective.optionsRiskBps/10000);
 let snapshot:MarketSnapshot;try{snapshot=await loadMarketSnapshot(symbol)}catch{return noOption("Current option-chain or underlying data could not be verified.",["Restore the market-data provider and rerun analysis."],"WAIT")}
 const {underlying,payload}=snapshot,feed=process.env.ALPACA_OPTIONS_FEED||"indicative",now=new Date(),wanted=outlook==="bullish"?"CALL":"PUT",chain=Object.entries(payload.snapshots||{}).flatMap(([contractSymbol,s])=>{const c=decode(contractSymbol);if(!c)return[];const dte=Math.ceil((new Date(`${c.expiration}T20:00:00Z`).getTime()-now.getTime())/86400000),bid=Number(s.latestQuote?.bp||0),ask=Number(s.latestQuote?.ap||0),mid=(bid+ask)/2;if(dte<Math.max(14,targetDte-30)||dte>30||bid<=0||ask<=0||(!researchOnly&&ask*100>approvedRisk))return[];const spreadPct=mid?((ask-bid)/mid)*100:100,delta=Number(s.greeks?.delta||0),targetDelta=c.type==="CALL"?.45:-.45,volume=Number(s.dailyBar?.v||0),iv=Number(s.impliedVolatility||0),intrinsic=c.type==="CALL"?Math.max(0,underlying-c.strike):Math.max(0,c.strike-underlying),expectedMove=iv?underlying*iv*Math.sqrt(dte/365):null,score=Math.max(0,Math.round(100-Math.abs(delta-targetDelta)*70-Math.min(40,spreadPct)-Math.abs(dte-targetDte)*.3+Math.min(10,Math.log10(volume+1)*4)));return[{contractSymbol,quoteAsOf:s.latestQuote?.t||null,...c,dte,bid,ask,mid,last:Number(s.latestTrade?.p||0)||null,volume,openInterest:Number(s.openInterest||0)||null,impliedVolatility:iv||null,delta:s.greeks?.delta??null,gamma:s.greeks?.gamma??null,theta:s.greeks?.theta??null,vega:s.greeks?.vega??null,rho:s.greeks?.rho??null,intrinsicValue:intrinsic,extrinsicValue:Math.max(0,mid-intrinsic),breakEven:c.type==="CALL"?c.strike+ask:c.strike-ask,expectedMove,midpointContractCost:mid*100,maximumPremiumRisk:ask*100,spreadPct,liquidityQuality:spreadPct<=8&&volume>=10?"GOOD":spreadPct<=18?"FAIR":"POOR",score}]}).sort((a,b)=>b.score-a.score),best=chain[0];
 try{await authoritativeRecommendation(db,{householdId,accountId,symbol,force:researchOnly});}catch{return noOption("Central underlying research could not be verified; no option entry is authorized.",["Refresh the underlying research and account risk evidence."],"WAIT");}
 if(!best)return noOption("No contract passed expiration, quote, and maximum-premium filters.",["A quoted contract with sufficient DTE and premium within account capacity is required."]);
 const latest=await db.prepare("SELECT output_json,data_timestamp,created_at,status FROM ai_decision_runs WHERE account_id=? AND ticker=? AND strategy<>'OPTIONS' ORDER BY created_at DESC LIMIT 1").bind(accountId,symbol).first<J>(),thesisAge=latest?.created_at?Date.now()-new Date(String(latest.created_at)).getTime():Infinity,underlyingThesis=latest?.status==='COMPLETED'&&thesisAge>=0&&thesisAge<=20*60*1000?parse(latest?.output_json):null,flow=await optionsFlowForSymbol(db,symbol),catalystContext=await loadCatalystContext(symbol,db),catalystGate=evaluateCatalystEntryGate(catalystContext,{mode:"OPTIONS",contractDte:best.dte,allowEventTrade:false}),asOf=snapshot.asOf;
 const assessedChain=chain.map(c=>{const assessment=assessOptionVolatility(snapshot.volatility,c.impliedVolatility,c.dte,c.vega,evaluateCatalystEntryGate(catalystContext,{mode:"OPTIONS",contractDte:c.dte,allowEventTrade:false}).pass);const quoteTime=payload.snapshots?.[c.contractSymbol]?.latestQuote?.t,age=quoteTime?Date.now()-Date.parse(quoteTime):Infinity;const issues=[...(!limits.effective.optionsEnabled?['Options entries are disabled for this account; research only.']:[]),...(feed!=='opra'?['Indicative option quotes are not executable real-time OPRA quotes.']:[]),...(!(age>=0&&age<=120000)?['Option quote is stale or has no verified timestamp.']:[]),...(c.volume<10?['Recent contract volume is insufficient or unavailable.']:[]),...(c.openInterest==null?['Open interest unavailable.']:[])];const researchAllowed=assessment.allowed&&optionQuoteResearchFresh(quoteTime||'')&&c.volume>=10&&Number(c.openInterest)>0;return {...c,volatility:{...assessment,researchAllowed,allowed:assessment.allowed&&issues.length===0,reasons:[...assessment.reasons,...issues]}};});
 const decision=await decideInvestment({householdId,accountId,accountName:account.name,strategy:"OPTIONS",ticker:symbol,requestType:researchOnly?"OPTIONS_NEXT_OPEN_RESEARCH":"OPTIONS_SELECTOR",candidates:researchOnly?buildNextOpenOptionCandidates(assessedChain,underlyingThesis as DecisionOutput|null,spendableCash):buildOptionCandidates(assessedChain,underlyingThesis as DecisionOutput|null,spendableCash,approvedRisk,catalystGate.pass),features:{volatility:snapshot.volatility,contractVolatility:assessedChain.slice(0,30).map(c=>({contractSymbol:c.contractSymbol,...c.volatility})),account,maxRisk:approvedRisk,institutionalOptionsFlow:flow.summary,catalystGate,underlying:{price:underlying,outlook},underlyingThesis,selectedContract:best,chainSummary:chain.slice(0,20)},evidence:[...(Array.isArray(underlyingThesis?.evidenceSources)?underlyingThesis.evidenceSources:[]),{label:"currentPrice",value:underlying,sourceType:"PROVIDER",sourceId:snapshot.quoteSource,asOf},{label:"catalystGate",value:{...catalystGate,events:catalystContext.events},sourceType:"PROVIDER",sourceId:catalystContext.provider,asOf:catalystContext.asOf},{label:"institutionalOptionsFlow",value:flow.summary,sourceType:"PROVIDER",sourceId:String(flow.summary?.source_mode||"NOT_CONFIGURED"),asOf:flow.summary?.data_as_of||asOf},{label:"underlyingPrice",value:underlying,sourceType:"PROVIDER",sourceId:snapshot.quoteSource,asOf},{label:"underlyingThesis",value:underlyingThesis,sourceType:"MODEL_INFERENCE",sourceId:String(underlyingThesis?.decisionId||"SWING_DECISION"),asOf:latest?.created_at},{label:"optionQuote",value:{bid:best.bid,ask:best.ask,mid:best.mid},sourceType:"PROVIDER",sourceId:"ALPACA_OPTIONS",asOf:best.quoteAsOf||""},{label:"greeks",value:{delta:best.delta,gamma:best.gamma,theta:best.theta,vega:best.vega,rho:best.rho},sourceType:"PROVIDER",sourceId:"ALPACA_OPTIONS",asOf},{label:"liquidity",value:{volume:best.volume,openInterest:best.openInterest,spreadPct:best.spreadPct},sourceType:"CALCULATION",asOf},{label:"accountCash",value:account.available_cash_cents,sourceType:"USER",asOf}],dataTimestamp:asOf,requiredFacts:["underlyingPrice","underlyingThesis","catalystGate","optionQuote","greeks","liquidity","accountCash"]},{db,persist:true});
 const selected=chain.find(c=>c.contractSymbol===decision.contractSymbol)||best;
 const selectedVolatility=assessedChain.find(c=>c.contractSymbol===selected.contractSymbol)!.volatility;
 const researchQualified=researchOnly&&decision.providerStatus==="AVAILABLE"&&["CALL","PUT"].includes(String(decision.instrument))&&selectedVolatility.researchAllowed;
 const isOption=!researchOnly&&["CALL","PUT"].includes(String(decision.instrument))&&["BUY_IF","BUY_NOW"].includes(decision.action)&&selectedVolatility.allowed;
 const decisionLabel=researchQualified?`${selected.type} NEXT-OPEN WATCH`:isOption?`${selected.type} SETUP`:decision.instrument==="SHARES"?"SHARES PREFERRED":["WAIT","INSUFFICIENT_CONFIRMATION"].includes(decision.action)?"WAIT":"NO OPTION TRADE";
 const contract={...selected,contractMultiplier:100,premium:selected.ask*100,maxLoss:selected.maximumPremiumRisk,breakeven:selected.breakEven,iv:selected.impliedVolatility},status=researchQualified?"RESEARCH":isOption?"CANDIDATE":"NO_TRADE",rationale=[`${selected.liquidityQuality} quoted liquidity with a ${selected.spreadPct.toFixed(1)}% spread`,`${selected.dte} DTE and Delta ${Number(selected.delta||0).toFixed(2)} observed; suitability still depends on the underlying, liquidity and account checks`,selected.maximumPremiumRisk<=approvedRisk?`One-contract premium ${selected.maximumPremiumRisk.toFixed(2)} is within the risk cap; available cash and reserves still apply`:`One-contract premium ${selected.maximumPremiumRisk.toFixed(2)} exceeds this account risk cap; research only`,underlyingThesis?`Aligned against latest Swing action ${underlyingThesis.action}`:"No current account-specific Swing thesis is available",catalystGate.summary,flow.summary?.provider_status==="CONNECTED"?"Options-flow evidence was included":"Options-flow evidence is unavailable and did not increase confidence"];
 return Response.json({status,decisionLabel,researchOnly,researchQualified,executionReady:false,analyzedAt:new Date().toISOString(),quoteAsOf:selected.quoteAsOf,volatility:selectedVolatility,underlying:symbol,underlyingPrice:underlying,account:{id:account.id,name:account.name,strategy:account.strategy_type},outlook,feed,asOf,contract:isOption||researchQualified?contract:null,chain:chain.slice(0,30),rationale:[...selectedVolatility.reasons,...rationale],decision,catalystGate,warnings:[...((payload as J).limitations||[]),"Analysis only; no option order is placed.","Calls and Puts use separate short-duration theses from long-term holdings.","Verify live quote, earnings timing, implied-volatility crush, liquidity, taxes, and account permissions."]},{headers:{"Cache-Control":"private, no-store"}});
 }catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Options analysis unavailable"},{status:500})}}

export async function analyzeAndStoreOptions(db:PostgresDatabase,householdId:string,body:J){const response=await analyzeOptions(db,householdId,body);if(!response.ok)return response;const result=await response.json();await db.transaction(async tx=>{await tx.prepare('INSERT INTO options_account_decisions(account_id,symbol,decision_json) VALUES(?,?,?::jsonb) ON CONFLICT(account_id,symbol) DO UPDATE SET decision_json=EXCLUDED.decision_json,updated_at=CURRENT_TIMESTAMP').bind(body.accountId,result.underlying,JSON.stringify(result)).run();await tx.prepare('INSERT INTO options_account_history(id,account_id,symbol,decision_json) VALUES(?,?,?,?::jsonb)').bind(id('option_decision'),body.accountId,result.underlying,JSON.stringify(result)).run();});return Response.json(result,{headers:{'Cache-Control':'private, no-store'}});}
