import {id,type PostgresDatabase} from '@/lib/db';
import {loadRuntimeSecrets} from '@/lib/runtime-secrets';
import {marketResearchInputs} from '@/lib/market-research-inputs';
import {optionsChain} from '@/lib/providers/options-chain';
import {rankOptionContracts} from '@/lib/options-contract-ranking';
import {accountRiskSettings} from '@/lib/account-risk-settings';
import {optionStage,OPTIONS_RESEARCH_VERSION,OPTION_STAGES} from '@/lib/options-research-queue';
import {nextOpenResearch} from '@/lib/options-next-open';
type Row=Record<string,any>;
export async function runOptionsResearch(db:PostgresDatabase,householdId:string,body:Row){
 await loadRuntimeSecrets();const accountId=String(body.accountId||''),symbol=String(body.symbol||'').toUpperCase();
 if(!/^[A-Z][A-Z0-9.-]{0,11}$/.test(symbol))throw Error('INVALID_SYMBOL');
 const account=await db.prepare("SELECT a.id,COALESCE(a.nickname,a.name) name,s.strategy_type FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN investment_account_settings s ON s.account_id=a.id WHERE a.id=? AND e.household_id=? AND a.hidden=0 AND a.type='investment'").bind(accountId,householdId).first<Row>();if(!account)throw Error('ACCOUNT_NOT_FOUND');
 const stage=(name:string,status:string,details:Row={},error:string|null=null)=>optionStage(db,accountId,symbol,name,status,details,error);
 for(const name of OPTION_STAGES)await db.prepare("INSERT INTO options_research_stages(account_id,symbol,research_version,stage) VALUES(?,?,?,?) ON CONFLICT DO NOTHING").bind(accountId,symbol,OPTIONS_RESEARCH_VERSION,name).run();
 await stage('SCREENED','COMPLETE',{source:'Supported universe or explicit ticker request'});
 const research=await marketResearchInputs(db,symbol,Boolean(body.force),stage);
 await stage('VOLATILITY_ANALYSIS','REFRESHING');let chain:Row={snapshots:{},feed:process.env.ALPACA_OPTIONS_FEED||'indicative'},chainError:string|null=null;
 try{chain=await optionsChain(symbol,Boolean(body.force));await stage('CHAIN_QUALIFIED',Object.keys(chain.snapshots||{}).length?'COMPLETE':'PARTIAL',{contracts:Object.keys(chain.snapshots||{}).length},Object.keys(chain.snapshots||{}).length?null:'NO_CONTRACTS_RETURNED');}catch(e){chainError=e instanceof Error?e.message:'CHAIN_PROVIDER_FAILED';await stage('CHAIN_QUALIFIED',/timeout|abort|budget/i.test(chainError)?'TIMED_OUT':'FAILED',{},chainError);}
 await stage('VOLATILITY_ANALYSIS',research.volatility.realized&&Object.keys(chain.snapshots).length?'COMPLETE':'PARTIAL',{...research.volatility,limitations:chain.limitations||[]},chainError||(!research.volatility.realized?'REALIZED_VOLATILITY_MISSING':null));
 await stage('ACCOUNT_RISK_FIT','REFRESHING');const risk=await accountRiskSettings(db,householdId,accountId);
 const reserved=await db.prepare("SELECT COALESCE(SUM(CASE WHEN status='ROTATION_READY' THEN (allocation_json->>'reservedCash')::numeric ELSE (plan_json->>'reservedCash')::numeric END),0)::text value FROM trade_lifecycle_exits WHERE account_id=? AND status IN ('REENTRY_WATCH','REENTRY_READY','ROTATION_READY')").bind(accountId).first<Row>();
 const cash=Math.max(0,risk.cash-risk.value*risk.effective.cashReserveBps/10000-Number(reserved?.value||0)),premiumCap=Math.min(cash,risk.value*risk.effective.optionsRiskBps/10000,body.maxRisk==null?Infinity:Math.max(0,Number(body.maxRisk)||0));
 await stage('ACCOUNT_RISK_FIT','COMPLETE',{cash,premiumCap,optionsEnabled:risk.effective.optionsEnabled});
 await stage('CONTRACT_SEARCH','REFRESHING',{expectation:research.technical.expectation});
 const ranked=rankOptionContracts(chain,research,{cash,premiumCap,optionsEnabled:risk.effective.optionsEnabled,intradayConfirmed:false});
 await stage('CONTRACT_SEARCH',chainError?'PARTIAL':'COMPLETE',{contracts:ranked.length,expectation:research.technical.expectation},chainError);
 const shown=[...ranked.filter(r=>r.type==='CALL').slice(0,8),...ranked.filter(r=>r.type==='PUT').slice(0,8)].sort((a,b)=>Number(b.qualified)-Number(a.qualified)||b.quality-a.quality);
 await stage('CONTRACT_RANKING','COMPLETE',{ranked:ranked.length,call:ranked.filter(r=>r.type==='CALL'&&r.qualified).length,put:ranked.filter(r=>r.type==='PUT'&&r.qualified).length,rejected:ranked.filter(r=>r.decision==='NO OPTION TRADE').length,scoring:'Evidence, volatility, liquidity, spread, Delta, Theta and DTE'});
 const owned=await db.prepare("SELECT COALESCE(SUM(h.quantity),0)::text shares,CASE WHEN SUM(h.quantity)>0 THEN SUM(h.cost_basis_cents)/SUM(h.quantity)/100 END average_cost FROM holdings h JOIN securities s ON s.id=h.security_id WHERE h.account_id=? AND s.ticker=?").bind(accountId,symbol).first<Row>();
 const errors={...research.stageErrors,...(chainError?{CHAIN_QUALIFIED:chainError}:{})},qualified=shown.filter(r=>r.qualified),partial=Object.keys(errors).length>0||!research.marketFresh;
 const best=qualified[0],decisionLabel=best?.decision||(!research.technical.direction?'WAIT':ranked.some(r=>r.reasons.some(s=>/time decay|Spread|premium/.test(s)))?'SHARES PREFERRED':'NO OPTION TRADE');
 const result:Row={underlying:symbol,underlyingPrice:research.quote.last||null,asOf:research.asOf,analyzedAt:new Date().toISOString(),account:{id:accountId,name:account.name,strategy:account.strategy_type},researchVersion:OPTIONS_RESEARCH_VERSION,status:best?'RESEARCH':'NO_TRADE',analysisState:partial?'INCOMPLETE':best?'QUALIFIED':'COMPLETE',freshness:partial?'PARTIAL':'COMPLETE',decisionLabel,researchOnly:nextOpenResearch(),researchQualified:Boolean(best),executionReady:false,contract:null,researchDecisions:shown,expectation:research.technical,stageErrors:errors,rationale:research.technical.evidence,missing:research.limitations,coverage:{contractsSearched:ranked.length,qualified:qualified.length,rejected:ranked.filter(r=>r.decision==='NO OPTION TRADE').length},holdingComparison:{shares:Number(owned?.shares||0),stockAverageCost:owned?.average_cost==null?null:Number(owned.average_cost),optionPremiumSeparate:true,decision:Number(owned?.shares)>0?(research.technical.direction==='CALL'?'Compare adding shares with limited-risk CALL premium; avoid increasing concentration without account room.':research.technical.direction==='PUT'?'Compare holding/trim with a protective PUT. Hedge construction is not enabled; these are directional research contracts only.':'HOLD / review existing exposure; no directional option thesis.'):'No shares recorded; compare a new share position, option premium and cash.'},decision:{action:best?'PREPARE':'WAIT',shares:0,providerStatus:'DETERMINISTIC_RESEARCH',confidence:research.technical.confidence,confidenceBand:'EVIDENCE_SCORE',interpretation:best?'Research-ranked option; confirm current quote, underlying trigger, account permission and risk before acting.':Object.values(errors).join('; ')||'No contract passes the current directional, volatility and liquidity requirements.',whatWouldChange:['Updated expectation, confirmed technical trigger, cleared catalyst risk and a contract within account capacity.'],reasoningFactors:research.technical.evidence,dataQuality:Math.max(0,100-Object.keys(errors).length*12)}};
 const previous=await db.prepare('SELECT decision_json FROM options_account_decisions WHERE account_id=? AND symbol=?').bind(accountId,symbol).first<Row>();
 if(partial&&previous){result.lastValidResearch=[...(previous.decision_json.researchDecisions||[]),...(previous.decision_json.lastValidResearch||[])].filter((r:Row)=>r.qualified).map((r:Row)=>({...r,executionReady:false,freshness:'STALE',decision:'WAIT',reasons:['Refresh incomplete; saved research must be revalidated',...(r.reasons||[])]}));}
 await db.transaction(async tx=>{await tx.prepare('INSERT INTO options_account_decisions(account_id,symbol,decision_json) VALUES(?,?,?::jsonb) ON CONFLICT(account_id,symbol) DO UPDATE SET decision_json=EXCLUDED.decision_json,updated_at=CURRENT_TIMESTAMP').bind(accountId,symbol,JSON.stringify(result)).run();await tx.prepare('INSERT INTO options_account_history(id,account_id,symbol,decision_json) VALUES(?,?,?,?::jsonb)').bind(id('option_research'),accountId,symbol,JSON.stringify(result)).run();});
 await stage('DECISION',partial?'PARTIAL':'COMPLETE',{expectation:research.technical.expectation,decision:decisionLabel,qualified:qualified.length,asOf:research.asOf},partial?'Some research stages need refresh':null);
 return {result,retryable:partial};
}
