import {id,type PostgresDatabase} from '@/lib/db';
export const OPTIONS_RESEARCH_VERSION='options-research-v2';
export const OPTION_STAGES=['SCREENED','CHAIN_QUALIFIED','UNDERLYING_RESEARCH','VOLATILITY_ANALYSIS','TECHNICAL_ANALYSIS','FUNDAMENTAL_ANALYSIS','NEWS_CATALYST','MARKET_SECTOR_REGIME','ACCOUNT_RISK_FIT','CONTRACT_SEARCH','CONTRACT_RANKING','DECISION'];
export async function queueOptionResearch(db:PostgresDatabase,householdId:string,accountId:string,symbol:string,manual=false,priority=0){
 return db.transaction(async tx=>{
  const account=await tx.prepare('SELECT a.id FROM accounts a JOIN entities e ON e.id=a.entity_id WHERE a.id=? AND e.household_id=? AND a.hidden=0 FOR UPDATE OF a').bind(accountId,householdId).first();if(!account)throw Error('ACCOUNT_NOT_FOUND');
  const active=await tx.prepare("SELECT id,status,updated_at FROM background_jobs WHERE job_type='OPTIONS_ACCOUNT_REVIEW' AND payload_json->>'accountId'=? AND payload_json->>'symbol'=? AND status IN ('QUEUED','RUNNING','FAILED') AND attempts<6 ORDER BY created_at LIMIT 1").bind(accountId,symbol).first<any>();
  if(active){if(manual&&active.status!=='RUNNING')await tx.prepare("UPDATE background_jobs SET payload_json=payload_json||?::jsonb,available_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify({manual:true,force:true,researchVersion:OPTIONS_RESEARCH_VERSION}),active.id).run();return {jobId:active.id,status:active.status==='RUNNING'?'REFRESHING':'QUEUED',deduplicated:true};}
  const jobId=id('options_research');await tx.prepare("INSERT INTO background_jobs(id,household_id,job_type,idempotency_key,payload_json) VALUES(?,?,'OPTIONS_ACCOUNT_REVIEW',?,?::jsonb)").bind(jobId,householdId,jobId,JSON.stringify({accountId,symbol,manual,force:manual,priority,researchVersion:OPTIONS_RESEARCH_VERSION})).run();
  await tx.prepare("INSERT INTO options_research_stages(account_id,symbol,research_version,stage,status,job_id) SELECT ?,?,?,stage,'QUEUED',? FROM unnest(?::text[]) stage ON CONFLICT(account_id,symbol,research_version,stage) DO UPDATE SET status='QUEUED',job_id=EXCLUDED.job_id,freshness='QUEUED',next_retry_at=NULL,updated_at=CURRENT_TIMESTAMP").bind(accountId,symbol,OPTIONS_RESEARCH_VERSION,jobId,OPTION_STAGES).run();
  return {jobId,status:'QUEUED',deduplicated:false};
 });
}
export async function optionStage(db:PostgresDatabase,accountId:string,symbol:string,stage:string,status:string,details:Record<string,any>={},error:string|null=null){
 return db.prepare(`INSERT INTO options_research_stages(account_id,symbol,research_version,stage,status,started_at,completed_at,last_error,freshness,details_json,next_retry_at,retry_count) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP,CASE WHEN ?<>'REFRESHING' THEN CURRENT_TIMESTAMP END,?,?,?::jsonb,CASE WHEN ?::text IS NOT NULL THEN CURRENT_TIMESTAMP+INTERVAL '1 minute' END,CASE WHEN ?::text IS NOT NULL THEN 1 ELSE 0 END) ON CONFLICT(account_id,symbol,research_version,stage) DO UPDATE SET status=EXCLUDED.status,started_at=CASE WHEN EXCLUDED.status='REFRESHING' THEN CURRENT_TIMESTAMP ELSE options_research_stages.started_at END,completed_at=EXCLUDED.completed_at,last_error=EXCLUDED.last_error,freshness=EXCLUDED.freshness,details_json=EXCLUDED.details_json,retry_count=options_research_stages.retry_count+CASE WHEN EXCLUDED.last_error IS NOT NULL THEN 1 ELSE 0 END,next_retry_at=CASE WHEN EXCLUDED.last_error IS NOT NULL THEN CURRENT_TIMESTAMP+(LEAST(3600,30*POWER(2,LEAST(options_research_stages.retry_count,7))) * INTERVAL '1 second') END,updated_at=CURRENT_TIMESTAMP`).bind(accountId,symbol,OPTIONS_RESEARCH_VERSION,stage,status,status,error,status==='COMPLETE'?'FRESH':status,JSON.stringify(details),error,error).run();
}
