import {QuantDataProvider} from "@/lib/providers/quant-data";
import {providerSignal} from "@/lib/work-budget";
import{createHash}from"node:crypto";
import{id,type PostgresDatabase}from"@/lib/db";
import{loadRuntimeSecrets}from"@/lib/runtime-secrets";
type J=Record<string,any>;
type Direction="BULLISH"|"BEARISH"|"NEUTRAL"|"UNKNOWN";
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0,clamp=(v:number)=>Math.max(0,Math.min(100,Math.round(v))),json=(v:unknown,f:any)=>{if(v&&typeof v==="object")return v;try{return JSON.parse(String(v))}catch{return f}};
const eventId=(e:J)=>String(e.id||e.eventId||createHash("sha256").update(JSON.stringify([e.symbol,e.contractSymbol,e.timestamp,e.price,e.size,e.premium])).digest("hex"));
export function classifyFlow(raw:J,settings:J){
 const optionType=String(raw.optionType||raw.type||"").toUpperCase(),trade=n(raw.tradePrice??raw.price),bid=n(raw.bid),ask=n(raw.ask),contracts=Math.round(n(raw.contracts??raw.size)),premium=n(raw.premiumCents)?n(raw.premiumCents):Math.round(trade*contracts*10000),oi=Math.round(n(raw.openInterest)),volume=Math.round(n(raw.volume)),volumeOi=oi>0?volume/oi:volume>0?99:0,atAsk=ask>0&&trade>=ask*.995,atBid=bid>0&&trade<=bid*1.005,aggression=atAsk?"AT_OR_ABOVE_ASK":atBid?"AT_OR_BELOW_BID":"MID_OR_UNKNOWN",opening=volume>oi&&oi>0?"OPENING_LIKELY":raw.opening===true?"OPENING_LIKELY":raw.closing===true?"CLOSING_LIKELY":"UNKNOWN",isSweep=Boolean(raw.isSweep)||/sweep/i.test(String(raw.providerClassification||raw.classification||"")),repeated=Boolean(raw.repeated)||n(raw.repeatCount)>=2;
 let direction:Direction="UNKNOWN";if(atAsk)direction=optionType==="CALL"?"BULLISH":optionType==="PUT"?"BEARISH":"UNKNOWN";else if(atBid)direction=optionType==="CALL"?"BEARISH":optionType==="PUT"?"BULLISH":"UNKNOWN";
 const reasons:string[]=[];let score=10;if(premium>=n(settings.golden_min_premium_cents)){score+=22;reasons.push("Institutional-size premium")}else if(premium>=25000000){score+=12;reasons.push("Large premium")};if(volumeOi>=1.5){score+=18;reasons.push(`Volume/OI ${volumeOi.toFixed(1)}×`)}if(contracts>=n(settings.golden_min_contracts)){score+=12;reasons.push("Large contract count")}if(atAsk||atBid){score+=14;reasons.push(`Aggressive ${aggression.toLowerCase().replaceAll("_"," ")} execution`)}if(isSweep){score+=12;reasons.push("Sweep routing reported")}if(repeated){score+=12;reasons.push("Repeated strike/expiration activity")}if(opening==="OPENING_LIKELY"){score+=8;reasons.push("Volume suggests a possible opening position")}if(direction==="UNKNOWN"){score-=18;reasons.push("Direction cannot be inferred safely")}if(raw.multiLeg){score-=18;reasons.push("Possible multi-leg strategy reduces directional confidence")}
 const conviction=clamp(score),golden=isSweep&&premium>=n(settings.golden_min_premium_cents)&&contracts>=n(settings.golden_min_contracts)&&volumeOi>=n(settings.golden_min_volume_oi)&&aggression!=="MID_OR_UNKNOWN",classification=golden?"GOLDEN_HIGH_CONVICTION_SWEEP":repeated&&isSweep?"REPEATED_SWEEP":isSweep?`${direction}_SWEEP`:premium>=25000000?"LARGE_PREMIUM":"UNUSUAL_FLOW";
 return{optionType,direction,trade,bid,ask,contracts,premium,oi,volume,volumeOi,aggression,opening,conviction,classification,reasons,isSweep,golden}
}
async function symbols(db:PostgresDatabase){const r=await db.prepare("SELECT DISTINCT symbol FROM market_watchlist UNION SELECT DISTINCT s.ticker symbol FROM holdings h JOIN securities s ON s.id=h.security_id WHERE s.ticker IS NOT NULL UNION SELECT symbol FROM market_discovery_candidates WHERE status<>'REJECTED' ORDER BY symbol LIMIT 250").all<{symbol:string}>();return r.results.map(x=>String(x.symbol).toUpperCase()).filter(Boolean)}
export async function evaluateOptionsFlow(db:PostgresDatabase){
 await loadRuntimeSecrets();const universe=await symbols(db),settings=await db.prepare("SELECT * FROM options_flow_settings WHERE id='global'").first<J>()||{},url=process.env.OPTIONS_FLOW_PROVIDER_URL,token=process.env.OPTIONS_FLOW_PROVIDER_TOKEN,asOf=new Date().toISOString();
 if(!url||!token){for(const symbol of universe)await db.prepare("INSERT INTO options_flow_summaries(symbol,source_mode,provider_status,provider_error,data_as_of) VALUES(?,'LIMITED_CHAIN_SNAPSHOT','NOT_CONFIGURED','Dedicated raw-print options-flow provider is not configured; Alpaca chain snapshots are not labeled as sweeps.',?) ON CONFLICT(symbol) DO UPDATE SET source_mode=EXCLUDED.source_mode,provider_status=EXCLUDED.provider_status,provider_error=EXCLUDED.provider_error,data_as_of=EXCLUDED.data_as_of,updated_at=CURRENT_TIMESTAMP").bind(symbol,asOf).run();return{status:"not_configured",symbols:universe.length,events:0,reason:"No raw-print options-flow provider configured; no sweep or dark-pool event was fabricated."}}
 const response=await fetch(url,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({symbols:universe,include:["options_flow","dark_pool","gamma"],sinceMinutes:10}),cache:"no-store",signal:providerSignal(30000)});if(!response.ok)throw new Error(`OPTIONS_FLOW_PROVIDER_${response.status}`);const payload=await response.json()as J,events=Array.isArray(payload.events)?payload.events:[],bySymbol=new Map<string,J[]>();
 for(const raw of events){const symbol=String(raw.symbol||"").toUpperCase();if(!symbol)continue;const c=classifyFlow(raw,settings),provider=String(payload.provider||raw.provider||"configured-flow-provider"),pid=eventId(raw),occurred=String(raw.timestamp||raw.occurredAt||asOf),cluster=String(raw.clusterKey||`${symbol}:${raw.contractSymbol||""}:${occurred.slice(0,13)}`);await db.prepare("INSERT INTO options_flow_events(id,provider_event_id,provider,symbol,contract_symbol,option_type,strike_cents,expiration,occurred_at,underlying_price_cents,trade_price_cents,bid_cents,ask_cents,contracts,premium_cents,volume,open_interest,volume_oi_ratio,implied_volatility,delta,gamma,theta,vega,exchange_routes_json,raw_json,provider_classification,northstar_classification,direction,opening_likelihood,execution_aggression,conviction_score,reasons_json,next_day_oi_confirmed,cluster_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(provider,provider_event_id) DO NOTHING").bind(id("flow"),pid,provider,symbol,raw.contractSymbol||null,c.optionType||null,Math.round(n(raw.strike)*100),raw.expiration||null,occurred,Math.round(n(raw.underlyingPrice)*100),Math.round(c.trade*100),Math.round(c.bid*100),Math.round(c.ask*100),c.contracts,c.premium,c.volume,c.oi,c.volumeOi,n(raw.impliedVolatility),n(raw.delta),n(raw.gamma),n(raw.theta),n(raw.vega),JSON.stringify(raw.exchangeRoutes||[]),JSON.stringify(raw),raw.providerClassification||raw.classification||null,c.classification,c.direction,c.opening,c.aggression,c.conviction,JSON.stringify(c.reasons),raw.nextDayOiConfirmed??null,cluster).run();const list=bySymbol.get(symbol)||[];list.push({...raw,...c,occurredAt:occurred});bySymbol.set(symbol,list)}
 for(const symbol of universe){const list=(bySymbol.get(symbol)||[]).sort((a,b)=>b.premium-a.premium),calls=list.filter(x=>x.optionType==="CALL"),puts=list.filter(x=>x.optionType==="PUT"),bull=list.filter(x=>x.direction==="BULLISH").reduce((s,x)=>s+x.premium,0),bear=list.filter(x=>x.direction==="BEARISH").reduce((s,x)=>s+x.premium,0),conviction=list.length?Math.round(list.reduce((s,x)=>s+x.conviction,0)/list.length):0,trend=bull>bear*1.5?"BULLISH_ACCELERATING":bear>bull*1.5?"BEARISH_ACCELERATING":list.length?"MIXED":"INSUFFICIENT_DATA";await db.prepare("INSERT INTO options_flow_summaries(symbol,source_mode,net_call_premium_cents,net_put_premium_cents,bullish_premium_cents,bearish_premium_cents,sweep_count,high_conviction_count,largest_trades_json,timeline_json,dark_pool_levels_json,gex_json,call_wall_cents,put_wall_cents,zero_gamma_cents,flow_trend,institutional_conviction,provider_status,provider_error,data_as_of) VALUES(?,'RAW_PRINTS',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'CONNECTED',NULL,?) ON CONFLICT(symbol) DO UPDATE SET source_mode=EXCLUDED.source_mode,net_call_premium_cents=EXCLUDED.net_call_premium_cents,net_put_premium_cents=EXCLUDED.net_put_premium_cents,bullish_premium_cents=EXCLUDED.bullish_premium_cents,bearish_premium_cents=EXCLUDED.bearish_premium_cents,sweep_count=EXCLUDED.sweep_count,high_conviction_count=EXCLUDED.high_conviction_count,largest_trades_json=EXCLUDED.largest_trades_json,timeline_json=EXCLUDED.timeline_json,dark_pool_levels_json=EXCLUDED.dark_pool_levels_json,gex_json=EXCLUDED.gex_json,call_wall_cents=EXCLUDED.call_wall_cents,put_wall_cents=EXCLUDED.put_wall_cents,zero_gamma_cents=EXCLUDED.zero_gamma_cents,flow_trend=EXCLUDED.flow_trend,institutional_conviction=EXCLUDED.institutional_conviction,provider_status='CONNECTED',provider_error=NULL,data_as_of=EXCLUDED.data_as_of,updated_at=CURRENT_TIMESTAMP").bind(symbol,calls.reduce((s,x)=>s+x.premium,0),puts.reduce((s,x)=>s+x.premium,0),bull,bear,list.filter(x=>x.isSweep).length,list.filter(x=>x.conviction>=n(settings.high_conviction_threshold)).length,JSON.stringify(list.slice(0,8)),JSON.stringify(list.slice().sort((a,b)=>String(a.occurredAt).localeCompare(String(b.occurredAt))).slice(-40)),JSON.stringify(payload.darkPool?.[symbol]||[]),JSON.stringify(payload.gamma?.[symbol]||{}),Math.round(n(payload.gamma?.[symbol]?.callWall)*100)||null,Math.round(n(payload.gamma?.[symbol]?.putWall)*100)||null,Math.round(n(payload.gamma?.[symbol]?.zeroGamma)*100)||null,trend,conviction,asOf).run()}
 return{status:"completed",symbols:universe.length,events:events.length,sourceMode:"RAW_PRINTS"}
}
export async function optionsFlowForSymbol(db:PostgresDatabase,symbol:string){const normalized=symbol.toUpperCase(),stored=await db.prepare("SELECT * FROM options_flow_summaries WHERE symbol=?").bind(normalized).first<J>(),events=await db.prepare("SELECT * FROM options_flow_events WHERE symbol=? ORDER BY occurred_at DESC LIMIT 100").bind(normalized).all<J>(),summary:J=stored||{symbol:normalized,source_mode:"LIMITED_CHAIN_SNAPSHOT",provider_status:"NOT_CONFIGURED",provider_error:"Dedicated raw-print options-flow coverage is unavailable for this symbol. Northstar will not fabricate sweeps, dark-pool prints, or directional conviction.",data_as_of:new Date().toISOString(),flow_trend:"INSUFFICIENT_DATA",institutional_conviction:0};const quantData=await new QuantDataProvider(db).getEvidence(normalized).catch(()=>null);return{symbol:normalized,quantData,summary:{...summary,largest_trades:json(summary.largest_trades_json,[]),timeline:json(summary.timeline_json,[]),dark_pool_levels:json(summary.dark_pool_levels_json,[]),gex:json(summary.gex_json,{})} as J,events:events.results.map(e=>({...e,reasons:json(e.reasons_json,[]),exchange_routes:json(e.exchange_routes_json,[])}))}}
