import {id,workspace} from "@/lib/db";
export const dynamic="force-dynamic";

const validSymbol=(value:unknown)=>typeof value==="string"&&/^[A-Z.]{1,10}$/.test(value);

async function updateDailyMarks(db:any,householdId:string,trades:Array<Record<string,any>>){
  const symbols=[...new Set(trades.filter(t=>t.asset_type==="stock").map(t=>String(t.symbol)).filter(s=>validSymbol(s)))];
  if(!symbols.length||!process.env.ALPACA_API_KEY||!process.env.ALPACA_API_SECRET)return {status:"unavailable",prices:{}};
  try{
    const feed=process.env.ALPACA_DATA_FEED||"iex",response=await fetch(`https://data.alpaca.markets/v2/stocks/snapshots?symbols=${encodeURIComponent(symbols.join(","))}&feed=${encodeURIComponent(feed)}`,{headers:{"APCA-API-KEY-ID":process.env.ALPACA_API_KEY,"APCA-API-SECRET-KEY":process.env.ALPACA_API_SECRET},cache:"no-store"});
    if(!response.ok)return {status:"unavailable",prices:{}};
    const snapshots=await response.json() as Record<string,{latestTrade?:{p?:number};dailyBar?:{c?:number}}>;
    const marketDate=new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),markedAt=new Date().toISOString(),prices:Record<string,number>={};
    for(const symbol of symbols){const price=Number(snapshots[symbol]?.latestTrade?.p||snapshots[symbol]?.dailyBar?.c);if(!Number.isFinite(price)||price<=0)continue;prices[symbol]=price;await db.prepare("INSERT INTO paper_daily_marks(id,household_id,instrument,symbol,market_date,price,source,marked_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(household_id,instrument,market_date) DO UPDATE SET price=excluded.price,source=excluded.source,marked_at=excluded.marked_at").bind(id("mark"),householdId,symbol,symbol,marketDate,price,`Alpaca ${feed}`,markedAt).run()}
    return {status:Object.keys(prices).length?"live":"unavailable",prices,marketDate,markedAt,source:`Alpaca ${feed}`};
  }catch{return {status:"unavailable",prices:{}}}
}

export async function GET(request:Request){try{const{db,householdId}=await workspace(request);const trades=(await db.prepare("SELECT id,side,symbol,instrument,asset_type,practice_mode,quantity,unit_price,multiplier,total,note,contract_json,executed_at FROM paper_trades WHERE household_id=? ORDER BY executed_at DESC LIMIT 1000").bind(householdId).all()).results as Array<Record<string,any>>;const market=await updateDailyMarks(db,householdId,trades);const marks=(await db.prepare("SELECT instrument,symbol,market_date,price,source,marked_at FROM paper_daily_marks WHERE household_id=? ORDER BY market_date DESC,marked_at DESC LIMIT 2000").bind(householdId).all()).results;return Response.json({trades,marks,market},{headers:{"Cache-Control":"private, no-store"}})}catch(e){if(e instanceof Response)return e;throw e}}

export async function POST(request:Request){try{const{db,householdId,userId}=await workspace(request),b=await request.json() as Record<string,any>;if(!["BUY","SELL"].includes(b.side)||!validSymbol(b.symbol)||!["stock","call","put"].includes(b.assetType)||!["swing","long-term","options"].includes(b.practiceMode)||!Number.isFinite(Number(b.quantity))||Number(b.quantity)<=0||!Number.isFinite(Number(b.unitPrice))||Number(b.unitPrice)<=0)return Response.json({error:"Valid simulated trade details are required"},{status:400});const tradeId=id("paper"),executedAt=String(b.createdAt||new Date().toISOString()),instrument=String(b.instrument||b.symbol).slice(0,80),multiplier=b.assetType==="stock"?1:100,total=Number(b.unitPrice)*multiplier*Number(b.quantity);await db.batch([db.prepare("INSERT INTO paper_trades(id,household_id,user_id,side,symbol,instrument,asset_type,practice_mode,quantity,unit_price,multiplier,total,note,contract_json,executed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(tradeId,householdId,userId,b.side,b.symbol,instrument,b.assetType,b.practiceMode,Number(b.quantity),Number(b.unitPrice),multiplier,total,String(b.note||"No thesis recorded").slice(0,2000),b.contract?JSON.stringify(b.contract):null,executedAt),db.prepare("INSERT INTO audit_log(id,household_id,user_id,action,target_type,target_id,metadata_json) VALUES(?,?,?,?,?,?,?)").bind(id("audit"),householdId,userId,"paper_trade.created","paper_trade",tradeId,JSON.stringify({symbol:b.symbol,side:b.side,assetType:b.assetType}))]);return Response.json({id:tradeId,total,executedAt},{status:201})}catch(e){if(e instanceof Response)return e;throw e}}

export async function DELETE(request:Request){try{const{db,householdId,userId}=await workspace(request);await db.batch([db.prepare("DELETE FROM paper_daily_marks WHERE household_id=?").bind(householdId),db.prepare("DELETE FROM paper_trades WHERE household_id=?").bind(householdId),db.prepare("INSERT INTO audit_log(id,household_id,user_id,action,target_type,target_id) VALUES(?,?,?,?,?,?)").bind(id("audit"),householdId,userId,"paper_account.reset","household",householdId)]);return Response.json({ok:true})}catch(e){if(e instanceof Response)return e;throw e}}
