export type Migration = {
  id: string;
  description: string;
  statements: readonly string[];
};

export const migrations: readonly Migration[] = [
  {
    id: "0009_investment_domain_foundation",
    description: "Account strategies, investment ledger, theses, recommendations, and predictions",
    statements: [
      `CREATE TABLE IF NOT EXISTS investment_account_settings (
        account_id TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
        strategy_type TEXT NOT NULL CHECK(strategy_type IN ('SWING','GROWTH_5_7','RETIREMENT','CHILD_GROWTH','COLLEGE','AGGRESSIVE_GROWTH','DIVIDEND_INCOME','HOUSE_FUND','CAPITAL_PRESERVATION','CUSTOM')),
        share_mode TEXT NOT NULL DEFAULT 'WHOLE' CHECK(share_mode IN ('WHOLE','FRACTIONAL')),
        benchmark_symbol TEXT,
        goal_name TEXT NOT NULL,
        horizon_months INTEGER,
        risk_profile TEXT NOT NULL DEFAULT 'BALANCED' CHECK(risk_profile IN ('CONSERVATIVE','BALANCED','GROWTH','AGGRESSIVE')),
        maximum_position_bps INTEGER NOT NULL DEFAULT 1000 CHECK(maximum_position_bps BETWEEN 0 AND 10000),
        maximum_risk_bps INTEGER NOT NULL DEFAULT 50 CHECK(maximum_risk_bps BETWEEN 0 AND 10000),
        available_cash_cents BIGINT NOT NULL DEFAULT 0,
        policy_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS account_allocation_targets (
        id TEXT PRIMARY KEY,
        account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        category TEXT NOT NULL,
        target_bps INTEGER NOT NULL CHECK(target_bps BETWEEN 0 AND 10000),
        minimum_bps INTEGER CHECK(minimum_bps BETWEEN 0 AND 10000),
        maximum_bps INTEGER CHECK(maximum_bps BETWEEN 0 AND 10000),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(account_id, category)
      )`,
      `CREATE TABLE IF NOT EXISTS investment_transactions (
        id TEXT PRIMARY KEY,
        household_id TEXT NOT NULL REFERENCES households(id),
        account_id TEXT NOT NULL REFERENCES accounts(id),
        security_id TEXT REFERENCES securities(id),
        transaction_type TEXT NOT NULL CHECK(transaction_type IN ('BUY','SELL','DIVIDEND','DEPOSIT','WITHDRAWAL','INTEREST','FEE','TRANSFER','SPLIT')),
        trade_at TIMESTAMPTZ NOT NULL,
        settle_at TIMESTAMPTZ,
        quantity NUMERIC(28,8),
        price_cents BIGINT,
        amount_cents BIGINT NOT NULL,
        fee_cents BIGINT NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'USD',
        source TEXT NOT NULL CHECK(source IN ('MANUAL','PLAID','IMPORT')),
        external_id TEXT,
        transfer_account_id TEXT REFERENCES accounts(id),
        split_numerator NUMERIC(28,8),
        split_denominator NUMERIC(28,8),
        notes TEXT,
        reverses_transaction_id TEXT REFERENCES investment_transactions(id),
        created_by_user_id TEXT NOT NULL REFERENCES users(id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(account_id, source, external_id)
      )`,
      `CREATE TABLE IF NOT EXISTS tax_lots (
        id TEXT PRIMARY KEY,
        account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        security_id TEXT NOT NULL REFERENCES securities(id),
        opening_transaction_id TEXT NOT NULL REFERENCES investment_transactions(id),
        acquired_at TIMESTAMPTZ NOT NULL,
        original_quantity NUMERIC(28,8) NOT NULL CHECK(original_quantity > 0),
        remaining_quantity NUMERIC(28,8) NOT NULL CHECK(remaining_quantity >= 0),
        total_basis_cents BIGINT NOT NULL,
        remaining_basis_cents BIGINT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS tax_lot_disposals (
        id TEXT PRIMARY KEY,
        lot_id TEXT NOT NULL REFERENCES tax_lots(id),
        sell_transaction_id TEXT NOT NULL REFERENCES investment_transactions(id),
        quantity NUMERIC(28,8) NOT NULL CHECK(quantity > 0),
        basis_cents BIGINT NOT NULL,
        proceeds_cents BIGINT NOT NULL,
        realized_pnl_cents BIGINT NOT NULL,
        disposed_at TIMESTAMPTZ NOT NULL,
        UNIQUE(lot_id, sell_transaction_id)
      )`,
      `CREATE TABLE IF NOT EXISTS investment_theses (
        id TEXT PRIMARY KEY,
        account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        security_id TEXT NOT NULL REFERENCES securities(id),
        state TEXT NOT NULL CHECK(state IN ('STRONG','INTACT','WATCH','WEAKENING','BROKEN')),
        thesis TEXT NOT NULL,
        invalidation TEXT NOT NULL,
        evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        reviewed_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(account_id, security_id)
      )`,
      `CREATE TABLE IF NOT EXISTS recommendations (
        id TEXT PRIMARY KEY,
        household_id TEXT NOT NULL REFERENCES households(id),
        account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        security_id TEXT NOT NULL REFERENCES securities(id),
        strategy_type TEXT NOT NULL,
        action TEXT NOT NULL CHECK(action IN ('STRONG_BUY','BUY','BUY_PARTIAL','ACCUMULATE','HOLD','WAIT','WATCH','TAKE_PARTIAL_PROFIT','REDUCE','SELL','EXIT','THESIS_REVIEW','THESIS_BROKEN','EVENT_RISK')),
        lifecycle TEXT NOT NULL CHECK(lifecycle IN ('MONITORING','TRIGGERED','EXPIRED','CANCELLED','INVALIDATED','COMPLETED','MISSED')),
        suggested_quantity NUMERIC(28,8) NOT NULL DEFAULT 0,
        entry_low_cents BIGINT,
        entry_high_cents BIGINT,
        ideal_price_cents BIGINT,
        invalidation_cents BIGINT,
        targets_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        confidence INTEGER NOT NULL CHECK(confidence BETWEEN 0 AND 100),
        reason TEXT NOT NULL,
        checks_json JSONB NOT NULL,
        actionable BOOLEAN NOT NULL DEFAULT FALSE,
        model_version TEXT NOT NULL,
        evidence_as_of TIMESTAMPTZ NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS recommendation_triggers (
        id TEXT PRIMARY KEY,
        recommendation_id TEXT NOT NULL REFERENCES recommendations(id) ON DELETE CASCADE,
        trigger_type TEXT NOT NULL,
        condition_json JSONB NOT NULL,
        cooldown_until TIMESTAMPTZ,
        triggered_at TIMESTAMPTZ,
        last_evaluated_at TIMESTAMPTZ,
        status TEXT NOT NULL DEFAULT 'MONITORING'
      )`,
      `CREATE TABLE IF NOT EXISTS predictions (
        id TEXT PRIMARY KEY,
        household_id TEXT NOT NULL REFERENCES households(id),
        account_id TEXT REFERENCES accounts(id) ON DELETE CASCADE,
        security_id TEXT NOT NULL REFERENCES securities(id),
        horizon TEXT NOT NULL,
        model_version TEXT NOT NULL,
        feature_fingerprint TEXT NOT NULL,
        input_snapshot_json JSONB NOT NULL,
        scenarios_json JSONB NOT NULL,
        confidence INTEGER NOT NULL CHECK(confidence BETWEEN 0 AND 100),
        evidence_as_of TIMESTAMPTZ NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS prediction_points (
        id TEXT PRIMARY KEY,
        prediction_id TEXT NOT NULL REFERENCES predictions(id) ON DELETE CASCADE,
        scenario TEXT NOT NULL CHECK(scenario IN ('BULL','BASE','BEAR')),
        point_at TIMESTAMPTZ NOT NULL,
        price_cents BIGINT NOT NULL,
        lower_cents BIGINT,
        upper_cents BIGINT,
        UNIQUE(prediction_id, scenario, point_at)
      )`,
      `CREATE TABLE IF NOT EXISTS prediction_evaluations (
        prediction_id TEXT PRIMARY KEY REFERENCES predictions(id) ON DELETE CASCADE,
        actual_price_cents BIGINT NOT NULL,
        actual_at TIMESTAMPTZ NOT NULL,
        direction_correct BOOLEAN,
        inside_expected_range BOOLEAN,
        absolute_error_bps INTEGER,
        evaluated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS portfolio_snapshots (
        id TEXT PRIMARY KEY,
        household_id TEXT NOT NULL REFERENCES households(id),
        account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        captured_at TIMESTAMPTZ NOT NULL,
        market_value_cents BIGINT NOT NULL,
        cash_cents BIGINT NOT NULL,
        cost_basis_cents BIGINT NOT NULL,
        realized_pnl_cents BIGINT NOT NULL,
        unrealized_pnl_cents BIGINT NOT NULL,
        allocation_json JSONB NOT NULL,
        source_freshness_json JSONB NOT NULL,
        UNIQUE(account_id, captured_at)
      )`,
      `CREATE INDEX IF NOT EXISTS idx_investment_transactions_account_time ON investment_transactions(account_id, trade_at DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_investment_transactions_household_time ON investment_transactions(household_id, trade_at DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_tax_lots_account_security ON tax_lots(account_id, security_id, acquired_at)`,
      `CREATE INDEX IF NOT EXISTS idx_recommendations_account_created ON recommendations(account_id, created_at DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_recommendations_symbol_lifecycle ON recommendations(security_id, lifecycle, expires_at)`,
      `CREATE INDEX IF NOT EXISTS idx_predictions_security_created ON predictions(security_id, created_at DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_portfolio_snapshots_account_time ON portfolio_snapshots(account_id, captured_at DESC)`,
    ],
  },
  {
    id: "0010_persistent_alert_delivery",
    description: "Persistent alert delivery state and notification preferences",
    statements: [
      `CREATE TABLE IF NOT EXISTS alert_deliveries (
        id TEXT PRIMARY KEY,
        alert_id TEXT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        channel TEXT NOT NULL CHECK(channel IN ('IN_APP','BROWSER_PUSH','EMAIL')),
        status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','DELIVERED','FAILED','DISMISSED')),
        attempted_at TIMESTAMPTZ,
        delivered_at TIMESTAMPTZ,
        error_code TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(alert_id,user_id,channel)
      )`,
      `CREATE TABLE IF NOT EXISTS notification_preferences (
        household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        in_app_enabled BOOLEAN NOT NULL DEFAULT TRUE,
        browser_push_enabled BOOLEAN NOT NULL DEFAULT FALSE,
        email_enabled BOOLEAN NOT NULL DEFAULT FALSE,
        quiet_hours_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        timezone TEXT NOT NULL DEFAULT 'America/Phoenix',
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(household_id,user_id)
      )`,
      `CREATE INDEX IF NOT EXISTS idx_alerts_household_unread ON alerts(household_id,read_at,created_at DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_alert_deliveries_user_status ON alert_deliveries(user_id,status,created_at DESC)`,
    ],
  },
  {
    id: "0011_planned_actions",
    description: "Persistent non-executing action guidance plans",
    statements: [
      `CREATE TABLE IF NOT EXISTS planned_actions (
        id TEXT PRIMARY KEY,
        household_id TEXT NOT NULL REFERENCES households(id),
        account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        security_id TEXT REFERENCES securities(id),
        recommendation_id TEXT REFERENCES recommendations(id),
        action_type TEXT NOT NULL CHECK(action_type IN ('BUY_NOW','PLACE_ON_WATCH','WAIT_FOR_PRICE','BUY_ON_CONFIRMATION','SELL','REDUCE','TAKE_PROFIT','HOLD','DO_NOTHING')),
        lifecycle TEXT NOT NULL CHECK(lifecycle IN ('PROPOSED','MONITORING','READY','TRIGGERED','INVALIDATED','EXPIRED','COMPLETED','MISSED')),
        priority TEXT NOT NULL CHECK(priority IN ('CRITICAL','ACTION_NOW','READY_IF_PRICE_TRIGGERS','WATCH','NO_ACTION')),
        suggested_quantity NUMERIC(28,8) NOT NULL DEFAULT 0,
        target_total_quantity NUMERIC(28,8),
        entry_low_cents BIGINT,
        entry_high_cents BIGINT,
        preferred_price_cents BIGINT,
        invalidation_cents BIGINT,
        targets_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        conditions_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        capital_source_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        rationale TEXT NOT NULL,
        evidence_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        model_version TEXT NOT NULL,
        evidence_as_of TIMESTAMPTZ NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL,
        executed_transaction_id TEXT REFERENCES investment_transactions(id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS idx_planned_actions_account_priority ON planned_actions(account_id,lifecycle,priority,created_at DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_planned_actions_household_lifecycle ON planned_actions(household_id,lifecycle,expires_at)`,
      `CREATE INDEX IF NOT EXISTS idx_planned_actions_security ON planned_actions(security_id,account_id,created_at DESC)`,
    ],
  },
  {
    id: "0012_real_estate_operations",
    description: "Property ownership, operating activity, debt, occupancy, projects, watchlists, and historical performance",
    statements: [
      `ALTER TABLE properties ADD COLUMN IF NOT EXISTS use_type TEXT NOT NULL DEFAULT 'OTHER'`,
      `ALTER TABLE properties ADD COLUMN IF NOT EXISTS ownership_bps INTEGER NOT NULL DEFAULT 10000`,
      `ALTER TABLE properties ADD COLUMN IF NOT EXISTS acquisition_date DATE`,
      `ALTER TABLE properties ADD COLUMN IF NOT EXISTS include_in_net_worth BOOLEAN NOT NULL DEFAULT TRUE`,
      `ALTER TABLE properties ADD COLUMN IF NOT EXISTS include_in_cash_flow BOOLEAN NOT NULL DEFAULT TRUE`,
      `ALTER TABLE properties ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ACTIVE'`,
      `ALTER TABLE properties ADD COLUMN IF NOT EXISTS reserve_balance_cents BIGINT NOT NULL DEFAULT 0`,
      `ALTER TABLE properties ADD COLUMN IF NOT EXISTS target_reserve_cents BIGINT NOT NULL DEFAULT 0`,
      `CREATE TABLE IF NOT EXISTS property_loans (
        id TEXT PRIMARY KEY, property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
        lender TEXT, loan_type TEXT NOT NULL DEFAULT 'FIXED', original_balance_cents BIGINT,
        current_balance_cents BIGINT NOT NULL, interest_rate_bps INTEGER, monthly_payment_cents BIGINT,
        principal_payment_cents BIGINT, interest_payment_cents BIGINT, next_due_at DATE,
        maturity_date DATE, rate_reset_at DATE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS property_transactions (
        id TEXT PRIMARY KEY, property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
        transaction_id TEXT REFERENCES transactions(id) ON DELETE SET NULL, occurred_at DATE NOT NULL,
        direction TEXT NOT NULL CHECK(direction IN ('INCOME','EXPENSE')), category TEXT NOT NULL,
        amount_cents BIGINT NOT NULL, capital_improvement BOOLEAN NOT NULL DEFAULT FALSE,
        description TEXT, vendor TEXT, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS property_occupancies (
        id TEXT PRIMARY KEY, property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
        occupancy_type TEXT NOT NULL CHECK(occupancy_type IN ('TENANT','GUEST','OWNER','VACANT')),
        display_name TEXT, start_at DATE NOT NULL, end_at DATE, rent_cents BIGINT,
        deposit_cents BIGINT, status TEXT NOT NULL DEFAULT 'ACTIVE', metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb
      )`,
      `CREATE TABLE IF NOT EXISTS property_projects (
        id TEXT PRIMARY KEY, property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
        title TEXT NOT NULL, project_type TEXT NOT NULL DEFAULT 'MAINTENANCE', vendor TEXT,
        estimated_cost_cents BIGINT, actual_cost_cents BIGINT, status TEXT NOT NULL DEFAULT 'PLANNED',
        due_at DATE, warranty_expires_at DATE, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS property_budgets (
        id TEXT PRIMARY KEY, property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
        year INTEGER NOT NULL, category TEXT NOT NULL, budget_cents BIGINT NOT NULL,
        UNIQUE(property_id,year,category)
      )`,
      `CREATE TABLE IF NOT EXISTS property_snapshots (
        id TEXT PRIMARY KEY, property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
        captured_at DATE NOT NULL, estimated_value_cents BIGINT NOT NULL, debt_cents BIGINT NOT NULL DEFAULT 0,
        income_cents BIGINT NOT NULL DEFAULT 0, expense_cents BIGINT NOT NULL DEFAULT 0,
        noi_cents BIGINT NOT NULL DEFAULT 0, occupancy_bps INTEGER, source TEXT NOT NULL,
        UNIQUE(property_id,captured_at)
      )`,
      `CREATE TABLE IF NOT EXISTS property_opportunities (
        id TEXT PRIMARY KEY, household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
        name TEXT NOT NULL, address TEXT, strategy TEXT NOT NULL, asking_price_cents BIGINT,
        target_price_cents BIGINT, required_cap_rate_bps INTEGER, required_cash_flow_cents BIGINT,
        assumptions_json JSONB NOT NULL DEFAULT '{}'::jsonb, notes TEXT, status TEXT NOT NULL DEFAULT 'WATCH',
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS idx_property_transactions_property_date ON property_transactions(property_id,occurred_at DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_property_loans_property ON property_loans(property_id)`,
      `CREATE INDEX IF NOT EXISTS idx_property_projects_property_status ON property_projects(property_id,status,due_at)`,
      `CREATE INDEX IF NOT EXISTS idx_property_snapshots_property_date ON property_snapshots(property_id,captured_at DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_property_opportunities_household_status ON property_opportunities(household_id,status,updated_at DESC)`,
    ],
  },
] as const;
