import {workspace} from "@/lib/db";
export const dynamic="force-dynamic";
type Status="IMPLEMENTED"|"PARTIAL"|"NOT_IMPLEMENTED"|"PROVIDER_REQUIRED"|"BROKEN";
type Capability={id:string;category:string;name:string;status:Status;evidence:string;gap:string;route?:string;provider?:string};
const configured=(...names:string[])=>names.every(name=>Boolean(process.env[name]));
export async function GET(request:Request){try{const{db}=await workspace(request);const[worker,discovery,loop]=await Promise.all([db.prepare("SELECT status,last_success_at,last_error_at,error_code,heartbeat_at FROM worker_heartbeats WHERE worker_name='aws-market-worker'").first<Record<string,unknown>>(),db.prepare("SELECT status,completed_at,error_code,universe_size,screened_count,candidates_created FROM market_discovery_runs ORDER BY started_at DESC LIMIT 1").first<Record<string,unknown>>(),db.prepare("SELECT status,completed_at,error_code FROM intelligence_loop_runs ORDER BY created_at DESC LIMIT 1").first<Record<string,unknown>>()]);const market=configured("ALPACA_API_KEY","ALPACA_API_SECRET"),fundamentals=Boolean(process.env.FINNHUB_API_KEY),ai=Boolean(process.env.OPENAI_API_KEY),push=configured("VAPID_PUBLIC_KEY","VAPID_PRIVATE_KEY"),email=Boolean(process.env.RESEND_API_KEY),workerAt=worker?.heartbeat_at?new Date(String(worker.heartbeat_at)).getTime():0,workerFresh=workerAt>Date.now()-20*60_000,workerBroken=worker!==null&&(!workerFresh||String(worker.status).toUpperCase()==="ERROR");const items:Capability[]=[
{id:"charts-core",category:"Charts & research",name:"Candlesticks, timeframes and core indicators",status:market?"IMPLEMENTED":"PROVIDER_REQUIRED",provider:"Alpaca",route:"/workspace/charts",evidence:"Provider-backed OHLCV chart workspace includes SMA/EMA, VWAP, Bollinger Bands, RSI, MACD, ATR, Fibonacci, support/resistance and account decision overlays.",gap:market?"Automated visual-regression coverage remains limited.":"Configure Alpaca credentials for current bars and quotes."},
{id:"charts-orderflow",category:"Charts & research",name:"Footprint, TPO, volume delta and volume profile",status:"PROVIDER_REQUIRED",provider:"Tick-level/order-flow feed",route:"/workspace/charts",evidence:"Northstar stores classified options-flow evidence, but lacks exchange-grade bid/ask trade classification required for footprint or TPO rendering.",gap:"License an order-flow feed and implement provider-backed footprint/TPO/volume-delta series."},
{id:"chart-alerts",category:"Alerts & automation",name:"Server-side price and recommendation alerts",status:workerBroken?"BROKEN":market?"PARTIAL":"PROVIDER_REQUIRED",provider:"Alpaca + AWS worker",route:"/workspace/settings",evidence:"Durable alert preferences, background jobs, idempotency and Web Push/email delivery paths exist.",gap:workerBroken?"Market worker heartbeat/status is unhealthy.":"Indicator, drawing/trendline and arbitrary multi-condition alert authoring are not complete."},
{id:"scanner",category:"Discovery",name:"Full-market scanner and candidate discovery",status:String(discovery?.status)==="FAILED"?"BROKEN":market&&fundamentals?"PARTIAL":"PROVIDER_REQUIRED",provider:"Alpaca + Finnhub",route:"/workspace/new-candidates",evidence:`Persisted scheduled discovery scans the active U.S. directory. Latest run: ${discovery?.status||"never"}; universe ${discovery?.universe_size||0}, evaluated ${discovery?.screened_count||0}, accepted ${discovery?.candidates_created||0}.`,gap:"User-defined filters, saved/scheduled scans, chart-grid and heatmap views are not complete."},
{id:"watchlists",category:"Discovery",name:"Advanced watchlists",status:"PARTIAL",route:"/workspace/markets",evidence:"Persistent household watchlist supports purpose, target, invalidation, notes, quotes and monitoring.",gap:"Custom columns, multiple named lists, bulk operations and synchronized linked widgets are incomplete."},
{id:"risk",category:"Portfolio",name:"Portfolio Risk Center and stress tests",status:"PARTIAL",route:"/workspace/portfolio",evidence:"Account-aware concentration, effective exposure, overlap and market/sector/rate stress estimates exist.",gap:"Correlation matrix, beta, volatility, historical drawdown and an interactive add/remove/resize What-If simulator are incomplete."},
{id:"options-chain",category:"Options",name:"Professional options chain and analytics",status:market?"PARTIAL":"PROVIDER_REQUIRED",provider:"Alpaca options",route:"/workspace/options",evidence:"Single-contract selection exposes bid/ask, IV, delta, spread, DTE and breakeven; options-flow records support volume/OI and Greeks when supplied.",gap:"Complete calls/puts chain, gamma/theta/vega everywhere, IV surface, P/L surface and multi-leg strategy builder are incomplete."},
{id:"options-flow",category:"Options",name:"Unusual/institutional options flow",status:"PROVIDER_REQUIRED",provider:"Licensed options-flow feed",route:"/workspace/options",evidence:"Idempotent ingestion, classification, clusters and Northstar Flow Conviction Score are implemented for provider events.",gap:"No production-grade licensed event feed is guaranteed; provider-defined sweep labels cannot be inferred safely."},
{id:"paper",category:"Simulation",name:"Paper trading",status:market?"PARTIAL":"PROVIDER_REQUIRED",provider:"Alpaca market data",route:"/workspace/simulation",evidence:"Persistent simulated stock/call/put ledger, separate practice modes, current references and daily marks exist.",gap:"Order lifecycle, bid/ask fill model, configurable slippage/commissions, backtesting and full performance attribution are incomplete."},
{id:"performance",category:"Simulation",name:"Trading performance analytics",status:"PARTIAL",route:"/workspace/portfolio",evidence:"Recommendation audit/outcome and portfolio performance endpoints exist.",gap:"Universal trade-to-recommendation linkage, MAE/MFE, profit factor, expectancy and HOLD benchmark attribution are incomplete."},
{id:"news",category:"Intelligence",name:"Real-time News Intelligence",status:fundamentals?"PARTIAL":"PROVIDER_REQUIRED",provider:"Finnhub/news provider",route:"/workspace/market-news",evidence:"News is fetched for market research and can contribute to server-side alert evidence.",gap:"Complete story clustering, materiality ranking and automatic affected-security re-analysis need broader provider coverage and tests."},
{id:"decision",category:"Intelligence",name:"Authoritative account-specific AI Decision Engine",status:ai?(String(loop?.status)==="FAILED"?"BROKEN":"IMPLEMENTED"):"PROVIDER_REQUIRED",provider:"OpenAI + market providers",route:"/workspace/daily-action-plan",evidence:"Account-scoped decision runs separate company quality, valuation, technical setup, portfolio fit, regime and final action with an audit trail.",gap:ai?"Quality still depends on provider freshness and evidence coverage.":"Configure the server-side AI provider key."},
{id:"continuous-loop",category:"Intelligence",name:"Continuous intelligence loop",status:workerBroken?"BROKEN":workerFresh?"IMPLEMENTED":"PARTIAL",provider:"AWS scheduler/worker",route:"/workspace/system-health",evidence:`Durable Sync → Analyze → Predict → Recommend → Alert → Measure → Learn cycle exists. Worker: ${worker?.status||"no heartbeat"}.`,gap:workerBroken?"Restore worker health and confirm successful cycles.":"Continue production monitoring and outcome calibration."},
{id:"notifications",category:"Alerts & automation",name:"Closed-app push, in-app and email delivery",status:push?(email?"IMPLEMENTED":"PARTIAL"):"PROVIDER_REQUIRED",provider:"Web Push + Resend",route:"/workspace/settings",evidence:"Subscription registry, delivery queue, retry states, deep links, history, preferences and idempotency are implemented.",gap:!push?"Configure VAPID credentials.":!email?"Configure RESEND_API_KEY for email delivery.":"Delivery timing remains subject to platform/network constraints."},
{id:"linked-workspace",category:"Experience",name:"Linked ticker workspace",status:"PARTIAL",route:"/workspace/charts",evidence:"Selected ticker flows into chart, analysis, news/options requests and research detail routes.",gap:"Desktop resizable widget layouts and universal cross-panel synchronization are incomplete."},
{id:"mobile",category:"Experience",name:"Mobile-first critical workflows",status:"PARTIAL",route:"/workspace/dashboard",evidence:"Responsive mobile routes, PWA installation, safe areas, stacked cards and route-level overflow tests exist.",gap:"Full-screen touch chart gestures, options contract cards across the complete chain, and CI device coverage need expansion."},
];const counts=items.reduce<Record<string,number>>((a,item)=>(a[item.status]=(a[item.status]||0)+1,a),{});return Response.json({generatedAt:new Date().toISOString(),counts,providers:{market,fundamentals,ai,push,email},runtime:{worker,discovery,loop},items},{headers:{"Cache-Control":"private, no-store"}})}catch(error){if(error instanceof Response)return error;return Response.json({error:"Capability audit is temporarily unavailable.",detail:process.env.NODE_ENV==="development"?(error instanceof Error?error.message:String(error)):undefined},{status:500})}}
