import{expect,test}from"@playwright/test";

const routes=[
 ["Today","/workspace/daily-action-plan"],["Portfolio","/workspace/portfolio"],["Investment Account","/workspace/investment-account"],
 ["Security Detail","/workspace/security-detail"],["New Candidates","/workspace/new-candidates"],["Options","/workspace/options"],
 ["Options Detail","/workspace/options-detail"],["Markets","/workspace/charts"],["Household Finance","/workspace/household"],
 ["Accounts","/workspace/accounts"],["Transactions","/workspace/transactions"],["Spending","/workspace/spending"],
 ["Budgets","/workspace/budgets"],["Debt","/workspace/debt"],["Notifications","/workspace/notifications"],
 ["Kids / Goals","/workspace/kids-goals"],["Settings","/workspace/settings"],["System Health","/workspace/system-health"],
]as const;
const viewports=[{name:"360x800",width:360,height:800},{name:"375x812",width:375,height:812},{name:"390x844",width:390,height:844},{name:"393x852",width:393,height:852},{name:"412x915",width:412,height:915},{name:"430x932",width:430,height:932},{name:"768-tablet",width:768,height:1024},{name:"1440-desktop",width:1440,height:1000}]as const;

for(const viewport of viewports)test.describe(viewport.name,()=>{test.use({viewport:{width:viewport.width,height:viewport.height}});for(const[name,path]of routes)test(`${name} has no horizontal overflow`,async({page})=>{await page.goto(path,{waitUntil:"domcontentloaded"});await page.waitForLoadState("networkidle").catch(()=>undefined);await expect(page.locator('main[aria-label="Checking secure sign-in"]')).toHaveCount(0,{timeout:20_000});expect(await page.locator(".auth-page").count(),"Authenticated E2E storage is required; set NORTHSTAR_E2E_STORAGE_STATE").toBe(0);const metrics=await page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,offenders:[...document.querySelectorAll<HTMLElement>("body *")].map(element=>{const box=element.getBoundingClientRect();return{tag:element.tagName,className:String(element.className).slice(0,140),left:box.left,right:box.right,width:box.width}}).filter(item=>item.right>document.documentElement.clientWidth+2||item.left<-2).slice(0,15)}));expect(metrics.offenders,JSON.stringify(metrics.offenders,null,2)).toEqual([]);expect(metrics.scrollWidth).toBeLessThanOrEqual(metrics.clientWidth+2);await expect(page.locator("main.workspace-view")).toBeVisible();if(viewport.width<=768){await expect(page.locator(".mobile-bottom-navigation")).toBeVisible();await expect(page.locator(".app-sidebar")).not.toBeInViewport()}else{await expect(page.locator(".mobile-bottom-navigation")).toBeHidden();await expect(page.locator(".app-sidebar")).toBeVisible()}const primary=page.locator("main.workspace-view button:visible,main.workspace-view a:visible").first();await expect(primary).toBeVisible();await page.screenshot({path:`test-results/mobile/${viewport.name}/${name.replaceAll(/[^a-z0-9]+/gi,"-").toLowerCase()}.png`,fullPage:true})})});
