import {inspectServerConfiguration} from '@/lib/server-configuration';
import {workspace,id} from "@/lib/db";
import {GLOBAL_DEFAULTS,validateGlobalSettings} from "@/lib/app-configuration";
import {accountRiskSettings} from "@/lib/account-risk-settings";
import {validateTradingPolicy} from "@/lib/trading-policy";
import {PROVIDERS,providerConfiguration,testProvider,type Provider} from "@/lib/provider-health";
export const dynamic="force-dynamic";
export async function GET(request:Request){try{
  const {db,householdId,userId}=await workspace(request),configured=await providerConfiguration(),saved=await db.prepare("SELECT settings_json FROM app_user_settings WHERE household_id=? AND user_id=?").bind(householdId,userId).first<{settings_json:typeof GLOBAL_DEFAULTS}>();
  const accounts=await db.prepare("SELECT a.id,COALESCE(a.nickname,a.name) name FROM accounts a JOIN entities e ON e.id=a.entity_id WHERE e.household_id=? AND a.type='investment' AND a.hidden=0").bind(householdId).all<{id:string;name:string}>();
  const risk=[];for(const a of accounts.results)risk.push({...await accountRiskSettings(db,householdId,a.id),name:a.name});
  const health=await db.prepare("SELECT provider,status,last_success_at,last_error,checked_at FROM provider_health_checks").all<{provider:string;status:string;last_success_at:string;last_error:string;checked_at:string}>();
  const providers=PROVIDERS.map(name=>{const state=health.results.find(h=>h.provider===name);return {name,configured:configured[name],status:!configured[name]?"NOT CONFIGURED":state?.status||"DEGRADED",lastSuccess:state?.last_success_at||null,lastError:state?.last_error||null,lastTest:state?.checked_at||null,environment:name.startsWith("Plaid")?process.env.PLAID_ENV:null};});
  return Response.json({serverConfiguration:inspectServerConfiguration(process.env),settings:saved?.settings_json||GLOBAL_DEFAULTS,defaults:GLOBAL_DEFAULTS,accounts:risk,providers,configurationHealth:providers.some(p=>!p.configured)?"Missing Provider":providers.some(p=>p.status!=="HEALTHY")?"Needs Attention":"Ready"},{headers:{"Cache-Control":"private, no-store"}});
}catch(e){if(e instanceof Response)return e;return Response.json({error:"Configuration unavailable"},{status:503});}}
export async function PUT(request:Request){try{
  const {db,householdId,userId,role}=await workspace(request),body=await request.json() as Record<string,unknown>;
  if(body.accountId||body.testProvider){if(!["owner","co_owner","manager","investment_manager"].includes(role))return Response.json({error:"Account manager permission required"},{status:403});}
  if(body.testProvider){if(!PROVIDERS.includes(body.testProvider as Provider))throw Error("Unknown provider");let result;try{result=await testProvider(body.testProvider as Provider);}catch{result={status:"ERROR",error:"PROVIDER_REQUEST_FAILED"};}await db.prepare("INSERT INTO provider_health_checks(provider,status,last_success_at,last_error) VALUES(?,?,CASE WHEN ? THEN CURRENT_TIMESTAMP END,?) ON CONFLICT(provider) DO UPDATE SET status=EXCLUDED.status,last_success_at=COALESCE(EXCLUDED.last_success_at,provider_health_checks.last_success_at),last_error=EXCLUDED.last_error,checked_at=CURRENT_TIMESTAMP").bind(body.testProvider,result.status,result.status==="HEALTHY",result.error).run();return Response.json(result);}
  if(body.accountId){const current=await accountRiskSettings(db,householdId,String(body.accountId)),health=await db.prepare("SELECT provider FROM provider_health_checks WHERE status='HEALTHY' AND checked_at>CURRENT_TIMESTAMP-INTERVAL '15 minutes'").all<{provider:string}>(),names=new Set(health.results.map(h=>h.provider));const next=body.restore===true?current.recommended:validateTradingPolicy(body.policy,current.recommended,{intraday:names.has("Market Data"),options:names.has("Options")},body.acceptHigherRisk===true);
    await db.transaction(async tx=>{await tx.prepare("UPDATE account_risk_config SET custom_json=?,updated_at=CURRENT_TIMESTAMP WHERE account_id=?").bind(body.restore===true?null:JSON.stringify(next),body.accountId).run();await tx.prepare("UPDATE investment_account_settings SET maximum_risk_bps=?,maximum_position_bps=?,policy_json=jsonb_set(COALESCE(policy_json,'{}'::jsonb),'{tradingPolicy}',?::jsonb),updated_at=CURRENT_TIMESTAMP WHERE account_id=?").bind(next.swingRiskBps,next.maxPositionBps,JSON.stringify(next),body.accountId).run();await tx.prepare("INSERT INTO audit_log(id,household_id,user_id,action,target_type,target_id,metadata_json) VALUES(?,?,?,'risk_policy_changed','account',?,?)").bind(id("audit"),householdId,userId,body.accountId,JSON.stringify({previous:current.effective,next,acceptedHigherRisk:body.acceptHigherRisk===true})).run();await tx.prepare("UPDATE recommendations SET actionable=FALSE,pipeline_status='INCOMPLETE' WHERE account_id=? AND household_id=?").bind(body.accountId,householdId).run();await tx.prepare("INSERT INTO background_jobs(id,household_id,job_type,idempotency_key,payload_json) VALUES(?,?,'ACCOUNT_INTELLIGENCE_LOOP',?,?)").bind(id("job"),householdId,id("risk-review"),JSON.stringify({householdId,accountId:body.accountId,trigger:"RISK_SETTINGS_CHANGED",cycleKey:id("risk-cycle")})).run();});return Response.json({ok:true,policy:next});
  }
  const settings=body.restore===true?GLOBAL_DEFAULTS:validateGlobalSettings(body.settings);
  if(settings.defaultAccountId&&!await db.prepare("SELECT a.id FROM accounts a JOIN entities e ON e.id=a.entity_id WHERE a.id=? AND e.household_id=?").bind(settings.defaultAccountId,householdId).first())throw Error("Default account does not belong to this household");
  await db.prepare("INSERT INTO app_user_settings(household_id,user_id,settings_json) VALUES(?,?,?) ON CONFLICT(household_id,user_id) DO UPDATE SET settings_json=EXCLUDED.settings_json,updated_at=CURRENT_TIMESTAMP").bind(householdId,userId,JSON.stringify(settings)).run();
  await db.prepare("UPDATE notification_preferences SET timezone=?,updated_at=CURRENT_TIMESTAMP WHERE household_id=? AND user_id=?").bind(settings.timezone,householdId,userId).run();return Response.json({ok:true,settings});
}catch(e){if(e instanceof Response)return e;return Response.json({error:e instanceof Error?e.message:"Invalid configuration"},{status:400});}}
