import { workspace } from "@/lib/db";
import { decryptSecret } from "@/lib/crypto";

export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  try {
    const { db, householdId } = await workspace(request);
    const connections = await db.prepare("SELECT c.id,c.institution_name || ' · ' || COALESCE(u.display_name,'Household member') institution_name,c.status,c.last_synced_at,c.error_code,c.created_at,c.connected_by_user_id,COALESCE(u.display_name,'Household member') owner_name FROM connections c LEFT JOIN users u ON u.id=c.connected_by_user_id WHERE c.household_id=? AND c.provider='plaid' ORDER BY c.created_at DESC").bind(householdId).all();
    const accounts = await db.prepare("SELECT a.id,a.connection_id,a.name,a.official_name,a.nickname,a.investment_purpose,a.type,a.subtype,a.currency,a.mask,a.current_balance_cents,a.available_balance_cents,a.credit_limit_cents,a.updated_at,c.institution_name,COALESCE(u.display_name,'Household member') owner_name FROM accounts a JOIN entities e ON e.id=a.entity_id LEFT JOIN connections c ON c.id=a.connection_id LEFT JOIN users u ON u.id=c.connected_by_user_id WHERE e.household_id=? AND a.hidden=0 ORDER BY a.updated_at DESC").bind(householdId).all();
    const holdings = await db.prepare("SELECT h.account_id,a.nickname,a.investment_purpose,a.subtype account_subtype,s.ticker,s.name,s.type,h.quantity,h.cost_basis_cents,h.price_cents,h.price_at,(h.quantity*h.price_cents) market_value_cents,COALESCE(u.display_name,'Household member') owner_name FROM holdings h JOIN securities s ON s.id=h.security_id JOIN accounts a ON a.id=h.account_id JOIN entities e ON e.id=a.entity_id LEFT JOIN connections c ON c.id=a.connection_id LEFT JOIN users u ON u.id=c.connected_by_user_id WHERE e.household_id=? ORDER BY market_value_cents DESC").bind(householdId).all();
    const canonical=new Map<string,Record<string,any>>(),accountMap=new Map<string,string>();
    for(const raw of accounts.results as Array<Record<string,any>>){const key=[raw.institution_name||"",raw.official_name||raw.name||"",raw.type||"",raw.subtype||"",raw.mask||""].map(value=>String(value).trim().toLowerCase()).join("|");const existing=canonical.get(key);if(existing){accountMap.set(String(raw.id),String(existing.id));const owners=new Set([...(existing.owner_names||[existing.owner_name]),raw.owner_name]);existing.owner_names=[...owners];existing.owner_name=[...owners].join(", ");if(!existing.nickname&&raw.nickname)existing.nickname=raw.nickname;if(!existing.investment_purpose&&raw.investment_purpose)existing.investment_purpose=raw.investment_purpose;continue}const account={...raw,owner_names:[raw.owner_name]};canonical.set(key,account);accountMap.set(String(raw.id),String(raw.id))}
    const dedupedHoldings=new Map<string,Record<string,any>>();for(const raw of holdings.results as Array<Record<string,any>>){const accountId=accountMap.get(String(raw.account_id))||String(raw.account_id),key=`${accountId}|${String(raw.ticker||raw.name||"").toUpperCase()}`,existing=dedupedHoldings.get(key),candidate:Record<string,any>={...raw,account_id:accountId};if(!existing||Date.parse(String(candidate.price_at||""))>Date.parse(String(existing.price_at||"")))dedupedHoldings.set(key,candidate)}
    return Response.json({ connections: connections.results, accounts: [...canonical.values()], holdings: [...dedupedHoldings.values()], duplicateAccountsCollapsed:(accounts.results.length-canonical.size) });
  } catch (error) {
    if (error instanceof Response) return error;
    return Response.json({ error: error instanceof Error ? error.message : "Unable to load connections" }, { status: 500 });
  }
}

export async function PATCH(request:Request){try{const{db,householdId}=await workspace(request),body=await request.json() as {accountId?:string;nickname?:string;investmentPurpose?:string};const purposes=["Swing","Options","Long-term","Retirement","Dividend income","Mixed"];if(!body.accountId)return Response.json({error:"accountId required"},{status:400});if(body.investmentPurpose&&!purposes.includes(body.investmentPurpose))return Response.json({error:"Invalid investment purpose"},{status:400});const account=await db.prepare("SELECT a.id FROM accounts a JOIN entities e ON e.id=a.entity_id WHERE a.id=? AND e.household_id=?").bind(body.accountId,householdId).first();if(!account)return Response.json({error:"Account not found"},{status:404});await db.prepare("UPDATE accounts SET nickname=?,investment_purpose=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(String(body.nickname||"").trim().slice(0,80)||null,body.investmentPurpose||null,body.accountId).run();const saved=await db.prepare("SELECT id,nickname,investment_purpose,updated_at FROM accounts WHERE id=?").bind(body.accountId).first();return Response.json({ok:true,account:saved})}catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Unable to update account"},{status:500})}}

export async function POST(request:Request){try{const{db,householdId,entityId,userId}=await workspace(request),body=await request.json() as {alias?:string;accountType?:string;purpose?:string;source?:string},accountTypes=["Taxable brokerage","401(k)","Traditional IRA","Roth IRA","SEP IRA","Other investment"],purposes=["Swing","Options","Long-term","Retirement","Dividend income","Mixed"],alias=String(body.alias||"").trim().slice(0,80);if(body.source!=="manual")return Response.json({error:"Invalid account source"},{status:400});if(!alias)return Response.json({error:"Account alias is required"},{status:400});if(!accountTypes.includes(String(body.accountType)))return Response.json({error:"Invalid account type"},{status:400});if(!purposes.includes(String(body.purpose)))return Response.json({error:"Invalid investment purpose"},{status:400});const accountId=`manual_account_${crypto.randomUUID()}`;await db.batch([db.prepare("INSERT INTO accounts(id,entity_id,provider_account_id,name,official_name,nickname,investment_purpose,type,subtype,currency,current_balance_cents,updated_at) VALUES(?,?,?,'Manual investment account',?,?,?,'investment',?,'USD',0,CURRENT_TIMESTAMP)").bind(accountId,entityId,accountId,alias,alias,body.purpose,body.accountType),db.prepare("INSERT INTO audit_log(id,household_id,user_id,action,target_type,target_id,metadata_json) VALUES(?,?,?,?,?,?,?)").bind(`audit_${crypto.randomUUID()}`,householdId,userId,"manual_investment_account_created","account",accountId,JSON.stringify({accountType:body.accountType,purpose:body.purpose}))]);return Response.json({ok:true,account:{id:accountId,nickname:alias,subtype:body.accountType,investment_purpose:body.purpose,source:"manual"}},{status:201})}catch(error){if(error instanceof Response)return error;console.error("MANUAL_INVESTMENT_ACCOUNT_CREATE_FAILED",error);return Response.json({error:"Manual investment account could not be created.",code:"MANUAL_ACCOUNT_CREATE_FAILED"},{status:500})}}

export async function DELETE(request:Request){try{const{db,householdId,userId,role}=await workspace(request),body=await request.json() as {connectionId?:string};if(!body.connectionId)return Response.json({error:"connectionId required"},{status:400});const connection=await db.prepare("SELECT id,institution_name,connected_by_user_id,encrypted_access_token FROM connections WHERE id=? AND household_id=? AND provider='plaid'").bind(body.connectionId,householdId).first<Record<string,string>>();if(!connection)return Response.json({error:"Plaid connection not found"},{status:404});if(connection.connected_by_user_id!==userId&&!['owner','co_owner'].includes(role))return Response.json({error:"Only the connection owner or a household owner can remove this connection"},{status:403});if(connection.encrypted_access_token){const host=process.env.PLAID_ENV==="production"?"https://production.plaid.com":process.env.PLAID_ENV==="development"?"https://development.plaid.com":"https://sandbox.plaid.com",token=await decryptSecret(connection.encrypted_access_token),revocation=await fetch(`${host}/item/remove`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({client_id:process.env.PLAID_CLIENT_ID,secret:process.env.PLAID_SECRET,access_token:token}),cache:"no-store"});if(!revocation.ok)return Response.json({error:`Plaid could not revoke this connection (${revocation.status}). Nothing was deleted.`},{status:502})}await db.batch([db.prepare("DELETE FROM holdings WHERE account_id IN (SELECT id FROM accounts WHERE connection_id=?)").bind(body.connectionId),db.prepare("DELETE FROM transactions WHERE account_id IN (SELECT id FROM accounts WHERE connection_id=?)").bind(body.connectionId),db.prepare("DELETE FROM accounts WHERE connection_id=?").bind(body.connectionId),db.prepare("DELETE FROM connections WHERE id=? AND household_id=?").bind(body.connectionId,householdId)]);return Response.json({ok:true,institution:connection.institution_name||"Plaid institution"})}catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Unable to remove connection"},{status:500})}}
