import {loadRuntimeSecrets} from "@/lib/runtime-secrets";

export const dynamic="force-dynamic";
type Bar={c:number;t:string};
const universe=["SCHD","DGRO","VIG","MSFT","AAPL","AVGO","JPM","V","COST","HD","XOM","CVX","NEE","KO","PEP","PG","JNJ","ABBV","MCD","TXN"];
const funds=new Set(["SCHD","DGRO","VIG"]);
const avg=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;

export async function GET(){
  await loadRuntimeSecrets();
  const alpacaKey=process.env.ALPACA_API_KEY,alpacaSecret=process.env.ALPACA_API_SECRET,finnhubKey=process.env.FINNHUB_API_KEY,feed=process.env.ALPACA_DATA_FEED||"iex";
  if(!alpacaKey||!alpacaSecret||!finnhubKey)return Response.json({error:"Alpaca and Finnhub are required for dividend-growth analysis."},{status:503});
  const start=new Date(Date.now()-360*86400000).toISOString(),barsResponse=await fetch(`https://data.alpaca.markets/v2/stocks/bars?symbols=${universe.join(",")}&timeframe=1Day&start=${encodeURIComponent(start)}&limit=10000&adjustment=all&feed=${feed}`,{headers:{"APCA-API-KEY-ID":alpacaKey,"APCA-API-SECRET-KEY":alpacaSecret},cache:"no-store"});
  if(!barsResponse.ok)return Response.json({error:"Dividend-growth price history is unavailable."},{status:502});
  const barsData=await barsResponse.json() as {bars?:Record<string,Bar[]>};
  const candidates=await Promise.all(universe.map(async symbol=>{const bars=barsData.bars?.[symbol]||[];if(bars.length<100)return null;const closes=bars.map(bar=>Number(bar.c)).filter(Number.isFinite),price=closes.at(-1)!,sma50=avg(closes.slice(-50)),sma100=avg(closes.slice(-100));try{const[metricResponse,profileResponse]=await Promise.all([fetch(`https://finnhub.io/api/v1/stock/metric?symbol=${symbol}&metric=all`,{headers:{"X-Finnhub-Token":finnhubKey},cache:"no-store"}),fetch(`https://finnhub.io/api/v1/stock/profile2?symbol=${symbol}`,{headers:{"X-Finnhub-Token":finnhubKey},cache:"no-store"})]),metric=(await metricResponse.json() as {metric?:Record<string,number>}).metric||{},profile=await profileResponse.json() as {name?:string;marketCapitalization?:number},yieldPct=metric.dividendYieldIndicatedAnnual??metric.currentDividendYieldTTM??0,dividendGrowth5Y=metric.dividendGrowthRate5Y??metric.dividendGrowth5Y??null,revenueGrowth3Y=metric.revenueGrowth3Y??null,epsGrowth3Y=metric.epsGrowth3Y??null,pe=metric.peTTM??null,marketCap=profile.marketCapitalization??null,isFund=funds.has(symbol),trend=price>sma50&&sma50>sma100?"Bullish":price<sma100?"Bearish":"Mixed";let score=45;score+=yieldPct>=1.5&&yieldPct<=6?12:yieldPct>0?5:-10;score+=dividendGrowth5Y!==null?(dividendGrowth5Y>=8?12:dividendGrowth5Y>0?6:-8):isFund?6:-5;score+=epsGrowth3Y!==null?(epsGrowth3Y>=10?10:epsGrowth3Y>0?5:-8):0;score+=revenueGrowth3Y!==null?(revenueGrowth3Y>=8?8:revenueGrowth3Y>0?3:-5):0;score+=marketCap!==null&&marketCap>=10000?7:0;score+=pe!==null?(pe<=28?7:pe>45?-7:2):isFund?3:0;score+=trend==="Bullish"?9:trend==="Bearish"?-9:0;score=Math.max(0,Math.min(100,Math.round(score)));const growth=Math.max(2,Math.min(14,avg([epsGrowth3Y,revenueGrowth3Y,dividendGrowth5Y].filter((value):value is number=>value!==null&&Number.isFinite(value))))),years=3,base=price*Math.pow(1+growth/100,years),bear=price*Math.pow(1+Math.max(-.08,(growth-12)/100),years),bull=price*Math.pow(1+(growth+6)/100,years),decision=score>=80&&trend!=="Bearish"?"STRONG DIVIDEND-GROWTH RESEARCH":score>=65?"WATCH / VALIDATE":"NOT QUALIFIED NOW";return{symbol,name:profile.name||symbol,isFund,price,score,decision,trend,sma50,sma100,yieldPct,dividendGrowth5Y,revenueGrowth3Y,epsGrowth3Y,pe,marketCap,bear,base,bull,asOf:bars.at(-1)?.t,coverage:[yieldPct||null,dividendGrowth5Y,revenueGrowth3Y,epsGrowth3Y,pe,marketCap].filter(value=>value!==null).length}}catch{return null}}));
  const ranked=candidates.filter(candidate=>candidate!==null).sort((a,b)=>b.score-a.score);
  return Response.json({provider:"Alpaca + Finnhub",feed,asOf:new Date().toISOString(),candidates:ranked},{headers:{"Cache-Control":"private, no-store"}});
}
