import{workspace,id}from"@/lib/db";
export const dynamic="force-dynamic";
const compare=(type:string,current:bigint,threshold:bigint,previous:bigint|null)=>type==="PRICE_AT_OR_ABOVE"?current>=threshold:type==="PRICE_AT_OR_BELOW"?current<=threshold:type==="PRICE_CROSSES_ABOVE"?previous!==null&&previous<threshold&&current>=threshold:type==="PRICE_CROSSES_BELOW"?previous!==null&&previous>threshold&&current<=threshold:false;
export async function POST(request:Request){
 try{
  const{db,householdId,userId}=await workspace(request),body=await request.json()as{symbol?:string;currentPriceCents?:string;previousPriceCents?:string;asOf?:string},symbol=String(body.symbol||"").trim().toUpperCase(),asOf=body.asOf||new Date().toISOString();
  if(!/^[A-Z0-9.-]{1,12}$/.test(symbol)||!/^\d+$/.test(String(body.currentPriceCents))||!Number.isFinite(Date.parse(asOf)))return Response.json({error:"Valid symbol, currentPriceCents, and asOf are required"},{status:400});
  const current=BigInt(String(body.currentPriceCents)),previous=/^\d+$/.test(String(body.previousPriceCents))?BigInt(String(body.previousPriceCents)):null,result=await db.prepare("SELECT t.id,t.trigger_type,t.condition_json,t.cooldown_until,r.id recommendation_id,r.action,r.account_id FROM recommendation_triggers t JOIN recommendations r ON r.id=t.recommendation_id JOIN securities s ON s.id=r.security_id WHERE r.household_id=? AND s.ticker=? AND r.lifecycle='MONITORING' AND r.expires_at>? AND t.status='MONITORING'").bind(householdId,symbol,asOf).all<any>(),triggered=[]as Array<Record<string,unknown>>;
  await db.transaction(async tx=>{for(const row of result.results){const condition=typeof row.condition_json==="string"?JSON.parse(row.condition_json):row.condition_json,thresholdRaw=String(condition?.priceCents||"");if(!/^\d+$/.test(thresholdRaw)||row.cooldown_until&&Date.parse(row.cooldown_until)>Date.parse(asOf))continue;if(!compare(row.trigger_type,current,BigInt(thresholdRaw),previous))continue;const alertId=`alert_trigger_${row.id}`;await tx.prepare("UPDATE recommendation_triggers SET status='TRIGGERED',triggered_at=?,last_evaluated_at=? WHERE id=?").bind(asOf,asOf,row.id).run();await tx.prepare("UPDATE recommendations SET lifecycle='TRIGGERED' WHERE id=? AND household_id=?").bind(row.recommendation_id,householdId).run();await tx.prepare("INSERT INTO alerts(id,household_id,severity,type,title,explanation,evidence_json,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING").bind(alertId,householdId,"high","recommendation_trigger",`${symbol} · ${row.action} review triggered`,`The monitored price condition was reached. Confirm current evidence and whether you acted; Northstar has not placed an order.`,JSON.stringify({recommendationId:row.recommendation_id,triggerId:row.id,accountId:row.account_id,symbol,currentPriceCents:current.toString()}),asOf).run();await tx.prepare("INSERT INTO alert_deliveries(id,alert_id,user_id,channel,status) VALUES(?,?,?,'IN_APP','PENDING') ON CONFLICT(alert_id,user_id,channel) DO NOTHING").bind(id("alert_delivery"),alertId,userId).run();triggered.push({recommendationId:row.recommendation_id,triggerId:row.id,alertId,accountId:row.account_id,action:row.action,symbol,currentPriceCents:current.toString()})}});
  return Response.json({symbol,asOf,evaluated:result.results.length,triggered})
 }catch(error){if(error instanceof Response)return error;return Response.json({error:error instanceof Error?error.message:"Recommendation triggers could not be evaluated"},{status:400})}
}
