import {workspace} from '@/lib/db';
import {accountRiskSettings} from '@/lib/account-risk-settings';
import {optionsDiscoveryCoverage} from '@/lib/options-discovery';
import {queueOptionResearch,OPTIONS_RESEARCH_VERSION} from '@/lib/options-research-queue';
import {optionQuoteResearchFresh} from '@/lib/options-next-open';
export const dynamic='force-dynamic';
async function context(request:Request,accountId:string){const ctx=await workspace(request);const account=await ctx.db.prepare("SELECT a.id FROM accounts a JOIN entities e ON e.id=a.entity_id WHERE a.id=? AND e.household_id=? AND a.hidden=0 AND a.type='investment'").bind(accountId,ctx.householdId).first();if(!account)throw Response.json({error:'Account not found'},{status:404});return ctx;}
export async function GET(request:Request){try{
 const url=new URL(request.url),accountId=url.searchParams.get('accountId')||'',{db,householdId}=await context(request,accountId);
 const risk=await accountRiskSettings(db,householdId,accountId),policy={optionsEnabled:risk.effective.optionsEnabled,premiumCap:Math.max(0,Math.min(risk.value*risk.effective.optionsRiskBps/10000,risk.cash-risk.value*risk.effective.cashReserveBps/10000)),suggestedDte:21,label:risk.effective.label};
 const rows=(await db.prepare("SELECT symbol,decision_json,updated_at FROM options_account_decisions WHERE account_id=? ORDER BY updated_at DESC").bind(accountId).all<any>()).results;
 const results=rows.map(row=>{const result=row.decision_json;return {...result,researchDecisions:(result.researchDecisions||[]).map((r:any)=>{const fresh=optionQuoteResearchFresh(r.quoteAsOf||'')&&optionQuoteResearchFresh(r.underlyingAsOf||'');return fresh?r:{...r,freshness:'STALE',executionReady:false,decision:'WAIT',reasons:['Saved evidence needs revalidation',...(r.reasons||[])]};}),updatedAt:row.updated_at};});
 const jobs=(await db.prepare("SELECT DISTINCT ON(payload_json->>'symbol') id,payload_json->>'symbol' symbol,status,attempts,error_code,created_at,updated_at,available_at FROM background_jobs WHERE household_id=? AND job_type='OPTIONS_ACCOUNT_REVIEW' AND payload_json->>'accountId'=? ORDER BY payload_json->>'symbol',created_at DESC").bind(householdId,accountId).all<any>()).results;
 const stages=(await db.prepare('SELECT symbol,stage,status,started_at,completed_at,retry_count,last_error,freshness,next_retry_at,updated_at FROM options_research_stages WHERE account_id=? AND research_version=? ORDER BY symbol,updated_at DESC').bind(accountId,OPTIONS_RESEARCH_VERSION).all()).results;
 const coverage:any=await optionsDiscoveryCoverage(db),contracts=results.flatMap(r=>r.researchDecisions||[]);
 Object.assign(coverage,{deep_researched:results.filter(r=>r.researchVersion===OPTIONS_RESEARCH_VERSION).length,actionable_call:contracts.filter(r=>r.type==='CALL'&&r.executionReady).length,actionable_put:contracts.filter(r=>r.type==='PUT'&&r.executionReady).length,call_candidates:contracts.filter(r=>r.type==='CALL'&&r.qualified&&r.freshness!=='STALE').length,put_candidates:contracts.filter(r=>r.type==='PUT'&&r.qualified&&r.freshness!=='STALE').length,shares_preferred:results.filter(r=>r.decisionLabel==='SHARES PREFERRED').length,wait:results.filter(r=>r.decisionLabel==='WAIT').length,stale:results.filter(r=>!optionQuoteResearchFresh(r.asOf||'')).length,queued:jobs.filter(j=>['QUEUED','RUNNING','FAILED'].includes(j.status)&&j.attempts<6).length,failed:jobs.filter(j=>j.status==='DEAD'||j.status==='FAILED').length});
 return Response.json({results,coverage,policy,jobs,stages,checkedAt:new Date().toISOString()},{headers:{'Cache-Control':'private, no-store'}});
 }catch(e){if(e instanceof Response)return e;return Response.json({error:'Research progress unavailable; saved results have been preserved'},{status:503});}}
export async function POST(request:Request){try{
 const body=await request.json(),accountId=String(body.accountId||''),{db,householdId}=await context(request,accountId),symbol=String(body.symbol||'').trim().toUpperCase();
 if(symbol&&!/^[A-Z][A-Z0-9.-]{0,11}$/.test(symbol))return Response.json({error:'Valid ticker required'},{status:400});
 const targets=symbol?[symbol]:(await db.prepare("SELECT o.symbol FROM options_discovery o JOIN discovery_queue d USING(symbol) WHERE d.active AND o.stage='CHAIN_QUALIFIED' ORDER BY d.priority DESC,COALESCE((d.seed_json->'seed'->'metrics'->>'relativeVolume')::numeric,0) DESC,o.checked_at DESC LIMIT 20").all<{symbol:string}>()).results.map(r=>r.symbol);
 if(!targets.length){const key='options-discovery-'+Math.floor(Date.now()/60000);await db.prepare("INSERT INTO background_jobs(id,job_type,idempotency_key,payload_json) VALUES(?,'OPTIONS_DISCOVERY',?,'{}'::jsonb) ON CONFLICT DO NOTHING").bind(key,key).run();return Response.json({status:'QUEUED',jobs:[],message:'Broad-market discovery queued; account research follows chain qualification.'},{status:202});}
 const jobs=[];for(const ticker of targets)jobs.push({symbol:ticker,...await queueOptionResearch(db,householdId,accountId,ticker,true)});
 return Response.json({status:'QUEUED',jobs,requestId:jobs[0]?.jobId,message:symbol?'Fresh ticker research queued.':'Fresh research queued for the 20 highest-priority chain-qualified stocks; the full-universe background rotation continues.'},{status:202});
 }catch(e){if(e instanceof Response)return e;return Response.json({error:'Could not queue research; Retry preserves saved results'},{status:503});}}
