import {database,id} from "@/lib/db";
import {requireUser} from "@/lib/auth";

const approverEmails=()=>new Set((process.env.FAMILY_APPROVER_EMAILS||"lisdanay.dm@gmail.com,jose.linaret@gmail.com").split(",").map(value=>value.trim().toLowerCase()).filter(Boolean));
async function approver(request:Request){const user=await requireUser(request);if(!approverEmails().has(user.email.toLowerCase()))throw new Response(JSON.stringify({error:"Family administrator access required"}),{status:403,headers:{"Content-Type":"application/json"}});return user}

export async function GET(request:Request){try{await approver(request);const db=await database(),requests=await db.prepare("SELECT id,user_id,email,display_name,status,requested_at,reviewed_at,reviewed_by FROM family_access_requests ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END,requested_at DESC LIMIT 100").all();return Response.json({requests:requests.results})}catch(error){if(error instanceof Response)return error;return Response.json({error:"Unable to load access requests"},{status:500})}}

export async function PATCH(request:Request){try{const admin=await approver(request),body=await request.json() as {id?:string;decision?:string};if(!body.id||!["approved","denied"].includes(body.decision||""))return Response.json({error:"Request id and approved/denied decision required"},{status:400});const db=await database(),row=await db.prepare("SELECT user_id,email,display_name,status FROM family_access_requests WHERE id=?").bind(body.id).first<{user_id:string;email:string;display_name:string;status:string}>();if(!row)return Response.json({error:"Access request not found"},{status:404});await db.prepare("UPDATE family_access_requests SET status=?,reviewed_at=CURRENT_TIMESTAMP,reviewed_by=? WHERE id=?").bind(body.decision,admin.userId,body.id).run();if(body.decision==="approved"){const householdId=`household_${row.user_id}`,entityId=`entity_${row.user_id}_personal`;await db.batch([db.prepare("INSERT OR IGNORE INTO households(id,name,goal_date) VALUES(?,?,?)").bind(householdId,"My Household","2036-12-31"),db.prepare("INSERT OR IGNORE INTO household_members(household_id,user_id,role,status) VALUES(?,?,?,'active')").bind(householdId,row.user_id,"owner"),db.prepare("INSERT OR IGNORE INTO entities(id,household_id,type,name) VALUES(?,?,?,?)").bind(entityId,householdId,"personal","Personal Finances"),db.prepare("INSERT INTO audit_log(id,household_id,user_id,action,target_type,target_id) VALUES(?,?,?,?,?,?)").bind(id("audit"),householdId,admin.userId,"family_access.approved","user",row.user_id)])}return Response.json({ok:true,status:body.decision})}catch(error){if(error instanceof Response)return error;return Response.json({error:"Unable to review access request"},{status:500})}}
